import express from "express";
import { createServer, type Server } from "node:http";
import { afterEach, describe, expect, it } from "vitest";

import { registerEngineeringJobHttp } from "../server/engineeringJobHttp";

let server: Server | undefined;
async function startApi() { const app = express(); app.use(express.json({ limit: "2mb" })); registerEngineeringJobHttp(app); server = createServer(app); await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve)); const address = server.address(); if (!address || typeof address === "string") throw new Error("TEST_HTTP_SERVER_UNAVAILABLE"); return `http://127.0.0.1:${address.port}`; }
async function stopApi() { if (server) await new Promise<void>((resolve, reject) => server!.close((error) => error ? reject(error) : resolve())); server = undefined; }
afterEach(stopApi);

async function realArtifact(base: string, project: { projectId: string; accessKey: string }, name: string, values: [string, string, string]) {
  const headers = { "content-type": "application/json", "x-engineering-access-key": project.accessKey };
  const createdResponse = await fetch(`${base}/api/projects/${project.projectId}/concept-designs`, { method: "POST", headers, body: JSON.stringify({ templateId: "CONCEPT_BACKREST_LOAD_PATH", name, description: `Real CAD source ${name}` }) });
  expect(createdResponse.status).toBe(201); const created = await createdResponse.json() as { seat: { id: string }; revisionId: string };
  const modelUrl = `${base}/api/projects/${project.projectId}/seat-designs/${created.seat.id}/revisions/${created.revisionId}/concept-design`;
  for (const [field, value] of [["BACKREST_WIDTH", values[0]], ["BACKREST_HEIGHT", values[1]], ["PLATE_THICKNESS", values[2]]]) expect((await fetch(`${modelUrl}/parameters/${field}`, { method: "PUT", headers, body: JSON.stringify({ value, unit: "mm" }) })).status).toBe(200);
  const generated = await fetch(`${modelUrl}/generate-cad`, { method: "POST", headers }); expect(generated.status).toBe(201); const body = await generated.json() as { artifact: { cadFileId: string; artifactHash: string } };
  return { ...body.artifact, seatDesignId: created.seat.id, seatRevisionId: created.revisionId };
}

describe("authoritative multi-artifact assembly API", () => {
  it("persists two real CAD artifacts, stable component identities, immutable revisions, comparison, and restart recovery", async () => {
    let base = await startApi();
    const projectResponse = await fetch(`${base}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Multi-artifact assembly proof" }) });
    const project = await projectResponse.json() as { projectId: string; accessKey: string }; const headers = { "content-type": "application/json", "x-engineering-access-key": project.accessKey };
    const artifactA = await realArtifact(base, project, "Artifact A", ["420", "560", "3"]);
    const artifactB = await realArtifact(base, project, "Artifact B", ["460", "540", "4"]);
    const artifactC = await realArtifact(base, project, "Artifact C", ["400", "600", "2.5"]);
    expect(new Set([artifactA.artifactHash, artifactB.artifactHash, artifactC.artifactHash]).size).toBe(3);
    const eligible = await fetch(`${base}/api/projects/${project.projectId}/assemblies/eligible-cad-files`, { headers }); expect(eligible.status).toBe(200); const options = await eligible.json() as Array<{ artifactId: string; artifactRevision: number; artifactSha256: string; verifiedIngestionState: string; geometryRepresentation: string }>;
    for (const artifact of [artifactA, artifactB, artifactC]) expect(options).toContainEqual(expect.objectContaining({ artifactId: artifact.cadFileId, artifactSha256: artifact.artifactHash, artifactRevision: 1, projectId: project.projectId, createdAt: expect.any(String), availability: "AVAILABLE", verifiedIngestionState: "VERIFIED", geometryRepresentation: "KERNEL_DERIVED_MESH" }));
    const sourceComponent = (label: string, artifact: typeof artifactA, translationMm: { x: number; y: number; z: number }, rotationDeg = { x: 0, y: 0, z: 0 }) => ({ label, cadFileId: artifact.cadFileId, sourceHash: artifact.artifactHash, translationMm, rotationDeg });
    const initialComponents = [sourceComponent("A", artifactA, { x: 10, y: 0, z: 0 }), sourceComponent("B", artifactB, { x: 0, y: 20, z: 0 })];
    const createdResponse = await fetch(`${base}/api/projects/${project.projectId}/assemblies`, { method: "POST", headers, body: JSON.stringify({ name: "R1 two-artifact assembly", components: initialComponents }) }); expect(createdResponse.status).toBe(201);
    const revision1 = await createdResponse.json() as { record: { id: string; revision: number }; assembly: { assemblyId: string; assemblyRevisionId: string; components: Array<{ componentId: string; artifactId: string; artifactRevision: number; artifactSha256: string; transform: { translationMm: { x: number } } }> } };
    expect(revision1.assembly.components).toHaveLength(2); expect(new Set(revision1.assembly.components.map((component) => component.componentId)).size).toBe(2); expect(revision1.assembly.assemblyRevisionId).toMatch(/^ASSEMBLY_REV-/);
    const revision2Inputs = revision1.assembly.components.map((component) => ({ componentId: component.componentId, label: component.artifactId === artifactA.cadFileId ? "A" : "B", cadFileId: component.artifactId, sourceHash: component.artifactSha256, translationMm: component.artifactId === artifactA.cadFileId ? { x: 75, y: 0, z: 0 } : { x: 0, y: 20, z: 0 }, rotationDeg: component.artifactId === artifactB.cadFileId ? { x: 0, y: 0, z: 25 } : { x: 0, y: 0, z: 0 } }));
    const revision2Response = await fetch(`${base}/api/projects/${project.projectId}/assemblies/${revision1.record.id}/revise`, { method: "POST", headers, body: JSON.stringify({ name: "R2 two-artifact assembly", reason: "Independent placement update", components: revision2Inputs }) }); expect(revision2Response.status).toBe(201);
    const revision2 = await revision2Response.json() as { record: { id: string; revision: number }; assembly: { assemblyId: string; assemblyRevisionId: string; components: Array<{ componentId: string; transformRevision: { transformRevisionId: string; previousTransform: { translationMm: { x: number } } | null } }> } };
    expect(revision2.record.revision).toBe(2); expect(revision2.assembly.assemblyId).toBe(revision1.assembly.assemblyId); expect(revision2.assembly.assemblyRevisionId).not.toBe(revision1.assembly.assemblyRevisionId); expect(revision2.assembly.components.map((component) => component.componentId).sort()).toEqual(revision1.assembly.components.map((component) => component.componentId).sort()); expect(revision2.assembly.components.every((component) => component.transformRevision.transformRevisionId)).toBe(true);
    const historyResponse = await fetch(`${base}/api/projects/${project.projectId}/assemblies/${revision2.record.id}/revisions`, { headers }); expect(historyResponse.status).toBe(200); const history = await historyResponse.json() as any[]; expect(history.map((item) => item.record.revision)).toEqual([1, 2]); expect(history[0].assembly.components.find((component: any) => component.transform.translationMm.x === 10)).toBeTruthy(); expect(history[1].assembly.components.find((component: any) => component.transform.translationMm.x === 75)).toBeTruthy();
    const comparisonResponse = await fetch(`${base}/api/projects/${project.projectId}/assemblies/${revision1.record.id}/compare/${revision2.record.id}`, { headers }); expect(comparisonResponse.status).toBe(200); await expect(comparisonResponse.json()).resolves.toMatchObject({ assemblyId: revision1.assembly.assemblyId, addedComponents: [], removedComponents: [], artifactBindingChanges: [], changedTransforms: expect.arrayContaining(revision1.assembly.components.map((component) => component.componentId)) });
    const bomResponse = await fetch(`${base}/api/projects/${project.projectId}/assemblies/${revision2.record.id}/bom`, { method: "POST", headers }); expect(bomResponse.status).toBe(201); const bom = await bomResponse.json() as { bomId: string; assemblyEntityId: string; assemblyRevisionId: string; assemblyRecordRevision: number; assemblyRevisionHash: string; status: string; bomHash: string; items: Array<{ quantity: number; sourceCadFileId: string; sourceCadRevision: number; sourceCadSha256: string; verification: string }> };
    expect(bom).toMatchObject({ assemblyEntityId: revision2.record.id, assemblyRevisionId: revision2.assembly.assemblyRevisionId, assemblyRecordRevision: 2, status: "DERIVED_FROM_VERIFIED_ASSEMBLY", bomHash: expect.stringMatching(/^[a-f0-9]{64}$/), items: expect.arrayContaining([expect.objectContaining({ quantity: 1, sourceCadFileId: artifactA.cadFileId, sourceCadRevision: 1, sourceCadSha256: artifactA.artifactHash, verification: "PARSED_VALID_KERNEL_MESH" }), expect.objectContaining({ quantity: 1, sourceCadFileId: artifactB.cadFileId, sourceCadRevision: 1, sourceCadSha256: artifactB.artifactHash, verification: "PARSED_VALID_KERNEL_MESH" })]) });
    const bomHistoryResponse = await fetch(`${base}/api/projects/${project.projectId}/assemblies/${revision2.record.id}/bom`, { headers }); expect(bomHistoryResponse.status).toBe(200); await expect(bomHistoryResponse.json()).resolves.toEqual([expect.objectContaining({ bomId: bom.bomId, bomHash: bom.bomHash })]);
    const foreignProject = await fetch(`${base}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Foreign BOM project" }) }); const foreign = await foreignProject.json() as { projectId: string; accessKey: string };
    const foreignBom = await fetch(`${base}/api/projects/${foreign.projectId}/assemblies/${revision2.record.id}/bom`, { method: "POST", headers: { "x-engineering-access-key": foreign.accessKey } }); expect(foreignBom.status).toBe(422); await expect(foreignBom.json()).resolves.toEqual({ error: "SEKB_ENTITY_NOT_FOUND" });
    const threeResponse = await fetch(`${base}/api/projects/${project.projectId}/assemblies`, { method: "POST", headers, body: JSON.stringify({ name: "Three-artifact assembly", components: [...initialComponents, sourceComponent("C", artifactC, { x: 0, y: 0, z: 30 })] }) }); expect(threeResponse.status).toBe(201); await expect(threeResponse.json()).resolves.toMatchObject({ assembly: { components: expect.arrayContaining([expect.objectContaining({ artifactId: artifactA.cadFileId }), expect.objectContaining({ artifactId: artifactB.cadFileId }), expect.objectContaining({ artifactId: artifactC.cadFileId })]) } });
    const badHash = await fetch(`${base}/api/projects/${project.projectId}/assemblies`, { method: "POST", headers, body: JSON.stringify({ name: "Bad binding", components: [{ ...initialComponents[0], sourceHash: "a".repeat(64) }] }) }); expect(badHash.status).toBe(422);
    await stopApi(); base = await startApi(); const restored = await fetch(`${base}/api/projects/${project.projectId}/assemblies/${revision2.record.id}`, { headers }); expect(restored.status).toBe(200); const restoredBody = await restored.json() as any;
    expect(restoredBody.record).toMatchObject({ id: revision2.record.id, revision: 2 }); expect(restoredBody.assembly.assemblyId).toBe(revision1.assembly.assemblyId); expect(restoredBody.assembly.assemblyRevisionId).toBe(revision2.assembly.assemblyRevisionId);
    expect(restoredBody.assembly.components.map((component: any) => component.componentId).sort()).toEqual(revision2.assembly.components.map((component: any) => component.componentId).sort());
    const restoredBomHistory = await fetch(`${base}/api/projects/${project.projectId}/assemblies/${revision2.record.id}/bom`, { headers }); expect(restoredBomHistory.status).toBe(200); await expect(restoredBomHistory.json()).resolves.toEqual([expect.objectContaining({ bomId: bom.bomId, assemblyRevisionId: revision2.assembly.assemblyRevisionId, bomHash: bom.bomHash })]);
  }, 120_000);
});
