import express from "express";
import { createServer, type Server } from "node:http";
import { afterEach, describe, expect, it } from "vitest";

import { registerEngineeringJobHttp } from "../server/engineeringJobHttp";

let server: Server | undefined;
async function startApi() { const app = express(); app.use(express.json({ limit: "2mb" })); registerEngineeringJobHttp(app); server = createServer(app); await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve)); const address = server.address(); if (!address || typeof address === "string") throw new Error("TEST_HTTP_SERVER_UNAVAILABLE"); return `http://127.0.0.1:${address.port}`; }
async function stopApi() { if (server) await new Promise<void>((resolve, reject) => server!.close((error) => error ? reject(error) : resolve())); server = undefined; }
afterEach(stopApi);

async function createRealArtifact(base: string, project: { projectId: string; accessKey: string }, name: string, dimensions: [string, string, string]) {
  const headers = { "content-type": "application/json", "x-engineering-access-key": project.accessKey };
  const created = await fetch(`${base}/api/projects/${project.projectId}/concept-designs`, { method: "POST", headers, body: JSON.stringify({ templateId: "CONCEPT_BACKREST_LOAD_PATH", name, description: "Real source for CAD-Agent command test" }) }); expect(created.status).toBe(201); const design = await created.json() as { seat: { id: string }; revisionId: string };
  const root = `${base}/api/projects/${project.projectId}/seat-designs/${design.seat.id}/revisions/${design.revisionId}/concept-design`;
  for (const [parameterName, value] of [["BACKREST_WIDTH", dimensions[0]], ["BACKREST_HEIGHT", dimensions[1]], ["PLATE_THICKNESS", dimensions[2]]]) expect((await fetch(`${root}/parameters/${parameterName}`, { method: "PUT", headers, body: JSON.stringify({ value, unit: "mm" }) })).status).toBe(200);
  const generated = await fetch(`${root}/generate-cad`, { method: "POST", headers }); expect(generated.status).toBe(201); return (await generated.json() as { artifact: { cadFileId: string; artifactHash: string } }).artifact;
}

describe("controlled CAD-Agent skills command API", () => {
  it("assesses commands, requires confirmation for the registered BOM operation, persists provenance, and blocks unadmitted solver requests", async () => {
    const base = await startApi();
    const projectResponse = await fetch(`${base}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "CAD-Agent command proof" }) }); const project = await projectResponse.json() as { projectId: string; accessKey: string }; const headers = { "content-type": "application/json", "x-engineering-access-key": project.accessKey };
    expect((await fetch(`${base}/api/projects/${project.projectId}/cad-agent/context`)).status).toBe(401);
    const skillsResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/skills`, { headers }); expect(skillsResponse.status).toBe(200); const skills = await skillsResponse.json() as Array<{ skillId: string; capabilityStatus: string; testStatus: string }>;
    expect(skills).toContainEqual(expect.objectContaining({ skillId: "assembly.derive_bom.v1", capabilityStatus: "SUPPORTED", testStatus: "VERIFIED" }));
    expect(skills).toContainEqual(expect.objectContaining({ skillId: "external.text_to_cad.cad.v1", capabilityStatus: "REQUIRES_DEPENDENCY", testStatus: "EXTERNAL_AUDIT_ONLY" }));
    const registryResponse = await fetch(`${base}/api/projects/${project.projectId}/capabilities`, { headers }); expect(registryResponse.status).toBe(200); const registry = await registryResponse.json() as { registryId: string; registryHash: string; persistedRecordId: string; capabilities: Array<{ capabilityId: string; status: string }> };
    expect(registry).toMatchObject({ registryId: "CAD-AGENT.CAPABILITY.REGISTRY", registryHash: expect.stringMatching(/^[a-f0-9]{64}$/), persistedRecordId: expect.any(String) });
    expect(registry.capabilities).toContainEqual(expect.objectContaining({ capabilityId: "CAD.ASSEMBLY.BOM.DERIVE", status: "VERIFIED" }));
    expect(registry.capabilities).toContainEqual(expect.objectContaining({ capabilityId: "CAD.CREATE.CONSTRAINT", status: "UNSUPPORTED" }));
    const artifactA = await createRealArtifact(base, project, "Command A", ["420", "560", "3"]); const artifactB = await createRealArtifact(base, project, "Command B", ["460", "540", "4"]);
    const assemblyResponse = await fetch(`${base}/api/projects/${project.projectId}/assemblies`, { method: "POST", headers, body: JSON.stringify({ name: "Command assembly", components: [{ label: "A", cadFileId: artifactA.cadFileId, sourceHash: artifactA.artifactHash, translationMm: { x: 0, y: 0, z: 0 }, rotationDeg: { x: 0, y: 0, z: 0 } }, { label: "B", cadFileId: artifactB.cadFileId, sourceHash: artifactB.artifactHash, translationMm: { x: 10, y: 0, z: 0 }, rotationDeg: { x: 0, y: 0, z: 0 } }] }) }); expect(assemblyResponse.status).toBe(201); const assembly = await assemblyResponse.json() as { record: { id: string } };
    const assessmentResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Generate a BOM for this assembly", assemblyEntityId: assembly.record.id }) }); expect(assessmentResponse.status).toBe(200); const assessment = await assessmentResponse.json() as { safety: string; execution: { status: string }; selectedSkill: { skillId: string }; capability: { capabilityId: string; status: string }; registry: { registryHash: string; persistedRecordId: string }; provenanceRecordId: string };
    expect(assessment).toMatchObject({ safety: "REQUIRES_CONFIRMATION", execution: { status: "NOT_EXECUTED" }, selectedSkill: { skillId: "assembly.derive_bom.v1" }, capability: { capabilityId: "CAD.ASSEMBLY.BOM.DERIVE", status: "VERIFIED" }, registry: { registryHash: registry.registryHash, persistedRecordId: registry.persistedRecordId }, provenanceRecordId: expect.any(String) });
    const missingParameters = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Add four mounting holes", assemblyEntityId: assembly.record.id }) }); expect(missingParameters.status).toBe(200); const holes = await missingParameters.json() as { commandKind: string; safety: string; capability: { capabilityId: string; status: string }; execution: { status: string }; requiredInputs: string[]; interpretation: { parameters: Array<{ name: string; value: number; confidence: string }>; missingInputs: string[] }; operationPlan: { planId: string; steps: Array<{ stage: string; status: string }>; prerequisites: Array<{ status: string }>; errorRecovery: string[] } };
    expect(holes).toMatchObject({ commandKind: "MODIFICATION", safety: "REQUIRES_PARAMETERS", capability: { capabilityId: "CAD.CREATE.HOLE", status: "VERIFIED" }, execution: { status: "REJECTED" }, requiredInputs: expect.arrayContaining(["Explicit supported feature", "Hole diameter with unit"]) });
    expect(holes.interpretation.parameters).toContainEqual(expect.objectContaining({ name: "COUNT", value: 4, confidence: "EXPLICIT" })); expect(holes.interpretation.missingInputs).toContain("Hole depth or through-all definition"); expect(holes.operationPlan).toMatchObject({ planId: expect.stringMatching(/^PLAN-CAD-AGENT-CMD-/), steps: expect.arrayContaining([expect.objectContaining({ stage: "CONTEXT_RETRIEVAL", status: "READY" }), expect.objectContaining({ stage: "PARAMETER_VALIDATION", status: "BLOCKED" })]), errorRecovery: expect.arrayContaining([expect.stringContaining("never invent")]) }); expect(holes.operationPlan.prerequisites.some((item) => item.status === "REQUIRED_INPUT")).toBe(true);
    const holeParameters = { diameter: 10, depth: 7, center: { x: 210, y: -1, z: 280 }, direction: { x: 0, y: 1, z: 0 }, unit: "mm" };
    const holeExecutionResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Create a 10 mm diameter, 7 mm depth hole with explicit coordinates", sourceFileId: artifactA.cadFileId, holeParameters, confirmed: true }) }); expect(holeExecutionResponse.status).toBe(200); const holeExecution = await holeExecutionResponse.json() as { safety: string; selectedSkill: { skillId: string }; capability: { capabilityId: string; status: string }; execution: { status: string; output: { artifactId: string; artifactHash: string; validationId: string; featureId: string; featureRevision: number } }; provenanceRecordId: string }; expect(holeExecution).toMatchObject({ safety: "REQUIRES_CONFIRMATION", selectedSkill: { skillId: "cad.create_cylindrical_hole.v1" }, capability: { capabilityId: "CAD.CREATE.HOLE", status: "VERIFIED" }, execution: { status: "EXECUTED", output: { artifactId: expect.any(String), artifactHash: expect.stringMatching(/^[a-f0-9]{64}$/), validationId: expect.stringMatching(/^CAD_VALIDATION-/), featureId: expect.stringMatching(/^FEATURE_CYLINDRICAL_HOLE-/), featureRevision: 1 } }, provenanceRecordId: expect.any(String) }); expect(holeExecution.execution.output.artifactId).not.toBe(artifactA.cadFileId);
    const cushion = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Create a 400 mm wide seat cushion", assemblyEntityId: assembly.record.id }) }); expect(cushion.status).toBe(200); const cushionPlan = await cushion.json() as { safety: string; execution: { status: string }; interpretation: { parameters: Array<{ name: string; value: number; normalizedValue: number; normalizedUnit: string }>; missingInputs: string[]; ambiguity: string[] } };
    expect(cushionPlan).toMatchObject({ safety: "REQUIRES_PARAMETERS", execution: { status: "REJECTED" }, interpretation: { parameters: expect.arrayContaining([expect.objectContaining({ name: "WIDTH", value: 400, normalizedValue: 400, normalizedUnit: "mm" })]), missingInputs: expect.arrayContaining(["Supported parametric template or complete geometry definition"]), ambiguity: expect.arrayContaining([expect.stringContaining("does not infer")]) } });
    const interference = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Check interference", assemblyEntityId: assembly.record.id }) }); expect(interference.status).toBe(200); await expect(interference.json()).resolves.toMatchObject({ commandKind: "ANALYSIS", safety: "UNSUPPORTED", execution: { status: "REJECTED" } });
    const constraints = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Solve sketch constraints", assemblyEntityId: assembly.record.id }) }); expect(constraints.status).toBe(200); await expect(constraints.json()).resolves.toMatchObject({ safety: "UNSUPPORTED", capability: { capabilityId: "CAD.CREATE.CONSTRAINT", status: "UNSUPPORTED" }, execution: { status: "REJECTED" } });
    const caeReadiness = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Prepare this revision for CAE", assemblyEntityId: assembly.record.id }) }); expect(caeReadiness.status).toBe(200); await expect(caeReadiness.json()).resolves.toMatchObject({ commandKind: "VALIDATION", safety: "SAFE_TO_EXECUTE", execution: { status: "NOT_EXECUTED" }, selectedSkill: { skillId: "cae.inspect_readiness.v1" } });
    const confirmedResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Generate a BOM for this assembly", assemblyEntityId: assembly.record.id, confirmed: true }) }); expect(confirmedResponse.status).toBe(200); const confirmed = await confirmedResponse.json() as { safety: string; execution: { status: string; output: { bomId: string; bomHash: string } } };
    expect(confirmed).toMatchObject({ safety: "REQUIRES_CONFIRMATION", execution: { status: "EXECUTED", output: { bomId: expect.stringMatching(/^BOM-/), bomHash: expect.stringMatching(/^[a-f0-9]{64}$/) } } });
    const solverResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/commands`, { method: "POST", headers, body: JSON.stringify({ message: "Run CalculiX simulation now", assemblyEntityId: assembly.record.id, confirmed: true }) }); expect(solverResponse.status).toBe(200); await expect(solverResponse.json()).resolves.toMatchObject({ commandKind: "SIMULATION", safety: "BLOCKED", execution: { status: "REJECTED" } });
    const historyResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/history`, { headers }); expect(historyResponse.status).toBe(200); const history = await historyResponse.json() as Array<{ title: string; content: string }>; expect(history.length).toBeGreaterThanOrEqual(6); expect(history.some((record) => record.content.includes("assembly.derive_bom.v1"))).toBe(true); expect(history.some((record) => record.content.includes("cae.dispatch_solver.v1"))).toBe(true);
    const foreignResponse = await fetch(`${base}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Foreign command project" }) }); const foreign = await foreignResponse.json() as { projectId: string; accessKey: string };
    const foreignHistory = await fetch(`${base}/api/projects/${project.projectId}/cad-agent/history`, { headers: { "x-engineering-access-key": foreign.accessKey } }); expect(foreignHistory.status).toBe(403);
    const foreignRegistry = await fetch(`${base}/api/projects/${project.projectId}/capabilities`, { headers: { "x-engineering-access-key": foreign.accessKey } }); expect(foreignRegistry.status).toBe(403);
  }, 120_000);
});
