import express from "express";
import { createServer, type Server } from "node:http";
import { afterEach, describe, expect, it } from "vitest";

import { registerEngineeringJobHttp } from "../server/engineeringJobHttp";

let server: Server | undefined;
async function startApi() { const app = express(); app.use(express.json({ limit: "3mb" })); registerEngineeringJobHttp(app); server = createServer(app); await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve)); const address = server.address(); if (!address || typeof address === "string") throw new Error("TEST_HTTP_SERVER_UNAVAILABLE"); return `http://127.0.0.1:${address.port}`; }
async function stopApi() { if (server) await new Promise<void>((resolve, reject) => server!.close((error) => error ? reject(error) : resolve())); server = undefined; }
afterEach(stopApi);

async function realArtifact(base: string, project: { projectId: string; accessKey: string }, name: string, values: [string, string, string]) {
  const headers = { "content-type": "application/json", "x-engineering-access-key": project.accessKey };
  const createdResponse = await fetch(`${base}/api/projects/${project.projectId}/concept-designs`, { method: "POST", headers, body: JSON.stringify({ templateId: "CONCEPT_BACKREST_LOAD_PATH", name, description: `Real CAD source ${name}` }) }); expect(createdResponse.status).toBe(201); const created = await createdResponse.json() as { seat: { id: string }; revisionId: string };
  const modelUrl = `${base}/api/projects/${project.projectId}/seat-designs/${created.seat.id}/revisions/${created.revisionId}/concept-design`;
  for (const [field, value] of [["BACKREST_WIDTH", values[0]], ["BACKREST_HEIGHT", values[1]], ["PLATE_THICKNESS", values[2]]]) expect((await fetch(`${modelUrl}/parameters/${field}`, { method: "PUT", headers, body: JSON.stringify({ value, unit: "mm" }) })).status).toBe(200);
  const generated = await fetch(`${modelUrl}/generate-cad`, { method: "POST", headers }); expect(generated.status).toBe(201); return await generated.json() as { artifact: { cadFileId: string; artifactHash: string } };
}

describe("artifact-bound CAD validation, Boolean Cut, and drawing exports", () => {
  it("validates real verified STEP, gates Boolean Cut approval, persists a new result artifact, and exports each supported view", async () => {
    let base = await startApi(); const projectResponse = await fetch(`${base}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "CAD artifact operations proof" }) }); const project = await projectResponse.json() as { projectId: string; accessKey: string }; const headers = { "content-type": "application/json", "x-engineering-access-key": project.accessKey };
    const source = await realArtifact(base, project, "Boolean source", ["480", "620", "5"]); const cutter = await realArtifact(base, project, "Boolean cutter", ["120", "180", "8"]);
    const validationResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/validations`, { method: "POST", headers }); expect(validationResponse.status).toBe(201); const validation = await validationResponse.json() as { validationId: string; overallStatus: string; artifact: { fileId: string; sha256: string; revision: number }; kernel: { status: string }; topology: { shapeValidity: string; counts: { solids: number; faces: number; edges: number; vertices: number } }; bounds: { status: string; diagonal: number }; persistedRecordId: string };
    expect(validation).toMatchObject({ overallStatus: expect.stringMatching(/PASS|WARNING/), artifact: { fileId: source.artifact.cadFileId, sha256: source.artifact.artifactHash, revision: 1 }, kernel: { status: "PASS" }, topology: { shapeValidity: "PASS", counts: { solids: expect.any(Number), faces: expect.any(Number), edges: expect.any(Number), vertices: expect.any(Number) } }, bounds: { status: "PASS", diagonal: expect.any(Number) }, persistedRecordId: expect.stringMatching(/^MEMORY-/) });
    const history = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/validations`, { headers }); expect(history.status).toBe(200); await expect(history.json()).resolves.toEqual([expect.objectContaining({ validationId: validation.validationId, artifact: expect.objectContaining({ sha256: source.artifact.artifactHash }) })]);
    const previewResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-operations/boolean-cut/preview`, { method: "POST", headers, body: JSON.stringify({ sourceFileId: source.artifact.cadFileId, cutterFileId: cutter.artifact.cadFileId }) }); expect(previewResponse.status).toBe(201); const preview = await previewResponse.json() as { operationId: string; previewStatus: string; approvalStatus: string; source: { sha256: string }; cutter: { sha256: string } };
    expect(preview).toMatchObject({ previewStatus: "PREVIEW_READY", approvalStatus: "REQUIRED", source: { sha256: source.artifact.artifactHash }, cutter: { sha256: cutter.artifact.artifactHash } });
    const sameSourcePreview = await fetch(`${base}/api/projects/${project.projectId}/cad-operations/boolean-cut/preview`, { method: "POST", headers, body: JSON.stringify({ sourceFileId: source.artifact.cadFileId, cutterFileId: source.artifact.cadFileId }) }); expect(sameSourcePreview.status).toBe(422);
    const sourceHistoryBefore = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/validations`, { headers }); expect(sourceHistoryBefore.status).toBe(200); await expect(sourceHistoryBefore.json()).resolves.toHaveLength(1);
    const executeResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-operations/boolean-cut/${preview.operationId}/approve`, { method: "POST", headers }); expect(executeResponse.status).toBe(201); const execution = await executeResponse.json() as { result: { artifact: { fileId: string; sha256: string; revision: number }; validationId: string; validationStatus: string }; provenance: { sourceArtifact: { sha256: string }; cutterArtifact: { sha256: string }; operation: string }; persistedRecordId: string };
    expect(execution).toMatchObject({ result: { artifact: { sha256: expect.stringMatching(/^[a-f0-9]{64}$/), revision: 1 }, validationStatus: expect.stringMatching(/PASS|WARNING/) }, provenance: { sourceArtifact: { sha256: source.artifact.artifactHash }, cutterArtifact: { sha256: cutter.artifact.artifactHash }, operation: "CUT" }, persistedRecordId: expect.stringMatching(/^MEMORY-/) }); expect(execution.result.artifact.fileId).not.toBe(source.artifact.cadFileId);
    const sourceHistoryAfter = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/validations`, { headers }); expect(sourceHistoryAfter.status).toBe(200); await expect(sourceHistoryAfter.json()).resolves.toHaveLength(1);
    const views = ["FRONT", "REAR", "LEFT", "RIGHT", "TOP", "BOTTOM", "ISOMETRIC"] as const; const drawings: Array<{ drawingId: string; sha256: string; source: { sha256: string }; view: string; storage: { url: string } }> = [];
    for (const view of views) { const response = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/drawings`, { method: "POST", headers, body: JSON.stringify({ validationId: validation.validationId, view }) }); expect(response.status).toBe(201); drawings.push(await response.json()); }
    expect(drawings.map((drawing) => drawing.view).sort()).toEqual([...views].sort()); expect(drawings.every((drawing) => /^[a-f0-9]{64}$/.test(drawing.sha256) && drawing.source.sha256 === source.artifact.artifactHash && drawing.storage.url.includes("/manus-storage/"))).toBe(true);
    const drawingsHistory = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/drawings`, { headers }); expect(drawingsHistory.status).toBe(200); await expect(drawingsHistory.json()).resolves.toHaveLength(7);
    const invalidDrawing = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/drawings`, { method: "POST", headers, body: JSON.stringify({ validationId: "CAD_VALIDATION-NOT-OWNED", view: "FRONT" }) }); expect(invalidDrawing.status).toBe(422);
    const foreignResponse = await fetch(`${base}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Foreign CAD operations project" }) }); const foreign = await foreignResponse.json() as { projectId: string; accessKey: string }; const foreignValidation = await fetch(`${base}/api/projects/${foreign.projectId}/cad-files/${source.artifact.cadFileId}/validations`, { method: "POST", headers: { "x-engineering-access-key": foreign.accessKey } }); expect(foreignValidation.status).toBe(422);
    await stopApi(); base = await startApi(); const restoredValidation = await fetch(`${base}/api/projects/${project.projectId}/cad-validations/${validation.validationId}`, { headers }); expect(restoredValidation.status).toBe(200); await expect(restoredValidation.json()).resolves.toMatchObject({ validationId: validation.validationId, artifact: { sha256: source.artifact.artifactHash } }); const restoredDrawings = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/drawings`, { headers }); expect(restoredDrawings.status).toBe(200); await expect(restoredDrawings.json()).resolves.toHaveLength(7);
  }, 180_000);

  it("creates a real cylindrical hole only from explicit coordinates and approval, then preserves source and project isolation", async () => {
    let base = await startApi(); const projectResponse = await fetch(`${base}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Cylindrical hole proof" }) }); const project = await projectResponse.json() as { projectId: string; accessKey: string }; const headers = { "content-type": "application/json", "x-engineering-access-key": project.accessKey }; const source = await realArtifact(base, project, "Hole source", ["480", "620", "5"]);
    const missing = await fetch(`${base}/api/projects/${project.projectId}/cad-operations/cylindrical-hole/preview`, { method: "POST", headers, body: JSON.stringify({ sourceFileId: source.artifact.cadFileId, parameters: { diameter: 10, unit: "mm" } }) }); expect(missing.status).toBe(422);
    const parameters = { diameter: 10, depth: 7, center: { x: 240, y: -1, z: 310 }, direction: { x: 0, y: 1, z: 0 }, unit: "mm" };
    const previewResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-operations/cylindrical-hole/preview`, { method: "POST", headers, body: JSON.stringify({ sourceFileId: source.artifact.cadFileId, parameters }) }); expect(previewResponse.status).toBe(201); const preview = await previewResponse.json() as { operationId: string; previewStatus: string; source: { sha256: string }; parameters: typeof parameters; feature: { featureId: string; featureRevision: number; parentArtifact: { sha256: string }; dependencies: string[]; executionStatus: string; validationStatus: string }; persistedRecordId: string }; expect(preview).toMatchObject({ previewStatus: "PREVIEW_READY", source: { sha256: source.artifact.artifactHash }, parameters, feature: { featureId: expect.stringMatching(/^FEATURE_CYLINDRICAL_HOLE-/), featureRevision: 1, parentArtifact: { sha256: source.artifact.artifactHash }, executionStatus: "PREVIEW_READY", validationStatus: "VALID" }, persistedRecordId: expect.stringMatching(/^MEMORY-/) });
    await stopApi(); base = await startApi(); const executionResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-operations/cylindrical-hole/${preview.operationId}/approve`, { method: "POST", headers }); expect(executionResponse.status).toBe(201); const execution = await executionResponse.json() as { result: { artifact: { fileId: string; sha256: string }; validationId: string; validationStatus: string }; feature: { featureId: string; featureRevision: number; outputArtifact: { sha256: string }; executionStatus: string }; provenance: { sourceArtifact: { sha256: string }; parameters: typeof parameters; operation: string } }; expect(execution).toMatchObject({ result: { artifact: { sha256: expect.stringMatching(/^[a-f0-9]{64}$/) }, validationStatus: expect.stringMatching(/PASS|WARNING/) }, feature: { featureId: preview.feature.featureId, featureRevision: 1, outputArtifact: { sha256: expect.stringMatching(/^[a-f0-9]{64}$/) }, executionStatus: "KERNEL_VALIDATED" }, provenance: { sourceArtifact: { sha256: source.artifact.artifactHash }, parameters, operation: "CYLINDRICAL_HOLE" } }); expect(execution.result.artifact.fileId).not.toBe(source.artifact.cadFileId);
    const revisedParameters = { ...parameters, diameter: 14 }; const revisedPreviewResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-operations/cylindrical-hole/preview`, { method: "POST", headers, body: JSON.stringify({ sourceFileId: source.artifact.cadFileId, parameters: revisedParameters, featureId: preview.feature.featureId, featureRevision: 2 }) }); expect(revisedPreviewResponse.status).toBe(201); const revisedPreview = await revisedPreviewResponse.json() as { operationId: string; feature: { featureId: string; featureRevision: number; parameters: typeof revisedParameters } }; expect(revisedPreview.feature).toMatchObject({ featureId: preview.feature.featureId, featureRevision: 2, parameters: revisedParameters }); const revisedExecutionResponse = await fetch(`${base}/api/projects/${project.projectId}/cad-operations/cylindrical-hole/${revisedPreview.operationId}/approve`, { method: "POST", headers }); expect(revisedExecutionResponse.status).toBe(201); const revisedExecution = await revisedExecutionResponse.json() as { result: { artifact: { sha256: string } }; feature: { featureId: string; featureRevision: number } }; expect(revisedExecution).toMatchObject({ feature: { featureId: preview.feature.featureId, featureRevision: 2 } }); expect(revisedExecution.result.artifact.sha256).not.toBe(execution.result.artifact.sha256);
    const sourceValidation = await fetch(`${base}/api/projects/${project.projectId}/cad-files/${source.artifact.cadFileId}/validations`, { method: "POST", headers }); expect(sourceValidation.status).toBe(201); await expect(sourceValidation.json()).resolves.toMatchObject({ artifact: { sha256: source.artifact.artifactHash } });
    const foreignResponse = await fetch(`${base}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Foreign hole project" }) }); const foreign = await foreignResponse.json() as { projectId: string; accessKey: string }; const foreignPreview = await fetch(`${base}/api/projects/${foreign.projectId}/cad-operations/cylindrical-hole/preview`, { method: "POST", headers: { "content-type": "application/json", "x-engineering-access-key": foreign.accessKey }, body: JSON.stringify({ sourceFileId: source.artifact.cadFileId, parameters }) }); expect(foreignPreview.status).toBe(422);
  }, 180_000);
});
