import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const h = (letter: string) => letter.repeat(64);
const constraints = ["CPU_LIMIT", "MEMORY_LIMIT", "DISK_LIMIT", "EXECUTION_TIMEOUT", "INPUT_SIZE_LIMIT", "OUTPUT_SIZE_LIMIT", "PROCESS_LIMIT", "CONCURRENT_JOB_LIMIT"] as const;
const verification = ["INPUT_INTEGRITY", "CAD_IDENTITY", "MESH_IDENTITY", "SOLVER_IDENTITY", "SOLVER_VERSION", "UNITS", "BOUNDARY_CONDITIONS", "MATERIAL", "CONVERGENCE", "WARNINGS", "RESULT_INTEGRITY", "REPRODUCIBILITY"] as const;
function jobInput() { return { cadRevision: "CAD-REV-1", cadGeometryHash: h("a"), requirementRevision: "REQ-REV-1", analysisType: "STATIC_STRUCTURAL" as const, analysisVersion: "ANALYSIS-V1", materialReference: "MAT-STEEL-SCHEMA", materialEvidenceHash: h("b"), boundaryConditions: [{ boundaryId: "BC-1", geometryReference: "FACE-1", type: "FIXED" as const, sourceHash: h("c") }], loads: [{ loadId: "LOAD-1", geometryReference: "FACE-2", type: "FORCE" as const, magnitude: 100, unit: "N" as const, direction: "GLOBAL_Z" as const, sourceHash: h("d") }], contacts: [], meshStrategy: { strategyReference: "MESH-STRATEGY-1", strategyHash: h("e"), elementIntent: "TETRAHEDRAL" as const, targetSize: 2, unit: "mm" as const, qualityRequirements: ["Future minimum quality gate"], status: "NOT_EXECUTED" as const }, solverReference: "CALCULIX_LINEAR_STATIC_SCHEMA_ONLY" as const, solverVersion: "SCHEMA-V1", environmentReference: "ENV-REFERENCE-1", resourcePolicy: { policyReference: "RESOURCE-POLICY-1", policyVersion: "V1", policyHash: h("f"), environmentReference: "ENV-REFERENCE-1", constraints: [...constraints] }, expectedOutputs: ["DISPLACEMENT", "VON_MISES_STRESS", "SOLVER_LOG", "EXECUTION_RECEIPT"] as ("DISPLACEMENT" | "VON_MISES_STRESS" | "SOLVER_LOG" | "EXECUTION_RECEIPT")[], verificationRequirements: [...verification], provenance: { requirementIds: ["REQ-1"], requirementRevision: "REQ-REV-1", requirementHash: h("1"), cadRevision: "CAD-REV-1", cadGeometryHash: h("a"), materialReference: "MAT-STEEL-SCHEMA", materialEvidenceHash: h("b"), createdBy: "EngineeringAuthor" }, createdBy: "EngineeringAuthor" }; }

describe("Phase 6.5 canonical CAE Job Contract", () => {
  it("validates immutable project-isolated non-executable job, artifact, verification, traceability, and stale-context contracts", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 6.5 canonical job" }); const access = { projectId: project.id, accessKey: project.accessKey }; const binding = await caller.cae.registerCADRevisionBinding({ ...access, cadProjectId: "CAD-PROJECT-JOB", cadRevision: "CAD-REV-1", cadGeometryHash: h("a"), source: "TEST_CAD_BINDING", creator: "EngineeringAuthor", revision: 1, provenance: ["Phase 6.9 test CAD binding."] }); const base = jobInput(); const input = { ...base, cadBindingId: binding.cadBindingId, cadProjectId: binding.cadProjectId, provenance: { ...base.provenance, cadBindingId: binding.cadBindingId, cadProjectId: binding.cadProjectId } };
    const job = await caller.cae.submitCAEJobContract({ ...access, input }); expect(job).toMatchObject({ contractVersion: "1.0.0", revision: 1, lifecycleState: "VALIDATED", readinessState: "DISABLED", executionEligible: false, executable: false }); expect(job.contractHash).toMatch(/^[a-f0-9]{64}$/); expect(job.meshStrategy.status).toBe("NOT_EXECUTED");
    await expect(caller.cae.submitCAEJobContract({ ...access, input: { ...input, cadRevision: "" } as any })).rejects.toThrow(); await expect(caller.cae.submitCAEJobContract({ ...access, input: { ...input, materialEvidenceHash: "missing" } as any })).rejects.toThrow(); await expect(caller.cae.submitCAEJobContract({ ...access, input: { ...input, loads: [{ ...input.loads[0], unit: "Pa" }] } as any })).rejects.toThrow();
    const staleCad = await caller.cae.evaluateCAEJobStaleness({ ...access, jobId: job.jobId, observedCadRevision: "CAD-REV-2", observedRequirementRevision: "REQ-REV-1", observedMaterialEvidenceHash: h("b"), observedMeshStrategyHash: h("e"), observedSolverVersion: "SCHEMA-V1" }); expect(staleCad).toMatchObject({ status: "STALE", executionEligible: false, executable: false }); const staleRequirements = await caller.cae.evaluateCAEJobStaleness({ ...access, jobId: job.jobId, observedCadRevision: "CAD-REV-1", observedRequirementRevision: "REQ-REV-2", observedMaterialEvidenceHash: h("b"), observedMeshStrategyHash: h("e"), observedSolverVersion: "SCHEMA-V1" }); expect(staleRequirements.status).toBe("STALE");
    const revised = await caller.cae.reviseCAEJobContract({ ...access, jobId: job.jobId, input: { ...input, loads: [{ ...input.loads[0], magnitude: 200 }] } }); expect(revised).toMatchObject({ revision: 2, revisionOf: job.jobId, executionEligible: false, executable: false }); expect((await caller.cae.listCAEJobContracts(access)).map((item) => item.jobId)).toEqual(expect.arrayContaining([job.jobId, revised.jobId]));
    const mesh = await caller.cae.registerNonExecutableMeshArtifact({ ...access, input: { jobId: job.jobId, sourceCadHash: h("a"), elementTypes: ["TETRA4"], coordinatesHash: h("2"), connectivityHash: h("3"), qualitySummary: "NOT_MEASURED", units: "mm", generatorReference: "GMSH-SCHEMA-ONLY", generatorVersion: "V1" } }); expect(mesh).toMatchObject({ jobId: job.jobId, status: "SCHEMA_REGISTERED", executable: false, qualitySummary: "NOT_MEASURED" });
    const solver = await caller.cae.registerAllowlistedSolverArtifact({ ...access, input: { solverName: "CALCULIX", solverVersion: "V2_22", artifactHash: h("4"), source: "OFFICIAL-SOURCE-REFERENCE", signatureStatus: "UNVERIFIED", allowlistStatus: "ALLOWLISTED_NON_EXECUTABLE", capabilities: ["STATIC_STRUCTURAL"], licenseReference: "GPL-2.0-REFERENCE", provenance: ["artifact metadata only"] } }); expect(solver.executable).toBe(false);
    const result = await caller.cae.registerFutureCAEJobResultArtifact({ ...access, input: { jobId: job.jobId, solverReference: "CALCULIX_LINEAR_STATIC_SCHEMA_ONLY", inputHash: h("5"), meshHash: h("6"), resultHash: h("7"), resultTypes: ["DISPLACEMENT"], units: ["mm"], convergenceStatus: "UNKNOWN", warnings: ["Future schema only"], provenance: ["No numerical results recorded"] } }); expect(result).toMatchObject({ verificationStatus: "NOT_VERIFIED", numericalResults: [] }); await expect(caller.cae.registerFutureCAEJobResultArtifact({ ...access, input: { ...result, jobId: "UNKNOWN-JOB" } as any })).rejects.toThrow(); await expect(caller.cae.registerFutureCAEJobResultArtifact({ ...access, input: { jobId: job.jobId, solverReference: "CALCULIX_LINEAR_STATIC_SCHEMA_ONLY", inputHash: h("5"), meshHash: h("6"), resultHash: h("8"), resultTypes: ["DISPLACEMENT"], units: ["mm"], convergenceStatus: "DIVERGED", warnings: ["Claimed solver behavior"], provenance: ["No approved runtime receipt exists"] } })).rejects.toThrow(/solver behavior without an approved runtime receipt/i);
    const record = await caller.cae.createCAEJobVerificationRecord({ ...access, jobId: job.jobId, resultId: result.resultId }); expect(record.status).toBe("NOT_VERIFIED"); expect(record.checks).toHaveLength(12); const trace = await caller.cae.buildCAEJobTraceability({ ...access, jobId: job.jobId }); expect(trace).toHaveLength(7); expect(trace.map((item) => `${item.from}->${item.to}`)).toEqual(expect.arrayContaining(["REQUIREMENT->CAD_REVISION", "CAE_JOB->MESH", "RESULT->VERIFICATION"]));
    const failure = await caller.cae.caeJobFailureModel(); expect(failure.readyForExecutionBehavior).toBe("DISABLED_IN_PHASE_6_5"); expect(failure.prohibited).toEqual(expect.arrayContaining(["ARBITRARY_COMMAND", "ARBITRARY_NETWORK", "ARBITRARY_FILESYSTEM"])); const graph = await caller.cae.caeJobContractGraph({ ...access, jobId: job.jobId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: job.jobId, type: "CAE_SIMULATION" }), expect.objectContaining({ id: job.cadRevision, type: "CAD_REVISION" })])); expect(graph.limitations.join(" ")).toMatch(/No solver, mesher, runtime/i);
    const audit = await caller.cae.securityAudit(access); expect(audit).toEqual(expect.arrayContaining([expect.objectContaining({ objectId: job.jobId, newState: "VALIDATED_NON_EXECUTABLE" })])); const other = await caller.persistentMemory.openProject({ name: "Phase 6.5 isolation" }); await expect(caller.cae.listCAEJobContracts({ projectId: other.id, accessKey: other.accessKey })).resolves.toEqual([]); expect(Object.keys(caller.cae)).not.toEqual(expect.arrayContaining(["executeSolver", "executeMesher", "executeRuntime", "runShell", "runProcess", "runPlugin"]));
  });
});
