import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const base64 = (value: string) => Buffer.from(value, "utf8").toString("base64");
const circle = { title: "Phase 5.2 real kernel source", centerX: 35, centerY: 0, radius: 5, extrudeDistance: 10, unit: "mm" as const };

describe("Phase 5.2 engineering evidence reconciliation and calibration", () => {
  it("keeps real CAD-linked evidence, decisions, datasets, calibration, comparison, graph, and adapter onboarding explicit and non-executable", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 5.2 reconciliation acceptance" }); const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: circle });
    const plan = await caller.cae.createPlan({ projectId: project.id, accessKey: project.accessKey, input: { projectId: project.id, sourceCadRevision: source.revisionId, sourceCadBranch: "ROOT", engineeringQuestion: "Create an evidence-linked structural plan for a real kernel circle extrusion.", analysisType: "STATIC_STRUCTURAL", selectedGeometry: { kind: "FEATURE", id: "EXTRUDE-CIRCLE-001", label: "Real circle extrusion", featureId: "EXTRUDE-CIRCLE-001", source: "FEATURE_TREE" }, featureHistory: ["CIRCLE-SKETCH-001", "EXTRUDE-CIRCLE-001"], geometryProvenance: "OPENCASCADE_KERNEL", geometryValidation: "VALID", material: { name: "Example steel", status: "COMPLETE", properties: [{ name: "ELASTIC_MODULUS", value: 200, unit: "GPa", source: "SOURCE_VERIFIED", requiredFor: ["STATIC_STRUCTURAL"] }, { name: "POISSON_RATIO", value: 0.3, unit: "dimensionless", source: "SOURCE_VERIFIED", requiredFor: ["STATIC_STRUCTURAL"] }] }, boundaryConditions: [{ id: "BC-1", type: "FIXED", direction: "ALL", source: "USER_PROVIDED", confidence: 1, assumptionStatus: "NOT_ASSUMED", geometryStatus: "PROVEN" }], loads: [{ id: "LOAD-1", type: "FORCE", magnitude: 1000, unit: "N", direction: "GLOBAL_Z", source: "USER_PROVIDED", assumptionStatus: "NOT_ASSUMED", geometryStatus: "PROVEN" }], contacts: [], meshStrategy: { elementType: "TETRAHEDRAL", targetSize: 2, unit: "mm", refinementRegions: [], qualityRequirements: ["Future actual mesh quality check"], convergenceRequirement: "Future real convergence study", status: "PLANNED" } } });
    const first = await caller.cae.registerMaterialEvidence({ projectId: project.id, accessKey: project.accessKey, input: { fileName: "grade-a.txt", mimeType: "text/plain", base64: base64("Yield strength 350 MPa"), type: "MATERIAL_DATASHEET", source: "Manufacturer A", material: "Example steel", materialGrade: "A", property: "YIELD_STRENGTH", value: 350, unit: "MPa", condition: "20 C", measurementUncertainty: "±5 MPa", provenance: "VERIFIED_SOURCE" } });
    const second = await caller.cae.registerMaterialEvidence({ projectId: project.id, accessKey: project.accessKey, input: { fileName: "grade-b.txt", mimeType: "text/plain", base64: base64("Yield strength 420 MPa"), type: "TEST_REPORT", source: "Laboratory B", material: "Example steel", materialGrade: "B", property: "YIELD_STRENGTH", value: 0.42, unit: "GPa", condition: "30 C", measurementUncertainty: "±15 MPa", provenance: "EXPERIMENTALLY_MEASURED" } });
    const reconciliation = await caller.cae.reconcileMaterialProperty({ projectId: project.id, accessKey: project.accessKey, material: "Example steel", property: "YIELD_STRENGTH" }); expect(reconciliation).toMatchObject({ state: "CONFLICT" }); expect(reconciliation.candidates).toEqual(expect.arrayContaining([expect.objectContaining({ evidenceId: first.evidenceId, normalizedValue: 350_000_000, normalizedUnit: "Pa" }), expect.objectContaining({ evidenceId: second.evidenceId, normalizedValue: 420_000_000, normalizedUnit: "Pa" })])); expect(reconciliation.conflicts.map((item) => item.kind)).toEqual(expect.arrayContaining(["VALUE_CONFLICT", "CONDITION_CONFLICT", "MATERIAL_GRADE_CONFLICT", "SOURCE_CONFLICT", "MEASUREMENT_UNCERTAINTY_CONFLICT"])); expect(reconciliation.selectedValue).toBeUndefined();
    await expect(caller.cae.recordEngineeringDecision({ projectId: project.id, accessKey: project.accessKey, reconciliationId: reconciliation.reconciliationId, reviewer: "", decision: "RESOLVE", selectedValue: 350, selectedUnit: "MPa", reason: "bad", evidenceIds: [first.evidenceId], revision: 1 })).rejects.toThrow(); const decision = await caller.cae.recordEngineeringDecision({ projectId: project.id, accessKey: project.accessKey, reconciliationId: reconciliation.reconciliationId, reviewer: "Licensed reviewer", reviewerRole: "Materials engineer", decision: "RESOLVE", selectedValue: 350, selectedUnit: "MPa", reason: "Select Manufacturer A after human source review; retain Laboratory B disagreement in the record.", evidenceIds: [first.evidenceId, second.evidenceId], revision: 1 }); expect(decision.authorType).toBe("HUMAN"); const resolved = await caller.cae.reconcileMaterialProperty({ projectId: project.id, accessKey: project.accessKey, material: "Example steel", property: "YIELD_STRENGTH" }); expect(resolved).toMatchObject({ state: "RESOLVED", selectedValue: 350, selectedUnit: "MPa" });
    const experiment = await caller.cae.createExperimentalPlan({ projectId: project.id, accessKey: project.accessKey, input: { simulationId: plan.simulationId, objective: "Capture force samples", hypothesis: "Measured records will support a future comparison.", testArticle: "Real test article", instrumentation: ["Load cell"], loads: ["Declared load"], boundaryConditions: ["Declared fixture"], measurements: ["Force"], acceptanceCriteria: ["Review before use"], uncertainties: ["Calibration unknown"], repeatability: "Three repeats", safetyRequirements: ["Qualified review"], simulationComparison: "No comparison result until an actual solver executes." } });
    const csv = "time,force[N]\n0,0\n1,10\n1,10\n"; const dataset = await caller.cae.ingestMeasurementDataset({ projectId: project.id, accessKey: project.accessKey, fileName: "force.csv", mimeType: "text/csv", base64: base64(csv), simulationId: plan.simulationId, experimentId: experiment.experimentId, metadata: { source: "Test lab", instrument: "Load cell", instrumentId: "LC-001", operator: "Operator", testDate: "2026-08-21", units: "N", samplingRate: "1 Hz", environment: "Lab", temperature: "20 C", humidity: "45%", testArticle: "Real test article", testRevision: source.revisionId, calibrationStatus: "UNKNOWN", uncertainty: "UNKNOWN", provenance: "MEASURED" } }); expect(dataset.fileHash).toBe(createHash("sha256").update(csv).digest("hex")); expect(dataset.stage).toBe("RAW"); expect(dataset.quality).toMatchObject({ status: "INCONSISTENT", duplicateSamples: 1, timestampsPresent: true }); const duplicate = await caller.cae.ingestMeasurementDataset({ projectId: project.id, accessKey: project.accessKey, fileName: "force-copy.csv", mimeType: "text/csv", base64: base64(csv), simulationId: plan.simulationId, metadata: { source: "Test lab", calibrationStatus: "UNKNOWN", provenance: "MEASURED" } }); expect(duplicate.datasetId).toBe(dataset.datasetId);
    const processing = await caller.cae.createDatasetProcessing({ projectId: project.id, accessKey: project.accessKey, datasetId: dataset.datasetId, stage: "NORMALIZED", transformation: "Declared unit-normalization proposal; raw dataset was not changed.", evidenceIds: [dataset.datasetId] }); expect(processing).toMatchObject({ stage: "NORMALIZED", sourceHash: dataset.fileHash, truthCategory: "DERIVED" }); const calibration = await caller.cae.recordCalibration({ projectId: project.id, accessKey: project.accessKey, datasetId: dataset.datasetId, instrument: "Load cell", calibrationDate: "2026-08-01", calibrationSource: "Certificate holder", certificateReference: "CERT-001", validFrom: "2026-08-01", validUntil: "2027-08-01", uncertainty: "±1%", status: "CALIBRATED", evidenceIds: [first.evidenceId], truthCategory: "DERIVED" }); expect(calibration.status).toBe("CALIBRATED"); await expect(caller.cae.recordCalibration({ projectId: project.id, accessKey: project.accessKey, instrument: "Unknown", status: "CALIBRATED", evidenceIds: [], truthCategory: "UNKNOWN" })).rejects.toThrow();
    const comparison = await caller.cae.createComparison({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId, datasetId: dataset.datasetId, quantity: "Force", measurementValue: 10, uncertainty: "±1%", comparisonMethod: "Future time-aligned point comparison" }); expect(comparison).toMatchObject({ status: "NO_SIMULATION_RESULT", measurementValue: 10 }); expect("simulationValue" in comparison).toBe(false); expect("difference" in comparison).toBe(false); expect("relativeDifference" in comparison).toBe(false); const candidate = await caller.cae.createCalibrationCandidate({ projectId: project.id, accessKey: project.accessKey, comparisonId: comparison.comparisonId, statement: "Future candidate only; no material or solver parameter changed." }); expect(candidate).toMatchObject({ status: "CALIBRATION_CANDIDATE", requiresHumanReview: true, prohibitsAutomaticParameterChange: true });
    const manifest = "{" + "\"id\":\"hypothetical\"" + "}"; const adapter = await caller.cae.registerExternalSolverAdapter({ projectId: project.id, accessKey: project.accessKey, input: { solverId: "HYPOTHETICAL", solverName: "Hypothetical Solver", version: "0.0", provider: "Test provider", adapterVersion: "1.0.0", supportedAnalysisTypes: ["STATIC_STRUCTURAL"], capabilities: ["planned static input"], executionMode: "CLOUD_UNCONFIGURED", inputSchemaVersion: "1", outputSchemaVersion: "1", securityRequirements: ["No shell", "No arbitrary filesystem", "No network without authorization"], adapterManifest: manifest, adapterHash: createHash("sha256").update(manifest).digest("hex"), publisherIdentity: "Unverified publisher", signature: "untrusted-signature", capabilityManifest: ["STATIC_STRUCTURAL"] } }); expect(adapter).toMatchObject({ verificationStatus: "UNVERIFIED", executable: false, revocable: true }); const graph = await caller.cae.extendedEvidenceGraph({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: dataset.datasetId, type: "MEASURED_DATASET" }), expect.objectContaining({ id: processing.recordId, type: "DATASET_PROCESSING" }), expect.objectContaining({ id: calibration.calibrationId, type: "CALIBRATION" }), expect.objectContaining({ id: comparison.comparisonId, type: "COMPARISON" }), expect.objectContaining({ id: decision.decisionId, type: "ENGINEERING_DECISION" }), expect.objectContaining({ id: adapter.registrationId, type: "ADAPTER_REGISTRATION" })])); expect(graph.limitations.join(" ")).toContain("non-executable");
  }, 120_000);
});
