import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const h = (letter: string) => letter.repeat(64);
const limits = ["CPU_LIMIT", "MEMORY_LIMIT", "DISK_LIMIT", "EXECUTION_TIMEOUT", "INPUT_SIZE_LIMIT", "OUTPUT_SIZE_LIMIT", "PROCESS_LIMIT", "CONCURRENT_JOB_LIMIT"] as const;
function planInput(projectId: string) { return { projectId, sourceCadRevision: "CAD-REV-PLAN-1", sourceCadBranch: "ROOT", engineeringQuestion: "Assess a bounded linear-static structural load case.", analysisType: "STATIC_STRUCTURAL" as const, selectedGeometry: { kind: "FACE" as const, id: "FACE-LOAD", label: "Declared load face", source: "VIEWER" as const }, featureHistory: ["FEATURE-1"], geometryProvenance: "OPENCASCADE_KERNEL" as const, geometryValidation: "VALID" as const, requirementIds: ["REQ-PLAN-1"], material: { materialId: "MAT-STEEL-1", name: "Steel schema", status: "COMPLETE" as const, properties: [{ name: "ELASTIC_MODULUS" as const, value: 210, unit: "GPa", source: "SOURCE_VERIFIED" as const, provenance: "Material evidence schema", requiredFor: ["STATIC_STRUCTURAL" as const] }, { name: "POISSON_RATIO" as const, value: 0.3, unit: "dimensionless", source: "SOURCE_VERIFIED" as const, provenance: "Material evidence schema", requiredFor: ["STATIC_STRUCTURAL" as const] }] }, boundaryConditions: [{ id: "BC-1", geometryReference: "FACE-FIXED", type: "FIXED" as const, source: "USER_PROVIDED" as const, confidence: 1, assumptionStatus: "NOT_ASSUMED" as const, geometryStatus: "PROVEN" as const }], loads: [{ id: "LOAD-1", type: "FORCE" as const, geometryReference: "FACE-LOAD", magnitude: 100, unit: "N", direction: "GLOBAL_Z" as const, source: "USER_PROVIDED" as const, assumptionStatus: "NOT_ASSUMED" as const, geometryStatus: "PROVEN" as const }], contacts: [], meshStrategy: { elementType: "TETRAHEDRAL" as const, targetSize: 2, unit: "mm", refinementRegions: [], qualityRequirements: ["Future quality evidence must be attached."], convergenceRequirement: "Future convergence policy", status: "PLANNED" as const } }; }

describe("Phase 6.6 CAE plan integration and mesh quality evidence", () => {
  it("captures validated plans, preserves immutable conversion, compares revisions, and fail-closes non-executable mesh quality evidence", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 6.6 integration" }); const access = { projectId: project.id, accessKey: project.accessKey }; const plan = await caller.cae.createPlan({ ...access, input: planInput(project.id) });
    const snapshot = await caller.cae.captureValidatedCAEPlanSnapshot({ ...access, simulationId: plan.simulationId, sourceCadGeometryHash: h("a"), requirementRevision: "REQ-REV-1", requirementHash: h("b"), materialEvidenceHash: h("c"), expectedOutputs: ["DISPLACEMENT", "VON_MISES_STRESS", "SOLVER_LOG", "EXECUTION_RECEIPT"] }); expect(snapshot).toMatchObject({ validationStatus: "VALIDATED", immutable: true, simulationId: plan.simulationId, sourceCadRevision: plan.sourceCadRevision }); expect(snapshot.validationFindings).toEqual([]); await expect(caller.cae.captureValidatedCAEPlanSnapshot({ ...access, simulationId: plan.simulationId, sourceCadGeometryHash: "bad", requirementRevision: "REQ-REV-1", requirementHash: h("b"), materialEvidenceHash: h("c"), expectedOutputs: ["DISPLACEMENT", "VON_MISES_STRESS"] } as any)).rejects.toThrow();
    const resourcePolicy = { policyReference: "RESOURCE-POLICY-1", policyVersion: "V1", policyHash: h("d"), environmentReference: "ENV-1", constraints: [...limits] }; const converted = await caller.cae.convertCAEPlanSnapshotToJob({ ...access, snapshotId: snapshot.snapshotId, solverVersion: "SCHEMA-V1", environmentReference: "ENV-1", resourcePolicy, createdBy: "IntegrationAuthor" }); expect(converted).toMatchObject({ conversion: { status: "CONVERTED_NON_EXECUTABLE", informationLoss: [] }, job: { executionEligible: false, executable: false, cadRevision: plan.sourceCadRevision, requirementRevision: "REQ-REV-1", materialEvidenceHash: h("c") } }); expect(converted.job.loads).toHaveLength(1); expect(converted.job.boundaryConditions).toHaveLength(1); expect(converted.job.provenance.sourcePlanId).toBe(plan.simulationId); const snapshots = await caller.cae.listCAEPlanSnapshots(access); expect(snapshots.find((item) => item.snapshotId === snapshot.snapshotId)?.planHash).toBe(snapshot.planHash);
    const revised = await caller.cae.reviseCAEJobContract({ ...access, jobId: converted.job.jobId, input: { ...converted.job, loads: [{ ...converted.job.loads[0]!, magnitude: 200 }], createdBy: "IntegrationAuthor" } as any }); const diff = await caller.cae.createCAEJobDiff({ ...access, baselineJobId: converted.job.jobId, comparedJobId: revised.jobId }); expect(diff).toMatchObject({ readOnly: true }); expect(diff.entries.find((item) => item.field === "LOADS")?.status).toBe("CHANGED"); expect(diff.entries.find((item) => item.field === "CAD_HASH")?.status).toBe("UNCHANGED");
    await expect(caller.cae.registerNonExecutableMeshArtifact({ ...access, input: { jobId: converted.job.jobId, sourceCadHash: h("z"), elementTypes: ["TETRA4"], coordinatesHash: h("1"), connectivityHash: h("2"), qualitySummary: "NOT_MEASURED", units: "mm", generatorReference: "MESH-SCHEMA", generatorVersion: "V1" } })).rejects.toThrow(); const mesh = await caller.cae.registerNonExecutableMeshArtifact({ ...access, input: { jobId: converted.job.jobId, sourceCadHash: h("a"), nodeCount: 0, elementCount: 0, elementTypes: ["UNKNOWN"], coordinatesHash: h("1"), connectivityHash: h("2"), qualitySummary: "NOT_MEASURED", units: "UNKNOWN", generatorReference: "MESH-SCHEMA", generatorVersion: "V1" } }); expect(mesh.executable).toBe(false);
    const qualityInput = { meshId: mesh.meshId, jobId: converted.job.jobId, sourceCadHash: h("a"), meshGenerator: "MESH-SCHEMA", meshGeneratorVersion: "V1", elementTypes: ["UNKNOWN"] as ("UNKNOWN" | "TETRA4" | "TETRA10" | "HEXA8" | "SHELL4" | "BEAM2")[], elementCount: 0, nodeCount: 0, qualityMetrics: [{ metric: "UNKNOWN" as const, source: "UNKNOWN" as const, status: "UNKNOWN" as const }], qualityThresholds: [{ metric: "ASPECT_RATIO" as const, value: 1, unit: "schema-unit", source: "Threshold evidence schema", version: "T-V1", rationale: "Schema validation fixture; no engineering threshold is claimed.", evidenceHash: h("3") }], provenance: { cadRevision: converted.job.cadRevision, cadGeometryHash: h("a"), jobId: converted.job.jobId, jobRevision: converted.job.revision, meshArtifactId: mesh.meshId, meshGenerator: "MESH-SCHEMA", meshGeneratorVersion: "V1", qualityAlgorithm: "QUALITY-SCHEMA", qualityAlgorithmVersion: "V1", thresholdVersion: "T-V1", references: ["Provenance schema only"] }, reportedStatus: "PASS" as const };
    const quality = await caller.cae.registerMeshQualityEvidence({ ...access, input: qualityInput }); expect(quality).toMatchObject({ qualityStatus: "UNKNOWN", executable: false }); const stale = await caller.cae.evaluateMeshQualityStaleness({ ...access, evidenceId: quality.evidenceId, observedCadHash: h("e"), observedJobId: converted.job.jobId, observedMeshId: mesh.meshId, observedQualityAlgorithmVersion: "V1", observedThresholdVersion: "T-V1" }); expect(stale).toMatchObject({ status: "STALE", executionEligible: false, executable: false });
    const conflict = await caller.cae.registerMeshQualityEvidence({ ...access, input: { ...qualityInput, qualityMetrics: [{ metric: "ASPECT_RATIO", value: 1, unit: "schema-unit", source: "DECLARED", status: "KNOWN" }, { metric: "ASPECT_RATIO", value: 2, unit: "schema-unit", source: "DECLARED", status: "KNOWN" }], reportedStatus: "WARNING" } }); expect(conflict.qualityStatus).toBe("CONFLICT"); const graph = await caller.cae.caePlanIntegrationGraph({ ...access, jobId: converted.job.jobId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: converted.job.jobId }), expect.objectContaining({ id: snapshot.snapshotId })])); expect(graph.limitations.join(" ")).toMatch(/no solver or mesher/i);
    const other = await caller.persistentMemory.openProject({ name: "Phase 6.6 isolation" }); await expect(caller.cae.listCAEPlanSnapshots({ projectId: other.id, accessKey: other.accessKey })).resolves.toEqual([]); expect(Object.keys(caller.cae)).not.toEqual(expect.arrayContaining(["runGmsh", "runCalculiX", "executeSolver", "executeMesher", "runShell", "runProcess"]));
  });
});
