import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const file = (text: string) => Buffer.from(text, "utf8").toString("base64");
const circleInput = { title: "Phase 5.1 evidence source", centerX: 30, centerY: 0, radius: 5, extrudeDistance: 10, unit: "mm" as const };

describe("Phase 5.1 CAE evidence and solver adapter foundation", () => {
  it("links a real kernel-validated CAD revision to immutable material evidence, a conflict, an experiment, explicit uncertainty, readiness, graph, review, and stale CAD detection without numerical output", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 5.1 evidence acceptance" }); const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: circleInput });
    const plan = await caller.cae.createPlan({ projectId: project.id, accessKey: project.accessKey, input: { projectId: project.id, sourceCadRevision: source.revisionId, sourceCadBranch: "ROOT", engineeringQuestion: "Create a static structural simulation planning record for the validated mounting interface.", selectedGeometry: { kind: "FEATURE", id: "EXTRUDE-CIRCLE-001", label: "Offset circular structural feature", featureId: "EXTRUDE-CIRCLE-001", source: "FEATURE_TREE" }, featureHistory: ["CIRCLE-SKETCH-001", "EXTRUDE-CIRCLE-001"], geometryProvenance: "OPENCASCADE_KERNEL", geometryValidation: "VALID", requirementIds: ["REQ-VALIDATION-001"], material: { name: "Example steel", status: "COMPLETE", properties: [{ name: "ELASTIC_MODULUS", value: 200, unit: "GPa", source: "SOURCE_VERIFIED", requiredFor: ["STATIC_STRUCTURAL"] }, { name: "POISSON_RATIO", value: 0.3, unit: "dimensionless", source: "SOURCE_VERIFIED", requiredFor: ["STATIC_STRUCTURAL"] }] }, boundaryConditions: [{ id: "BC-1", geometryReference: "FEATURE:EXTRUDE-CIRCLE-001", type: "FIXED", direction: "ALL", source: "USER_PROVIDED", confidence: 1, assumptionStatus: "NOT_ASSUMED", geometryStatus: "PROVEN" }], loads: [{ id: "LOAD-1", type: "FORCE", geometryReference: "FEATURE:EXTRUDE-CIRCLE-001", magnitude: 1000, unit: "N", direction: "GLOBAL_Z", source: "USER_PROVIDED", assumptionStatus: "NOT_ASSUMED", geometryStatus: "PROVEN" }], contacts: [], meshStrategy: { elementType: "TETRAHEDRAL", targetSize: 2, unit: "mm", refinementRegions: [], qualityRequirements: ["Check Jacobian quality."], convergenceRequirement: "Run an actual mesh convergence study after a solver is connected.", status: "PLANNED" } } });
    const adapter = await caller.cae.solverAdapter(); expect(adapter).toMatchObject({ contractVersion: "1.0.0", solverId: "NO_EXECUTABLE_SOLVER", status: "UNAVAILABLE", executable: false });
    const negotiation = await caller.cae.negotiateSolver({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId }); expect(negotiation).toMatchObject({ status: "UNAVAILABLE", adapter: { contractVersion: "1.0.0", status: "UNAVAILABLE" } });
    const first = await caller.cae.registerMaterialEvidence({ projectId: project.id, accessKey: project.accessKey, input: { fileName: "steel-datasheet.txt", mimeType: "text/plain", base64: file("Young modulus 200 GPa"), type: "MATERIAL_DATASHEET", source: "Manufacturer A", sourceDate: "2026-08-20", material: "Example steel", property: "ELASTIC_MODULUS", value: 200, unit: "GPa", condition: "room temperature", provenance: "VERIFIED_SOURCE" } });
    const same = await caller.cae.registerMaterialEvidence({ projectId: project.id, accessKey: project.accessKey, input: { fileName: "steel-datasheet.txt", mimeType: "text/plain", base64: file("Young modulus 200 GPa"), type: "MATERIAL_DATASHEET", source: "Manufacturer A", material: "Example steel", property: "ELASTIC_MODULUS", value: 200, unit: "GPa", provenance: "VERIFIED_SOURCE" } }); expect(same.evidenceId).toBe(first.evidenceId);
    const second = await caller.cae.registerMaterialEvidence({ projectId: project.id, accessKey: project.accessKey, input: { fileName: "steel-test-report.txt", mimeType: "text/plain", base64: file("Measured modulus 180 GPa"), type: "TEST_REPORT", source: "Test laboratory B", material: "Example steel", property: "ELASTIC_MODULUS", value: 180, unit: "GPa", condition: "room temperature", provenance: "EXPERIMENTALLY_MEASURED" } }); expect(second.sha256).not.toBe(first.sha256);
    const evidence = await caller.cae.listMaterialEvidence({ projectId: project.id, accessKey: project.accessKey }); expect(evidence).toEqual(expect.arrayContaining([expect.objectContaining({ evidenceId: first.evidenceId, sha256: expect.stringMatching(/^[a-f0-9]{64}$/), version: 1, verificationStatus: "VERIFIED" }), expect.objectContaining({ evidenceId: second.evidenceId, provenance: "EXPERIMENTALLY_MEASURED" })]));
    const conflicts = await caller.cae.materialConflicts({ projectId: project.id, accessKey: project.accessKey }); expect(conflicts).toEqual(expect.arrayContaining([expect.objectContaining({ property: "ELASTIC_MODULUS", status: "CONFLICT", evidenceIds: expect.arrayContaining([first.evidenceId, second.evidenceId]), requiresResolution: true })]));
    const experiment = await caller.cae.createExperimentalPlan({ projectId: project.id, accessKey: project.accessKey, input: { simulationId: plan.simulationId, objective: "Measure interface response under declared loading.", hypothesis: "The physical test will characterize the declared boundary and load response.", testArticle: "Instrumented mounting article", instrumentation: ["Load cell", "Displacement sensor"], loads: ["1000 N axial load"], boundaryConditions: ["Declared fixture"], measurements: ["Force", "Displacement"], samplingRate: "1 kHz", environment: "room temperature", acceptanceCriteria: ["Compare future solver output only after an executable run."], uncertainties: ["Fixture compliance", "Sensor calibration"], repeatability: "Three controlled repeats", safetyRequirements: ["Qualified test review before execution"], simulationComparison: "No comparison exists until a real solver result and measured evidence are available." } }); expect(experiment).toMatchObject({ simulationId: plan.simulationId, sourceCadRevision: source.revisionId, status: "READY_FOR_REVIEW" });
    const readiness = await caller.cae.readiness({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId }); expect(readiness).toMatchObject({ state: "READY_FOR_EXPERIMENT" }); expect(readiness.evidence).toEqual(expect.arrayContaining([expect.objectContaining({ category: "SOLVER", status: "FAIL", blocking: true })]));
    const uncertainty = await caller.cae.uncertainty({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId }); expect(uncertainty.items.map((item) => item.category)).toEqual(expect.arrayContaining(["MATERIAL", "GEOMETRY", "LOAD", "BOUNDARY", "MEASUREMENT", "MESH", "SOLVER", "EXPERIMENTAL_DATA"])); expect(uncertainty.summary).toContain("No uncertainty is collapsed");
    const graph = await caller.cae.evidenceGraph({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: source.revisionId, type: "CAD_REVISION" }), expect.objectContaining({ id: plan.simulationId, type: "CAE_SIMULATION" }), expect.objectContaining({ id: first.evidenceId, type: "MATERIAL_EVIDENCE" }), expect.objectContaining({ id: experiment.experimentId, type: "EXPERIMENT" })])); expect(graph.edges.some((item) => item.fromId === plan.simulationId && item.toId === experiment.experimentId)).toBe(true);
    const revised = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: { ...circleInput, title: "Changed CAD revision", radius: 6 } }); const stale = await caller.cae.invalidateCadContext({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId, observedCadRevision: revised.revisionId }); expect(stale).toMatchObject({ status: "STALE", previousCadRevision: source.revisionId, observedCadRevision: revised.revisionId }); expect(stale.affectedAssumptions).toContain("Topology references");
    const review = await caller.cae.reviewPlan({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId }); expect(review.adversarialReview).toEqual(expect.arrayContaining([expect.objectContaining({ reviewer: "EXPERIMENTAL", status: "UNKNOWN" }), expect.objectContaining({ reviewer: "SOLVER", status: "FAIL" })])); expect(review.selfCritique.experimentalMismatch?.join(" ")).toContain("No experimental plan"); expect(review.selfCritique.uncertaintyWarnings?.join(" ")).toContain("uncertainty");
    const execution = await caller.cae.requestExecution({ projectId: project.id, accessKey: project.accessKey, simulationId: plan.simulationId }); expect(execution).toMatchObject({ executed: false, result: { status: "SOLVER_UNAVAILABLE", numericalResults: [] } });
  }, 120_000);
});
