import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { createLocalCamToolpath, inspectLocalCamEngine, type CamOperation, type CamStock, type CamTool } from "../server/camEngine";
import { executeAndPersistLocalCam, listManagedCamArtifacts } from "../server/camExecution";
import { extractKernelViewerMesh, getOpenCascadeKernel } from "../server/cadKernel";
import { openPersistentProject, projectMemorySnapshot } from "../server/persistentMemory";

const sourceHash = createHash("sha256").update("real-opencascade-cam-box").digest("hex");
const tool: CamTool = { toolId: "T01-FLAT-6", type: "FLAT_END_MILL", diameterMm: 6, fluteCount: 2, material: "CARBIDE", maxSpindleRpm: 24_000, maxFeedMmMin: 2_000, cuttingFeedMmMin: 600, spindleRpm: 12_000 };
const stock: CamStock = { stockId: "STOCK-BOX-01", sizeMm: [30, 30, 30], originMm: [0, 0, 0], material: "TEST_FIXTURE", workOrigin: "STOCK_MIN_CORNER", coordinateSystem: "CARTESIAN_MM" };

async function geometry() { const oc = await getOpenCascadeKernel(); const box = new oc.BRepPrimAPI_MakeBox_2(20, 20, 20); try { return { sourceCadHash: sourceHash, vertices: extractKernelViewerMesh(oc, box.Shape(), "CAM-REAL-BOX", 1).vertices }; } finally { box.delete?.(); } }
const op = (kind: CamOperation["kind"]): CamOperation => ({ operationId: `OP-${kind}`, kind, depthMm: 2, safeZMm: 25, stepOverMm: 5, ...(kind === "POCKET" ? { pocket: { minX: 5, minY: 5, maxX: 15, maxY: 15 } } : {}) });

describe.sequential("local real 2.5D CAM engine", () => {
  it("discovers the deterministic local geometry-derived toolpath engine", () => { expect(inspectLocalCamEngine()).toMatchObject({ status: "ENGINE_AVAILABLE", engine: "CAD_AI_2P5D_CAM", supportedOperations: ["FACING", "POCKET", "CONTOUR"], supportedPostProcessors: ["GRBL_1_1"] }); });
  it("derives non-empty finite and stock-bounded facing, pocket, and contour paths from actual OpenCascade geometry", async () => { const source = await geometry(); for (const kind of ["FACING", "POCKET", "CONTOUR"] as const) { const result = createLocalCamToolpath({ geometry: source, tool, stock, operation: op(kind) }); expect(result).toMatchObject({ status: "READY", postProcessor: "GRBL_1_1", toolpathHash: expect.stringMatching(/^[a-f0-9]{64}$/), gcodeHash: expect.stringMatching(/^[a-f0-9]{64}$/) }); expect(result.toolpath?.length).toBeGreaterThan(0); expect(result.toolpath?.every((item) => [...item.from, ...item.to].every(Number.isFinite))).toBe(true); expect(result.gcode?.toString("utf8")).toMatch(/^%\n[\s\S]*G21[\s\S]*G90[\s\S]*G94[\s\S]*M30\n%\n$/); } }, 30_000);
  it("fails closed for invalid tool, stock, and machining envelope inputs", async () => { const source = await geometry(); expect(createLocalCamToolpath({ geometry: source, tool: { ...tool, cuttingFeedMmMin: 0 }, stock, operation: op("FACING") }).status).toBe("INVALID_INPUT"); expect(createLocalCamToolpath({ geometry: source, tool, stock: { ...stock, sizeMm: [10, 10, 10] }, operation: op("FACING") }).status).toBe("GEOMETRY_INVALID"); expect(createLocalCamToolpath({ geometry: source, tool, stock, operation: { ...op("POCKET"), pocket: { minX: -1, minY: 5, maxX: 15, maxY: 15 } } }).status).toBe("GEOMETRY_INVALID"); });
  it("persists only the exact validated G-code with provenance and immutable lineage", async () => { const project = await openPersistentProject({ name: "Real CAM artifact" }); const result = await executeAndPersistLocalCam({ projectId: project.id, accessKey: project.accessKey, geometry: await geometry(), tool, stock, operation: op("CONTOUR") }); expect(result).toMatchObject({ status: "READY", gcode: undefined, artifact: expect.objectContaining({ projectId: project.id, sourceCadHash: sourceHash, toolpathHash: expect.stringMatching(/^[a-f0-9]{64}$/), gcodeHash: expect.stringMatching(/^[a-f0-9]{64}$/), storageUrl: expect.stringMatching(/^\/manus-storage\//) }) }); const artifacts = await listManagedCamArtifacts({ projectId: project.id, accessKey: project.accessKey }); expect(artifacts).toEqual(expect.arrayContaining([expect.objectContaining({ artifactId: result.artifact?.artifactId })])); const snapshot = await projectMemorySnapshot({ projectId: project.id, accessKey: project.accessKey }); expect(snapshot.lineage).toEqual(expect.arrayContaining([expect.objectContaining({ sourceRecordId: result.artifact?.artifactId, kind: "CONFIGURATION", status: "VALIDATED" })])); }, 30_000);
});
