import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const base64 = (value: string) => Buffer.from(value, "utf8").toString("base64");
const adapterInput = (manifest: string) => ({ solverId: "TRUST-CLOSURE-ADAPTER", solverName: "Trust Closure Adapter", version: "1.0.0", provider: "Verified Publisher", adapterVersion: "1.0.0", supportedAnalysisTypes: ["STATIC_STRUCTURAL" as const], capabilities: ["STATIC_STRUCTURAL"], executionMode: "CLOUD_UNCONFIGURED" as const, inputSchemaVersion: "1", outputSchemaVersion: "1", securityRequirements: ["No shell", "No arbitrary filesystem", "No network"], adapterManifest: manifest, adapterHash: createHash("sha256").update(manifest).digest("hex"), publisherIdentity: "Publisher identity", signature: "detached-signature", capabilityManifest: ["STATIC_STRUCTURAL"] });
const status = (readiness: { gates: Array<{ gate: string; status: string }> }, gate: string) => readiness.gates.find((item) => item.gate === gate)?.status;

describe("Phase 5.4 execution-trust closure", () => {
  it("records independent trust evidence, exposes all nine gates, rejects incomplete or revoked signals, and permanently keeps execution disabled", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 5.4 execution trust closure" }); const access = { projectId: project.id, accessKey: project.accessKey }; const adapter = await caller.cae.registerExternalSolverAdapter({ ...access, input: adapterInput("{\"adapter\":\"closure\"}") }); const reviewer = await caller.cae.registerReviewer({ ...access, displayName: "Trust Reviewer", role: "Independent engineering reviewer", projectScope: [project.id], permissions: ["APPROVE_SOLVER_ADAPTER", "APPROVE_CALIBRATION", "APPROVE_VALIDATION"], actor: "Security admin" });
    const claim = await caller.cae.claimExternalIdentity({ ...access, provider: "Identity provider", providerVersion: "v1", subject: "publisher-subject", verificationMethod: "Provider claim", evidence: ["claim-evidence"], actor: "Publisher" }); expect(claim.status).toBe("IDENTITY_CLAIMED"); await expect(caller.cae.verifyExternalIdentity({ ...access, claimId: claim.claimId, reviewerId: reviewer.reviewerId, providerVerified: true, evidenceVerified: true, reason: "Blocked unverified reviewer" })).rejects.toThrow(/not verified/); await caller.cae.verifyReviewer({ ...access, reviewerId: reviewer.reviewerId, verificationMethod: "Independent human identity check", actor: "Security admin" }); const verifiedClaim = await caller.cae.verifyExternalIdentity({ ...access, claimId: claim.claimId, reviewerId: reviewer.reviewerId, providerVerified: true, evidenceVerified: true, reason: "Provider and evidence independently reviewed" }); expect(verifiedClaim.status).toBe("IDENTITY_VERIFIED");
    const certificate = await caller.cae.attachCalibrationCertificate({ ...access, fileName: "cert.txt", base64: base64("certificate"), issuer: "Accredited issuer", certificateNumber: "CERT-CLOSURE", instrument: "Load cell", calibrationDate: "2026-01-01", expirationDate: "2099-01-01", scope: "Force", uncertainty: "±1%", actor: "Lab owner" }); await caller.cae.verifyCalibrationCertificate({ ...access, certificateId: certificate.certificateId, reviewerId: reviewer.reviewerId, sourceVerified: true, signatureVerified: true, scopeMatch: true, reason: "Certificate independently verified" }); const singleSource = await caller.cae.ingestRevocationSource({ ...access, source: "Source A", sourceIdentity: "issuer-a", sourceContentBase64: base64("source-a"), certificateIdentifier: "CERT-CLOSURE", reportedStatus: "VALID", independentSourceCount: 1, sourceVerified: true, evidence: ["retrieval-a"], reviewerId: reviewer.reviewerId, actor: "Reviewer" }); expect(singleSource).toMatchObject({ revocationStatus: "UNKNOWN", verificationStatus: "UNVERIFIED" }); const sourceA = await caller.cae.ingestRevocationSource({ ...access, source: "Source A refresh", sourceIdentity: "issuer-a", sourceContentBase64: base64("source-a-refresh"), certificateIdentifier: "CERT-CLOSURE", reportedStatus: "VALID", independentSourceCount: 2, sourceVerified: true, evidence: ["retrieval-a-refresh"], reviewerId: reviewer.reviewerId, actor: "Reviewer" }); const sourceB = await caller.cae.ingestRevocationSource({ ...access, source: "Source B", sourceIdentity: "issuer-b", sourceContentBase64: base64("source-b"), certificateIdentifier: "CERT-CLOSURE", reportedStatus: "VALID", independentSourceCount: 2, sourceVerified: true, evidence: ["retrieval-b"], reviewerId: reviewer.reviewerId, actor: "Reviewer" }); expect(sourceA.sourceHash).toMatch(/^[a-f0-9]{64}$/); expect(sourceB.revocationStatus).toBe("VALID");
    const trust = await caller.cae.verifyAdapterTrust({ ...access, registrationId: adapter.registrationId, reviewerId: reviewer.reviewerId, manifestVerified: true, signatureVerified: true, verifiedCapabilities: ["STATIC_STRUCTURAL"], grantedPermissions: ["READ_CAD", "READ_REQUIREMENTS"], reason: "Manifest, signature, capability, and permissions independently checked" }); expect(trust).toMatchObject({ trustState: "VERIFIED", executable: false }); await caller.cae.authorizeEngineeringApproval({ ...access, reviewerId: reviewer.reviewerId, targetType: "ADAPTER", targetId: adapter.registrationId, decision: "APPROVE", evidenceIds: [trust.verificationId], revision: 1, reason: "Human approval after verification" }); const attestation = await caller.cae.declareSandboxAttestation({ ...access, registrationId: adapter.registrationId, version: "1.0.0", environmentIdentity: "bounded-cloud-environment", runtimeIdentity: "no-runtime", runtimeVersion: "0", operatingSystem: "cloud", resourceLimits: ["No runtime provisioned"], filesystemBoundary: ["managed evidence only"], networkPolicy: "NO_NETWORK", processPolicy: "No process execution", isolationMechanism: "declaration plus independent verification", attestationEvidence: ["attestation-evidence"], actor: "Security administrator" }); expect(attestation.verificationStatus).toBe("UNATTESTED"); const sandbox = await caller.cae.verifySandboxAttestation({ ...access, attestationId: attestation.attestationId, reviewerId: reviewer.reviewerId, identityVerified: true, integrityVerified: true, configurationVerified: true, permissionsVerified: true, resourceBoundariesVerified: true, networkRestrictionsVerified: true, filesystemRestrictionsVerified: true, reason: "Independent attestation verification" }); expect(sandbox.status).toBe("ATTESTED");
    const missing = await caller.cae.evaluateExecutionTrustReadiness({ ...access, registrationId: adapter.registrationId }); expect(missing.executionEligible).toBe(false); expect(missing.gates.every((item) => item.status !== "PASS") || status(missing, "EXECUTION_ELIGIBILITY")).toBeTruthy(); const readiness = await caller.cae.evaluateExecutionTrustReadiness({ ...access, registrationId: adapter.registrationId, externalIdentityClaimId: verifiedClaim.claimId, certificateId: certificate.certificateId, attestationId: attestation.attestationId }); expect(readiness.gates).toHaveLength(9); expect(status(readiness, "IDENTITY")).toBe("PASS"); expect(status(readiness, "ADAPTER_SIGNATURE")).toBe("PASS"); expect(status(readiness, "CAPABILITY")).toBe("PASS"); expect(status(readiness, "PERMISSIONS")).toBe("PASS"); expect(status(readiness, "CERTIFICATE")).toBe("PASS"); expect(status(readiness, "REVIEWER_APPROVAL")).toBe("PASS"); expect(status(readiness, "SANDBOX_ATTESTATION")).toBe("PASS"); expect(status(readiness, "REVOCATION_CHECK")).toBe("PASS"); expect(status(readiness, "EXECUTION_ELIGIBILITY")).toBe("FAIL"); expect(readiness).toMatchObject({ executionEligible: false, executable: false, gatesSatisfied: false });
    const revoked = await caller.cae.revokeExecutionTrustEvidence({ ...access, objectType: "EXTERNAL_IDENTITY", objectId: verifiedClaim.claimId, actor: "Security administrator", reason: "Identity revocation drill" }); expect(revoked.newState).toBe("REVOKED"); const revokedReadiness = await caller.cae.evaluateExecutionTrustReadiness({ ...access, registrationId: adapter.registrationId, externalIdentityClaimId: verifiedClaim.claimId, certificateId: certificate.certificateId, attestationId: attestation.attestationId }); expect(status(revokedReadiness, "IDENTITY")).toBe("FAIL"); expect(status(revokedReadiness, "REVOCATION_CHECK")).toBe("FAIL"); expect(revokedReadiness.executionEligible).toBe(false); const replacement = await caller.cae.claimExternalIdentity({ ...access, provider: "Identity provider", providerVersion: "v2", subject: "publisher-subject-reissued", verificationMethod: "Reissued provider claim", evidence: ["reissue-evidence"], actor: "Publisher" }); const restored = await caller.cae.verifyExternalIdentity({ ...access, claimId: replacement.claimId, reviewerId: reviewer.reviewerId, providerVerified: true, evidenceVerified: true, reason: "New independently verified identity claim" }); const restoredReadiness = await caller.cae.evaluateExecutionTrustReadiness({ ...access, registrationId: adapter.registrationId, externalIdentityClaimId: restored.claimId, certificateId: certificate.certificateId, attestationId: attestation.attestationId }); expect(status(restoredReadiness, "IDENTITY")).toBe("PASS"); expect(restoredReadiness.executionEligible).toBe(false);
    const benchmark = await caller.cae.runExecutionTrustSecurityBenchmark(access); expect(benchmark).toHaveLength(16); expect(benchmark.every((item) => item.expectedEligibility === false && item.observedEligibility === false && item.passed)).toBe(true); const audits = await caller.cae.securityAudit(access); expect(audits).toEqual(expect.arrayContaining([expect.objectContaining({ objectId: verifiedClaim.claimId, action: "REVOCATION" })])); const graph = await caller.cae.executionTrustEvidenceGraph({ ...access, simulationId: "NO-SOLVER", registrationId: adapter.registrationId, readinessId: restoredReadiness.readinessId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: restoredReadiness.readinessId, type: "EXECUTION_ELIGIBILITY" }), expect.objectContaining({ id: `${restoredReadiness.readinessId}-EXECUTION_ELIGIBILITY`, type: "EXECUTION_TRUST_GATE" })]));
  }, 120_000);
});
