import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const digest = (value: string) => createHash("sha256").update(value).digest("hex");
const kinds = ["CPU", "RAM", "STORAGE", "IO", "NETWORK", "PROCESS_LIMIT", "RESOURCE_LIMIT"] as const;

describe("Phase 6.2 external verification readiness", () => {
  it("preserves external evidence, refuses unverified or expired evidence, and never enables execution", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 6.2 external verification" }); const access = { projectId: project.id, accessKey: project.accessKey };
    const raw = "deterministic external evidence fixture";
    await expect(caller.cae.importInfrastructureEvidence({ ...access, kind: "CPU", measurement: "fixture CPU evidence", measurementMethod: "fixture import only", environment: "external-test-environment", source: "external fixture", issuer: "independent fixture issuer", timestamp: "2026-08-21T00:00:00.000Z", rawEvidence: raw, originalHash: "0".repeat(64), verificationMethod: "fixture verification" })).rejects.toThrow(/Original hash/i);
    const imported = [] as Array<{ evidenceId: string; kind: string; provenance: { originalHash: string }; verificationStatus: string }>;
    for (const kind of kinds) { const fixture = `${kind} external evidence fixture`; imported.push(await caller.cae.importInfrastructureEvidence({ ...access, kind, measurement: `${kind} measured fixture`, measurementMethod: "external fixture measurement", environment: "external-test-environment", source: "external fixture source", issuer: "independent fixture issuer", timestamp: "2026-08-21T00:00:00.000Z", rawEvidence: fixture, originalHash: digest(fixture), verificationMethod: "external import" })); }
    expect(imported.every((item) => item.verificationStatus === "UNVERIFIED")).toBe(true); expect(imported[0]?.provenance.originalHash).toBe(digest("CPU external evidence fixture"));
    const initially = await caller.cae.evaluateExternalVerificationReadiness(access); expect(initially).toMatchObject({ readiness: "NOT_READY", executionApproval: "DISABLED", executionEligible: false, executable: false });
    const sandboxRaw = "external sandbox review fixture"; const sandbox = await caller.cae.importSandboxReview({ ...access, reviewer: "External sandbox assessor", organization: "Independent assessor", scope: "Future runtime sandbox", architectureRevision: "PHASE-6.1", findings: ["No runtime was assessed by this fixture."], severity: "UNKNOWN", source: "external review fixture", issuer: "independent assessor", timestamp: "2026-08-21T00:00:00.000Z", rawEvidence: sandboxRaw, originalHash: digest(sandboxRaw), verificationMethod: "external document import", reportedStatus: "ACCEPTED" }); expect(sandbox).toMatchObject({ reportedStatus: "ACCEPTED", status: "NOT_REVIEWED", verificationStatus: "UNVERIFIED" });
    const environment = await caller.cae.registerHostileTestEnvironment({ ...access, environmentName: "External hostile-test fixture environment", declaredIsolation: "DESIGNED" }); expect(environment).toMatchObject({ productionExecutionProhibited: true, verificationStatus: "UNVERIFIED" });
    const logs = "fixture hostile-test logs"; const artifacts = ["fixture-artifact-ref"]; const hostileRaw = "external hostile test fixture"; const hostile = await caller.cae.importHostileTestEvidence({ ...access, testId: "FIXTURE-FILESYSTEM-ESCAPE", environmentId: environment.environmentId, testVersion: "1.0.0", attackDescription: "Fixture import representing an externally executed test; no production test is run.", expectedResult: "Fixture expectation is denial.", actualResult: "Fixture report says denied.", logs, artifacts, timestamp: "2026-08-21T00:00:00.000Z", hash: digest(`${logs}\n${artifacts.join("\n")}`), reviewer: "External test assessor", status: "PASS", source: "external test fixture", issuer: "independent assessor", rawEvidence: hostileRaw, originalHash: digest(hostileRaw), verificationMethod: "external evidence import" }); expect(hostile).toMatchObject({ status: "PASS", verificationStatus: "UNVERIFIED" }); expect((await caller.cae.evaluateExternalVerificationReadiness(access)).readiness).toBe("NOT_READY");
    const reviewer = await caller.cae.registerReviewer({ ...access, displayName: "Verified external evidence reviewer", role: "Security reviewer", projectScope: [project.id], permissions: ["APPROVE_VALIDATION"], actor: "fixture administrator" }); await caller.cae.verifyReviewer({ ...access, reviewerId: reviewer.reviewerId, verificationMethod: "fixture identity confirmation", actor: "fixture administrator" });
    for (const item of imported) await caller.cae.verifyExternalEvidence({ ...access, evidenceType: "INFRASTRUCTURE", evidenceId: item.evidenceId, reviewerId: reviewer.reviewerId, sourceVerified: true, verificationMethod: "independent fixture review", reason: "Fixture source and hash reviewed." });
    await caller.cae.verifyExternalEvidence({ ...access, evidenceType: "SANDBOX_REVIEW", evidenceId: sandbox.reviewId, reviewerId: reviewer.reviewerId, sourceVerified: true, verificationMethod: "independent fixture review", reason: "Fixture sandbox-review source reviewed." });
    await caller.cae.verifyExternalEvidence({ ...access, evidenceType: "HOSTILE_TEST_ENVIRONMENT", evidenceId: environment.environmentId, reviewerId: reviewer.reviewerId, sourceVerified: true, verificationMethod: "independent fixture review", reason: "Fixture environment-isolation evidence reviewed." });
    await caller.cae.verifyExternalEvidence({ ...access, evidenceType: "HOSTILE_TEST", evidenceId: hostile.evidenceId, reviewerId: reviewer.reviewerId, sourceVerified: true, verificationMethod: "independent fixture review", reason: "Fixture hostile-test source and artifact hash reviewed." });
    const externalReview = await caller.cae.evaluateExternalVerificationReadiness(access); expect(externalReview).toMatchObject({ readiness: "READY_FOR_EXTERNAL_REVIEW", executionApproval: "DISABLED", executionEligible: false, executable: false }); expect(externalReview.gates.every((gate) => gate.status === "PASS")).toBe(true);
    await caller.cae.recordExternalEvidenceLifecycle({ ...access, evidenceType: "INFRASTRUCTURE", evidenceId: imported[0]!.evidenceId, event: "EXPIRED", reason: "Fixture expiration", actor: "fixture administrator" }); const expired = await caller.cae.evaluateExternalVerificationReadiness(access); expect(expired.readiness).toBe("NOT_READY"); expect(expired.gates.find((gate) => gate.gate === "INFRASTRUCTURE")?.status).not.toBe("PASS");
    const restoredRaw = "replacement CPU external evidence fixture"; const restored = await caller.cae.importInfrastructureEvidence({ ...access, kind: "CPU", measurement: "CPU measured fixture", measurementMethod: "external fixture measurement", environment: "external-test-environment", source: "replacement fixture", issuer: "independent fixture issuer", timestamp: "2026-08-21T00:00:01.000Z", rawEvidence: restoredRaw, originalHash: digest(restoredRaw), verificationMethod: "external import" }); await caller.cae.verifyExternalEvidence({ ...access, evidenceType: "INFRASTRUCTURE", evidenceId: restored.evidenceId, reviewerId: reviewer.reviewerId, sourceVerified: true, verificationMethod: "independent fixture review", reason: "Replacement fixture source and hash reviewed." }); expect((await caller.cae.evaluateExternalVerificationReadiness(access)).readiness).toBe("READY_FOR_EXTERNAL_REVIEW");
    const conflictRaw = "contradictory CPU external evidence fixture"; const conflict = await caller.cae.importInfrastructureEvidence({ ...access, kind: "CPU", measurement: "Contradictory CPU measured fixture", measurementMethod: "external fixture measurement", environment: "external-test-environment", source: "conflicting fixture", issuer: "independent fixture issuer", timestamp: "2026-08-21T00:00:02.000Z", rawEvidence: conflictRaw, originalHash: digest(conflictRaw), verificationMethod: "external import" }); await caller.cae.verifyExternalEvidence({ ...access, evidenceType: "INFRASTRUCTURE", evidenceId: conflict.evidenceId, reviewerId: reviewer.reviewerId, sourceVerified: true, verificationMethod: "independent fixture review", reason: "Conflict fixture source and hash reviewed." }); const contradiction = await caller.cae.evaluateExternalVerificationReadiness(access); expect(contradiction).toMatchObject({ readiness: "NOT_READY", executionEligible: false, executable: false }); expect(contradiction.contradictions.length).toBeGreaterThan(0);
    const graph = await caller.cae.externalVerificationGraph({ ...access, readinessId: contradiction.readinessId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ type: "EXTERNAL_VERIFICATION_READINESS" }), expect.objectContaining({ id: conflict.evidenceId, type: "EXTERNAL_INFRASTRUCTURE_EVIDENCE" })])); const audit = await caller.cae.securityAudit(access); expect(audit).toEqual(expect.arrayContaining([expect.objectContaining({ action: "EXTERNAL_EVIDENCE_IMPORT", objectId: imported[0]!.evidenceId }), expect.objectContaining({ action: "EXTERNAL_EVIDENCE_LIFECYCLE", objectId: imported[0]!.evidenceId })])); const other = await caller.persistentMemory.openProject({ name: "Phase 6.2 isolated project" }); await expect(caller.cae.listInfrastructureEvidence({ projectId: other.id, accessKey: other.accessKey })).resolves.toEqual([]); expect(Object.keys(caller.cae)).not.toEqual(expect.arrayContaining(["executeSolver", "executeHostileTest", "executeRuntime", "runShell", "launchPlugin", "openFilesystem"]));
  }, 120_000);
});
