import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { canMachineBeCertified, evaluateMachineCamRelease, validateFixtureStock, validateGcodeAgainstController, validateTooling, type CamVerification, type MachineCamInput } from "../server/machineAwareCam";

const verification: CamVerification = { axisTravel: "PASS", toolpathSimulation: "PASS", toolFixtureCollision: "PASS", holderCollision: "PASS", stockCollision: "PASS", rapidMoves: "PASS", spindleFeedLimits: "PASS", unsupportedCommands: "PASS", controllerValidation: "PASS", postValidation: "PASS", gcodeSyntax: "PASS" };
const machine = { machineId: "VF2-001", machineType: "3_AXIS_MILL" as const, axes: ["X", "Y", "Z"], travelLimitsMm: { x: 762, y: 406, z: 508 }, spindleLimitsRpm: { min: 100, max: 8100 }, feedLimitsMmMin: { min: 1, max: 12000 }, rapidLimitMmMin: 18000, controller: { identity: "HAAS-NGC", version: "100.22" }, postProcessor: "haas-ngc-v2", coordinateConventions: "G54 / Z+ away from table", workOffsetBehavior: "Explicit G54", toolChangeBehavior: "M06 with spindle stop", safetyConstraints: ["Door interlock", "Dry-run"], revision: "machine-r1", active: true };
const tooling = { toolId: "T06", toolType: "END_MILL" as const, diameterMm: 10, fluteCount: 3, lengthMm: 63, holder: "ER20", stickoutMm: 28, material: "carbide", spindleLimitsRpm: { min: 3000, max: 8100 }, feedLimitsMmMin: { min: 120, max: 1800 }, provenance: "tool://T06/r4" };
const fixture = { stockId: "STOCK-01", stockMm: { x: 100, y: 60, z: 25 }, fixture: "vise", clamps: ["left", "right"], workholding: "soft jaws", machineTable: "T-slot", keepOutZones: ["jaw envelope"], collisionAnalysisSupported: true, revision: "fixture-r1" };
const gcode = "%\n; CONTROLLER:HAAS-NGC\n; POST:haas-ngc-v2\nG90 G54\nM30\n%";
const input = (): MachineCamInput => ({ cadRevision: "cad-r7", camOperation: "OP-10", machine, tooling, fixture, selectedController: "HAAS-NGC", selectedPost: "haas-ngc-v2", generatedToolpathHash: `sha256:${"a".repeat(64)}`, gcode, gcodeHash: `sha256:${createHash("sha256").update(gcode).digest("hex")}`, verification, capturedMachineRevision: "machine-r1", capturedToolProvenance: "tool://T06/r4" });

describe("machine-aware CAM/CNC governance", () => {
  it("accepts complete machine, tooling, fixture, controller, post, G-code, and provenance", () => { const result = evaluateMachineCamRelease(input()); expect(result).toMatchObject({ status: "MACHINE_TRIAL_REQUIRED", releaseAllowed: true, machineCertified: false }); expect(result.blockers).toEqual([]); });
  it("never certifies automatically even when all digital checks pass", () => { const result = evaluateMachineCamRelease(input()); expect(canMachineBeCertified(result, false)).toBe(false); expect(canMachineBeCertified(result, true)).toBe(true); });
  it.each(["axisTravel", "toolFixtureCollision", "holderCollision", "stockCollision", "rapidMoves", "spindleFeedLimits", "unsupportedCommands", "controllerValidation", "postValidation", "gcodeSyntax"] as const)("fails closed for %s", (key) => { const value = input(); value.verification = { ...verification, [key]: "FAIL" }; expect(evaluateMachineCamRelease(value).releaseAllowed).toBe(false); });
  it("rejects incomplete tooling and invalid holder", () => { expect(validateTooling({ ...tooling, holder: "" })).toContain("INVALID_TOOL_HOLDER"); expect(validateTooling({ ...tooling, diameterMm: 0 })).toContain("INVALID_TOOL_DIAMETER"); expect(validateTooling({ ...tooling, stickoutMm: 70 })).toContain("INVALID_TOOL_GEOMETRY"); });
  it("rejects incomplete fixtures and unsupported collision analysis", () => { expect(validateFixtureStock({ ...fixture, clamps: [] })).toContain("INVALID_FIXTURE_CLAMPS"); expect(validateFixtureStock({ ...fixture, collisionAnalysisSupported: false })).toContain("FIXTURE_COLLISION_ANALYSIS_UNSUPPORTED"); });
  it.each([
    ["controller mismatch", "; CONTROLLER:OTHER", "CONTROLLER_MISMATCH"],
    ["post mismatch", "; POST:other", "POST_MISMATCH"],
    ["unsupported command", "G28", "UNSUPPORTED_GCODE_COMMAND"],
    ["malformed program", "G90", "MALFORMED_GCODE"],
  ])("rejects %s", (_name, fragment, expected) => { const candidate = fragment.includes(":") ? gcode.replace(fragment.startsWith("; CONTROLLER") ? "; CONTROLLER:HAAS-NGC" : "; POST:haas-ngc-v2", fragment) : `${gcode}\n${fragment}`; expect(validateGcodeAgainstController(candidate, "HAAS-NGC", "haas-ngc-v2")).toContain(expected); });
  it("rejects stale machine, CAD, tooling, hash, and unsafe verification inputs", () => { const staleMachine = input(); staleMachine.capturedMachineRevision = "old"; expect(evaluateMachineCamRelease(staleMachine).blockers).toContain("STALE_MACHINE_PROFILE"); const staleCad = input(); staleCad.cadRevision = ""; expect(evaluateMachineCamRelease(staleCad).blockers).toContain("STALE_CAD_REVISION"); const staleTool = input(); staleTool.capturedToolProvenance = "old"; expect(evaluateMachineCamRelease(staleTool).blockers).toContain("STALE_TOOLING"); const badHash = input(); badHash.gcodeHash = "sha256:" + "b".repeat(64); expect(evaluateMachineCamRelease(badHash).blockers).toContain("GCODE_HASH_MISMATCH"); const unsafeRapid = input(); unsafeRapid.verification = { ...verification, rapidMoves: "FAIL" }; expect(evaluateMachineCamRelease(unsafeRapid).releaseAllowed).toBe(false); });
});
