import { beforeAll, describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const artifact = (kind: "REQUIREMENT_SET" | "CAD_MODEL", title: string, revision: string, sourceArtifactIds: string[] = []) => ({ kind, title, revision, state: "DECLARED" as const, truthStatus: "UNVERIFIED" as const, sourceArtifactIds, externalSourceRecordIds: [], provenance: ["Optimization foundation acceptance fixture."], limitations: ["No numerical solver or performance result is claimed."], declaredBy: "OptimizationFixture" });

describe("Phase 6.14 Conceptual Optimization Foundation", () => {
  const caller = appRouter.createCaller(ctx);
  let access: { projectId: string; accessKey: string };
  let other: { projectId: string; accessKey: string };
  let cad: any;
  let study: any;
  let candidate: any;

  beforeAll(async () => {
    const project = await caller.persistentMemory.openProject({ name: "Phase 6.14 conceptual optimization" });
    const isolated = await caller.persistentMemory.openProject({ name: "Phase 6.14 optimization isolation" });
    access = { projectId: project.id, accessKey: project.accessKey };
    other = { projectId: isolated.id, accessKey: isolated.accessKey };
    const requirements = await caller.digitalThread.createArtifact({ ...access, input: artifact("REQUIREMENT_SET", "Declared optimization requirements", "REQ-OPT-R1") });
    cad = await caller.digitalThread.createArtifact({ ...access, input: artifact("CAD_MODEL", "Parametric design source", "CAD-OPT-R1", [requirements.artifactId]) });
    study = await caller.optimization.createStudy({ ...access, input: { title: "Mass and manufacturability exploration", revision: "OPT-R1", sourceArtifactIds: [cad.artifactId], method: "MULTI_OBJECTIVE_PLAN", variables: [{ variableId: "WALL_THICKNESS", name: "Wall thickness", kind: "CONTINUOUS", unit: "mm", minimum: 1.5, maximum: 4, sourceArtifactId: cad.artifactId, truthStatus: "UNVERIFIED" }], objectives: [{ objectiveId: "MINIMIZE_MASS", title: "Minimize mass", direction: "MINIMIZE", metricReference: "Requires verified material density and CAD volume evidence.", unit: "kg", sourceArtifactIds: [cad.artifactId], evaluationAvailability: "NUMERICAL_CAE_UNAVAILABLE", truthStatus: "UNVERIFIED" }], constraints: [{ constraintId: "MANUFACTURING_CONSTRAINT", title: "Declared manufacturing constraint", comparison: "DECLARED", sourceArtifactIds: [cad.artifactId], evaluationAvailability: "CONCEPTUAL_ONLY", truthStatus: "UNVERIFIED" }], state: "DECLARED", provenance: ["CAD source artifact retained."], limitations: ["No verified numerical CAE environment exists."], declaredBy: "OptimizationFixture" } });
    candidate = await caller.optimization.createCandidate({ ...access, input: { optimizationStudyId: study.optimizationStudyId, candidateLabel: "Candidate A · 2.5 mm", parameterValues: [{ variableId: "WALL_THICKNESS", value: 2.5, truthStatus: "UNVERIFIED" }], sourceArtifactIds: [cad.artifactId], provenance: ["Declared parameter candidate."], limitations: ["No regeneration or numerical evaluation was performed."], declaredBy: "OptimizationFixture" } });
  });

  it("1. creates an immutable CAD-bound optimization study with unavailable numerical evaluation", () => expect(study).toMatchObject({ evaluationAvailability: "NUMERICAL_CAE_UNAVAILABLE", numericalResultsAvailable: false, executionEligible: false, executable: false, retention: { historicalRecordPreserved: true, deletionPolicy: "NO_SILENT_DELETION" } }));
  it("2. rejects a study without a project-scoped CAD model source", async () => await expect(caller.optimization.createStudy({ ...access, input: { title: "Unbound study", revision: "BAD-R1", sourceArtifactIds: ["MISSING-ARTIFACT"], method: "SINGLE_OBJECTIVE_PLAN", variables: [{ variableId: "V", name: "V", kind: "CONTINUOUS", sourceArtifactId: "MISSING", truthStatus: "UNVERIFIED" }], objectives: [{ objectiveId: "O", title: "O", direction: "MINIMIZE", metricReference: "M", sourceArtifactIds: [cad.artifactId], evaluationAvailability: "CONCEPTUAL_ONLY", truthStatus: "UNVERIFIED" }], constraints: [], state: "DECLARED", provenance: ["p"], limitations: [], declaredBy: "Fixture" } })).rejects.toThrow(/CAD model artifact/i));
  it("3. rejects a numerical-unavailable objective falsely described as calculated", async () => await expect(caller.optimization.createStudy({ ...access, input: { title: "False numerical study", revision: "BAD-R2", sourceArtifactIds: [cad.artifactId], method: "SINGLE_OBJECTIVE_PLAN", variables: [{ variableId: "V", name: "V", kind: "CONTINUOUS", sourceArtifactId: cad.artifactId, truthStatus: "UNVERIFIED" }], objectives: [{ objectiveId: "O", title: "O", direction: "MINIMIZE", metricReference: "M", sourceArtifactIds: [cad.artifactId], evaluationAvailability: "NUMERICAL_CAE_UNAVAILABLE", truthStatus: "CALCULATED" }], constraints: [], state: "DECLARED", provenance: ["p"], limitations: [], declaredBy: "Fixture" } })).rejects.toThrow(/cannot be represented as CALCULATED/i));
  it("4. records a conceptual candidate without objective values, constraint values, rank, or regenerated CAD", () => expect(candidate).toMatchObject({ evaluationStatus: "NOT_EVALUATED", objectiveValues: [], constraintValues: [], rankingState: "BLOCKED_NUMERICAL_EVALUATION_UNAVAILABLE", rankAssigned: false, validity: "CONCEPTUAL_ONLY", executionEligible: false, executable: false }));
  it("5. rejects candidate values for undeclared or duplicated design variables", async () => { await expect(caller.optimization.createCandidate({ ...access, input: { optimizationStudyId: study.optimizationStudyId, candidateLabel: "Invalid variable", parameterValues: [{ variableId: "UNKNOWN", value: 3, truthStatus: "UNVERIFIED" }], sourceArtifactIds: [cad.artifactId], provenance: ["p"], limitations: [], declaredBy: "Fixture" } })).rejects.toThrow(/declared study variables/i); await expect(caller.optimization.createCandidate({ ...access, input: { optimizationStudyId: study.optimizationStudyId, candidateLabel: "Duplicate variable", parameterValues: [{ variableId: "WALL_THICKNESS", value: 2, truthStatus: "UNVERIFIED" }, { variableId: "WALL_THICKNESS", value: 3, truthStatus: "UNVERIFIED" }], sourceArtifactIds: [cad.artifactId], provenance: ["p"], limitations: [], declaredBy: "Fixture" } })).rejects.toThrow(/cannot duplicate/i); });
  it("6. returns an assessment that refuses ranking, Pareto selection, sensitivity results, and numerical claims", async () => expect(await caller.optimization.assess({ ...access, optimizationStudyId: study.optimizationStudyId })).toMatchObject({ rankingState: "BLOCKED_NUMERICAL_EVALUATION_UNAVAILABLE", executionEligible: false, executable: false, limitations: expect.arrayContaining([expect.stringMatching(/No numerical CAE evidence/i)]) }));
  it("7. preserves optimization studies and candidates in the digital thread", async () => { const artifacts = await caller.digitalThread.listArtifacts(access); expect(artifacts.map((item) => item.kind)).toEqual(expect.arrayContaining(["OPTIMIZATION_STUDY", "OPTIMIZATION_CANDIDATE"])); });
  it("8. isolates studies and candidates by project", async () => { expect(await caller.optimization.listStudies(other)).toEqual([]); expect(await caller.optimization.listCandidates(other)).toEqual([]); });
  it("9. exposes no candidate evaluation, ranking, Pareto, regeneration, solver, mesher, or process execution endpoint", () => expect(Object.keys(caller.optimization)).not.toEqual(expect.arrayContaining(["evaluateCandidate", "rankCandidates", "generatePareto", "regenerateCAD", "executeSolver", "executeMesher", "runProcess"])));
});
