import type { TrpcContext } from "../server/_core/context";
import { appRouter } from "../server/routers";
import { describe, expect, it } from "vitest";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const offsetBoss = { title: "Phase 4.9 offset boss", centerX: 30, centerY: 30, radius: 4, extrudeDistance: 8, unit: "mm" as const };

describe("Phase 4.9 controlled CAD capability expansion", () => {
  it("recognizes only explicit circular and rectangular pattern inputs, returning targeted questions rather than guessed geometry references", async () => {
    const caller = appRouter.createCaller(ctx);
    const xPlan = await caller.featureHistory.planCircularPattern({ message: "source: CIRCLE-REVISION-abcdef; feature: EXTRUDE-CIRCLE-001; axis: GLOBAL_X; 3 instances; 120°" });
    const yPlan = await caller.featureHistory.planCircularPattern({ message: "source: CIRCLE-REVISION-abcdef; feature: EXTRUDE-CIRCLE-001; axis: GLOBAL_Y; 3 instances; 120°" });
    expect(xPlan).toMatchObject({ status: "READY_FOR_PREVIEW", input: { axis: "GLOBAL_X", instanceCount: 3 } }); expect(yPlan).toMatchObject({ status: "READY_FOR_PREVIEW", input: { axis: "GLOBAL_Y", instanceCount: 3 } });
    const incomplete = await caller.featureHistory.planRectangularPattern({ message: "Make a rectangular pattern of these bosses" });
    expect(incomplete).toMatchObject({ status: "OPEN_QUESTION", executable: false, operation: "RECTANGULAR_PATTERN" }); expect(incomplete.questions).toEqual(expect.arrayContaining([expect.stringContaining("source revision"), expect.stringContaining("X direction"), expect.stringContaining("spacing")]));
    const ready = await caller.featureHistory.planRectangularPattern({ message: "source: CIRCLE-REVISION-abcdef; feature: EXTRUDE-CIRCLE-001; direction x: GLOBAL_X_POSITIVE; direction y: GLOBAL_Y_POSITIVE; 3 x 2; spacing x: 20mm; spacing y: 25mm" });
    expect(ready).toMatchObject({ status: "READY_FOR_PREVIEW", input: { countX: 3, countY: 2, spacingX: 20, spacingY: 25 } });
  });

  it("creates real OpenCascade circular patterns about GLOBAL_X, GLOBAL_Y, and GLOBAL_Z and preserves each explicit axis in immutable history", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 4.9 global axes" }); const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: offsetBoss });
    for (const axis of ["GLOBAL_X", "GLOBAL_Y", "GLOBAL_Z"] as const) { const revision = await caller.featureHistory.createCircularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: `Pattern ${axis}`, sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", axis, instanceCount: 3, angleDegrees: 120, direction: "COUNTERCLOCKWISE" } }); const node = revision.features.find((feature) => feature.featureType === "CIRCULAR_PATTERN"); expect(revision).toMatchObject({ status: "KERNEL_VALIDATED", geometry: { validation: "VALID", export: { format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED" } } }); expect(node?.operationData?.axis).toBe(axis); expect(node?.generatedInstances).toHaveLength(3); expect(revision.geometry.export?.provenance?.sha256).toMatch(/^[a-f0-9]{64}$/); }
  }, 90_000);

  it("creates, edits, branches, exports, and topology-checks a real guarded rectangular pattern without mutating its parent", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 4.9 rectangular pattern" }); const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: offsetBoss });
    const base = await caller.featureHistory.createRectangularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "3 by 2 grid", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", directionX: "GLOBAL_X_POSITIVE", directionY: "GLOBAL_Y_POSITIVE", countX: 3, countY: 2, spacingX: 20, spacingY: 25, unit: "mm" } });
    const node = base.features.find((feature) => feature.featureType === "RECTANGULAR_PATTERN"); expect(base).toMatchObject({ status: "KERNEL_VALIDATED", parentRevisionId: source.revisionId, geometry: { validation: "VALID", export: { status: "AVAILABLE", format: "STEP_GEOMETRY" } } }); expect(node?.generatedInstances).toHaveLength(6); expect(node?.operationData).toMatchObject({ count_x: 3, count_y: 2, spacing_x_mm: 20, spacing_y_mm: 25 }); expect(base.geometry.export?.provenance?.sha256).toMatch(/^[a-f0-9]{64}$/);
    const preview = await caller.featureHistory.previewRectangularPattern({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: base.revisionId, edit: { spacingX: 30, countX: 2, unit: "mm" } }); expect(preview).toMatchObject({ status: "PREVIEW", geometry: { validation: "VALID" } }); const child = await caller.featureHistory.executeRectangularPattern({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: preview.revisionId }); expect(child).toMatchObject({ status: "KERNEL_VALIDATED", parentRevisionId: base.revisionId }); expect(base.features.find((feature) => feature.featureType === "RECTANGULAR_PATTERN")?.operationData?.spacing_x_mm).toBe(20); expect(child.features.find((feature) => feature.featureType === "RECTANGULAR_PATTERN")?.operationData?.spacing_x_mm).toBe(30);
    const report = await caller.featureHistory.topologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: base.revisionId, targetRevisionId: child.revisionId }); expect(report.summary.invalidated).toBeGreaterThan(0); expect(report.matches.some((match) => match.status === "TOPOLOGY_REFERENCE_INVALIDATED")).toBe(true); const gate = await caller.featureHistory.filletGate({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: base.revisionId, targetRevisionId: child.revisionId }); expect(gate.ready).toBe(false); expect(gate.missing).toEqual(expect.arrayContaining(["TOPOLOGY_MATCHING", "KERNEL_FILLET_EXECUTION_SUPPORTED"]));
    const invalid = await caller.featureHistory.createRectangularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "overlap", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", directionX: "GLOBAL_X_POSITIVE", directionY: "GLOBAL_Y_POSITIVE", countX: 2, countY: 1, spacingX: 8, spacingY: 20, unit: "mm" } }); expect(invalid).toMatchObject({ status: "FAILED", failure: { stage: "VALIDATION" } }); expect(base.status).toBe("KERNEL_VALIDATED");
  }, 90_000);

  it("stress-tests repeated pattern regeneration, expansion, reduction, branches, unsafe matching, invalid inputs, and independent real-kernel builds", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 4.9 topology stress" }); const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: offsetBoss });
    const base = await caller.featureHistory.createRectangularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "stress base", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", directionX: "GLOBAL_X_POSITIVE", directionY: "GLOBAL_Y_POSITIVE", countX: 2, countY: 2, spacingX: 20, spacingY: 20, unit: "mm" } });
    const expansionPreview = await caller.featureHistory.previewRectangularPattern({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: base.revisionId, edit: { countX: 3, countY: 2, spacingX: 24, unit: "mm" } }); const expanded = await caller.featureHistory.executeRectangularPattern({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: expansionPreview.revisionId });
    const growth = await caller.featureHistory.topologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: base.revisionId, targetRevisionId: expanded.revisionId }); expect(growth.summary.newEntities).toBeGreaterThan(0); expect(growth.summary.ambiguous).toBeGreaterThan(0);
    const reductionPreview = await caller.featureHistory.previewRectangularPattern({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: expanded.revisionId, edit: { countX: 1, countY: 2, spacingY: 28, unit: "mm" } }); const reduced = await caller.featureHistory.executeRectangularPattern({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: reductionPreview.revisionId });
    const reduction = await caller.featureHistory.topologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: expanded.revisionId, targetRevisionId: reduced.revisionId }); expect(reduction.summary.invalidated).toBeGreaterThan(0); expect(reduction.matches.some((match) => match.status === "TOPOLOGY_REFERENCE_INVALIDATED")).toBe(true);
    const branchPreview = await caller.featureHistory.previewRectangularPattern({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: base.revisionId, edit: { countX: 2, countY: 3, spacingX: 26, unit: "mm" } }); const branch = await caller.featureHistory.executeRectangularPattern({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: branchPreview.revisionId }); expect(branch.parentRevisionId).toBe(base.revisionId); expect(reduced.parentRevisionId).toBe(expanded.revisionId); expect(base.status).toBe("KERNEL_VALIDATED");
    const independentA = await caller.featureHistory.createRectangularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "independent A", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", directionX: "GLOBAL_X_POSITIVE", directionY: "GLOBAL_Y_POSITIVE", countX: 2, countY: 2, spacingX: 20, spacingY: 20, unit: "mm" } }); const independentB = await caller.featureHistory.createRectangularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "independent B", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", directionX: "GLOBAL_X_POSITIVE", directionY: "GLOBAL_Y_POSITIVE", countX: 2, countY: 2, spacingX: 20, spacingY: 20, unit: "mm" } }); const independent = await caller.featureHistory.topologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: independentA.revisionId, targetRevisionId: independentB.revisionId }); expect(independent.summary.matched).toBeGreaterThan(0); expect(independent.summary.invalidated).toBe(0);
    await expect(caller.featureHistory.createCircularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "invalid axis", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", axis: "ARBITRARY_AXIS" as any, instanceCount: 3, angleDegrees: 120, direction: "COUNTERCLOCKWISE" } })).rejects.toThrow(); await expect(caller.featureHistory.createRectangularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "invalid direction", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", directionX: "ARBITRARY" as any, directionY: "GLOBAL_Y_POSITIVE", countX: 2, countY: 2, spacingX: 20, spacingY: 20, unit: "mm" } })).rejects.toThrow();
  }, 120_000);
});
