import { describe, expect, it } from "vitest";
import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";
import { runWorkbenchMessage } from "../server/cadWorkbench";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const circleInput = { title: "Phase 4.10 offset boss", centerX: 30, centerY: 0, radius: 5, extrudeDistance: 10, unit: "mm" as const };

describe("Phase 4.10 CAD foundation closure", () => {
  it("uses real kernel circle topology evidence to report deterministic rim proof, explicit ambiguity, persistence, replacement, and deletion without transient-handle claims", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 4.10 edge proof" }); const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: circleInput });
    const proofs = await caller.featureHistory.edgeProofs({ projectId: project.id, accessKey: project.accessKey, revisionId: source.revisionId }); expect(proofs.filter((proof) => proof.status === "PASS")).toHaveLength(2); expect(proofs.find((proof) => proof.role === "CIRCLE_RIM_UNQUALIFIED")).toMatchObject({ status: "UNKNOWN", uncertainty: expect.stringContaining("AMBIGUOUS") });
    const same = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: { ...circleInput, title: "Independent same-input edge proof" } }); const persisted = await caller.featureHistory.edgeTopologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: source.revisionId, targetRevisionId: same.revisionId }); expect(persisted.summary.PERSISTED).toBeGreaterThanOrEqual(2); expect(persisted.summary.AMBIGUOUS).toBeGreaterThan(0);
    const preview = await caller.featureHistory.previewCircle({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: source.revisionId, edit: { featureId: "CIRCLE-SKETCH-001", parameter: { name: "radius", value: 6, unit: "mm" } } }); const replacement = await caller.featureHistory.executeCircle({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: preview.revisionId }); const replaced = await caller.featureHistory.edgeTopologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: source.revisionId, targetRevisionId: replacement.revisionId }); expect(replaced.summary.REPLACED).toBeGreaterThanOrEqual(2);
    const unrelated = await caller.featureHistory.create({ projectId: project.id, accessKey: project.accessKey, input: { title: "Unrelated rectangle", width: 20, height: 10, extrudeDistance: 5, unit: "mm" } }); const deleted = await caller.featureHistory.edgeTopologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: source.revisionId, targetRevisionId: unrelated.revisionId }); expect(deleted.summary.DELETED).toBeGreaterThanOrEqual(2); expect(deleted.limitations.join(" ")).toContain("Transient OpenCascade object identity is never used");
  }, 75_000);

  it("creates a bounded real-kernel YZ-plane Mirror, preserves its parent, and exposes preview/reject behavior", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 4.10 bounded Mirror" }); const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: circleInput });
    const plan = await caller.featureHistory.planMirror({ message: `source: ${source.revisionId}; feature: EXTRUDE-CIRCLE-001; mirror across the YZ plane` }); expect(plan).toMatchObject({ status: "READY_FOR_PREVIEW", executable: true, operation: "MIRROR", input: { mirrorPlane: "GLOBAL_X" } });
    const mirrored = await caller.featureHistory.createMirror({ projectId: project.id, accessKey: project.accessKey, input: { title: "Mirror across YZ", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", mirrorPlane: "GLOBAL_X" } }); expect(mirrored).toMatchObject({ status: "KERNEL_VALIDATED", parentRevisionId: source.revisionId, geometry: { validation: "VALID", export: { format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED" } } }); expect(mirrored.features.find((feature) => feature.featureType === "MIRROR")?.operationData).toMatchObject({ mirror_plane: "GLOBAL_X", mirrored_center_x_mm: -30 }); expect(mirrored.geometry.boundingBox?.min[0]).toBeCloseTo(-35, 4); expect(mirrored.geometry.boundingBox?.max[0]).toBeCloseTo(-25, 4);
    const preview = await caller.featureHistory.previewMirror({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: mirrored.revisionId, edit: { mirrorPlane: "GLOBAL_Y" } }); expect(preview).toMatchObject({ status: "PREVIEW", parentRevisionId: mirrored.revisionId, geometry: { validation: "VALID" } }); const rejected = await caller.featureHistory.rejectMirrorPreview({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: preview.revisionId }); expect(rejected).toMatchObject({ rejected: true, preservedRevisionId: mirrored.revisionId, status: "REJECTED" }); expect(source.status).toBe("KERNEL_VALIDATED");
  }, 75_000);

  it("runs the deterministic CAD execution benchmark without confusing CAD KERNEL VALIDATED with ENGINEERING VALIDATED", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 4.10 CAD benchmark" });
    const rectangle = await caller.featureHistory.create({ projectId: project.id, accessKey: project.accessKey, input: { title: "Benchmark rectangle", width: 2, height: 1, extrudeDistance: 0.5, unit: "cm" } }); expect(rectangle).toMatchObject({ status: "KERNEL_VALIDATED", truth: "KERNEL_VALIDATED" }); expect(rectangle.features.map((feature) => feature.featureType)).toEqual(["RECTANGLE_SKETCH", "EXTRUDE"]);
    const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: { title: "Benchmark circle", centerX: 30, centerY: 30, radius: 5, extrudeDistance: 10, unit: "mm" } }); expect(source).toMatchObject({ status: "KERNEL_VALIDATED", truth: "KERNEL_VALIDATED" });
    const circular = [];
    for (const axis of ["GLOBAL_X", "GLOBAL_Y", "GLOBAL_Z"] as const) circular.push(await caller.featureHistory.createCircularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: `Benchmark ${axis}`, sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", axis, instanceCount: 3, angleDegrees: 180, direction: "COUNTERCLOCKWISE" } }));
    expect(circular.every((revision) => revision.status === "KERNEL_VALIDATED")).toBe(true);
    const pattern = circular[2]; const patternNode = pattern.features.find((feature) => feature.featureType === "CIRCULAR_PATTERN")!; expect(patternNode.generatedInstances?.every((instance) => instance.topologyStatus === "PROVEN" && Boolean(instance.geometryReference))).toBe(true); const patternMesh = await caller.featureHistory.viewerMesh({ projectId: project.id, accessKey: project.accessKey, revisionId: pattern.revisionId }); expect(patternMesh.status).toBe("AVAILABLE"); if (patternMesh.status === "AVAILABLE") { expect(patternMesh.mesh.faceRanges.every((range) => range.instanceIdentity === "PROVEN" && Boolean(range.instanceKey))).toBe(true); expect(patternMesh.mesh.faceRanges.some((range) => range.instanceKey === "CIRCULAR-002")).toBe(true); }
    const grid = await caller.featureHistory.createRectangularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "Benchmark grid", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", directionX: "GLOBAL_X_POSITIVE", directionY: "GLOBAL_Y_NEGATIVE", countX: 2, countY: 2, spacingX: 20, spacingY: 20, unit: "mm" } }); expect(grid).toMatchObject({ status: "KERNEL_VALIDATED", truth: "KERNEL_VALIDATED" }); expect(grid.features.find((feature) => feature.featureType === "RECTANGULAR_PATTERN")?.generatedInstances?.[3]).toMatchObject({ instanceKey: "GRID-X2-Y2", topologyStatus: "PROVEN" });
    const mirrors = [];
    for (const mirrorPlane of ["GLOBAL_X", "GLOBAL_Y", "GLOBAL_Z"] as const) mirrors.push(await caller.featureHistory.createMirror({ projectId: project.id, accessKey: project.accessKey, input: { title: `Benchmark ${mirrorPlane} Mirror`, sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", mirrorPlane } }));
    expect(mirrors.every((revision) => revision.status === "KERNEL_VALIDATED")).toBe(true); const mirrorPreview = await caller.featureHistory.previewMirror({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: mirrors[0].revisionId, edit: { mirrorPlane: "GLOBAL_Y" } }); const mirrorBranch = await caller.featureHistory.executeMirror({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: mirrorPreview.revisionId }); expect(mirrorBranch.parentRevisionId).toBe(mirrors[0].revisionId);
    const failedRegeneration = await caller.featureHistory.previewCircle({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: source.revisionId, edit: { featureId: "CIRCLE-SKETCH-001", parameter: { name: "radius", value: -1, unit: "mm" } } }); expect(failedRegeneration).toMatchObject({ status: "FAILED", failure: { stage: "VALIDATION" } }); await expect(caller.featureHistory.createMirror({ projectId: project.id, accessKey: project.accessKey, input: { title: "Invalid reference", sourceRevisionId: "MISSING-REVISION", sourceFeatureId: "EXTRUDE-CIRCLE-001", mirrorPlane: "GLOBAL_X" } })).rejects.toThrow();
    const gate = await caller.featureHistory.filletGate({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: source.revisionId, targetRevisionId: source.revisionId }); expect(gate.ready).toBe(false); expect(gate.evidence).toEqual(expect.arrayContaining([expect.objectContaining({ id: "EDGE_IDENTITY", status: "PASS" }), expect.objectContaining({ id: "LOCAL_PRECONDITIONS", status: "UNKNOWN" }), expect.objectContaining({ id: "KERNEL_EXECUTION", status: "FAIL" }), expect.objectContaining({ id: "REGENERATION", status: "PASS" }), expect.objectContaining({ id: "FAILURE_PRESERVATION", status: "PASS" })]));
    const agent = runWorkbenchMessage({ projectId: project.id, message: `source: ${source.revisionId}; feature: EXTRUDE-CIRCLE-001; Mirror this boss across the YZ plane`, mode: "NORMAL", selectedGeometry: { kind: "FEATURE", id: "EXTRUDE-CIRCLE-001", label: "EXTRUDE-CIRCLE-001", featureId: "EXTRUDE-CIRCLE-001", source: "FEATURE_TREE" }, validationStage: "GEOMETRICALLY_VALIDATED" }); expect(agent.agentMessage.text).toContain("GLOBAL_X"); expect(agent.agentMessage.text).toContain("CAD KERNEL VALIDATED does not imply engineering validation"); const incompleteAgent = runWorkbenchMessage({ projectId: `${project.id}-incomplete`, message: "Mirror this boss", mode: "NORMAL", selectedGeometry: { kind: "FEATURE", id: "EXTRUDE-CIRCLE-001", label: "boss", featureId: "EXTRUDE-CIRCLE-001", source: "FEATURE_TREE" } }); expect(incompleteAgent.agentMessage.text).toContain("Which validated source revision");
  }, 120_000);
});
