import { beforeAll, describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";
import type { DigitalThreadArtifactKind } from "../shared/digitalThread";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const artifactInput = (kind: DigitalThreadArtifactKind, title: string, revision: string, sourceArtifactIds: string[] = []) => ({ kind, title, revision, state: "DECLARED" as const, truthStatus: "UNVERIFIED" as const, sourceArtifactIds, externalSourceRecordIds: [], provenance: ["Deterministic Phase 6.13 fixture provenance."], limitations: ["No engineering release or execution is claimed."], declaredBy: "PlanningFoundationFixture" });

describe("Phase 6.13 Drawing, BOM/PLM, and Manufacturing Planning", () => {
  const caller = appRouter.createCaller(ctx);
  let access: { projectId: string; accessKey: string };
  let isolated: { projectId: string; accessKey: string };
  let cad: any; let cadFeature: any; let drawing: any; let bom: any; let plm: any; let manufacturing: any;

  beforeAll(async () => {
    const project = await caller.persistentMemory.openProject({ name: "Phase 6.13 planning foundation" });
    const other = await caller.persistentMemory.openProject({ name: "Phase 6.13 isolated planning foundation" });
    access = { projectId: project.id, accessKey: project.accessKey }; isolated = { projectId: other.id, accessKey: other.accessKey };
    const requirement = await caller.digitalThread.createArtifact({ ...access, input: artifactInput("REQUIREMENT_SET", "Fixture requirements", "REQ-R1") });
    const concept = await caller.digitalThread.createArtifact({ ...access, input: artifactInput("CONCEPT", "Fixture concept", "CONCEPT-C1", [requirement.artifactId]) });
    cad = await caller.digitalThread.createArtifact({ ...access, input: artifactInput("CAD_MODEL", "Fixture CAD model", "CAD-R1", [concept.artifactId]) });
    cadFeature = await caller.digitalThread.createArtifact({ ...access, input: artifactInput("CAD_FEATURE", "Fixture CAD feature", "FEATURE-R1", [cad.artifactId]) });
    drawing = await caller.planning.createDrawingPackage({ ...access, input: { title: "Concept fixture drawing", revision: "DRAW-R1", sourceCadArtifactIds: [cad.artifactId, cadFeature.artifactId], sourceCadRevision: "CAD-R1", views: [{ viewId: "VIEW-FRONT", kind: "ORTHOGRAPHIC", label: "Front declared view", sourceGeometryReference: "CAD-R1", declaredOnly: true }], dimensions: [{ dimensionId: "DIM-WIDTH", label: "Declared width", value: 120, unit: "mm", sourceReference: "CAD-R1.PARAM.width", truthStatus: "UNVERIFIED" }], annotations: [{ annotationId: "NOTE-1", text: "Declared planning drawing only.", category: "NOTE", truthStatus: "UNVERIFIED" }], titleBlock: { partNumber: "PART-FIXTURE", drawingNumber: "DRW-FIXTURE", preparedBy: "PlanningFixture", status: "REVIEW_REQUIRED" }, state: "REVIEW_REQUIRED", provenance: ["CAD model artifact reference."], limitations: ["No rendering engine is available."], declaredBy: "PlanningFixture" } });
    bom = await caller.planning.createBOMRevision({ ...access, input: { title: "Fixture assembly BOM", revision: "BOM-R1", sourceArtifactIds: [cad.artifactId, cadFeature.artifactId], items: [{ lineId: "LINE-1", partNumber: "PART-FIXTURE", title: "Fixture CAD part", quantity: 1, sourceArtifactId: cad.artifactId, materialReference: "MATERIAL-UNKNOWN", supplierSource: "UNKNOWN", truthStatus: "UNVERIFIED" }], state: "REVIEW_REQUIRED", provenance: ["CAD model artifact reference."], limitations: ["No procurement or inventory data is present."], declaredBy: "PlanningFixture" } });
    plm = await caller.planning.createPLMRevision({ ...access, input: { partNumber: "PART-FIXTURE", revision: "PLM-R1", sourceArtifactIds: [cad.artifactId, drawing.digitalThreadArtifactId, bom.digitalThreadArtifactId], lifecycleState: "REVIEW", engineeringChangeReason: "Initial declared planning revision.", comparisonSummary: "No prior release exists.", provenance: ["CAD, drawing, and BOM artifact identities."], limitations: ["No release approval has been recorded."], declaredBy: "PlanningFixture" } });
    manufacturing = await caller.planning.createManufacturingPlan({ ...access, input: { title: "Fixture manufacturing plan", revision: "MFG-R1", sourceArtifactIds: [cad.artifactId, bom.digitalThreadArtifactId], processIntent: ["MILLING"], materialProcessCompatibility: [{ materialReference: "MATERIAL-UNKNOWN", process: "MILLING", status: "UNKNOWN", rationale: "Material evidence is not available." }], dfmFindings: [{ findingId: "DFM-1", category: "DFM", finding: "Review wall thickness against the actual manufacturing process.", truthStatus: "UNVERIFIED", requiredEvidence: ["Material/process capability evidence."] }], setupPlanning: [{ setupId: "SETUP-1", description: "Declared first setup; fixture and datum evidence required.", status: "DECLARED" }], toolSelectionMetadata: [{ toolId: "TOOL-UNKNOWN", description: "Tool selection requires capability evidence.", source: "UNKNOWN" }], inspectionPlanning: [{ inspectionId: "INSPECT-1", characteristic: "Declared width", method: "Method not selected", status: "UNKNOWN" }], state: "REVIEW_REQUIRED", provenance: ["CAD and BOM artifact identities."], limitations: ["No toolpath, post processor, machine command, or manufacturing simulation exists."], declaredBy: "PlanningFixture" } });
  }, 30_000);

  it("1. records a CAD-referenced drawing with declared-only views and source-bound dimensions", () => expect(drawing).toMatchObject({ state: "REVIEW_REQUIRED", validation: { cadReferenceResolved: true, dimensionsSourceBound: true, rendererAvailable: false, standardsComplianceClaimed: false }, executionEligible: false, executable: false }));
  it("2. refuses a numeric drawing dimension without an explicit CAD source reference", async () => await expect(caller.planning.createDrawingPackage({ ...access, input: { title: "Invalid drawing", revision: "DRAW-BAD", sourceCadArtifactIds: [cad.artifactId], sourceCadRevision: "CAD-R1", views: [{ viewId: "VIEW-1", kind: "ORTHOGRAPHIC", label: "View", declaredOnly: true }], dimensions: [{ dimensionId: "DIM-BAD", label: "Invented", value: 10, unit: "mm", truthStatus: "UNVERIFIED" }], annotations: [], titleBlock: { preparedBy: "Fixture", status: "DRAFT" }, state: "DECLARED", provenance: ["Fixture"], limitations: ["Fixture"], declaredBy: "Fixture" } })).rejects.toThrow(/requires an explicit source reference/i));
  it("3. records a BOM with positive declared quantities and immutable part sources", () => expect(bom).toMatchObject({ revision: "BOM-R1", validation: { sourceArtifactsResolved: true, quantitiesDeclared: true, autoStructureInference: false }, executionEligible: false, executable: false }));
  it("4. refuses a BOM line without a positive quantity or resolvable source artifact", async () => await expect(caller.planning.createBOMRevision({ ...access, input: { title: "Invalid BOM", revision: "BOM-BAD", sourceArtifactIds: [cad.artifactId], items: [{ lineId: "LINE-BAD", partNumber: "PART-BAD", title: "Invalid item", quantity: 0, sourceArtifactId: "UNKNOWN-ARTIFACT", truthStatus: "UNVERIFIED" }], state: "DECLARED", provenance: ["Fixture"], limitations: ["Fixture"], declaredBy: "Fixture" } })).rejects.toThrow());
  it("5. records a PLM revision that is explicitly not approved or released", () => expect(plm).toMatchObject({ lifecycleState: "REVIEW", approvalState: "NOT_APPROVED", releaseState: "NOT_RELEASED", executionEligible: false, executable: false }));
  it("6. retains PLM parent lineage and refuses a missing parent in the authorized project", async () => { const successor = await caller.planning.createPLMRevision({ ...access, input: { partNumber: "PART-FIXTURE", revision: "PLM-R2", parentPLMRevisionId: plm.plmRevisionId, sourceArtifactIds: [cad.artifactId, drawing.digitalThreadArtifactId, bom.digitalThreadArtifactId], lifecycleState: "SUPERSEDED", engineeringChangeReason: "Declared successor review.", comparisonSummary: "Declared comparison only.", provenance: ["PLM parent identity."], limitations: ["No release authority."], declaredBy: "PlanningFixture" } }); expect(successor.parentPLMRevisionId).toBe(plm.plmRevisionId); await expect(caller.planning.createPLMRevision({ ...access, input: { partNumber: "PART-INVALID", revision: "PLM-BAD", parentPLMRevisionId: "MISSING-PLM", sourceArtifactIds: [cad.artifactId, drawing.digitalThreadArtifactId, bom.digitalThreadArtifactId], lifecycleState: "REVIEW", engineeringChangeReason: "Invalid", comparisonSummary: "Invalid", provenance: ["Fixture"], limitations: ["Fixture"], declaredBy: "Fixture" } })).rejects.toThrow(/parent must exist/i); });
  it("7. records manufacturing planning without claiming tooling capability, a toolpath, post processing, machine output, or certification", () => expect(manufacturing).toMatchObject({ validation: { toolpathPlanningAvailable: false, postProcessorAvailable: false, machineOutputGenerated: false, certificationClaimed: false }, executionEligible: false, executable: false }));
  it("8. constrains manufacturing tool metadata to unverified capability", () => expect(manufacturing.toolSelectionMetadata[0].capabilityVerified).toBe(false));
  it("9. exposes immutable project-scoped planning history", async () => { expect(await caller.planning.listDrawingPackages(access)).toHaveLength(1); expect(await caller.planning.listBOMRevisions(access)).toHaveLength(1); expect((await caller.planning.listPLMRevisions(access)).length).toBe(2); expect(await caller.planning.listManufacturingPlans(access)).toHaveLength(1); });
  it("10. isolates all planning records by project", async () => { expect(await caller.planning.listDrawingPackages(isolated)).toEqual([]); expect(await caller.planning.listBOMRevisions(isolated)).toEqual([]); expect(await caller.planning.listPLMRevisions(isolated)).toEqual([]); expect(await caller.planning.listManufacturingPlans(isolated)).toEqual([]); });
  it("11. provides no renderer, exporter, release, toolpath, post processor, machine, or execution endpoint", () => expect(Object.keys(caller.planning)).not.toEqual(expect.arrayContaining(["renderDrawing", "exportDrawing", "release", "generateToolpath", "postProcess", "sendToMachine", "execute"])));
});
