import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const kinds = ["CPU_LIMIT", "MEMORY_LIMIT", "DISK_LIMIT", "EXECUTION_TIMEOUT", "INPUT_SIZE_LIMIT", "OUTPUT_SIZE_LIMIT", "PROCESS_LIMIT", "CONCURRENT_JOB_LIMIT"] as const;
const units = ["millicores", "bytes", "bytes", "seconds", "bytes", "bytes", "count", "count"];

describe("Phase 6.1 execution infrastructure readiness", () => {
  it("keeps unknown capacity and unexecuted security evidence fail-closed while recording only design and verification requirements", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 6.1 runtime readiness" }); const access = { projectId: project.id, accessKey: project.accessKey };
    const review = await caller.cae.createRuntimeReadinessReview(access);
    expect(review).toMatchObject({ contractVersion: "1.0.0", readiness: "NOT_READY", executionApproval: "DISABLED", executionEligible: false, executable: false }); expect(review.capacityPolicy).toMatchObject({ state: "UNKNOWN" }); expect(review.capacityPolicy.limits).toHaveLength(8); expect(review.capacityPolicy.limits.every((item) => item.value === "UNKNOWN")).toBe(true); expect(review.sandboxDesign.controls).toHaveLength(9); expect(review.sandboxDesign.controls.every((item) => item.status === "DESIGNED")).toBe(true); expect(review.sandboxDesign.statement).toMatch(/does not mean IMPLEMENTED, VERIFIED, or ATTESTED/i); expect(review.hostileTests).toHaveLength(17); expect(review.hostileTests.every((item) => item.status === "NOT_RUN")).toBe(true); expect(review.securityInvariants).toHaveLength(10); expect(review.securityInvariants.every((item) => item.status === "NOT_VERIFIED")).toBe(true); expect(review.assurance.map((item) => item.dimension)).toEqual(["THREAT_COVERAGE", "EVIDENCE_QUALITY", "SANDBOX_ASSURANCE", "RESOURCE_ASSURANCE", "IDENTITY_ASSURANCE", "AUDIT_ASSURANCE"]);
    const unknown = await caller.cae.validateCapacityPolicy({ ...access, policyId: review.capacityPolicy.policyId, limit: "CPU_LIMIT", observedValue: "UNKNOWN", observedUnit: "millicores" }); expect(unknown).toMatchObject({ outcome: "UNKNOWN_LIMIT", safe: false }); expect(unknown.reason).toMatch(/not safe/i);
    const declared = await caller.cae.createCapacityPolicy({ ...access, limits: kinds.map((kind, index) => ({ kind, value: index + 1, unit: units[index]!, rationale: "Declared design value only; not infrastructure evidence.", environment: "candidate runtime", version: "2.0.0", effectiveDate: "2026-08-21" })) }); expect(declared.state).toBe("DECLARED"); const within = await caller.cae.validateCapacityPolicy({ ...access, policyId: declared.policyId, limit: "CPU_LIMIT", observedValue: 1, observedUnit: "millicores" }); const exceeds = await caller.cae.validateCapacityPolicy({ ...access, policyId: declared.policyId, limit: "CPU_LIMIT", observedValue: 2, observedUnit: "millicores" }); expect(within).toMatchObject({ outcome: "WITHIN_LIMIT", safe: false }); expect(exceeds).toMatchObject({ outcome: "EXCEEDS_LIMIT", safe: false });
    const independent = await caller.cae.registerIndependentSandboxAttestation({ ...access, designId: review.sandboxDesign.designId, attestorIdentity: "Independent assurance assessor", attestorPublisherRelationship: "INDEPENDENT", attestationScope: "Sandbox design review", environmentIdentity: "candidate-environment", evidenceHash: "a".repeat(64), attestationTime: "2026-08-21T00:00:00.000Z", verificationMethod: "Document and identity review" }); expect(independent).toMatchObject({ status: "NOT_ATTESTED" }); const publisher = await caller.cae.registerIndependentSandboxAttestation({ ...access, designId: review.sandboxDesign.designId, attestorIdentity: "Adapter publisher", attestorPublisherRelationship: "SAME_PUBLISHER", attestationScope: "Invalid self-attestation", environmentIdentity: "candidate-environment", evidenceHash: "b".repeat(64), attestationTime: "2026-08-21T00:00:00.000Z", verificationMethod: "Self assertion" }); expect(publisher).toMatchObject({ status: "INVALID" });
    const refreshed = await caller.cae.createRuntimeReadinessReview(access); expect(refreshed.independentAttestations).toEqual(expect.arrayContaining([expect.objectContaining({ attestationEvidenceId: independent.attestationEvidenceId, status: "NOT_ATTESTED" }), expect.objectContaining({ attestationEvidenceId: publisher.attestationEvidenceId, status: "INVALID" })])); expect(refreshed.readiness).toBe("NOT_READY"); expect(refreshed.executionEligible).toBe(false); const graph = await caller.cae.runtimeReadinessGraph({ ...access, readinessId: refreshed.readinessId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: refreshed.readinessId, type: "RUNTIME_READINESS" }), expect.objectContaining({ id: refreshed.capacityPolicy.policyId, type: "CAPACITY_POLICY" }), expect.objectContaining({ id: independent.attestationEvidenceId, type: "INDEPENDENT_ATTESTATION" })])); expect(graph.limitations.join(" ")).toMatch(/No solver, mesher, shell/i);
    const audit = await caller.cae.securityAudit(access); expect(audit).toEqual(expect.arrayContaining([expect.objectContaining({ action: "RUNTIME_READINESS_REVIEW", objectType: "RUNTIME_READINESS", objectId: refreshed.readinessId }), expect.objectContaining({ action: "INDEPENDENT_ATTESTATION_EVIDENCE", objectType: "INDEPENDENT_ATTESTATION", objectId: independent.attestationEvidenceId })])); const other = await caller.persistentMemory.openProject({ name: "Phase 6.1 isolation" }); await expect(caller.cae.listRuntimeReadinessReviews({ projectId: other.id, accessKey: other.accessKey })).resolves.toEqual([]); expect(Object.keys(caller.cae)).not.toEqual(expect.arrayContaining(["executeSolver", "executeRuntime", "startExecution", "runShell", "launchPlugin", "openFilesystem"]));
  }, 120_000);
});
