import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;

describe("Phase 6.4 runtime implementation readiness review", () => {
  it("records a comprehensive review-only implementation assessment with genuine blockers and no execution surface", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 6.4 runtime readiness" }); const access = { projectId: project.id, accessKey: project.accessKey };
    const review = await caller.cae.createRuntimeImplementationReadinessReview(access);
    expect(review).toMatchObject({ contractVersion: "1.0.0", finalDecision: "RUNTIME_IMPLEMENTATION_BLOCKED", estimatedComplexity: "XL", executionEligible: false, executable: false });
    expect(review.inventory).toHaveLength(13); expect(review.inventory).toEqual(expect.arrayContaining([expect.objectContaining({ capability: "CAD_KERNEL", status: "IMPLEMENTED" }), expect.objectContaining({ capability: "CAE_PLANNING", status: "IMPLEMENTED" }), expect.objectContaining({ capability: "SANDBOX_ARCHITECTURE", status: "DESIGNED_ONLY" }), expect.objectContaining({ capability: "CAPACITY_POLICY", status: "DESIGNED_ONLY" })]));
    expect(review.blockers.filter((item) => item.preventsFirstControlledRuntime)).toHaveLength(7); expect(review.blockers).toEqual(expect.arrayContaining([expect.objectContaining({ title: "No controlled CAE job compiler", classification: "BLOCKER" }), expect.objectContaining({ title: "No solver-grade meshing or mesh-quality verifier", classification: "BLOCKER" }), expect.objectContaining({ title: "No implemented and independently attested execution sandbox", classification: "BLOCKER" }), expect.objectContaining({ title: "No result collector and verifier", classification: "BLOCKER" }), expect.objectContaining({ title: "No allowlisted executable adapter or solver image", classification: "BLOCKER" })]));
    expect(review.solverOptions).toHaveLength(5); expect(review.solverOptions).toEqual(expect.arrayContaining([expect.objectContaining({ option: "NATIVE_OPEN_SOURCE_SOLVER", representative: expect.stringMatching(/CalculiX/i), recommendation: "FIRST_CANDIDATE" }), expect.objectContaining({ option: "CONTAINERIZED_SOLVER", recommendation: "FIRST_CANDIDATE" }), expect.objectContaining({ option: "REMOTE_SOLVER", recommendation: "NOT_FOR_FIRST_RUNTIME" })]));
    expect(review.meshingOptions).toEqual(expect.arrayContaining([expect.objectContaining({ option: "OPENCASCADE_TRIANGULATION", recommendation: "NOT_FOR_FIRST_RUNTIME" }), expect.objectContaining({ option: "DEDICATED_OPEN_SOURCE_MESHER", recommendation: "FIRST_CANDIDATE" })]));
    expect(review.minimumViableCAE).toMatchObject({ analysis: "LINEAR_STATIC_STRUCTURAL" }); expect(review.minimumViableCAE.excluded).toEqual(expect.arrayContaining(["Nonlinear material/contact", "crash/explicit dynamics", "automatic design modification"]));
    expect(review.runtimeBoundary).toHaveLength(7); expect(review.runtimeBoundary.every((item) => item.immutableInputs.length > 0 && item.prohibited.length > 0 && item.requiredHashes.length > 0)).toBe(true);
    expect(review.resultTrust).toHaveLength(12); expect(review.resultTrust.every((item) => item.requiredEvidence.length > 0)).toBe(true); expect(review.essentialSecurityGates).toHaveLength(7); expect(review.essentialSecurityGates.filter((item) => item.currentState === "FAIL")).toHaveLength(6); expect(review.failureModel).toHaveLength(12); expect(review.failureModel.every((item) => item.preservedArtifacts.length > 0)).toBe(true); expect(review.implementationPlan).toHaveLength(5); expect(review.implementationPlan.at(-1)?.gateBeforeNext).toMatch(/never execution authorization/i);
    expect(review.sourceUrls).toEqual(expect.arrayContaining(["https://www.calculix.de/", "https://gmsh.info/", "https://csrc.nist.gov/pubs/sp/800/190/final"])); expect(review.decisionReason).toMatch(/no controlled CAE job compiler/i);
    const saved = await caller.cae.listRuntimeImplementationReadinessReviews(access); expect(saved).toHaveLength(1); expect(saved[0]?.reviewId).toBe(review.reviewId);
    const graph = await caller.cae.runtimeImplementationReadinessGraph({ ...access, reviewId: review.reviewId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: `DECISION-${review.reviewId}`, type: "RUNTIME_DECISION", label: "RUNTIME_IMPLEMENTATION_BLOCKED" }), expect.objectContaining({ id: "BOUNDARY-CAD-JOB", type: "RUNTIME_BOUNDARY" })])); expect(graph.limitations.join(" ")).toMatch(/No solver, mesher, runtime process, shell/i);
    const audit = await caller.cae.securityAudit(access); expect(audit).toEqual(expect.arrayContaining([expect.objectContaining({ action: "RUNTIME_ARCHITECTURE_REVIEW", objectType: "RUNTIME_ARCHITECTURE", objectId: review.reviewId, newState: "RUNTIME_IMPLEMENTATION_BLOCKED" })]));
    const other = await caller.persistentMemory.openProject({ name: "Phase 6.4 isolation" }); await expect(caller.cae.listRuntimeImplementationReadinessReviews({ projectId: other.id, accessKey: other.accessKey })).resolves.toEqual([]); expect(Object.keys(caller.cae)).not.toEqual(expect.arrayContaining(["executeSolver", "executeRuntime", "startExecution", "installSolver", "createMesher", "runShell", "runMesher"]));
  });
});
