import { beforeAll, describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const h = (value: string) => value.repeat(64);
const controls = ["PROCESS_ISOLATION", "FILESYSTEM_ISOLATION", "NETWORK_ISOLATION", "RESOURCE_LIMITS", "CPU_LIMITS", "MEMORY_LIMITS", "EXECUTION_TIMEOUT", "STORAGE_LIMITS", "PRIVILEGE_BOUNDARIES", "SECRET_ISOLATION", "DEPENDENCY_ISOLATION", "EGRESS_CONTROL", "FAILURE_CONTAINMENT", "AUDITABILITY", "REPRODUCIBILITY"] as const;
const window = () => ({ validFrom: new Date(Date.now() - 60_000).toISOString(), validUntil: new Date(Date.now() + 3_600_000).toISOString() });
const reviewWindow = () => ({ reviewValidFrom: new Date(Date.now() - 60_000).toISOString(), reviewValidUntil: new Date(Date.now() + 3_600_000).toISOString() });
const controlSet = (state: "PASS" | "FAIL" | "UNKNOWN" | "NOT_APPLICABLE" = "PASS", evidence = true) => controls.map((controlId) => ({ controlId, state, evidenceIds: evidence ? [`EVIDENCE-${controlId}`] : [], rationale: `Bounded ${controlId} evidence declaration.` }));

describe("Phase 6.11 Security Evidence Foundation", () => {
  const caller = appRouter.createCaller(ctx);
  let access: { projectId: string; accessKey: string };
  let other: { projectId: string; accessKey: string };
  let reviewer: any;
  let authorization: any;
  let rubric: any;
  let attestation: any;
  let artifact: any;
  let hostile: any;
  let runtimeReview: any;

  beforeAll(async () => {
    const project = await caller.persistentMemory.openProject({ name: "Phase 6.11 security evidence" });
    const isolated = await caller.persistentMemory.openProject({ name: "Phase 6.11 security evidence isolation" });
    access = { projectId: project.id, accessKey: project.accessKey };
    other = { projectId: isolated.id, accessKey: isolated.accessKey };
    reviewer = await caller.cae.registerReviewer({ ...access, displayName: "Independent Security Reviewer", role: "Security Validation", projectScope: [project.id], permissions: ["APPROVE_VALIDATION", "APPROVE_SOLVER_ADAPTER"], actor: "Admin" });
    reviewer = await caller.cae.verifyReviewer({ ...access, reviewerId: reviewer.reviewerId, verificationMethod: "DIRECT", actor: "Admin" });
    authorization = await caller.cae.authorizeReviewerForEvidence({ ...access, reviewerId: reviewer.reviewerId, organization: "Independent QA", role: "Security Reviewer", authorizationScope: ["APPROVE_VALIDATION", "APPROVE_SOLVER_ADAPTER"], authorizationSource: "Phase 6.11 fixture authority", authorizationHash: h("a"), issuedBy: "IndependentIssuer", ...window(), independenceStatement: "The issuing authority is independent from the reviewer, evidence submitter, and artifact publisher." });
    runtimeReview = await caller.cae.createRuntimeArchitectureReview(access);
    rubric = await caller.cae.createSandboxAttestationRubric({ ...access, attestationSubject: "FUTURE-RUNTIME-ENVIRONMENT", attestationScope: "Future single-job static structural runtime boundary only." });
    attestation = await caller.cae.recordSandboxSecurityAttestation({ ...access, rubricId: rubric.rubricId, attestationSubject: "FUTURE-RUNTIME-ENVIRONMENT", attestationScope: "Future single-job static structural runtime boundary only.", attestorIdentity: reviewer.reviewerId, attestorAuthorizationId: authorization.reviewerAuthorizationId, independence: "INDEPENDENT", evidenceSource: "DECLARED_EXTERNAL_EVIDENCE", evidenceHash: h("b"), issuedAt: new Date().toISOString(), ...window(), controlAssessments: controlSet(), selfAttestationReviewRequired: false });
    artifact = await caller.cae.recordArtifactSBOMReview({ ...access, artifactIdentity: "FUTURE-SOLVER-IMAGE", artifactVersion: "V1", artifactHash: h("c"), signature: "NON_EXECUTABLE_SIGNATURE_DECLARATION", signatureHash: h("d"), publisher: "ExternalPublisher", source: "DECLARED_ARTIFACT_SOURCE", license: "DECLARED_LICENSE", dependencies: [{ name: "DEPENDENCY-ONE", version: "V1", sha256: h("e"), source: "DECLARED_DEPENDENCY_SOURCE", knownVulnerabilityState: "NONE_DECLARED", evidenceHash: h("f") }], sbomReference: "SBOM-FUTURE-V1", sbomHash: h("0"), knownVulnerabilities: [], buildProvenance: ["Declared build provenance."], reproducibilityEvidence: ["Declared reproduction identity."], reviewerId: reviewer.reviewerId, reviewerAuthorizationId: authorization.reviewerAuthorizationId, reviewIssuedAt: new Date().toISOString(), ...reviewWindow(), reviewStatus: "APPROVED", revocationState: "CURRENT", findings: ["Review record only; no artifact was acquired or executed."] });
    hostile = await caller.cae.recordSecurityHostileTestEvidence({ ...access, testId: "DECLARED-HOSTILE-TEST-1", testCategory: "FILESYSTEM_ESCAPE", testObjective: "Future evidence format only.", environmentIdentity: "DECLARED-ISOLATED-TEST-ENVIRONMENT", testInputHash: h("1"), expectedBehavior: "Future runtime must deny the declared action.", observedBehavior: "Evidence declared; CAD-AI did not execute a test.", result: "UNKNOWN", rawEvidenceHash: h("2"), timestamp: new Date().toISOString(), reviewerId: reviewer.reviewerId, reviewerAuthorizationId: authorization.reviewerAuthorizationId, limitations: ["No test was executed by CAD-AI."], reproducibilityInformation: ["Test environment identity and hash retained." ] });
  }, 30_000);

  it("1. provides every mandatory sandbox control in an immutable rubric", () => expect(rubric).toMatchObject({ requiredControlCount: 15, noEvidenceMayPass: true, controls: expect.arrayContaining([expect.objectContaining({ controlId: "PROCESS_ISOLATION", state: "UNKNOWN" }), expect.objectContaining({ controlId: "REPRODUCIBILITY", state: "UNKNOWN" })]), executionEligible: false, executable: false }));
  it("2. rejects a PASS sandbox control without evidence", async () => await expect(caller.cae.recordSandboxSecurityAttestation({ ...access, rubricId: rubric.rubricId, attestationSubject: "FUTURE-RUNTIME-ENVIRONMENT", attestationScope: "fixture", attestorIdentity: reviewer.reviewerId, attestorAuthorizationId: authorization.reviewerAuthorizationId, independence: "INDEPENDENT", evidenceSource: "fixture", evidenceHash: h("3"), issuedAt: new Date().toISOString(), ...window(), controlAssessments: controlSet("PASS", false), selfAttestationReviewRequired: false })).rejects.toThrow(/cannot be PASS without evidence/i));
  it("3. marks expired attestation evidence expired and never execution eligible", async () => { const expired = await caller.cae.recordSandboxSecurityAttestation({ ...access, rubricId: rubric.rubricId, attestationSubject: "FUTURE-EXPIRED-ENVIRONMENT", attestationScope: "fixture", attestorIdentity: reviewer.reviewerId, attestorAuthorizationId: authorization.reviewerAuthorizationId, independence: "INDEPENDENT", evidenceSource: "fixture", evidenceHash: h("4"), issuedAt: new Date().toISOString(), validFrom: new Date(Date.now() - 120_000).toISOString(), validUntil: new Date(Date.now() - 60_000).toISOString(), controlAssessments: controlSet(), selfAttestationReviewRequired: false }); expect(expired).toMatchObject({ status: "EXPIRED", executionEligible: false, executable: false }); });
  it("4. rejects an unauthorized attestor", async () => await expect(caller.cae.recordSandboxSecurityAttestation({ ...access, rubricId: rubric.rubricId, attestationSubject: "UNAUTHORIZED", attestationScope: "fixture", attestorIdentity: "MISSING-REVIEWER", attestorAuthorizationId: authorization.reviewerAuthorizationId, independence: "INDEPENDENT", evidenceSource: "fixture", evidenceHash: h("5"), issuedAt: new Date().toISOString(), ...window(), controlAssessments: controlSet(), selfAttestationReviewRequired: false })).rejects.toThrow(/verified project-scoped attestor/i));
  it("5. governs self-attestation explicitly and does not promote it to PASS", async () => { const self = await caller.cae.recordSandboxSecurityAttestation({ ...access, rubricId: rubric.rubricId, attestationSubject: reviewer.reviewerId, attestationScope: "fixture", attestorIdentity: reviewer.reviewerId, attestorAuthorizationId: authorization.reviewerAuthorizationId, independence: "SELF_ATTESTATION", evidenceSource: "fixture", evidenceHash: h("6"), issuedAt: new Date().toISOString(), ...window(), controlAssessments: controlSet(), selfAttestationReviewRequired: true }); expect(self).toMatchObject({ status: "UNKNOWN", selfAttestationReviewRequired: true, executable: false }); });
  it("6. detects immutable artifact hash mismatch as a conflict", async () => { const mismatch = await caller.cae.recordArtifactSBOMReview({ ...access, artifactIdentity: artifact.artifactIdentity, artifactVersion: artifact.artifactVersion, artifactHash: h("7"), publisher: "ExternalPublisher", source: "source", license: "license", dependencies: [{ name: "D", version: "V1", source: "source", knownVulnerabilityState: "UNKNOWN" }], sbomReference: artifact.sbomReference, sbomHash: artifact.sbomHash, knownVulnerabilities: [], buildProvenance: ["p"], reproducibilityEvidence: ["r"], reviewIssuedAt: new Date().toISOString(), ...reviewWindow(), reviewStatus: "UNDER_REVIEW", findings: [] }); expect(mismatch.reviewStatus).toBe("REJECTED"); expect((await caller.cae.listSecurityEvidenceConflicts(access)).some((item) => item.field === "ARTIFACT_HASH")).toBe(true); });
  it("7. detects SBOM mismatch as a conflict", async () => { const mismatch = await caller.cae.recordArtifactSBOMReview({ ...access, artifactIdentity: artifact.artifactIdentity, artifactVersion: artifact.artifactVersion, artifactHash: artifact.artifactHash, publisher: "ExternalPublisher", source: "source", license: "license", dependencies: [{ name: "D2", version: "V1", source: "source", knownVulnerabilityState: "UNKNOWN" }], sbomReference: artifact.sbomReference, sbomHash: h("8"), knownVulnerabilities: [], buildProvenance: ["p"], reproducibilityEvidence: ["r"], reviewIssuedAt: new Date().toISOString(), ...reviewWindow(), reviewStatus: "UNDER_REVIEW", findings: [] }); expect(mismatch.reviewStatus).toBe("REJECTED"); });
  it("8. detects inconsistent dependency hashes", async () => { const dependencyConflict = await caller.cae.recordArtifactSBOMReview({ ...access, artifactIdentity: "DEPENDENCY-CONFLICT", artifactVersion: "V1", artifactHash: h("9"), publisher: "Publisher", source: "source", license: "license", dependencies: [{ name: "DUPLICATE", version: "V1", sha256: h("a"), source: "source", knownVulnerabilityState: "NONE_DECLARED" }, { name: "DUPLICATE", version: "V1", sha256: h("b"), source: "source", knownVulnerabilityState: "NONE_DECLARED" }], sbomReference: "SBOM-CONFLICT", sbomHash: h("c"), knownVulnerabilities: [], buildProvenance: ["p"], reproducibilityEvidence: ["r"], reviewIssuedAt: new Date().toISOString(), ...reviewWindow(), reviewStatus: "UNDER_REVIEW", findings: [] }); expect(dependencyConflict.reviewStatus).toBe("REJECTED"); });
  it("9. rejects approved artifact review without independent reviewer authorization", async () => await expect(caller.cae.recordArtifactSBOMReview({ ...access, artifactIdentity: "UNAUTHORIZED-APPROVAL", artifactVersion: "V1", artifactHash: h("d"), signature: "sig", signatureHash: h("e"), publisher: "Publisher", source: "source", license: "license", dependencies: [{ name: "D", version: "V1", sha256: h("f"), source: "source", knownVulnerabilityState: "NONE_DECLARED" }], sbomReference: "SBOM-U", sbomHash: h("0"), knownVulnerabilities: [], buildProvenance: ["p"], reproducibilityEvidence: ["r"], reviewIssuedAt: new Date().toISOString(), ...reviewWindow(), reviewStatus: "APPROVED", findings: [] })).rejects.toThrow(/reviewer authorization/i));
  it("10. rejects hostile-test evidence with malformed hash identity", async () => await expect(caller.cae.recordSecurityHostileTestEvidence({ ...access, testId: "BAD-HASH", testCategory: "NETWORK_ESCAPE", testObjective: "fixture", environmentIdentity: "ENV", testInputHash: "not-a-hash", expectedBehavior: "deny", observedBehavior: "not run", result: "UNKNOWN", rawEvidenceHash: h("1"), timestamp: new Date().toISOString(), reviewerId: reviewer.reviewerId, reviewerAuthorizationId: authorization.reviewerAuthorizationId, limitations: [], reproducibilityInformation: ["r"] })).rejects.toThrow());
  it("11. preserves bounded hostile-test evidence without claiming test execution", () => expect(hostile).toMatchObject({ actualTestExecutionClaimed: false, executionEligible: false, executable: false, reviewerAuthorizationId: authorization.reviewerAuthorizationId }));
  it("12. resolves Runtime Review → Sandbox → Artifact/SBOM → Hostile Test → Reviewer traceability", async () => expect(await caller.cae.assessSecurityEvidenceTraceability({ ...access, runtimeArchitectureReviewId: runtimeReview.reviewId, rubricId: rubric.rubricId, attestationEvidenceId: attestation.attestationEvidenceId, artifactReviewId: artifact.artifactReviewId, hostileTestEvidenceId: hostile.hostileTestEvidenceId })).toMatchObject({ status: "RESOLVED", executionEligible: false, executable: false }));
  it("13. isolates all Phase 6.11 evidence by project", async () => { expect(await caller.cae.listSandboxAttestationRubrics(other)).toEqual([]); expect(await caller.cae.listArtifactSBOMReviews(other)).toEqual([]); expect(await caller.cae.listSecurityHostileTestEvidence(other)).toEqual([]); });
  it("14. exposes no sandbox, solver, mesher, shell, process, plugin, network, or filesystem execution endpoint", () => expect(Object.keys(caller.cae)).not.toEqual(expect.arrayContaining(["executeSandbox", "runHostileTest", "executeSolver", "executeMesher", "runShell", "runProcess", "runPlugin", "runNetwork", "accessFilesystem"])));
});
