import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const base64 = (value: string) => Buffer.from(value, "utf8").toString("base64");
const adapterInput = (manifest: string, hash = createHash("sha256").update(manifest).digest("hex")) => ({ solverId: "TRUSTED-ADAPTER", solverName: "Trust Adapter", version: "1.0.0", provider: "Verified Publisher", adapterVersion: "1.0.0", supportedAnalysisTypes: ["STATIC_STRUCTURAL" as const], capabilities: ["STATIC_STRUCTURAL"], executionMode: "CLOUD_UNCONFIGURED" as const, inputSchemaVersion: "1", outputSchemaVersion: "1", securityRequirements: ["No shell", "No arbitrary filesystem", "No network"], adapterManifest: manifest, adapterHash: hash, publisherIdentity: "Publisher identity", signature: "detached-signature", capabilityManifest: ["STATIC_STRUCTURAL"] });

describe("Phase 5.3 solver trust, identity, certificate, revocation, and audit foundation", () => {
  it("keeps every adapter non-executable while requiring verified human identity, evidence gates, approval, and non-destructive revocation", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 5.3 trust acceptance" }); const access = { projectId: project.id, accessKey: project.accessKey }; const manifest = "{\"adapter\":\"trust\",\"version\":\"1\"}";
    const adapter = await caller.cae.registerExternalSolverAdapter({ ...access, input: adapterInput(manifest) }); expect(adapter).toMatchObject({ verificationStatus: "UNVERIFIED", executable: false }); const tampered = await caller.cae.registerExternalSolverAdapter({ ...access, input: adapterInput("{\"adapter\":\"tampered\"}", "a".repeat(64)) }); expect(tampered.verificationStatus).toBe("REJECTED");
    const reviewer = await caller.cae.registerReviewer({ ...access, displayName: "Reviewer A", role: "Systems safety reviewer", projectScope: [project.id], permissions: ["APPROVE_SOLVER_ADAPTER", "APPROVE_CALIBRATION", "APPROVE_MATERIAL", "APPROVE_VALIDATION"], actor: "Administrator" }); expect(reviewer.status).toBe("UNVERIFIED"); await expect(caller.cae.verifyAdapterTrust({ ...access, registrationId: adapter.registrationId, reviewerId: reviewer.reviewerId, manifestVerified: true, signatureVerified: true, verifiedCapabilities: ["STATIC_STRUCTURAL"], grantedPermissions: ["READ_CAD"], reason: "Attempt with unverified reviewer" })).rejects.toThrow(/not verified/);
    const verifiedReviewer = await caller.cae.verifyReviewer({ ...access, reviewerId: reviewer.reviewerId, verificationMethod: "Reviewed organizational identity record", actor: "Administrator" }); expect(verifiedReviewer).toMatchObject({ identityStatus: "VERIFIED", status: "VERIFIED" });
    const certificate = await caller.cae.attachCalibrationCertificate({ ...access, fileName: "loadcell-cert.txt", mimeType: "text/plain", base64: base64("Calibration certificate data"), issuer: "Accredited issuer", certificateNumber: "CERT-1", instrument: "Load cell", calibrationDate: "2026-01-01", expirationDate: "2099-01-01", scope: "Force 0-10 kN", uncertainty: "±1%", actor: "Lab owner" }); expect(certificate.status).toBe("UNVERIFIED"); const certificateMissingProof = await caller.cae.verifyCalibrationCertificate({ ...access, certificateId: certificate.certificateId, reviewerId: reviewer.reviewerId, sourceVerified: false, signatureVerified: false, scopeMatch: false, reason: "Metadata only" }); expect(certificateMissingProof).toMatchObject({ status: "UNVERIFIED", filePresent: "PASS", sourceVerified: "FAIL", signatureVerified: "FAIL" }); const certificateValid = await caller.cae.verifyCalibrationCertificate({ ...access, certificateId: certificate.certificateId, reviewerId: reviewer.reviewerId, sourceVerified: true, signatureVerified: true, scopeMatch: true, reason: "Issuer, scope, date, and signature independently checked" }); expect(certificateValid.status).toBe("VALID"); const expired = await caller.cae.attachCalibrationCertificate({ ...access, fileName: "expired.txt", base64: base64("expired certificate"), issuer: "Issuer", certificateNumber: "EXPIRED-1", instrument: "Old load cell", calibrationDate: "2019-01-01", expirationDate: "2020-01-01", scope: "Force", uncertainty: "±2%", actor: "Lab owner" }); const expiredVerification = await caller.cae.verifyCalibrationCertificate({ ...access, certificateId: expired.certificateId, reviewerId: reviewer.reviewerId, sourceVerified: true, signatureVerified: true, scopeMatch: true, reason: "Checked expired record" }); expect(expiredVerification.status).toBe("EXPIRED");
    const badSignature = await caller.cae.verifyAdapterTrust({ ...access, registrationId: adapter.registrationId, reviewerId: reviewer.reviewerId, manifestVerified: true, signatureVerified: false, verifiedCapabilities: ["STATIC_STRUCTURAL"], grantedPermissions: ["READ_CAD"], reason: "Signature mismatch detected" }); expect(badSignature).toMatchObject({ trustState: "INVALID", signatureCheck: "FAIL", executionEligible: false, executable: false }); const capabilityMismatch = await caller.cae.verifyAdapterTrust({ ...access, registrationId: adapter.registrationId, reviewerId: reviewer.reviewerId, manifestVerified: true, signatureVerified: true, verifiedCapabilities: ["THERMAL"], grantedPermissions: ["READ_CAD"], reason: "Capability mismatch detected" }); expect(capabilityMismatch).toMatchObject({ trustState: "INVALID", capabilityCheck: "FAIL" }); const permissionEscalation = await caller.cae.verifyAdapterTrust({ ...access, registrationId: adapter.registrationId, reviewerId: reviewer.reviewerId, manifestVerified: true, signatureVerified: true, verifiedCapabilities: ["STATIC_STRUCTURAL"], grantedPermissions: ["READ_CAD", "NETWORK_ACCESS"], reason: "Permission escalation detected" }); expect(permissionEscalation).toMatchObject({ trustState: "INVALID", permissionCheck: "FAIL" });
    const verifiedTrust = await caller.cae.verifyAdapterTrust({ ...access, registrationId: adapter.registrationId, reviewerId: reviewer.reviewerId, manifestVerified: true, signatureVerified: true, verifiedCapabilities: ["STATIC_STRUCTURAL"], grantedPermissions: ["READ_CAD", "READ_REQUIREMENTS", "READ_MATERIAL_EVIDENCE", "READ_CAE_PLAN"], sandbox: { sandboxType: "DECLARATION_ONLY", networkPolicy: "DECLARATION_ONLY", filesystemScope: ["attempted"], resourceLimits: ["No runtime"], allowedInputs: ["CAD"], allowedOutputs: ["none"] }, reason: "All required declared trust evidence independently checked" }); expect(verifiedTrust).toMatchObject({ trustState: "VERIFIED", securityReview: "PASS", executable: false, executionEligible: false }); expect(verifiedTrust.sandbox).toMatchObject({ networkPolicy: "NO_NETWORK", filesystemScope: [], prohibitsShellExecution: true, prohibitsArbitraryFilesystem: true }); const beforeApproval = await caller.cae.adapterEligibility({ ...access, registrationId: adapter.registrationId }); expect(beforeApproval).toMatchObject({ trustState: "VERIFIED", executionEligible: false, executable: false });
    const approval = await caller.cae.authorizeEngineeringApproval({ ...access, reviewerId: reviewer.reviewerId, targetType: "ADAPTER", targetId: adapter.registrationId, decision: "APPROVE", evidenceIds: [verifiedTrust.verificationId, certificateValid.verificationId], revision: 1, reason: "Verified human approves only the recorded trust gates; no solver execution is authorized." }); expect(approval.reviewerId).toBe(reviewer.reviewerId); const eligible = await caller.cae.adapterEligibility({ ...access, registrationId: adapter.registrationId }); expect(eligible).toMatchObject({ trustState: "EXECUTION_ELIGIBLE", executionEligible: true, executable: false });
    const auditBefore = await caller.cae.securityAudit(access); const revokedAdapter = await caller.cae.revokeTrustObject({ ...access, objectType: "ADAPTER", objectId: adapter.registrationId, actor: "Security administrator", reason: "Security incident drill" }); expect(revokedAdapter).toMatchObject({ previousState: "UNVERIFIED", newState: "REVOKED" }); const ineligible = await caller.cae.adapterEligibility({ ...access, registrationId: adapter.registrationId }); expect(ineligible).toMatchObject({ trustState: "REVOKED", executionEligible: false, executable: false }); const auditAfterAdapterRevocation = await caller.cae.securityAudit(access); expect(auditAfterAdapterRevocation.length).toBeGreaterThan(auditBefore.length); expect(auditAfterAdapterRevocation).toEqual(expect.arrayContaining([expect.objectContaining({ action: "REVOCATION", objectId: adapter.registrationId })]));
    const revokedReviewer = await caller.cae.revokeTrustObject({ ...access, objectType: "REVIEWER", objectId: reviewer.reviewerId, actor: "Security administrator", reason: "Reviewer access revoked" }); expect(revokedReviewer.newState).toBe("REVOKED"); await expect(caller.cae.authorizeEngineeringApproval({ ...access, reviewerId: reviewer.reviewerId, targetType: "VALIDATION", targetId: "VALIDATION-1", decision: "APPROVE", evidenceIds: [certificateValid.verificationId], revision: 1, reason: "Blocked after reviewer revocation" })).rejects.toThrow(/not verified/); const revokedCertificate = await caller.cae.revokeTrustObject({ ...access, objectType: "CERTIFICATE", objectId: certificate.certificateId, actor: "Security administrator", reason: "Certificate superseded" }); expect(revokedCertificate.newState).toBe("REVOKED"); await expect(caller.cae.verifyCalibrationCertificate({ ...access, certificateId: certificate.certificateId, reviewerId: reviewer.reviewerId, sourceVerified: true, signatureVerified: true, scopeMatch: true, reason: "Blocked reviewer" })).rejects.toThrow(/not verified/); const audits = await caller.cae.securityAudit(access); expect(audits).toEqual(expect.arrayContaining([expect.objectContaining({ objectId: certificate.certificateId, action: "REVOCATION" }), expect.objectContaining({ objectId: reviewer.reviewerId, action: "REVOCATION" })])); const graph = await caller.cae.trustEvidenceGraph({ ...access, simulationId: "NO-CAE-SIMULATION-REQUIRED" }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: reviewer.reviewerId, type: "REVIEWER" }), expect.objectContaining({ id: certificate.certificateId, type: "CALIBRATION_CERTIFICATE" }), expect.objectContaining({ id: approval.approvalId, type: "ENGINEERING_DECISION" }), expect.objectContaining({ id: `ELIGIBILITY-${adapter.registrationId}`, type: "EXECUTION_ELIGIBILITY" })])); expect(graph.limitations.join(" ")).toContain("executable solver");
  }, 120_000);
});
