import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";
import { describe, expect, it } from "vitest";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const h = (letter: string) => letter.repeat(64);
const limits = ["CPU_LIMIT", "MEMORY_LIMIT", "DISK_LIMIT", "EXECUTION_TIMEOUT", "INPUT_SIZE_LIMIT", "OUTPUT_SIZE_LIMIT", "PROCESS_LIMIT", "CONCURRENT_JOB_LIMIT"] as const;
function planInput(projectId: string) { return { projectId, sourceCadRevision: "CAD-REV-PKG-1", sourceCadBranch: "ROOT", engineeringQuestion: "Assess a bounded static structural package contract.", analysisType: "STATIC_STRUCTURAL" as const, selectedGeometry: { kind: "FACE" as const, id: "FACE-PKG-LOAD", label: "Declared package load face", source: "VIEWER" as const }, featureHistory: ["FEATURE-PKG-1"], geometryProvenance: "OPENCASCADE_KERNEL" as const, geometryValidation: "VALID" as const, requirementIds: ["REQ-PKG-1"], material: { materialId: "MAT-PKG-1", name: "Steel schema", status: "COMPLETE" as const, properties: [{ name: "ELASTIC_MODULUS" as const, value: 210, unit: "GPa", source: "SOURCE_VERIFIED" as const, provenance: "Material evidence schema", requiredFor: ["STATIC_STRUCTURAL" as const] }, { name: "POISSON_RATIO" as const, value: 0.3, unit: "dimensionless", source: "SOURCE_VERIFIED" as const, provenance: "Material evidence schema", requiredFor: ["STATIC_STRUCTURAL" as const] }] }, boundaryConditions: [{ id: "BC-PKG-1", geometryReference: "FACE-PKG-FIXED", type: "FIXED" as const, source: "USER_PROVIDED" as const, confidence: 1, assumptionStatus: "NOT_ASSUMED" as const, geometryStatus: "PROVEN" as const }], loads: [{ id: "LOAD-PKG-1", type: "FORCE" as const, geometryReference: "FACE-PKG-LOAD", magnitude: 100, unit: "N", direction: "GLOBAL_Z" as const, source: "USER_PROVIDED" as const, assumptionStatus: "NOT_ASSUMED" as const, geometryStatus: "PROVEN" as const }], contacts: [], meshStrategy: { elementType: "TETRAHEDRAL" as const, targetSize: 2, unit: "mm", refinementRegions: [], qualityRequirements: ["External mesh quality verification is required."], convergenceRequirement: "Future convergence policy", status: "PLANNED" as const } }; }

describe("Phase 6.7 Solver Input Package Foundation", () => {
  it("records independent mesh verification and immutable non-executable package integrity without execution", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 6.7 package" }); const access = { projectId: project.id, accessKey: project.accessKey }; const plan = await caller.cae.createPlan({ ...access, input: planInput(project.id) }); const snapshot = await caller.cae.captureValidatedCAEPlanSnapshot({ ...access, simulationId: plan.simulationId, sourceCadGeometryHash: h("a"), requirementRevision: "REQ-PKG-REV-1", requirementHash: h("b"), materialEvidenceHash: h("c"), expectedOutputs: ["DISPLACEMENT", "VON_MISES_STRESS", "SOLVER_LOG", "EXECUTION_RECEIPT"] }); const resourcePolicy = { policyReference: "RESOURCE-PKG-1", policyVersion: "V1", policyHash: h("d"), environmentReference: "ENV-PKG-1", constraints: [...limits] }; const converted = await caller.cae.convertCAEPlanSnapshotToJob({ ...access, snapshotId: snapshot.snapshotId, solverVersion: "SCHEMA-V1", environmentReference: "ENV-PKG-1", resourcePolicy, createdBy: "PackageAuthor" });
    const job = converted.job; const mesh = await caller.cae.registerNonExecutableMeshArtifact({ ...access, input: { jobId: job.jobId, sourceCadHash: h("a"), nodeCount: 0, elementCount: 0, elementTypes: ["UNKNOWN"], coordinatesHash: h("1"), connectivityHash: h("2"), qualitySummary: "NOT_MEASURED", units: "UNKNOWN", generatorReference: "MESH-PACKAGE-SCHEMA", generatorVersion: "V1" } }); const quality = await caller.cae.registerMeshQualityEvidence({ ...access, input: { meshId: mesh.meshId, jobId: job.jobId, sourceCadHash: h("a"), meshGenerator: "MESH-PACKAGE-SCHEMA", meshGeneratorVersion: "V1", elementTypes: ["UNKNOWN"], elementCount: 0, nodeCount: 0, qualityMetrics: [{ metric: "UNKNOWN", source: "UNKNOWN", status: "UNKNOWN" }], qualityThresholds: [{ metric: "ASPECT_RATIO", value: 1, unit: "schema-unit", source: "Threshold evidence schema", version: "T-PKG-1", rationale: "Contract fixture only; no engineering threshold is claimed.", evidenceHash: h("3") }], provenance: { cadRevision: job.cadRevision, cadGeometryHash: h("a"), jobId: job.jobId, jobRevision: job.revision, meshArtifactId: mesh.meshId, meshGenerator: "MESH-PACKAGE-SCHEMA", meshGeneratorVersion: "V1", qualityAlgorithm: "QUALITY-PACKAGE-SCHEMA", qualityAlgorithmVersion: "V1", thresholdVersion: "T-PKG-1", references: ["Provenance schema only"] }, reportedStatus: "PASS" } }); expect(quality.qualityStatus).toBe("UNKNOWN");
    const reviewer = await caller.cae.registerReviewer({ ...access, displayName: "Independent Mesh Reviewer", role: "Validation Reviewer", projectScope: [project.id], permissions: ["APPROVE_VALIDATION"], actor: "GovernanceAdmin" }); const verifiedReviewer = await caller.cae.verifyReviewer({ ...access, reviewerId: reviewer.reviewerId, verificationMethod: "DIRECT_IDENTITY_VERIFICATION", actor: "GovernanceAdmin" }); await expect(caller.cae.createMeshQualityVerification({ ...access, meshQualityEvidenceId: quality.evidenceId, submitter: verifiedReviewer.reviewerId, verifier: verifiedReviewer.reviewerId, verificationMethod: "INDEPENDENT_REVIEW", verificationVersion: "V1", findings: ["Self verification must be rejected."], requestedStatus: "VERIFIED" })).rejects.toThrow(/self-verification/i); const verification = await caller.cae.createMeshQualityVerification({ ...access, meshQualityEvidenceId: quality.evidenceId, submitter: "MeshEvidenceSubmitter", verifier: verifiedReviewer.reviewerId, verificationMethod: "INDEPENDENT_REVIEW", verificationVersion: "V1", findings: ["Evidence identity reviewed; no meshing execution occurred."], requestedStatus: "VERIFIED" }); expect(verification).toMatchObject({ status: "VERIFIED", executable: false, meshId: mesh.meshId });
    await expect(caller.cae.createSolverInputPackageManifest({ ...access, jobId: job.jobId, meshId: "MESH-MISSING", meshHash: h("9"), meshQualityEvidenceId: quality.evidenceId, meshQualityVerificationId: verification.verificationId, solverConfigurationReference: "SOLVER-CONFIG-V1", solverConfigurationHash: h("4") })).rejects.toThrow(/missing mesh/i); await expect(caller.cae.createSolverInputPackageManifest({ ...access, jobId: job.jobId, meshId: mesh.meshId, meshHash: h("9"), meshQualityEvidenceId: quality.evidenceId, meshQualityVerificationId: verification.verificationId, solverConfigurationReference: "SOLVER-CONFIG-V1", solverConfigurationHash: h("4") })).rejects.toThrow(/mesh hash mismatch/i);
    const packageOne = await caller.cae.createSolverInputPackageManifest({ ...access, jobId: job.jobId, meshId: mesh.meshId, meshHash: mesh.artifactHash, meshQualityEvidenceId: quality.evidenceId, meshQualityVerificationId: verification.verificationId, solverConfigurationReference: "SOLVER-CONFIG-V1", solverConfigurationHash: h("4") }); const packageTwo = await caller.cae.createSolverInputPackageManifest({ ...access, jobId: job.jobId, meshId: mesh.meshId, meshHash: mesh.artifactHash, meshQualityEvidenceId: quality.evidenceId, meshQualityVerificationId: verification.verificationId, solverConfigurationReference: "SOLVER-CONFIG-V1", solverConfigurationHash: h("4") }); expect(packageOne.manifestHash).toBe(packageTwo.manifestHash); expect(packageOne).toMatchObject({ status: "VERIFIED", executionEligible: false, executable: false, securityBoundary: { immutableReferencesOnly: true, nonExecutable: true } }); expect(packageOne.securityBoundary.prohibited).toEqual(expect.arrayContaining(["ARBITRARY_COMMAND", "ARBITRARY_NETWORK", "CREDENTIAL"]));
    const conflict = await caller.cae.createSolverInputPackageManifest({ ...access, jobId: job.jobId, meshId: mesh.meshId, meshHash: mesh.artifactHash, meshQualityEvidenceId: quality.evidenceId, meshQualityVerificationId: verification.verificationId, solverConfigurationReference: "SOLVER-CONFIG-V2", solverConfigurationHash: h("5") }); expect(conflict.status).toBe("CONFLICT"); const filtered = await caller.cae.listSolverInputPackages({ ...access, cadRevision: job.cadRevision, cadGeometryHash: job.cadGeometryHash, jobRevision: job.revision, meshId: mesh.meshId, meshHash: mesh.artifactHash }); expect(filtered.map((item) => item.packageId)).toContain(packageOne.packageId); expect(await caller.cae.listSolverInputPackages({ ...access, cadRevision: "CAD-REV-OTHER" })).toEqual([]); const stale = await caller.cae.assessSolverInputPackageStaleness({ ...access, packageId: packageOne.packageId, observedCadRevision: "CAD-REV-OTHER", observedCadGeometryHash: job.cadGeometryHash, observedJobRevision: job.revision, observedMeshId: mesh.meshId, observedMeshHash: mesh.artifactHash, observedMaterialEvidenceHash: job.materialEvidenceHash, observedMeshQualityVerificationId: verification.verificationId }); expect(stale).toMatchObject({ status: "STALE", executionEligible: false, executable: false }); const graph = await caller.cae.solverInputPackageGraph({ ...access, packageId: packageOne.packageId }); expect(graph.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ id: packageOne.packageId }), expect.objectContaining({ id: mesh.meshId })])); expect(graph.limitations.join(" ")).toMatch(/no solver|non-executable/i);
    const other = await caller.persistentMemory.openProject({ name: "Phase 6.7 package isolation" }); await expect(caller.cae.listSolverInputPackages({ projectId: other.id, accessKey: other.accessKey })).resolves.toEqual([]); expect(Object.keys(caller.cae)).not.toEqual(expect.arrayContaining(["executeSolver", "executeMesher", "runGmsh", "runCalculiX", "runShell", "runProcess"]));
  });
});
