import type { TrpcContext } from "../server/_core/context";
import { appRouter } from "../server/routers";
import { describe, expect, it } from "vitest";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const circleInput = { title: "Offset boss", centerX: 30, centerY: 0, radius: 5, extrudeDistance: 10, unit: "mm" as const };

describe("Phase 4.8 topology naming and guarded circular pattern", () => {
  it("returns targeted Circular Pattern questions without guessing source or axis, then emits a bounded plan when all explicit evidence is supplied", async () => {
    const caller = appRouter.createCaller(ctx);
    const incomplete = await caller.featureHistory.planCircularPattern({ message: "Place six identical bosses around this center" });
    expect(incomplete).toMatchObject({ status: "OPEN_QUESTION", executable: false, operation: "CIRCULAR_PATTERN" }); expect(incomplete.questions).toEqual(expect.arrayContaining([expect.stringContaining("source revision"), expect.stringContaining("GLOBAL_Z"), expect.stringContaining("angle")]));
    const complete = await caller.featureHistory.planCircularPattern({ message: "source: CIRCLE-REVISION-abcdef; feature: EXTRUDE-CIRCLE-001; axis: GLOBAL_Z; 6 instances; 360°" });
    expect(complete).toMatchObject({ status: "READY_FOR_PREVIEW", executable: true, input: { sourceRevisionId: "CIRCLE-REVISION-abcdef", sourceFeatureId: "EXTRUDE-CIRCLE-001", axis: "GLOBAL_Z", instanceCount: 6, angleDegrees: 360 } });
  });

  it("creates revision-safe feature-role topology manifests with hash-backed STEP provenance and unique matching across a controlled circle regeneration", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Topology naming proof" });
    const base = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: circleInput });
    const manifest = await caller.featureHistory.topologyManifest({ projectId: project.id, accessKey: project.accessKey, revisionId: base.revisionId });
    expect(manifest.invariant).toBe("FEATURE_ROLE_AND_SIGNATURE"); expect(manifest.references.some((reference) => reference.provenance.role === "CIRCLE_TOP_CAP" && reference.validity === "VALID")).toBe(true); expect(manifest.references.some((reference) => reference.validity === "REVISION_SCOPED")).toBe(true);
    expect(base.geometry.export?.provenance).toMatchObject({ projectId: project.id, sourceRevisionId: base.revisionId, geometryValidation: "VALID", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED" }); expect(base.geometry.export?.provenance?.sha256).toMatch(/^[a-f0-9]{64}$/);
    const preview = await caller.featureHistory.previewCircle({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: base.revisionId, edit: { featureId: "CIRCLE-SKETCH-001", parameter: { name: "radius", value: 6, unit: "mm" } } }); const child = await caller.featureHistory.executeCircle({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: preview.revisionId });
    const report = await caller.featureHistory.topologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: base.revisionId, targetRevisionId: child.revisionId }); expect(report.summary.matched).toBeGreaterThan(0); expect(report.summary.ambiguous).toBe(0); expect(report.matches.some((item) => item.status === "TOPOLOGY_MATCHED" && item.reasons[0].includes("role survived"))).toBe(true); expect(report.matches.some((item) => item.status === "TOPOLOGY_REFERENCE_INVALIDATED" && item.reasons[0].includes("revision-scoped"))).toBe(true); expect(base.geometry.boundingBox?.size[0]).toBeCloseTo(10, 5); expect(child.geometry.boundingBox?.size[0]).toBeCloseTo(12, 5);
  }, 50_000);

  it("creates, regenerates, validates, branches, and exports a real guarded Global Z circular pattern while preserving source and reporting ambiguity/invalidation without guessing", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Guarded pattern proof" }); const source = await caller.featureHistory.createCircle({ projectId: project.id, accessKey: project.accessKey, input: circleInput });
    const pattern = await caller.featureHistory.createCircularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "Four boss pattern", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", axis: "GLOBAL_Z", instanceCount: 4, angleDegrees: 360, direction: "COUNTERCLOCKWISE" } });
    expect(pattern).toMatchObject({ status: "KERNEL_VALIDATED", parentRevisionId: source.revisionId, geometry: { validation: "VALID", export: { status: "AVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED" } } }); const node = pattern.features.find((feature) => feature.featureType === "CIRCULAR_PATTERN"); expect(node?.generatedInstances).toHaveLength(4); expect(node?.operationData).toMatchObject({ source_feature: "EXTRUDE-CIRCLE-001", axis: "GLOBAL_Z", instance_count: 4, angle_degrees: 360 }); expect(pattern.geometry.export?.provenance?.sha256).toMatch(/^[a-f0-9]{64}$/);
    const preview = await caller.featureHistory.previewCircularPattern({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: pattern.revisionId, edit: { instanceCount: 6, angleDegrees: 360, axis: "GLOBAL_Z", direction: "COUNTERCLOCKWISE" } }); expect(preview).toMatchObject({ status: "PREVIEW", geometry: { validation: "VALID" } }); const child = await caller.featureHistory.executeCircularPattern({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: preview.revisionId }); expect(child).toMatchObject({ status: "KERNEL_VALIDATED", parentRevisionId: pattern.revisionId }); expect(child.features.find((feature) => feature.featureType === "CIRCULAR_PATTERN")?.generatedInstances).toHaveLength(6);
    const growth = await caller.featureHistory.topologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: pattern.revisionId, targetRevisionId: child.revisionId }); expect(growth.summary.ambiguous).toBeGreaterThan(0); expect(growth.summary.newEntities).toBeGreaterThan(0); expect(growth.matches.some((item) => item.status === "TOPOLOGY_MATCH_AMBIGUOUS")).toBe(true); expect(growth.matches.some((item) => item.status === "NEW_ENTITY")).toBe(true);
    const shrinkPreview = await caller.featureHistory.previewCircularPattern({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: child.revisionId, edit: { instanceCount: 2, angleDegrees: 180, axis: "GLOBAL_Z", direction: "COUNTERCLOCKWISE" } }); const shrunk = await caller.featureHistory.executeCircularPattern({ projectId: project.id, accessKey: project.accessKey, previewRevisionId: shrinkPreview.revisionId }); const deletion = await caller.featureHistory.topologyMatch({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: child.revisionId, targetRevisionId: shrunk.revisionId }); expect(deletion.summary.invalidated).toBeGreaterThan(0); expect(deletion.matches.some((item) => item.status === "TOPOLOGY_REFERENCE_INVALIDATED")).toBe(true);
    const gate = await caller.featureHistory.filletGate({ projectId: project.id, accessKey: project.accessKey, sourceRevisionId: child.revisionId, targetRevisionId: shrunk.revisionId }); expect(gate.ready).toBe(false); expect(gate.missing).toEqual(expect.arrayContaining(["TOPOLOGY_MATCHING", "KERNEL_FILLET_EXECUTION_SUPPORTED"]));
    const invalid = await caller.featureHistory.createCircularPattern({ projectId: project.id, accessKey: project.accessKey, input: { title: "Overlapping", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", axis: "GLOBAL_Z", instanceCount: 24, angleDegrees: 360, direction: "COUNTERCLOCKWISE" } }); expect(invalid).toMatchObject({ status: "FAILED", failure: { stage: "VALIDATION" } }); expect(source.status).toBe("KERNEL_VALIDATED");
  }, 75_000);

  it("preserves project isolation for topology and pattern access", async () => {
    const caller = appRouter.createCaller(ctx); const first = await caller.persistentMemory.openProject({ name: "Pattern isolation A" }); const second = await caller.persistentMemory.openProject({ name: "Pattern isolation B" }); const source = await caller.featureHistory.createCircle({ projectId: first.id, accessKey: first.accessKey, input: circleInput }); await expect(caller.featureHistory.topologyManifest({ projectId: first.id, accessKey: second.accessKey, revisionId: source.revisionId })).rejects.toThrow(); await expect(caller.featureHistory.createCircularPattern({ projectId: first.id, accessKey: second.accessKey, input: { title: "Denied", sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", axis: "GLOBAL_Z", instanceCount: 4, angleDegrees: 360, direction: "COUNTERCLOCKWISE" } })).rejects.toThrow();
  }, 40_000);
});
