import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";

import { appRouter } from "../server/routers";
import type { TrpcContext } from "../server/_core/context";

const ctx = { user: null, req: { protocol: "https", headers: {} }, res: {} } as TrpcContext;
const digest = (value: string) => createHash("sha256").update(value).digest("hex");

describe("Phase 6.3 independent verification governance", () => {
  it("enforces reviewer separation, retention, revocation, lifecycle, conflicts, and fail-closed readiness without execution", async () => {
    const caller = appRouter.createCaller(ctx); const project = await caller.persistentMemory.openProject({ name: "Phase 6.3 governance" }); const access = { projectId: project.id, accessKey: project.accessKey };
    const policies = await caller.cae.ensureGovernancePolicies(access); expect(policies.separationPolicy.allowSelfReview).toBe(false); expect(policies.revocationPolicy.previouslyApprovedEvidence).toBe("REQUIRES_REVIEW"); expect(policies.retentionPolicies).toHaveLength(5); expect(policies.retentionPolicies.every((item) => item.deletionPolicy === "NO_SILENT_DELETION" && item.expirationBehavior === "HISTORICAL_NOT_GATE_VALID")).toBe(true);
    const reviewers = []; for (const [displayName, role] of [["Reviewer B", "Security reviewer"], ["Reviewer A", "Security reviewer"], ["Reviewer C", "Conflict reviewer"], ["Reviewer D", "Conflict resolver"]]) { const reviewer = await caller.cae.registerReviewer({ ...access, displayName, role, projectScope: [project.id], permissions: ["APPROVE_VALIDATION"], actor: "governance fixture" }); await caller.cae.verifyReviewer({ ...access, reviewerId: reviewer.reviewerId, verificationMethod: "fixture identity verification", actor: "governance fixture" }); reviewers.push(reviewer); } const [reviewerB, reviewerA, reviewerC, reviewerD] = reviewers;
    const raw = "Phase 6.3 CPU external fixture"; const cpu = await caller.cae.importInfrastructureEvidence({ ...access, kind: "CPU", measurement: "fixture CPU", measurementMethod: "external fixture", environment: "segregated fixture environment", source: "external fixture", issuer: "fixture issuer", timestamp: "2026-08-21T00:00:00.000Z", rawEvidence: raw, originalHash: digest(raw), verificationMethod: "external import" });
    const environment = await caller.cae.registerHostileTestEnvironment({ ...access, environmentName: "Segregated fixture test environment", declaredIsolation: "DESIGNED" }); const logs = "fixture isolated test logs"; const artifacts = ["fixture-artifact"]; const hostileRaw = "fixture hostile evidence"; const hostile = await caller.cae.importHostileTestEvidence({ ...access, testId: "GOVERNANCE-FIXTURE", environmentId: environment.environmentId, testVersion: "1.0.0", attackDescription: "Imported fixture only; production never executes hostile tests.", expectedResult: "denial", actualResult: "external fixture reports denial", logs, artifacts, timestamp: "2026-08-21T00:00:00.000Z", hash: digest(`${logs}\n${artifacts.join("\n")}`), reviewer: "External assessor", status: "PASS", source: "external fixture", issuer: "fixture issuer", rawEvidence: hostileRaw, originalHash: digest(hostileRaw), verificationMethod: "external import" });
    const self = await caller.cae.submitVerificationReview({ ...access, evidenceType: "INFRASTRUCTURE", evidenceReference: cpu.evidenceId, submitterIdentity: reviewerB!.reviewerId, reviewScope: "self-review refusal", reason: "Fixture submission." }); await expect(caller.cae.assignVerificationReview({ ...access, reviewId: self.review.reviewId, reviewerId: reviewerB!.reviewerId, reason: "Attempt self-review." })).rejects.toThrow(/self-review/i); await expect(caller.cae.submitVerificationReview({ ...access, evidenceType: "INFRASTRUCTURE", evidenceReference: cpu.evidenceId, submitterIdentity: "", reviewScope: "invalid", reason: "invalid" })).rejects.toThrow();
    const submitAssignDecide = async (reviewerId: string, decision: "ACCEPT" | "REJECT") => { const submitted = await caller.cae.submitVerificationReview({ ...access, evidenceType: "INFRASTRUCTURE", evidenceReference: cpu.evidenceId, submitterIdentity: "named-evidence-submitter", reviewScope: "Independent CPU evidence review", reason: "Fixture review submission." }); const assigned = await caller.cae.assignVerificationReview({ ...access, reviewId: submitted.review.reviewId, reviewerId, reason: "Independent reviewer assignment." }); return caller.cae.decideVerificationReview({ ...access, reviewId: assigned.review.reviewId, reviewerId, decision, reason: `Fixture reviewer decision: ${decision}.` }); };
    const acceptedB = await submitAssignDecide(reviewerB!.reviewerId, "ACCEPT"); expect(acceptedB.review.status).toBe("ACCEPTED"); const afterAccept = await caller.cae.evaluateVerificationGovernanceReadiness(access); expect(afterAccept.executionEligible).toBe(false); expect(afterAccept.executable).toBe(false); expect(afterAccept.gates.find((item) => item.gate === "INDEPENDENT_REVIEW")?.status).toBe("PASS");
    await caller.cae.revokeGovernanceReviewer({ ...access, reviewerId: reviewerB!.reviewerId, actor: "governance fixture", reason: "Fixture reviewer revocation." }); const afterRevocation = await caller.cae.evaluateVerificationGovernanceReadiness(access); expect(afterRevocation.readiness).toBe("NOT_READY"); expect(afterRevocation.gates.find((item) => item.gate === "REVIEWER_REVOCATION")?.status).toBe("FAIL");
    const acceptedA = await submitAssignDecide(reviewerA!.reviewerId, "ACCEPT"); const afterRereview = await caller.cae.evaluateVerificationGovernanceReadiness(access); expect(afterRereview.gates.find((item) => item.gate === "REVIEWER_REVOCATION")?.status).toBe("PASS"); const expired = await caller.cae.transitionVerificationReview({ ...access, reviewId: acceptedA.review.reviewId, reviewerId: reviewerA!.reviewerId, transition: "EXPIRE", reason: "Fixture review expiration." }); expect(expired.review.status).toBe("EXPIRED"); expect(expired.readiness.readiness).toBe("NOT_READY"); await submitAssignDecide(reviewerA!.reviewerId, "ACCEPT");
    const rejectedC = await submitAssignDecide(reviewerC!.reviewerId, "REJECT"); expect(rejectedC.conflict?.status).toBe("VERIFICATION_CONFLICT"); expect(rejectedC.readiness.readiness).toBe("NOT_READY"); const resolved = await caller.cae.resolveVerificationConflict({ ...access, conflictId: rejectedC.conflict!.conflictId, reviewerId: reviewerD!.reviewerId, reason: "Fixture authorized independent resolution." }); expect(resolved.conflict.status).toBe("RESOLVED"); expect(resolved.readiness.gates.find((item) => item.gate === "VERIFICATION_CONFLICT")?.status).toBe("PASS"); await caller.cae.verifyExternalEvidence({ ...access, evidenceType: "HOSTILE_TEST_ENVIRONMENT", evidenceId: environment.environmentId, reviewerId: reviewerA!.reviewerId, sourceVerified: true, verificationMethod: "fixture external verification", reason: "Fixture environment evidence verified." }); await caller.cae.verifyExternalEvidence({ ...access, evidenceType: "HOSTILE_TEST", evidenceId: hostile.evidenceId, reviewerId: reviewerA!.reviewerId, sourceVerified: true, verificationMethod: "fixture external verification", reason: "Fixture hostile evidence verified." }); const reference = await caller.cae.importTestEnvironmentEvidenceReference({ ...access, environmentId: environment.environmentId, testRunId: "EXTERNAL-RUN-001", testVersion: "1.0.0", evidenceHash: hostile.hash, source: "external segregated fixture", timestamp: "2026-08-21T00:00:00.000Z", reviewer: reviewerA!.reviewerId }); expect(reference.record.status).toBe("SUBMITTED");
    const lifecycle = await caller.cae.listGovernanceLifecycle(access); expect(lifecycle).toEqual(expect.arrayContaining([expect.objectContaining({ newState: "SUBMITTED" }), expect.objectContaining({ newState: "UNDER_REVIEW" }), expect.objectContaining({ newState: "ACCEPTED" }), expect.objectContaining({ newState: "EXPIRED" })])); const audit = await caller.cae.securityAudit(access); expect(audit).toEqual(expect.arrayContaining([expect.objectContaining({ action: "VERIFICATION_REVIEW" }), expect.objectContaining({ action: "VERIFICATION_CONFLICT" }), expect.objectContaining({ action: "GOVERNANCE_POLICY" })])); const other = await caller.persistentMemory.openProject({ name: "Phase 6.3 isolated project" }); await expect(caller.cae.listVerificationReviews({ projectId: other.id, accessKey: other.accessKey })).resolves.toEqual([]); expect(Object.keys(caller.cae)).not.toEqual(expect.arrayContaining(["executeSolver", "executeHostileTest", "executeRuntime", "runShell", "launchPlugin", "openFilesystem"]));
  }, 90_000);
});
