import { useEffect, useState } from "react";
import { ActivityIndicator, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

const MAX_BYTES = 5 * 1024 * 1024;
function badgeColor(value?: string) { if (["VERIFIED", "PASS", "CURRENT", "READY_FOR_EXPERIMENT"].includes(value ?? "")) return "#62B39A"; if (["CONFLICT", "STALE", "FAIL", "UNAVAILABLE", "MISSING_MATERIAL", "MISSING_LOADS", "MISSING_BOUNDARIES", "MISSING_MESH"].includes(value ?? "")) return "#E78966"; return "#8EC4E8"; }
function Badge({ value }: { value: string }) { const color = badgeColor(value); return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}16` }]}><Text style={[styles.badgeText, { color }]}>{value}</Text></View>; }
function list(value: string) { return value.split(";").map((item) => item.trim()).filter(Boolean); }
function webBase64(bytes: Uint8Array) { let output = ""; for (let index = 0; index < bytes.length; index += 0x8000) output += String.fromCharCode(...bytes.subarray(index, Math.min(bytes.length, index + 0x8000))); return globalThis.btoa(output); }

export function CAEEvidencePanel({ simulationId, observedCadRevision }: { simulationId: string; observedCadRevision?: string }) {
  const [project, setProject] = useState<StoredProjectAccess>(); const [notice, setNotice] = useState("Material evidence remains project-isolated, hash-tracked, immutable, and unvalidated until its provenance is reviewed.");
  const [material, setMaterial] = useState("Material name"); const [property, setProperty] = useState<"ELASTIC_MODULUS" | "POISSON_RATIO" | "DENSITY" | "YIELD_STRENGTH">("ELASTIC_MODULUS"); const [value, setValue] = useState(""); const [unit, setUnit] = useState("GPa"); const [source, setSource] = useState("Source reference"); const [provenance, setProvenance] = useState<"VERIFIED_SOURCE" | "USER_PROVIDED" | "EXPERIMENTALLY_MEASURED" | "CALCULATED" | "ASSUMED" | "UNKNOWN">("USER_PROVIDED");
  const [objective, setObjective] = useState(""); const [hypothesis, setHypothesis] = useState(""); const [article, setArticle] = useState(""); const [instrumentation, setInstrumentation] = useState(""); const [measurements, setMeasurements] = useState(""); const [criteria, setCriteria] = useState(""); const [safety, setSafety] = useState(""); const [repeatability, setRepeatability] = useState(""); const [comparison, setComparison] = useState("");
  const [readiness, setReadiness] = useState<Awaited<ReturnType<typeof import("@/server/caeEvidence").assessReadiness>>>(); const [uncertainty, setUncertainty] = useState<Awaited<ReturnType<typeof import("@/server/caeEvidence").assessUncertainty>>>(); const [graph, setGraph] = useState<Awaited<ReturnType<typeof import("@/server/caeEvidence").buildEvidenceGraph>>>(); const [invalidation, setInvalidation] = useState<Awaited<ReturnType<typeof import("@/server/caeEvidence").invalidateCadContext>>>();
  useEffect(() => { let cancelled = false; const load = async () => { const stored = await loadProjectAccess("active-engineering-workbench"); if (!cancelled && stored) setProject(stored); }; void load(); const timer = setInterval(() => void load(), 1_000); return () => { cancelled = true; clearInterval(timer); }; }, []);
  const adapter = trpc.cae.solverAdapter.useQuery(); const evidence = trpc.cae.listMaterialEvidence.useQuery({ projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }, { enabled: Boolean(project) }); const conflicts = trpc.cae.materialConflicts.useQuery({ projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }, { enabled: Boolean(project) }); const experiments = trpc.cae.listExperimentalPlans.useQuery({ projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE", simulationId }, { enabled: Boolean(project && simulationId) });
  const upload = trpc.cae.registerMaterialEvidence.useMutation(); const createExperiment = trpc.cae.createExperimentalPlan.useMutation(); const negotiate = trpc.cae.negotiateSolver.useQuery({ projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE", simulationId }, { enabled: Boolean(project && simulationId) }); const readinessMutation = trpc.cae.readiness.useMutation(); const uncertaintyMutation = trpc.cae.uncertainty.useMutation(); const graphMutation = trpc.cae.evidenceGraph.useMutation(); const invalidationMutation = trpc.cae.invalidateCadContext.useMutation();
  const pickEvidence = async () => { if (!project) return; try { const result = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "text/plain", "application/octet-stream"], copyToCacheDirectory: true }); if (result.canceled) { setNotice("Evidence selection was cancelled; no file or metadata was recorded."); return; } const asset = result.assets[0]; if (asset.size !== undefined && asset.size > MAX_BYTES) { setNotice("Evidence file exceeds the bounded 5 MiB envelope; it was not read or uploaded."); return; } const base64 = Platform.OS === "web" ? webBase64(new Uint8Array(await (await fetch(asset.uri)).arrayBuffer())) : await FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.Base64 }); upload.mutate({ projectId: project.projectId, accessKey: project.accessKey, input: { fileName: asset.name, mimeType: asset.mimeType ?? "application/octet-stream", base64, type: "MATERIAL_DATASHEET", source, material, property, ...(value.trim() ? { value: Number(value) } : {}), ...(unit.trim() ? { unit } : {}), provenance } }, { onSuccess: (item) => { setNotice(`Stored immutable evidence ${item.evidenceId} · SHA-256 ${item.sha256.slice(0, 16)}… · v${item.version}.`); void evidence.refetch(); void conflicts.refetch(); }, onError: (error) => setNotice(error.message) }); } catch (error) { setNotice(error instanceof Error ? error.message : "Evidence selection failed."); } };
  const makeExperiment = () => { if (!project) return; createExperiment.mutate({ projectId: project.projectId, accessKey: project.accessKey, input: { simulationId, objective, hypothesis, testArticle: article, instrumentation: list(instrumentation), loads: [], boundaryConditions: [], measurements: list(measurements), acceptanceCriteria: list(criteria), uncertainties: [], repeatability, safetyRequirements: list(safety), simulationComparison: comparison } }, { onSuccess: (item) => { setNotice(`Experimental validation plan ${item.experimentId} is ${item.status}; it contains no measured evidence or validation decision.`); void experiments.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const assess = () => { if (!project) return; readinessMutation.mutate({ projectId: project.projectId, accessKey: project.accessKey, simulationId }, { onSuccess: (item) => setReadiness(item), onError: (error) => setNotice(error.message) }); uncertaintyMutation.mutate({ projectId: project.projectId, accessKey: project.accessKey, simulationId }, { onSuccess: (item) => setUncertainty(item), onError: (error) => setNotice(error.message) }); graphMutation.mutate({ projectId: project.projectId, accessKey: project.accessKey, simulationId }, { onSuccess: (item) => setGraph(item), onError: (error) => setNotice(error.message) }); if (observedCadRevision) invalidationMutation.mutate({ projectId: project.projectId, accessKey: project.accessKey, simulationId, observedCadRevision }, { onSuccess: (item) => setInvalidation(item), onError: (error) => setNotice(error.message) }); };
  return <View style={styles.wrap}>
    <View style={styles.card}><View style={styles.row}><View><Text style={styles.kicker}>VERSIONED SOLVER ADAPTER</Text><Text style={styles.value}>{adapter.data?.displayName ?? "Loading adapter contract"}</Text></View><Badge value={adapter.data?.status ?? "UNKNOWN"} /></View><Text style={styles.meta}>Contract {adapter.data?.contractVersion ?? "UNKNOWN"} · {adapter.data?.executionEnvironment ?? "UNKNOWN"} · executable: {String(adapter.data?.executable ?? false)}</Text><Text style={styles.copy}>{adapter.data?.reason ?? "Adapter declaration unavailable."}</Text><Text style={styles.meta}>Negotiation: {negotiate.data?.status ?? "UNKNOWN"} · unsupported: {negotiate.data?.unsupported.slice(0, 3).join(" · ") || "unknown"}</Text></View>
    <View style={styles.card}><Text style={styles.kicker}>MATERIAL EVIDENCE</Text><Text style={styles.copy}>Attach a bounded datasheet, specification, test report, research document, standard, or user measurement. The file is hash tracked and stored in the authorized project; provenance is never upgraded silently.</Text><TextInput value={material} onChangeText={setMaterial} style={styles.input} placeholder="Material" placeholderTextColor="#71828B" /><View style={styles.choiceRow}>{(["ELASTIC_MODULUS", "POISSON_RATIO", "DENSITY", "YIELD_STRENGTH"] as const).map((item) => <Pressable key={item} style={[styles.choice, property === item && styles.choiceActive]} onPress={() => setProperty(item)}><Text style={styles.choiceText}>{item}</Text></Pressable>)}</View><View style={styles.pair}><TextInput value={value} onChangeText={setValue} style={styles.half} keyboardType="decimal-pad" placeholder="Value (optional)" placeholderTextColor="#71828B" /><TextInput value={unit} onChangeText={setUnit} style={styles.half} placeholder="Unit" placeholderTextColor="#71828B" /></View><TextInput value={source} onChangeText={setSource} style={styles.input} placeholder="Source" placeholderTextColor="#71828B" /><View style={styles.choiceRow}>{(["VERIFIED_SOURCE", "USER_PROVIDED", "EXPERIMENTALLY_MEASURED", "CALCULATED", "ASSUMED", "UNKNOWN"] as const).map((item) => <Pressable key={item} style={[styles.choice, provenance === item && styles.choiceActive]} onPress={() => setProvenance(item)}><Text style={styles.choiceText}>{item}</Text></Pressable>)}</View><Pressable disabled={!project || upload.isPending} style={[styles.primary, (!project || upload.isPending) && styles.disabled]} onPress={pickEvidence}><Text style={styles.primaryText}>{upload.isPending ? "STORING EVIDENCE…" : "ATTACH MATERIAL EVIDENCE"}</Text></Pressable>{evidence.data?.slice(0, 4).map((item) => <View key={item.evidenceId} style={styles.record}><View style={{ flex: 1 }}><Text style={styles.recordTitle}>{item.material} · {item.property} · v{item.version}</Text><Text style={styles.meta}>{item.fileName} · SHA-256 {item.sha256.slice(0, 16)}… · {item.provenance}</Text></View><Badge value={item.verificationStatus} /></View>)}{conflicts.data?.length ? <Text style={styles.warning}>CONFLICTS · {conflicts.data.map((item) => `${item.property}: ${item.reason}`).join(" ")}</Text> : null}</View>
    <View style={styles.card}><Text style={styles.kicker}>EXPERIMENTAL VALIDATION PLAN</Text><TextInput value={objective} onChangeText={setObjective} style={styles.input} placeholder="Objective" placeholderTextColor="#71828B" /><TextInput value={hypothesis} onChangeText={setHypothesis} style={styles.input} placeholder="Hypothesis" placeholderTextColor="#71828B" /><TextInput value={article} onChangeText={setArticle} style={styles.input} placeholder="Test article" placeholderTextColor="#71828B" /><TextInput value={instrumentation} onChangeText={setInstrumentation} style={styles.input} placeholder="Instrumentation; separated by semicolons" placeholderTextColor="#71828B" /><TextInput value={measurements} onChangeText={setMeasurements} style={styles.input} placeholder="Measurements; separated by semicolons" placeholderTextColor="#71828B" /><TextInput value={criteria} onChangeText={setCriteria} style={styles.input} placeholder="Acceptance criteria; separated by semicolons" placeholderTextColor="#71828B" /><TextInput value={safety} onChangeText={setSafety} style={styles.input} placeholder="Safety requirements; separated by semicolons" placeholderTextColor="#71828B" /><TextInput value={repeatability} onChangeText={setRepeatability} style={styles.input} placeholder="Repeatability method" placeholderTextColor="#71828B" /><TextInput value={comparison} onChangeText={setComparison} style={styles.input} placeholder="Future simulation comparison method" placeholderTextColor="#71828B" /><Pressable disabled={!project || createExperiment.isPending} style={[styles.secondary, (!project || createExperiment.isPending) && styles.disabled]} onPress={makeExperiment}><Text style={styles.secondaryText}>{createExperiment.isPending ? "CREATING…" : "CREATE EXPERIMENT PLAN"}</Text></Pressable>{experiments.data?.map((item) => <View key={item.experimentId} style={styles.record}><Text style={styles.recordTitle}>{item.objective}</Text><Badge value={item.status} /></View>)}</View>
    <View style={styles.card}><View style={styles.row}><View><Text style={styles.kicker}>READINESS, UNCERTAINTY & EVIDENCE GRAPH</Text><Text style={styles.meta}>Assess explicit evidence; no state implies a numerical result or physical validation.</Text></View><Pressable disabled={!project || readinessMutation.isPending || uncertaintyMutation.isPending || graphMutation.isPending} style={styles.secondary} onPress={assess}><Text style={styles.secondaryText}>ASSESS</Text></Pressable></View>{readiness ? <View style={styles.record}><View style={{ flex: 1 }}><Text style={styles.recordTitle}>CAE_READINESS · {readiness.reason}</Text><Text style={styles.meta}>{readiness.evidence.map((item) => `${item.category} ${item.status}`).join(" · ")}</Text></View><Badge value={readiness.state} /></View> : null}{uncertainty ? <Text style={styles.copy}>Uncertainty: {uncertainty.items.map((item) => `${item.category}: ${item.source}`).join(" · ")}</Text> : null}{invalidation ? <View style={styles.record}><Text style={styles.recordTitle}>CAD context · {invalidation.reason}</Text><Badge value={invalidation.status} /></View> : null}{graph ? <Text style={styles.meta}>Evidence graph · {graph.nodes.length} nodes · {graph.edges.length} explicit relationships. {graph.limitations[0]}</Text> : null}</View>
    <Text style={styles.notice}>{notice}</Text>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 }, kicker: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, value: { color: "#F3F1EA", fontSize: 12, fontWeight: "800", marginTop: 3 }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, meta: { color: "#90A0A8", fontSize: 8, lineHeight: 13 }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3, alignSelf: "flex-start" }, badgeText: { fontSize: 7, fontWeight: "900" }, input: { color: "#F3F1EA", backgroundColor: "#111C22", borderColor: "#34434B", borderWidth: 1, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 7, fontSize: 9 }, pair: { flexDirection: "row", gap: 7 }, half: { flex: 1, color: "#F3F1EA", backgroundColor: "#111C22", borderColor: "#34434B", borderWidth: 1, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 7, fontSize: 9 }, choiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 5 }, choice: { borderWidth: 1, borderColor: "#34434B", borderRadius: 6, paddingHorizontal: 6, paddingVertical: 4 }, choiceActive: { borderColor: "#5B9DCA", backgroundColor: "#1E3A4A" }, choiceText: { color: "#B5C8D0", fontSize: 7, fontWeight: "800" }, primary: { backgroundColor: "#1167B1", minHeight: 40, justifyContent: "center", alignItems: "center", borderRadius: 9 }, primaryText: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, secondary: { borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 6, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, disabled: { opacity: 0.45 }, record: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, borderTopWidth: 1, borderTopColor: "#2B3A41", paddingTop: 7 }, recordTitle: { color: "#F3F1EA", fontSize: 9, fontWeight: "800", flex: 1 }, warning: { color: "#F0AB79", fontSize: 9, lineHeight: 14, backgroundColor: "#3A2A1C", padding: 7, borderRadius: 7 }, notice: { color: "#8EC4E8", fontSize: 8, lineHeight: 13, textAlign: "center" } });
