import { useEffect, useState } from "react";
import { ActivityIndicator, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

const MAX_BYTES = 5 * 1024 * 1024;
function webBase64(bytes: Uint8Array) { let text = ""; for (let offset = 0; offset < bytes.length; offset += 0x8000) text += String.fromCharCode(...bytes.subarray(offset, Math.min(offset + 0x8000, bytes.length))); return globalThis.btoa(text); }
function Badge({ value }: { value: string }) { const color = ["CONFLICT", "REJECTED", "NO_SIMULATION_RESULT", "UNVERIFIED", "UNKNOWN", "UNAVAILABLE"].includes(value) ? "#E78966" : ["RESOLVED", "CONSISTENT", "MEASURED"].includes(value) ? "#62B39A" : "#8EC4E8"; return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.badgeText, { color }]}>{value}</Text></View>; }

export function CAEReconciliationPanel({ simulationId }: { simulationId: string }) {
  const [project, setProject] = useState<StoredProjectAccess>(); const [notice, setNotice] = useState("Review gates require a named human reviewer; no conflicting value can be selected automatically.");
  const [material, setMaterial] = useState("Material name"); const [reviewer, setReviewer] = useState(""); const [decisionReason, setDecisionReason] = useState(""); const [instrument, setInstrument] = useState("Instrument"); const [quantity, setQuantity] = useState("Measured quantity"); const [measurementValue, setMeasurementValue] = useState(""); const [graph, setGraph] = useState<{ nodes: unknown[]; edges: unknown[]; limitations: string[] }>();
  useEffect(() => { let dead = false; const load = async () => { const stored = await loadProjectAccess("active-engineering-workbench"); if (!dead && stored) setProject(stored); }; void load(); const interval = setInterval(() => void load(), 1_000); return () => { dead = true; clearInterval(interval); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" };
  const reconcile = trpc.cae.reconcileMaterialProperty.useMutation(); const decide = trpc.cae.recordEngineeringDecision.useMutation(); const datasets = trpc.cae.listMeasurementDatasets.useQuery({ ...access, simulationId }, { enabled: Boolean(project && simulationId) }); const calibrations = trpc.cae.listCalibrationRecords.useQuery(access, { enabled: Boolean(project) }); const comparisons = trpc.cae.listComparisons.useQuery({ ...access, simulationId }, { enabled: Boolean(project && simulationId) }); const adapters = trpc.cae.listExternalSolverAdapters.useQuery(access, { enabled: Boolean(project) }); const uploadDataset = trpc.cae.ingestMeasurementDataset.useMutation(); const recordCalibration = trpc.cae.recordCalibration.useMutation(); const createComparison = trpc.cae.createComparison.useMutation(); const extendedGraph = trpc.cae.extendedEvidenceGraph.useMutation();
  const [reconciliation, setReconciliation] = useState<Awaited<ReturnType<typeof import("@/server/caeReconciliation").reconcileMaterialProperty>>>();
  const runReconciliation = () => { if (!project) return; reconcile.mutate({ ...access, material, property: "YIELD_STRENGTH" }, { onSuccess: (item) => { setReconciliation(item); setNotice(`${item.state}: ${item.conflicts.length} explicit conflict class(es); no value was selected.`); }, onError: (error) => setNotice(error.message) }); };
  const resolve = () => { if (!project || !reconciliation) return; decide.mutate({ ...access, reconciliationId: reconciliation.reconciliationId, reviewer, decision: "REQUEST_EVIDENCE", reason: decisionReason, evidenceIds: reconciliation.candidates.map((item) => item.evidenceId), revision: reconciliation.revision + 1 }, { onSuccess: (item) => { setNotice(`Recorded HUMAN decision ${item.decisionId}; reconciliation remains evidence-led.`); }, onError: (error) => setNotice(error.message) }); };
  const pickDataset = async () => { if (!project) return; try { const result = await DocumentPicker.getDocumentAsync({ type: ["text/csv", "text/tab-separated-values", "application/json", "text/plain"], copyToCacheDirectory: true }); if (result.canceled) return setNotice("Dataset selection was cancelled; no bytes or metadata were recorded."); const asset = result.assets[0]; if (asset.size && asset.size > MAX_BYTES) return setNotice("Dataset exceeds the 5 MiB evidence limit; no bytes were read."); const base64 = Platform.OS === "web" ? webBase64(new Uint8Array(await (await fetch(asset.uri)).arrayBuffer())) : await FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.Base64 }); uploadDataset.mutate({ ...access, fileName: asset.name, mimeType: asset.mimeType ?? "text/plain", base64, simulationId, metadata: { source: "USER_ATTACHED", instrument, calibrationStatus: "UNKNOWN", provenance: "MEASURED" } }, { onSuccess: (item) => { setNotice(`Stored immutable RAW dataset ${item.datasetId} · SHA-256 ${item.fileHash.slice(0, 16)}… · quality ${item.quality.status}. Parsing did not establish scientific validity.`); void datasets.refetch(); }, onError: (error) => setNotice(error.message) }); } catch (error) { setNotice(error instanceof Error ? error.message : "Dataset selection failed."); } };
  const dataset = datasets.data?.[0]; const calibrate = () => { if (!project || !dataset) return; recordCalibration.mutate({ ...access, datasetId: dataset.datasetId, instrument, status: "UNCALIBRATED", evidenceIds: [], truthCategory: "UNKNOWN" }, { onSuccess: (item) => { setNotice(`Calibration record ${item.calibrationId} is ${item.status}; no calibration claim was made.`); void calibrations.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const compare = () => { if (!project || !dataset) return; createComparison.mutate({ ...access, simulationId, datasetId: dataset.datasetId, quantity, ...(measurementValue.trim() ? { measurementValue: Number(measurementValue) } : {}), comparisonMethod: "Declared future solver-versus-measurement comparison; no solver value available." }, { onSuccess: (item) => { setNotice(`Created ${item.status} comparison. Difference and relative difference remain absent because no solver result exists.`); void comparisons.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const inspectGraph = () => { if (!project) return; extendedGraph.mutate({ ...access, simulationId }, { onSuccess: setGraph, onError: (error) => setNotice(error.message) }); };
  return <View style={styles.wrap}>
    <View style={styles.card}><Text style={styles.kicker}>MATERIAL EVIDENCE REVIEW</Text><Text style={styles.copy}>Conflicts remain visible and no AI action can approve or choose a value. Reconciliation converts compatible units only for comparison; it never alters source evidence.</Text><TextInput value={material} onChangeText={setMaterial} style={styles.input} placeholder="Material" placeholderTextColor="#71828B" /><Pressable style={styles.secondary} disabled={!project || reconcile.isPending} onPress={runReconciliation}><Text style={styles.secondaryText}>{reconcile.isPending ? "CHECKING…" : "REVIEW YIELD-STRENGTH EVIDENCE"}</Text></Pressable>{reconciliation ? <View style={styles.conflict}><View style={styles.row}><Text style={styles.recordTitle}>{reconciliation.material} · {reconciliation.property}</Text><Badge value={reconciliation.state} /></View>{reconciliation.candidates.map((item) => <Text key={item.evidenceId} style={styles.meta}>Source {item.source} · {item.value ?? "UNKNOWN"} {item.unit ?? ""} · hash {item.sourceHash.slice(0, 12)}…</Text>)}{reconciliation.conflicts.map((item) => <Text key={item.kind} style={styles.warning}>⚠ {item.kind}: {item.statement}</Text>)}<TextInput value={reviewer} onChangeText={setReviewer} style={styles.input} placeholder="Human reviewer name" placeholderTextColor="#71828B" /><TextInput value={decisionReason} onChangeText={setDecisionReason} style={styles.input} placeholder="Reason for requesting further evidence" placeholderTextColor="#71828B" /><Pressable style={styles.secondary} disabled={decide.isPending} onPress={resolve}><Text style={styles.secondaryText}>RECORD HUMAN REVIEW GATE</Text></Pressable></View> : null}</View>
    <View style={styles.card}><Text style={styles.kicker}>MEASURED DATA & CALIBRATION</Text><Text style={styles.copy}>CSV, TSV, and JSON raw files are hash-tracked and immutable. Structural checks report quality without declaring scientific validity, calibration, or accuracy.</Text><TextInput value={instrument} onChangeText={setInstrument} style={styles.input} placeholder="Instrument / instrument ID" placeholderTextColor="#71828B" /><Pressable style={styles.primary} disabled={!project || uploadDataset.isPending} onPress={pickDataset}>{uploadDataset.isPending ? <ActivityIndicator color="#F3F1EA" /> : <Text style={styles.primaryText}>ATTACH RAW MEASURED DATA</Text>}</Pressable>{datasets.data?.map((item) => <View key={item.datasetId} style={styles.record}><View style={{ flex: 1 }}><Text style={styles.recordTitle}>{item.fileName}</Text><Text style={styles.meta}>SHA-256 {item.fileHash.slice(0, 16)}… · RAW · {item.quality.rowCount ?? "UNKNOWN"} rows</Text></View><Badge value={item.quality.status} /></View>)}<Pressable style={styles.secondary} disabled={!dataset || recordCalibration.isPending} onPress={calibrate}><Text style={styles.secondaryText}>RECORD UNCALIBRATED INSTRUMENT</Text></Pressable>{calibrations.data?.slice(0, 2).map((item) => <Text key={item.calibrationId} style={styles.meta}>{item.instrument} · {item.status} · evidence {item.evidenceIds.length}</Text>)}</View>
    <View style={styles.card}><Text style={styles.kicker}>COMPARISON, GRAPH & ADAPTER ONBOARDING</Text><TextInput value={quantity} onChangeText={setQuantity} style={styles.input} placeholder="Quantity" placeholderTextColor="#71828B" /><TextInput value={measurementValue} onChangeText={setMeasurementValue} style={styles.input} keyboardType="decimal-pad" placeholder="Measured value (optional)" placeholderTextColor="#71828B" /><Pressable style={styles.secondary} disabled={!dataset || createComparison.isPending} onPress={compare}><Text style={styles.secondaryText}>CREATE NO-RESULT COMPARISON</Text></Pressable>{comparisons.data?.slice(0, 2).map((item) => <View key={item.comparisonId} style={styles.record}><Text style={styles.recordTitle}>{item.quantity} · simulation value: UNKNOWN</Text><Badge value={item.status} /></View>)}<Pressable style={styles.secondary} disabled={!project || extendedGraph.isPending} onPress={inspectGraph}><Text style={styles.secondaryText}>INSPECT EXTENDED EVIDENCE GRAPH</Text></Pressable>{graph ? <Text style={styles.meta}>Graph: {graph.nodes.length} nodes · {graph.edges.length} explicit links · {graph.limitations.at(-1)}</Text> : null}<Text style={styles.copy}>External solver onboarding accepts only declared manifests, hashes, publisher identity, signatures, capabilities, and security requirements. Registration is non-executable until independent verification exists.</Text>{adapters.data?.slice(0, 2).map((item) => <View key={item.registrationId} style={styles.record}><Text style={styles.recordTitle}>{item.solverName} · executable: false</Text><Badge value={item.verificationStatus} /></View>)}</View>
    <Text style={styles.notice}>{notice}</Text>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, kicker: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, input: { color: "#F3F1EA", backgroundColor: "#111C22", borderColor: "#34434B", borderWidth: 1, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 7, fontSize: 9 }, primary: { backgroundColor: "#1167B1", minHeight: 40, justifyContent: "center", alignItems: "center", borderRadius: 9 }, primaryText: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, secondary: { borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 6, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, record: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, borderTopWidth: 1, borderTopColor: "#2B3A41", paddingTop: 7 }, recordTitle: { color: "#F3F1EA", fontSize: 9, fontWeight: "800", flex: 1 }, meta: { color: "#90A0A8", fontSize: 8, lineHeight: 13 }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3, alignSelf: "flex-start" }, badgeText: { fontSize: 7, fontWeight: "900" }, conflict: { backgroundColor: "#33251D", borderColor: "#9A6843", borderWidth: 1, borderRadius: 8, padding: 8, gap: 6 }, warning: { color: "#F0AB79", fontSize: 8, lineHeight: 13 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 }, notice: { color: "#8EC4E8", fontSize: 8, lineHeight: 13, textAlign: "center" } });
