import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { CADViewer } from "@/components/cad-viewer";
import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";
import type { CADAgentResult } from "@/shared/cadAgent";
import type { GeometrySelectionContext } from "@/shared/cadWorkbench";
import type { CAESimulationPlan } from "@/shared/cae";
import { CAEEvidencePanel } from "@/components/cae-evidence-panel";
import { CAEReconciliationPanel } from "@/components/cae-reconciliation-panel";
import { SolverTrustPanel } from "@/components/solver-trust-panel";
import { TrustReadinessPanel } from "@/components/trust-readiness-panel";
import { RuntimeArchitectureReviewPanel } from "@/components/runtime-architecture-review-panel";
import { RuntimeReadinessPanel } from "@/components/runtime-readiness-panel";

function color(status?: string) { if (["COMPLETED", "READY_FOR_SOLVER", "PASS", "INPUT_VERIFIED"].includes(status ?? "")) return "#62B39A"; if (["NOT_READY", "FAILED", "FAIL", "SOLVER_UNAVAILABLE"].includes(status ?? "")) return "#E78966"; return "#8EC4E8"; }
function Badge({ label }: { label: string }) { const tint = color(label); return <View style={[styles.badge, { borderColor: tint, backgroundColor: `${tint}18` }]}><Text style={[styles.badgeText, { color: tint }]}>{label}</Text></View>; }
function short(items: string[], fallback: string) { return items.length ? items.slice(0, 3).join(" · ") : fallback; }

export function CAEWorkspace({ sourceCadRevision, model, selectedGeometry, featureIds, geometryValidated }: { sourceCadRevision?: string; model?: CADAgentResult; selectedGeometry: GeometrySelectionContext; featureIds: string[]; geometryValidated: boolean }) {
  const [project, setProject] = useState<StoredProjectAccess>();
  const [question, setQuestion] = useState("Determine whether this concept should be investigated for crash loading.");
  const [selectedId, setSelectedId] = useState<string>();
  const [reviewed, setReviewed] = useState<CAESimulationPlan>();
  const [notice, setNotice] = useState("CAE planning is available; numerical solver execution is intentionally unavailable.");
  useEffect(() => { let cancelled = false; const hydrate = async () => { const stored = await loadProjectAccess("active-engineering-workbench"); if (!cancelled && stored) setProject(stored); }; void hydrate(); const timer = setInterval(() => void hydrate(), 1_000); return () => { cancelled = true; clearInterval(timer); }; }, []);
  const plans = trpc.cae.listPlans.useQuery({ projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }, { enabled: Boolean(project) });
  const create = trpc.cae.createPlan.useMutation(); const review = trpc.cae.reviewPlan.useMutation(); const execute = trpc.cae.requestExecution.useMutation();
  const selected = useMemo(() => reviewed ?? plans.data?.find((item) => item.simulationId === selectedId) ?? plans.data?.[0], [plans.data, reviewed, selectedId]);
  const sourceReady = Boolean(project && sourceCadRevision && geometryValidated);
  const createPlan = () => { if (!project || !sourceCadRevision) return; setReviewed(undefined); create.mutate({ projectId: project.projectId, accessKey: project.accessKey, input: { projectId: project.projectId, sourceCadRevision, sourceCadBranch: "CAD_WORKSPACE", engineeringQuestion: question, selectedGeometry, featureHistory: featureIds, geometryProvenance: "OPENCASCADE_KERNEL", geometryValidation: geometryValidated ? "VALID" : "UNKNOWN", material: { status: "UNKNOWN", properties: [] }, boundaryConditions: [], loads: [], contacts: [], meshStrategy: { refinementRegions: [], qualityRequirements: ["No mesh quality target has been verified."], status: "MESH_KNOWLEDGE_GAP" } } }, { onSuccess: (plan) => { setSelectedId(plan.simulationId); setReviewed(plan); setNotice(`Created ${plan.simulationId}. ${plan.unknowns.filter((item) => item.blocking).length} blocking knowledge gap(s) remain; no solver was run.`); void plans.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const runReview = () => { if (!project || !selected) return; review.mutate({ projectId: project.projectId, accessKey: project.accessKey, simulationId: selected.simulationId }, { onSuccess: (plan) => { setReviewed(plan); setNotice("Adversarial CAE review and self-critique completed. No numerical result was generated."); }, onError: (error) => setNotice(error.message) }); };
  const requestSolver = () => { if (!project || !selected) return; execute.mutate({ projectId: project.projectId, accessKey: project.accessKey, simulationId: selected.simulationId }, { onSuccess: (result) => setNotice(result.result.reason), onError: (error) => setNotice(error.message) }); };
  const blocking = selected?.unknowns.filter((item) => item.blocking) ?? [];
  return <View style={styles.wrap}>
    <View style={styles.hero}><View style={{ flex: 1 }}><Text style={styles.kicker}>PHASE 5.0 · CAE AGENT FOUNDATION</Text><Text style={styles.title}>Simulation planning, not simulation results</Text><Text style={styles.copy}>The CAE Agent links a declared CAD revision to physics, inputs, evidence, and validation gates. It cannot modify CAD or generate stress, displacement, temperature, safety-factor, fatigue, or modal results.</Text></View><Badge label="NO SOLVER" /></View>
    <View style={styles.grid}><View style={styles.card}><Text style={styles.cardKicker}>CAD HANDOFF · READ ONLY</Text><Text style={styles.value}>{sourceCadRevision ?? "NO VALIDATED CAD REVISION"}</Text><Text style={styles.meta}>{geometryValidated ? "OpenCascade-kernel geometry validation declared by the active CAD workspace." : "CAE planning is blocked until a validated CAD revision is active."}</Text><Text style={styles.meta}>Selected geometry: {selectedGeometry.label} · Feature context: {featureIds.length ? featureIds.join(", ") : "none declared"}</Text></View><View style={styles.card}><Text style={styles.cardKicker}>SOLVER STATE</Text><Text style={styles.value}>UNAVAILABLE</Text><Text style={styles.meta}>No mesher, solver, results reader, convergence evidence, or executable adapter is installed in Phase 5.0.</Text></View></View>
    {model?.viewerMesh ? <View style={styles.viewer}><Text style={styles.cardKicker}>REUSED CAD VIEWPORT · CONTEXT ONLY</Text><CADViewer mesh={model.viewerMesh} /></View> : null}
    <View style={styles.card}><Text style={styles.cardKicker}>ENGINEERING QUESTION</Text><TextInput value={question} onChangeText={setQuestion} multiline style={styles.input} placeholder="Create a static structural simulation plan…" placeholderTextColor="#71828B" /><Pressable disabled={!sourceReady || create.isPending} style={({ pressed }) => [styles.primary, (!sourceReady || create.isPending) && styles.disabled, pressed && styles.pressed]} onPress={createPlan}>{create.isPending ? <ActivityIndicator color="#F3F1EA" /> : <Text style={styles.primaryText}>CREATE AUDITABLE CAE PLAN</Text>}</Pressable><Text style={styles.meta}>{sourceReady ? "The plan records missing material, loads, constraints, mesh, solver, and validation evidence instead of inferring it." : "Generate or select a geometrically validated CAD revision before creating a CAE plan."}</Text></View>
    <View style={styles.card}><View style={styles.row}><View><Text style={styles.cardKicker}>SIMULATION PLAN NAVIGATOR</Text><Text style={styles.meta}>{plans.data?.length ?? 0} project-isolated plan(s)</Text></View>{selected ? <Badge label={selected.status} /> : <Badge label="NOT_READY" />}</View>{plans.data?.length ? <View style={styles.planList}>{plans.data.slice(0, 5).map((plan) => <Pressable key={plan.simulationId} style={[styles.planRow, plan.simulationId === selected?.simulationId && styles.planActive]} onPress={() => { setReviewed(undefined); setSelectedId(plan.simulationId); }}><View style={{ flex: 1 }}><Text style={styles.planTitle}>{plan.analysisType} · {plan.simulationId}</Text><Text style={styles.meta}>{plan.engineeringQuestion}</Text></View><Badge label={plan.status} /></Pressable>)}</View> : <Text style={styles.meta}>No plan exists yet. A plan remains a structured engineering artifact, not evidence of physical performance.</Text>}</View>
    {selected ? <>
      <View style={styles.card}><View style={styles.row}><View><Text style={styles.cardKicker}>PLAN INSPECTOR</Text><Text style={styles.value}>{selected.analysisType}</Text></View><Badge label={selected.truthStatus} /></View><Text style={styles.copy}>Physics scope: {short(selected.physicsModel, "No physics model defined.")}</Text><Text style={styles.meta}>Geometry scope: {selected.geometryScope.sourceCadRevision} · {selected.geometryScope.geometryProvenance} · selection {selected.geometryScope.selectionStatus}</Text><Text style={styles.meta}>Contacts: {selected.contacts.length} · Boundary conditions: {selected.boundaryConditions.length} · Loads: {selected.loads.length} · Material properties: {selected.materialDefinition.properties.length}</Text></View>
      <View style={styles.grid}><View style={styles.card}><Text style={styles.cardKicker}>ASSUMPTIONS</Text><Text style={styles.copy}>{short(selected.assumptions.map((item) => `${item.category}: ${item.statement}`), "No assumptions recorded.")}</Text></View><View style={styles.card}><Text style={styles.cardKicker}>MESH & VALIDATION</Text><Text style={styles.copy}>{selected.meshStrategy.status} · {selected.meshStrategy.convergenceRequirement ?? "No convergence requirement."}</Text><Text style={styles.meta}>{short(selected.validationRequirements, "No validation requirement.")}</Text></View></View>
      <View style={styles.card}><View style={styles.row}><View><Text style={styles.cardKicker}>KNOWLEDGE GAPS & EVIDENCE</Text><Text style={styles.meta}>{blocking.length} blocking gap(s) · {selected.evidenceRequirements.length} evidence requirement(s)</Text></View><Badge label={selected.result.status} /></View><Text style={styles.copy}>{short(blocking.map((item) => item.kind === "MATERIAL_KNOWLEDGE_GAP" ? `${item.missingProperty}: ${item.whyRequired}` : item.missingInformation), "No blocking gap is currently declared.")}</Text><Text style={styles.meta}>Result state: {selected.result.reason}</Text></View>
      <View style={styles.card}><View style={styles.row}><View><Text style={styles.cardKicker}>ADVERSARIAL REVIEW & SELF-CRITIQUE</Text><Text style={styles.meta}>{selected.adversarialReview.length ? `${selected.adversarialReview.length} deterministic reviewer findings` : "Not run"}</Text></View><Pressable style={styles.secondary} disabled={review.isPending} onPress={runReview}><Text style={styles.secondaryText}>{review.isPending ? "REVIEWING…" : "CHALLENGE THIS SETUP"}</Text></Pressable></View>{selected.adversarialReview.length ? <Text style={styles.copy}>{short(selected.adversarialReview.map((item) => `${item.reviewer} ${item.status}: ${item.finding}`), "No review evidence.")}</Text> : null}{selected.selfCritique.correctedSummary ? <Text style={styles.meta}>{selected.selfCritique.correctedSummary}</Text> : null}</View>
      <View style={styles.noSolver}><Text style={styles.cardKicker}>EXECUTION SAFETY GATE</Text><Text style={styles.copy}>Execution is disabled. This action records a refusal because required inputs and an executable numerical solver do not exist.</Text><Pressable style={styles.secondary} disabled={execute.isPending} onPress={requestSolver}><Text style={styles.secondaryText}>{execute.isPending ? "CHECKING…" : "REQUEST SOLVER EXECUTION"}</Text></Pressable></View>
      <CAEEvidencePanel simulationId={selected.simulationId} observedCadRevision={sourceCadRevision} />
      <CAEReconciliationPanel simulationId={selected.simulationId} />
      <SolverTrustPanel simulationId={selected.simulationId} />
      <TrustReadinessPanel simulationId={selected.simulationId} />
      <RuntimeArchitectureReviewPanel />
      <RuntimeReadinessPanel />
    </> : null}
    <Text style={styles.notice}>{notice}</Text>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 10 }, hero: { backgroundColor: "#1A2933", borderWidth: 1, borderColor: "#2F4652", padding: 14, borderRadius: 14, flexDirection: "row", gap: 8 }, kicker: { color: "#8EC4E8", fontSize: 9, letterSpacing: 1, fontWeight: "800" }, title: { color: "#F3F1EA", fontSize: 16, fontWeight: "800", marginTop: 4 }, copy: { color: "#D7E0E3", fontSize: 11, lineHeight: 16, marginTop: 7 }, meta: { color: "#90A0A8", fontSize: 9, lineHeight: 14, marginTop: 5 }, grid: { gap: 8 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 12, gap: 5 }, cardKicker: { color: "#9DAEB6", fontSize: 8, letterSpacing: 0.9, fontWeight: "800" }, value: { color: "#F3F1EA", fontSize: 12, fontWeight: "800", marginTop: 3 }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 7, paddingVertical: 4, alignSelf: "flex-start" }, badgeText: { fontSize: 8, fontWeight: "900" }, input: { minHeight: 70, color: "#F3F1EA", backgroundColor: "#111C22", borderColor: "#34434B", borderWidth: 1, borderRadius: 9, padding: 9, textAlignVertical: "top", fontSize: 11, lineHeight: 16 }, primary: { backgroundColor: "#1167B1", minHeight: 43, borderRadius: 10, justifyContent: "center", alignItems: "center", marginTop: 4 }, primaryText: { color: "#F3F1EA", fontSize: 10, fontWeight: "900" }, secondary: { borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 7, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, disabled: { opacity: 0.45 }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, planList: { gap: 5, marginTop: 5 }, planRow: { flexDirection: "row", alignItems: "center", gap: 8, padding: 8, borderRadius: 9, backgroundColor: "#152129" }, planActive: { backgroundColor: "#203846", borderWidth: 1, borderColor: "#5B9DCA" }, planTitle: { color: "#F3F1EA", fontSize: 10, fontWeight: "800" }, noSolver: { backgroundColor: "#33251D", borderColor: "#9A6843", borderWidth: 1, borderRadius: 12, padding: 12, gap: 4 }, notice: { color: "#8EC4E8", fontSize: 9, lineHeight: 14, textAlign: "center", paddingHorizontal: 6 }, viewer: { backgroundColor: "#111C22", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, overflow: "hidden", paddingTop: 9 } });
