import { useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

function tint(value?: string) { if (["VALIDATED", "FRESH", "VERIFIED", "PASS"].includes(value ?? "")) return "#62B39A"; if (["REJECTED", "STALE", "FAIL", "CONFLICT"].includes(value ?? "")) return "#E78966"; return "#8EC4E8"; }
function Badge({ value }: { value: string }) { const color = tint(value); return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.badgeText, { color }]}>{value}</Text></View>; }
function Field({ label, value }: { label: string; value?: string }) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><Text style={styles.fieldValue} numberOfLines={2}>{value ?? "UNKNOWN"}</Text></View>; }

export function CAEPlanIntegrationPanel() {
  const [project, setProject] = useState<StoredProjectAccess>(); const [diffNote, setDiffNote] = useState<string>(); const [graphNote, setGraphNote] = useState<string>();
  useEffect(() => { let cancelled = false; const hydrate = async () => { const stored = await loadProjectAccess("active-engineering-workbench"); if (!cancelled && stored) setProject(stored); }; void hydrate(); const timer = setInterval(() => void hydrate(), 1_000); return () => { cancelled = true; clearInterval(timer); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }; const snapshots = trpc.cae.listCAEPlanSnapshots.useQuery(access, { enabled: Boolean(project) }); const jobs = trpc.cae.listCAEJobContracts.useQuery(access, { enabled: Boolean(project) }); const qualities = trpc.cae.listMeshQualityEvidence.useQuery(access, { enabled: Boolean(project) }); const diff = trpc.cae.createCAEJobDiff.useMutation(); const graph = trpc.cae.caePlanIntegrationGraph.useMutation();
  const latestJob = jobs.data?.[0]; const priorJob = jobs.data?.[1]; const latestSnapshot = snapshots.data?.[0]; const latestQuality = qualities.data?.[0]; const qualityMetrics = useMemo(() => latestQuality?.qualityMetrics ?? [], [latestQuality]);
  const compare = () => { if (!project || !latestJob || !priorJob) return; diff.mutate({ ...access, baselineJobId: priorJob.jobId, comparedJobId: latestJob.jobId }, { onSuccess: (value) => setDiffNote(value.entries.map((item) => `${item.field}: ${item.status}`).join(" · ")) }); };
  const inspectGraph = () => { if (!project || !latestJob) return; graph.mutate({ ...access, jobId: latestJob.jobId }, { onSuccess: (value) => setGraphNote(`${value.nodes.length} traceability nodes · ${value.edges.length} declared links · ${value.limitations[0]}`) }); };
  return <View style={styles.wrap}>
    <View style={styles.hero}><View style={{ flex: 1 }}><Text style={styles.kicker}>PHASE 6.6 · PLAN INTEGRATION & MESH QUALITY EVIDENCE</Text><Text style={styles.title}>Immutable traceability, not meshing</Text><Text style={styles.copy}>Validated plan snapshots may deterministically become non-executable job contracts. Mesh quality remains evidence-only: no Gmsh, solver, real mesh, numerical result, process, network, plugin, or filesystem execution is available.</Text></View><Badge value="EXECUTION DISABLED" /></View>
    <View style={styles.card}><View style={styles.row}><View><Text style={styles.kicker}>CAE PLAN SNAPSHOT</Text><Text style={styles.value}>{latestSnapshot?.snapshotId ?? "NO SNAPSHOT"}</Text></View><Badge value={latestSnapshot?.validationStatus ?? "UNKNOWN"} /></View>{latestSnapshot ? <><Field label="SOURCE PLAN" value={`${latestSnapshot.simulationId} · ${latestSnapshot.planHash}`} /><Field label="CAD & REQUIREMENTS" value={`${latestSnapshot.sourceCadRevision} · ${latestSnapshot.sourceCadGeometryHash} · ${latestSnapshot.requirementRevision}`} /><Text style={styles.meta}>Immutable snapshot preserves analysis intent, material evidence, loads, boundaries, contacts, mesh strategy, expected outputs, requirements, CAD revision, and CAD hash. Findings: {latestSnapshot.validationFindings.join(" · ") || "none"}</Text></> : <Text style={styles.meta}>No validated plan snapshot exists. This panel will not infer missing CAD, material, loads, boundaries, contacts, mesh strategy, or requirement traceability.</Text>}</View>
    <View style={styles.grid}><View style={styles.card}><Text style={styles.kicker}>JOB CONTRACT INTEGRATION</Text><Text style={styles.value}>{latestJob?.jobId ?? "NO JOB"}</Text><Text style={styles.meta}>{latestJob ? `Revision ${latestJob.revision} · ${latestJob.lifecycleState} · ${latestJob.readinessState}` : "A canonical job is created only from an immutable validated snapshot through bounded APIs."}</Text><Text style={styles.meta}>Every changed source requires a new revision; historic job contracts are never mutated.</Text></View><View style={styles.card}><Text style={styles.kicker}>TRACEABILITY STATE</Text><Text style={styles.copy}>Requirement → CAD revision → Plan Snapshot → Canonical Job → Mesh Artifact → Solver Artifact → Future Result → Verification → Evidence</Text><Pressable disabled={!latestJob || graph.isPending} style={[styles.secondary, !latestJob && styles.disabled]} onPress={inspectGraph}><Text style={styles.secondaryText}>{graph.isPending ? "INSPECTING…" : "INSPECT INTEGRATION GRAPH"}</Text></Pressable>{graphNote ? <Text style={styles.meta}>{graphNote}</Text> : null}</View></View>
    <View style={styles.card}><View style={styles.row}><View><Text style={styles.kicker}>READ-ONLY JOB DIFF</Text><Text style={styles.meta}>CAD revision/hash · requirements · material evidence · loads · boundaries · contacts · mesh · solver · verification</Text></View><Badge value={priorJob && latestJob ? "AVAILABLE" : "UNKNOWN"} /></View><Pressable disabled={!priorJob || !latestJob || diff.isPending} style={[styles.secondary, (!priorJob || !latestJob) && styles.disabled]} onPress={compare}><Text style={styles.secondaryText}>{diff.isPending ? "COMPARING…" : "COMPARE LATEST TWO REVISIONS"}</Text></Pressable><Text style={styles.meta}>{diffNote ?? (priorJob && latestJob ? "No comparison has been requested yet. The comparison is immutable and does not edit either revision." : "At least two immutable job revisions are required; UNKNOWN is not a change claim.")}</Text></View>
    <View style={styles.card}><View style={styles.row}><View><Text style={styles.kicker}>MESH QUALITY EVIDENCE</Text><Text style={styles.value}>{latestQuality?.evidenceId ?? "NOT AVAILABLE"}</Text></View><Badge value={latestQuality?.qualityStatus ?? "NOT_AVAILABLE"} /></View>{latestQuality ? <><Field label="MESH / GENERATOR" value={`${latestQuality.meshId} · ${latestQuality.meshGenerator} ${latestQuality.meshGeneratorVersion}`} /><Field label="PROVENANCE" value={`${latestQuality.provenance.qualityAlgorithm} ${latestQuality.provenance.qualityAlgorithmVersion} · threshold ${latestQuality.provenance.thresholdVersion}`} /><Text style={styles.copy}>Metrics: {qualityMetrics.map((item) => `${item.metric}: ${item.value ?? item.status} ${item.unit ?? ""}`).join(" · ")}</Text><Text style={styles.meta}>Thresholds: {latestQuality.qualityThresholds.map((item) => `${item.metric} ${item.value} ${item.unit} · ${item.version}`).join(" · ")}</Text><Text style={styles.meta}>Evidence is unverified unless an independent verifier records it. Reported PASS is fail-closed to UNKNOWN in this phase; UNKNOWN never becomes PASS automatically.</Text></> : <Text style={styles.meta}>No mesh-quality evidence exists. Element/node counts, quality metrics, thresholds, and pass/fail statements are not fabricated.</Text>}</View>
    <View style={styles.card}><Text style={styles.kicker}>STALE & CONFLICT POLICY</Text><Text style={styles.copy}>CAD change, job revision, mesh artifact change, quality-algorithm change, or threshold-version change makes quality evidence STALE. Different values for the same metric or threshold version create CONFLICT. Neither state can be silently reused or passed.</Text><Text style={styles.meta}>Visible states: VERIFIED · UNVERIFIED · UNKNOWN · STALE · CONFLICT. Execution eligibility remains false for every state.</Text></View>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 10 }, hero: { backgroundColor: "#1A2933", borderWidth: 1, borderColor: "#2F4652", padding: 14, borderRadius: 14, flexDirection: "row", gap: 8 }, kicker: { color: "#8EC4E8", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, title: { color: "#F3F1EA", fontSize: 15, fontWeight: "900", marginTop: 4 }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15, marginTop: 6 }, meta: { color: "#90A0A8", fontSize: 9, lineHeight: 14, marginTop: 5 }, value: { color: "#F3F1EA", fontSize: 11, fontWeight: "900", marginTop: 3 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 12, gap: 5 }, grid: { gap: 8 }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 7, paddingVertical: 4, alignSelf: "flex-start" }, badgeText: { fontSize: 8, fontWeight: "900" }, field: { gap: 2, marginTop: 4 }, fieldLabel: { color: "#9DAEB6", fontSize: 8, letterSpacing: 0.7, fontWeight: "900" }, fieldValue: { color: "#D7E0E3", fontSize: 9, lineHeight: 13 }, secondary: { marginTop: 7, borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 7, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, disabled: { opacity: 0.42 } });
