import { useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";
import type { CanonicalCAEJobContract } from "@/shared/cae";

function tone(value?: string) { if (["FRESH", "VALIDATED", "PASS"].includes(value ?? "")) return "#62B39A"; if (["STALE", "REJECTED", "FAIL", "DISABLED"].includes(value ?? "")) return "#E78966"; return "#8EC4E8"; }
function Badge({ value }: { value: string }) { const color = tone(value); return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.badgeText, { color }]}>{value}</Text></View>; }
function Field({ label, value }: { label: string; value?: string }) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><Text style={styles.fieldValue} numberOfLines={2}>{value ?? "NOT DECLARED"}</Text></View>; }

export function CAEJobContractInspector() {
  const [project, setProject] = useState<StoredProjectAccess>(); const [selectedId, setSelectedId] = useState<string>(); const [graphSummary, setGraphSummary] = useState<string>();
  useEffect(() => { let cancelled = false; const hydrate = async () => { const stored = await loadProjectAccess("active-engineering-workbench"); if (!cancelled && stored) setProject(stored); }; void hydrate(); const timer = setInterval(() => void hydrate(), 1_000); return () => { cancelled = true; clearInterval(timer); }; }, []);
  const contracts = trpc.cae.listCAEJobContracts.useQuery({ projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }, { enabled: Boolean(project) });
  const selected = useMemo<CanonicalCAEJobContract | undefined>(() => contracts.data?.find((item) => item.jobId === selectedId) ?? contracts.data?.[0], [contracts.data, selectedId]);
  const staleness = trpc.cae.listCAEJobStaleness.useQuery({ projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE", jobId: selected?.jobId }, { enabled: Boolean(project && selected) });
  const failures = trpc.cae.caeJobFailureModel.useQuery(); const graph = trpc.cae.caeJobContractGraph.useMutation();
  const inspectGraph = () => { if (!project || !selected) return; graph.mutate({ projectId: project.projectId, accessKey: project.accessKey, jobId: selected.jobId }, { onSuccess: (value) => setGraphSummary(`${value.nodes.length} traceability nodes · ${value.edges.length} declared links · ${value.limitations[0]}`) }); };
  const currentStaleness = staleness.data?.[0];
  return <View style={styles.wrap}>
    <View style={styles.hero}><View style={{ flex: 1 }}><Text style={styles.kicker}>PHASE 6.5 · CANONICAL CAE JOB CONTRACT</Text><Text style={styles.title}>Immutable data contract, not a runtime job</Text><Text style={styles.copy}>This inspector is read-only. It never starts meshing, a solver, a sandbox, a process, a plugin, shell access, network access, or numerical result generation.</Text></View><Badge value="EXECUTION DISABLED" /></View>
    <View style={styles.card}><Text style={styles.kicker}>JOB REVISION NAVIGATOR</Text><Text style={styles.meta}>{contracts.data?.length ?? 0} project-isolated immutable contract revision(s)</Text>{contracts.data?.length ? <View style={styles.list}>{contracts.data.slice(0, 6).map((item) => <Pressable key={item.jobId} onPress={() => { setSelectedId(item.jobId); setGraphSummary(undefined); }} style={[styles.item, item.jobId === selected?.jobId && styles.itemActive]}><View style={{ flex: 1 }}><Text style={styles.itemTitle}>Revision {item.revision} · {item.jobId}</Text><Text style={styles.meta}>{item.analysisType} · {item.solverReference}</Text></View><Badge value={item.lifecycleState} /></Pressable>)}</View> : <Text style={styles.meta}>No job contract is registered. Contracts are created only through bounded, validated project APIs; this inspector will not invent one.</Text>}</View>
    {selected ? <><View style={styles.card}><View style={styles.row}><View><Text style={styles.kicker}>IMMUTABLE JOB IDENTITY</Text><Text style={styles.value}>{selected.jobId}</Text></View><Badge value={selected.readinessState} /></View><Field label="CONTRACT HASH" value={selected.contractHash} /><View style={styles.grid}><Field label="CAD REVISION" value={selected.cadRevision} /><Field label="REQUIREMENTS REVISION" value={selected.requirementRevision} /><Field label="ANALYSIS" value={`${selected.analysisType} · ${selected.analysisVersion}`} /><Field label="SOLVER REFERENCE" value={`${selected.solverReference} · ${selected.solverVersion}`} /></View><Text style={styles.meta}>Revision {selected.revision}{selected.revisionOf ? ` supersedes ${selected.revisionOf}` : " is the initial immutable revision"}. Any changed CAD, material, loads, boundaries, mesh strategy, solver, or resource policy must create a new revision.</Text></View>
      <View style={styles.grid}><View style={styles.card}><Text style={styles.kicker}>MATERIAL & PROVENANCE</Text><Field label="MATERIAL" value={selected.materialReference} /><Field label="MATERIAL EVIDENCE HASH" value={selected.materialEvidenceHash} /><Field label="CREATED BY" value={selected.createdBy} /><Text style={styles.meta}>{selected.provenance.requirementIds.length} requirement reference(s) · {selected.provenance.sourcePlanId ?? "no source plan declared"}</Text></View><View style={styles.card}><Text style={styles.kicker}>MESH STRATEGY · NON-EXECUTED</Text><Field label="STRATEGY" value={`${selected.meshStrategy.strategyReference} · ${selected.meshStrategy.elementIntent}`} /><Field label="STRATEGY HASH" value={selected.meshStrategy.strategyHash} /><Text style={styles.meta}>Quality requirements: {selected.meshStrategy.qualityRequirements.join(" · ")}</Text><Badge value={selected.meshStrategy.status} /></View></View>
      <View style={styles.card}><Text style={styles.kicker}>DECLARED PHYSICS INPUTS</Text><Text style={styles.copy}>Boundary conditions: {selected.boundaryConditions.map((item) => `${item.type} @ ${item.geometryReference}`).join(" · ")}</Text><Text style={styles.copy}>Loads: {selected.loads.map((item) => `${item.type} ${item.magnitude} ${item.unit} @ ${item.geometryReference}`).join(" · ")}</Text><Text style={styles.meta}>Contacts: {selected.contacts.length ? selected.contacts.map((item) => item.type).join(" · ") : "none declared"} · expected outputs: {selected.expectedOutputs.join(" · ")}</Text></View>
      <View style={styles.card}><View style={styles.row}><View><Text style={styles.kicker}>STALE CONTEXT CHECK</Text><Text style={styles.value}>{currentStaleness?.status ?? "UNKNOWN"}</Text></View><Badge value={currentStaleness?.status ?? "UNKNOWN"} /></View><Text style={styles.meta}>{currentStaleness ? currentStaleness.checks.map((item) => `${item.dimension}: ${item.status}`).join(" · ") : "No observation has been recorded. Unknown is never considered fresh, and no stale job can be executed."}</Text></View>
      <View style={styles.card}><Text style={styles.kicker}>FUTURE VERIFICATION CONTRACT</Text><Text style={styles.copy}>{selected.verificationRequirements.join(" · ")}</Text><Text style={styles.meta}>All checks are NOT_VERIFIED until a future result verifier independently validates hashes, identity, units, inputs, convergence, warnings, result integrity, and reproducibility. This phase creates no result values.</Text></View>
      <View style={styles.card}><Text style={styles.kicker}>FAILURE MODEL & SECURITY BOUNDARY</Text><Text style={styles.copy}>{failures.data?.states.join(" → ") ?? "Loading failure states…"}</Text><Text style={styles.meta}>READY_FOR_EXECUTION is explicitly {failures.data?.readyForExecutionBehavior ?? "DISABLED"}. Prohibited: {failures.data?.prohibited.join(" · ") ?? "arbitrary instructions"}.</Text></View>
      <View style={styles.card}><Text style={styles.kicker}>TRACEABILITY</Text><Text style={styles.meta}>Requirement → CAD revision → CAE Job → Mesh → Solver → Result → Verification → Evidence. Result schemas are rejected unless they reference an authorized job; no orphan result is accepted.</Text><Pressable style={styles.secondary} disabled={graph.isPending} onPress={inspectGraph}><Text style={styles.secondaryText}>{graph.isPending ? "INSPECTING…" : "INSPECT DECLARED TRACEABILITY"}</Text></Pressable>{graphSummary ? <Text style={styles.meta}>{graphSummary}</Text> : null}</View>
    </> : null}
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 10 }, hero: { backgroundColor: "#1A2933", borderWidth: 1, borderColor: "#2F4652", padding: 14, borderRadius: 14, flexDirection: "row", gap: 8 }, kicker: { color: "#8EC4E8", fontSize: 8, fontWeight: "900", letterSpacing: 1 }, title: { color: "#F3F1EA", fontSize: 15, fontWeight: "900", marginTop: 4 }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15, marginTop: 7 }, meta: { color: "#90A0A8", fontSize: 9, lineHeight: 14, marginTop: 5 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 12, gap: 6 }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, value: { color: "#F3F1EA", fontSize: 11, fontWeight: "900", marginTop: 3 }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 7, paddingVertical: 4, alignSelf: "flex-start" }, badgeText: { fontSize: 8, fontWeight: "900" }, list: { gap: 5, marginTop: 6 }, item: { flexDirection: "row", alignItems: "center", gap: 8, padding: 8, borderRadius: 9, backgroundColor: "#152129" }, itemActive: { backgroundColor: "#203846", borderWidth: 1, borderColor: "#5B9DCA" }, itemTitle: { color: "#F3F1EA", fontSize: 9, fontWeight: "800" }, grid: { gap: 8 }, field: { gap: 2, marginTop: 5 }, fieldLabel: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.7 }, fieldValue: { color: "#D7E0E3", fontSize: 9, lineHeight: 13 }, secondary: { marginTop: 7, borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 7, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" } });
