import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { approveCadCylindricalHole, listEligibleAssemblyCadFiles, loadEngineeringConnection, previewCadCylindricalHole, type CylindricalHolePreviewSnapshot, type EligibleAssemblyCadFile, type EngineeringConnection } from "@/lib/engineering-api";

const numeric = (value: string) => Number(value.trim());
const initial = { diameter: "", depth: "", x: "", y: "", z: "", dx: "", dy: "", dz: "" };
function message(error: unknown) { return error instanceof Error ? error.message : String(error || "HOLE_OPERATION_UNAVAILABLE"); }

export function CylindricalHoleAuthoring() {
  const [connection, setConnection] = useState<EngineeringConnection | null>(null); const [files, setFiles] = useState<EligibleAssemblyCadFile[]>([]); const [sourceFileId, setSourceFileId] = useState<string>(); const [values, setValues] = useState(initial); const [preview, setPreview] = useState<CylindricalHolePreviewSnapshot | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(true);
  useEffect(() => { (async () => { const next = await loadEngineeringConnection(); setConnection(next); if (!next) return setNotice("PROJECT_ACCESS_REQUIRED — create or open a project first."); const artifacts = await listEligibleAssemblyCadFiles(next); setFiles(artifacts); setSourceFileId(artifacts[0]?.artifactId); })().catch((error) => setNotice(message(error))).finally(() => setBusy(false)); }, []);
  const set = (key: keyof typeof initial, value: string) => { setValues((current) => ({ ...current, [key]: value })); setPreview(null); };
  const parameters = { diameter: numeric(values.diameter), depth: numeric(values.depth), center: { x: numeric(values.x), y: numeric(values.y), z: numeric(values.z) }, direction: { x: numeric(values.dx), y: numeric(values.dy), z: numeric(values.dz) }, unit: "mm" as const };
  async function previewHole() { if (!connection || !sourceFileId) return; try { setBusy(true); const next = await previewCadCylindricalHole(connection, sourceFileId, parameters); setPreview(next); setNotice(next.previewStatus === "PREVIEW_READY" ? "Kernel preview ready. Source artifact remains unchanged until explicit approval." : next.failures.join(" ")); } catch (error) { setNotice(message(error)); } finally { setBusy(false); } }
  async function approveHole() { if (!connection || !preview) return; try { setBusy(true); const next = await approveCadCylindricalHole(connection, preview.operationId); setNotice(`Approved hole result persisted as verified artifact ${next.result.artifact.fileId}.`); setPreview(null); } catch (error) { setNotice(message(error)); } finally { setBusy(false); } }
  return <View style={styles.root}><Text style={styles.eyebrow}>CONTROLLED FEATURE</Text><Text style={styles.title}>Cylindrical Hole</Text><Text style={styles.description}>This executes a real OpenCascade cylinder subtraction only when every parameter is explicit. It has no inferred face selection, default depth, unit conversion, mate, tolerance, or manufacturing meaning.</Text>{busy ? <ActivityIndicator color="#2EC5E8" /> : null}{notice ? <Text style={styles.notice}>{notice}</Text> : null}{connection ? <><Text style={styles.label}>Source verified STEP artifact</Text><ScrollView horizontal contentContainerStyle={styles.choices}>{files.map((file) => <Pressable key={file.artifactId} onPress={() => { setSourceFileId(file.artifactId); setPreview(null); }} style={[styles.choice, sourceFileId === file.artifactId && styles.choiceActive]}><Text style={styles.choiceTitle}>{file.fileName}</Text><Text style={styles.meta}>v{file.artifactRevision} · {file.artifactSha256.slice(0, 14)}…</Text></Pressable>)}</ScrollView><Text style={styles.label}>Explicit parameters — all values in mm</Text><View style={styles.grid}>{(["diameter", "depth", "x", "y", "z", "dx", "dy", "dz"] as const).map((key) => <View key={key} style={styles.field}><Text style={styles.fieldLabel}>{key === "diameter" || key === "depth" ? key.toUpperCase() : key.startsWith("d") ? `DIRECTION ${key.slice(1).toUpperCase()}` : `CENTER ${key.toUpperCase()}`}</Text><TextInput value={values[key]} onChangeText={(value) => set(key, value)} keyboardType="decimal-pad" placeholder="Required" placeholderTextColor="#61798A" style={styles.input} /></View>)}</View><Pressable disabled={busy || !sourceFileId} onPress={previewHole} style={styles.previewButton}><Text style={styles.previewText}>Preview OpenCascade Hole</Text></Pressable>{preview ? <View style={styles.detail}><Text style={styles.ready}>{preview.previewStatus} · approval {preview.approvalStatus}</Text><Text style={styles.meta}>Source SHA-256 {preview.source.sha256}</Text><Text style={styles.meta}>Diameter {preview.parameters.diameter} mm · depth {preview.parameters.depth} mm</Text>{preview.warnings.map((item) => <Text key={item} style={styles.warning}>{item}</Text>)}{preview.failures.map((item) => <Text key={item} style={styles.failure}>{item}</Text>)}{preview.previewStatus === "PREVIEW_READY" ? <Pressable disabled={busy} onPress={approveHole} style={styles.approveButton}><Text style={styles.approveText}>Approve and create new verified STEP</Text></Pressable> : null}</View> : null}</> : <Text style={styles.empty}>A project-scoped engineering access key is required before CAD artifacts can be selected.</Text>}</View>;
}

const styles = StyleSheet.create({ root: { backgroundColor: "#102B3C", borderColor: "#41647A", borderRadius: 14, borderWidth: 1, gap: 9, marginTop: 18, padding: 13 }, eyebrow: { color: "#F5C65A", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: "#E7F0F6", fontSize: 17, fontWeight: "900" }, description: { color: "#B7CCDA", fontSize: 11, lineHeight: 16 }, label: { color: "#8BA4B8", fontSize: 10, fontWeight: "900" }, choices: { gap: 7 }, choice: { backgroundColor: "#071827", borderColor: "#26495E", borderRadius: 8, borderWidth: 1, maxWidth: 180, padding: 8 }, choiceActive: { borderColor: "#F5C65A", borderWidth: 2 }, choiceTitle: { color: "#E7F0F6", fontSize: 10, fontWeight: "800" }, meta: { color: "#B7CCDA", fontSize: 10, lineHeight: 14 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, field: { minWidth: "22%", flexGrow: 1 }, fieldLabel: { color: "#8BA4B8", fontSize: 9, fontWeight: "800", marginBottom: 3 }, input: { backgroundColor: "#071827", borderColor: "#31556B", borderRadius: 7, borderWidth: 1, color: "#E7F0F6", fontSize: 12, paddingHorizontal: 8, paddingVertical: 7 }, previewButton: { alignItems: "center", borderColor: "#2EC5E8", borderRadius: 8, borderWidth: 1, padding: 10 }, previewText: { color: "#93E6F7", fontSize: 11, fontWeight: "900" }, detail: { backgroundColor: "#071827", borderColor: "#24465B", borderRadius: 8, borderWidth: 1, gap: 4, padding: 8 }, ready: { color: "#80E7B5", fontSize: 10, fontWeight: "900" }, warning: { color: "#FFE2A3", fontSize: 10, lineHeight: 15 }, failure: { color: "#FF9A9A", fontSize: 10, lineHeight: 15 }, notice: { backgroundColor: "#153348", borderLeftColor: "#2EC5E8", borderLeftWidth: 3, color: "#E7F0F6", fontSize: 10, lineHeight: 15, padding: 8 }, approveButton: { alignItems: "center", borderColor: "#F5C65A", borderRadius: 8, borderWidth: 1, marginTop: 4, padding: 10 }, approveText: { color: "#FFE2A3", fontSize: 11, fontWeight: "900" }, empty: { color: "#B7CCDA", fontSize: 10, lineHeight: 15 } });
