import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

function Chip({ label, tone = "neutral" }: { label: string; tone?: "danger" | "neutral" | "good" }) { const color = tone === "danger" ? "#E78966" : tone === "good" ? "#62B39A" : "#8EC4E8"; return <View style={[styles.chip, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.chipText, { color }]}>{label}</Text></View>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.card}><Text style={styles.kicker}>{title}</Text>{children}</View>; }

export function RuntimeArchitectureReviewPanel() {
  const [project, setProject] = useState<StoredProjectAccess>(); const [notice, setNotice] = useState("A future execution runtime is not approved. This workspace only records architecture and security requirements."); const [graphSummary, setGraphSummary] = useState("");
  useEffect(() => { let stopped = false; const load = async () => { const current = await loadProjectAccess("active-engineering-workbench"); if (!stopped && current) setProject(current); }; void load(); const timer = setInterval(() => void load(), 1_000); return () => { stopped = true; clearInterval(timer); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }; const reviews = trpc.cae.listRuntimeArchitectureReviews.useQuery(access, { enabled: Boolean(project) }); const create = trpc.cae.createRuntimeArchitectureReview.useMutation(); const graph = trpc.cae.runtimeArchitectureGraph.useMutation(); const review = reviews.data?.[0];
  const createReview = () => { if (!project) return; create.mutate(access, { onSuccess: (item) => { setNotice(item.decisionReason); void reviews.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const inspectGraph = () => { if (!project || !review) return; graph.mutate({ ...access, reviewId: review.reviewId }, { onSuccess: (item) => setGraphSummary(`${item.nodes.length} nodes · ${item.edges.length} review links · ${item.limitations.at(-1)}`), onError: (error) => setNotice(error.message) }); };
  return <View style={styles.wrap} accessibilityLabel="Phase 6 runtime architecture review">
    <View style={styles.hero}><Text style={styles.kicker}>PHASE 6.0 · REVIEW / DESIGN ONLY</Text><Text style={styles.title}>Future solver runtime security architecture</Text><Text style={styles.copy}>This review creates no execution environment. There is no solver, mesher, shell, plugin runtime, process launch, arbitrary network access, or arbitrary filesystem access.</Text><View style={styles.decision}><Text style={styles.decisionLabel}>IMPLEMENTATION READINESS</Text><Text style={styles.decisionValue}>RUNTIME_NOT_APPROVED</Text><Text style={styles.copy}>Execution eligibility: false · Executable: false</Text></View></View>
    {!review ? <Section title="CREATE REVIEW ARTIFACT"><Text style={styles.copy}>Persist the supplied review-only architecture specification as immutable project evidence. This action cannot register, install, start, or authorize a solver.</Text><Pressable style={({ pressed }) => [styles.primary, (create.isPending || !project) && styles.disabled, pressed && styles.pressed]} disabled={create.isPending || !project} onPress={createReview}>{create.isPending ? <ActivityIndicator color="#F3F1EA" /> : <Text style={styles.primaryText}>CREATE REVIEW-ONLY SECURITY SPECIFICATION</Text>}</Pressable></Section> : <>
      <Section title="RUNTIME ARCHITECTURE & BOUNDARIES"><Text style={styles.flow}>{review.architecture.join("  →  ")}</Text>{review.boundaries.map((item) => <View key={item.boundaryId} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.from} → {item.to}</Text><Text style={styles.meta}>Permitted: {item.permittedData.join(" · ")}</Text><Text style={styles.warn}>Prohibited: {item.prohibitedOperations.join(" · ")}</Text></View><Chip label="REVIEW" /></View>)}</Section>
      <Section title="THREAT MODEL · NOT ACCEPTED"><Text style={styles.copy}>Every listed threat remains non-accepted until the required mitigation is independently implemented and tested.</Text>{review.threats.map((item) => <View key={item.threat} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.threat}</Text><Text style={styles.meta}>{item.entryPoint} · {item.impact}</Text><Text style={styles.meta}>Required: {item.requiredMitigations.join(" · ")}</Text></View><Chip label={item.residualRisk} tone="danger" /></View>)}</Section>
      <Section title="PERMISSIONS · DEFAULT DENY"><Text style={styles.copy}>No permission is granted by declaration. Any future grant must be constrained by verified human approval, adapter policy, attestation, and enforcement outside the adapter.</Text><View style={styles.chipRow}>{review.permissions.map((item) => <Chip key={item.permission} label={`${item.permission} · DENY`} tone="danger" />)}</View></Section>
      <Section title="SANDBOX & RESOURCE ENFORCEMENT"><Text style={styles.copy}>{review.sandboxRequirements.join(" ")}</Text>{review.resourceLimits.map((item) => <View key={item.resource} style={styles.row}><Text style={styles.rowTitle}>{item.resource}</Text><Chip label={item.status} tone="danger" /><Text style={styles.meta}>{item.enforcementPoint} · no approved limit ({item.unit})</Text></View>)}</Section>
      <Section title="INPUT / OUTPUT & RESULT TRUST"><Text style={styles.rowTitle}>{review.ioContract.parserTrustRule}</Text><Text style={styles.meta}>Input: {review.ioContract.inputSchema.join(" · ")}</Text><Text style={styles.meta}>Configuration: {review.ioContract.configurationSchema.join(" · ")}</Text><Text style={styles.meta}>Output: {review.ioContract.outputSchema.join(" · ")}</Text><Text style={styles.meta}>Provenance required: {review.resultTrustRequirements.join(" · ")}</Text></Section>
      <Section title="RESULT VERIFICATION"><Text style={styles.copy}>Parsed output is never automatically verified. Candidate outputs can only be classified through the review policy below.</Text><View style={styles.chipRow}>{review.verification.resultStates.map((item) => <Chip key={item} label={item} tone={item === "VERIFIED" ? "good" : item === "INVALID" ? "danger" : "neutral"} />)}</View><Text style={styles.meta}>Mandatory checks: {review.verification.requiredChecks.join(" · ")}</Text></Section>
      <Section title="FAILURE, REPRODUCIBILITY & HUMAN GATES"><Text style={styles.copy}>All failures remain immutable history and cannot become trusted results through retry or parsing.</Text>{review.failures.map((item) => <View key={item.failure} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.failure} → {item.resultState}</Text><Text style={styles.meta}>{item.response}</Text></View><Chip label="IMMUTABLE" /></View>)}<Text style={styles.rowTitle}>REPRODUCIBILITY</Text><Text style={styles.meta}>Required: {review.reproducibility.requiredReferences.join(" · ")}</Text><Text style={styles.warn}>{review.reproducibility.missingReferenceBehavior} · Human review required.</Text>{review.humanGates.map((item) => <View key={item.operation} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.operation}</Text><Text style={styles.meta}>{item.actor} only · AI may recommend, never approve.</Text></View><Chip label="HUMAN GATE" /></View>)}</Section>
      <Section title="PRE-EXECUTION SECURITY TEST PLAN"><Text style={styles.copy}>Every test must pass with independently reviewed evidence before a future implementation could be reconsidered.</Text>{review.securityTests.map((item) => <View key={item.test} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.test}</Text><Text style={styles.meta}>{item.passCriteria}</Text></View><Chip label="REQUIRED" tone="danger" /></View>)}<Pressable style={styles.secondary} disabled={graph.isPending} onPress={inspectGraph}><Text style={styles.secondaryText}>{graph.isPending ? "INSPECTING…" : "INSPECT REVIEW EVIDENCE GRAPH"}</Text></Pressable>{graphSummary ? <Text style={styles.meta}>{graphSummary}</Text> : null}</Section>
    </>}
    <Text style={styles.notice}>{notice}</Text>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, hero: { backgroundColor: "#33251D", borderColor: "#9A6843", borderWidth: 1, borderRadius: 12, padding: 12, gap: 6 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, kicker: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, title: { color: "#F3F1EA", fontSize: 14, fontWeight: "900" }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, decision: { borderColor: "#E78966", backgroundColor: "#E7896618", borderWidth: 1, borderRadius: 9, padding: 9, gap: 2 }, decisionLabel: { color: "#E9B198", fontSize: 8, fontWeight: "900", letterSpacing: 0.7 }, decisionValue: { color: "#E78966", fontSize: 15, fontWeight: "900" }, flow: { color: "#8EC4E8", fontSize: 9, lineHeight: 15, fontWeight: "800" }, row: { gap: 5, borderTopColor: "#2B3A41", borderTopWidth: 1, paddingTop: 8 }, rowTitle: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, meta: { color: "#90A0A8", fontSize: 8, lineHeight: 13 }, warn: { color: "#E9B198", fontSize: 8, lineHeight: 13 }, chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 5 }, chip: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3, alignSelf: "flex-start" }, chipText: { fontSize: 7, fontWeight: "900" }, primary: { backgroundColor: "#1167B1", minHeight: 42, borderRadius: 9, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, secondary: { borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 7, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, notice: { color: "#8EC4E8", fontSize: 8, lineHeight: 13, textAlign: "center" }, disabled: { opacity: 0.45 }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] } });
