import { FlatList, StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

const gateNames = ["G0_APPROVED_TEST_ENVIRONMENT", "G1_REAL_SANDBOX", "G2_ESCAPE_RESISTANCE", "G3_RESOURCE_ISOLATION", "G4_REAL_GMSH", "G5_MESH_VERIFICATION", "G6_REAL_CALCULIX", "G7_NUMERICAL_VALIDATION", "G8_RESULT_INTEGRITY", "G9_HOSTILE_SECURITY_TESTING", "G10_FAILURE_RECOVERY", "G11_REPRODUCIBILITY", "G12_INDEPENDENT_REVIEW", "G13_PRODUCTION_READINESS"] as const;
type GateRow = { gateId: string; state: string; determination: string; missingEvidence: string[]; evidenceIds: string[]; internalEvidenceIds: string[] };

function tint(state: string) { if (state === "PASS") return "#62B39A"; if (state === "FAIL" || state === "BLOCKED") return "#E78966"; if (state === "INCONCLUSIVE") return "#E8B65D"; return "#8EC4E8"; }
function Badge({ value }: { value: string }) { const color = tint(value); return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.badgeText, { color }]}>{value.replaceAll("_", " ")}</Text></View>; }

export function RuntimeAssuranceDashboard() {
  const [project, setProject] = useState<StoredProjectAccess>();
  useEffect(() => { let cancelled = false; const hydrate = async () => { const saved = await loadProjectAccess("active-engineering-workbench"); if (!cancelled && saved) setProject(saved); }; void hydrate(); const timer = setInterval(() => void hydrate(), 1_000); return () => { cancelled = true; clearInterval(timer); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" };
  const assessments = trpc.runtimeAssurance.listAssessments.useQuery(access, { enabled: Boolean(project) });
  const environments = trpc.runtimeAssurance.listEnvironments.useQuery(access, { enabled: Boolean(project) });
  const tests = trpc.runtimeAssurance.listObservedTests.useQuery(access, { enabled: Boolean(project) });
  const failures = trpc.runtimeAssurance.listFailures.useQuery(access, { enabled: Boolean(project) });
  const repairs = trpc.runtimeAssurance.listRepairAttempts.useQuery(access, { enabled: Boolean(project) });
  const assessment = assessments.data?.[0];
  const gates: GateRow[] = assessment?.gates ?? gateNames.map((gateId) => ({ gateId, state: "UNKNOWN", determination: "NO_ASSESSMENT_RECORDED", missingEvidence: ["No immutable gate assessment exists for this project."], evidenceIds: [], internalEvidenceIds: [] }));
  const independentCount = tests.data?.filter((item) => item.evidenceScope === "INDEPENDENTLY_VERIFIED" && item.evidenceOrigin === "EXTERNAL_OBSERVED").length ?? 0;
  const escalationCount = repairs.data?.filter((item) => item.escalationRequired).length ?? 0;

  return <View style={styles.wrap} accessibilityLabel="Runtime assurance gate dashboard">
    <View style={styles.hero}><Text style={styles.kicker}>PHASE 6.15 · STRICT ASSURANCE GOVERNANCE</Text><Text style={styles.title}>G0–G13 evidence ledger</Text><Text style={styles.copy}>Only preserved, observed evidence can inform this dashboard. Internal checks do not become independent verification, and independent verification does not become production authorization. This screen never provisions an environment or runs a sandbox, hostile test, mesher, solver, process, shell, network, filesystem, or numerical workload.</Text><View style={styles.decision}><Text style={styles.decisionLabel}>CURRENT READINESS</Text><Text style={styles.decisionValue}>{assessment?.readiness ?? "NOT_READY"}</Text><Text style={styles.copy}>Execution eligible: false · Executable: false · Production authorization: false</Text></View></View>
    <View style={styles.summary}><View style={styles.summaryCell}><Text style={styles.metric}>{environments.data?.length ?? 0}</Text><Text style={styles.metricLabel}>environment records</Text></View><View style={styles.summaryCell}><Text style={styles.metric}>{independentCount}</Text><Text style={styles.metricLabel}>independent observed tests</Text></View><View style={styles.summaryCell}><Text style={styles.metric}>{escalationCount}</Text><Text style={styles.metricLabel}>root-cause escalations</Text></View></View>
    <View style={styles.card}><Text style={styles.sectionTitle}>DEPENDENCY-ORDERED GATES</Text><Text style={styles.meta}>A blocked, failed, unknown, or inconclusive upstream gate prevents a dependent gate from passing. No pass is inferred from a policy, schema, fixture, or dashboard state.</Text><FlatList data={gates} scrollEnabled={false} keyExtractor={(item) => item.gateId} renderItem={({ item }) => <View style={styles.gateRow}><View style={{ flex: 1 }}><Text style={styles.gateTitle}>{item.gateId.replaceAll("_", " ")}</Text><Text style={styles.meta}>{item.determination.replaceAll("_", " ")}</Text><Text style={styles.missing}>Missing: {item.missingEvidence.slice(0, 2).join(" · ") || "No missing evidence recorded."}</Text>{item.internalEvidenceIds.length ? <Text style={styles.internal}>Internal evidence retained: {item.internalEvidenceIds.length}. It does not authorize a pass.</Text> : null}</View><Badge value={item.state} /></View>} />
    </View>
    <View style={styles.card}><Text style={styles.sectionTitle}>FAILURE AND REPAIR ESCALATION</Text><Text style={styles.meta}>Each record preserves a root-cause classification and a materially distinct repair strategy. Three unsuccessful strategies require escalation instead of repeating the same repair.</Text><FlatList data={failures.data ?? []} scrollEnabled={false} ListEmptyComponent={<Text style={styles.meta}>No immutable assurance failure record is stored for this project.</Text>} keyExtractor={(item) => item.failureId} renderItem={({ item }) => <View style={styles.gateRow}><View style={{ flex: 1 }}><Text style={styles.gateTitle}>{item.gateId.replaceAll("_", " ")} · {item.classification}</Text><Text style={styles.meta}>{item.rootCauseSummary}</Text><Text style={styles.missing}>Remaining risk: {item.remainingRisk}</Text></View><Badge value={item.state} /></View>} />
    </View>
    <View style={styles.card}><Text style={styles.sectionTitle}>INDEPENDENT REVIEW SEPARATION</Text><Text style={styles.copy}>An independent reviewer must receive a complete immutable package for sandbox, escape, resource, Gmsh, mesh, CalculiX, numerical, result integrity, hostile testing, recovery, reproducibility, artifact/SBOM, audit, and environment evidence. No self-approval, fabricated reviewer, fabricated signature, or production authorization is available here.</Text></View>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, hero: { backgroundColor: "#302222", borderColor: "#9A5F55", borderWidth: 1, borderRadius: 13, padding: 13, gap: 6 }, kicker: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, title: { color: "#F3F1EA", fontSize: 15, fontWeight: "900" }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, decision: { borderColor: "#E78966", borderWidth: 1, borderRadius: 9, padding: 9, backgroundColor: "#E7896618", gap: 2 }, decisionLabel: { color: "#E9B198", fontSize: 8, fontWeight: "900" }, decisionValue: { color: "#E78966", fontSize: 15, fontWeight: "900" }, summary: { flexDirection: "row", gap: 7 }, summaryCell: { flex: 1, backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 10, padding: 9, gap: 2 }, metric: { color: "#F3F1EA", fontSize: 16, fontWeight: "900" }, metricLabel: { color: "#90A0A8", fontSize: 7, lineHeight: 10, fontWeight: "800" }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, sectionTitle: { color: "#F3F1EA", fontSize: 10, fontWeight: "900" }, meta: { color: "#90A0A8", fontSize: 8, lineHeight: 13 }, missing: { color: "#E9B198", fontSize: 8, lineHeight: 13, marginTop: 3 }, internal: { color: "#E8B65D", fontSize: 8, lineHeight: 13, marginTop: 3 }, gateRow: { flexDirection: "row", gap: 8, borderTopColor: "#2B3A41", borderTopWidth: 1, paddingTop: 8, marginTop: 2 }, gateTitle: { color: "#F3F1EA", fontSize: 9, fontWeight: "900", lineHeight: 13 }, badge: { maxWidth: 110, borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3, alignSelf: "flex-start" }, badgeText: { fontSize: 7, fontWeight: "900", textAlign: "center", lineHeight: 9 } });
