import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

type Tone = "danger" | "good" | "neutral";
function toneFor(value: string): Tone { return value.includes("IMPLEMENTED") || value === "PASS" || value.includes("FIRST_CANDIDATE") || value === "EVIDENCE_BACKED" ? "good" : value.includes("BLOCKED") || value === "FAIL" || value.includes("NOT_FOR") ? "danger" : "neutral"; }
function Badge({ value }: { value: string }) { const tone = toneFor(value); const color = tone === "good" ? "#62B39A" : tone === "danger" ? "#E78966" : "#8EC4E8"; return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.badgeText, { color }]}>{value.replaceAll("_", " ")}</Text></View>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.card}><Text style={styles.kicker}>{title}</Text>{children}</View>; }

export function RuntimeImplementationReadinessPanel() {
  const [project, setProject] = useState<StoredProjectAccess>(); const [notice, setNotice] = useState("No Phase 6.4 implementation readiness review exists. Runtime implementation has not been approved."); const [graphSummary, setGraphSummary] = useState("");
  useEffect(() => { let stopped = false; const hydrate = async () => { const current = await loadProjectAccess("active-engineering-workbench"); if (!stopped && current) setProject(current); }; void hydrate(); const timer = setInterval(() => void hydrate(), 1_000); return () => { stopped = true; clearInterval(timer); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }; const reviews = trpc.cae.listRuntimeImplementationReadinessReviews.useQuery(access, { enabled: Boolean(project) }); const create = trpc.cae.createRuntimeImplementationReadinessReview.useMutation(); const graph = trpc.cae.runtimeImplementationReadinessGraph.useMutation(); const review = reviews.data?.[0];
  const createReview = () => { if (!project) return; create.mutate(access, { onSuccess: (item) => { setNotice(item.decisionReason); void reviews.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const inspectGraph = () => { if (!project || !review) return; graph.mutate({ ...access, reviewId: review.reviewId }, { onSuccess: (item) => setGraphSummary(`${item.nodes.length} nodes · ${item.edges.length} links · ${item.limitations.at(-1)}`), onError: (error) => setNotice(error.message) }); };
  return <View style={styles.wrap} accessibilityLabel="Phase 6.4 runtime implementation readiness review">
    <View style={styles.hero}><Text style={styles.kicker}>PHASE 6.4 · FINAL RUNTIME BOUNDARY REVIEW</Text><Text style={styles.title}>Runtime implementation readiness</Text><Text style={styles.copy}>This is an architecture and evidence review. It does not install or execute a solver or mesher, and it does not expose a process, shell, plugin, network, filesystem, credential, or runtime control.</Text><View style={styles.decision}><Text style={styles.decisionLabel}>FINAL DECISION</Text><Text style={styles.decisionValue}>{review?.finalDecision ?? "RUNTIME_IMPLEMENTATION_BLOCKED"}</Text><Text style={styles.copy}>Execution eligibility: false · Executable: false · No Phase 7 work is included.</Text></View></View>
    {!review ? <Section title="CREATE IMMUTABLE REVIEW"><Text style={styles.copy}>Create the project-isolated Phase 6.4 assessment. It inventories implemented foundations and identifies only concrete runtime blockers.</Text><Pressable disabled={!project || create.isPending} onPress={createReview} style={({ pressed }) => [styles.primary, (!project || create.isPending) && styles.disabled, pressed && styles.pressed]}>{create.isPending ? <ActivityIndicator color="#F3F1EA" /> : <Text style={styles.primaryText}>CREATE IMPLEMENTATION READINESS REVIEW</Text>}</Pressable></Section> : <>
      <Section title="CURRENT ARCHITECTURE INVENTORY"><Text style={styles.copy}>Existing capabilities are recorded without rebuilding them. A foundation is not treated as an executable runtime.</Text>{review.inventory.map((item) => <View key={item.capability} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.capability}</Text><Text style={styles.meta}>{item.implementedEvidence.join(" · ")}</Text><Text style={styles.warn}>Runtime gap: {item.runtimeGap}</Text></View><Badge value={item.status} /></View>)}</Section>
      <Section title="REMAINING BLOCKERS"><Text style={styles.copy}>Classifications distinguish what genuinely prevents a first controlled runtime from later enhancements.</Text>{review.blockers.map((item) => <View key={item.blockerId} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.classification} · {item.title}</Text><Text style={styles.meta}>{item.why}</Text><Text style={styles.warn}>Evidence needed: {item.evidenceNeeded.join(" · ")}</Text></View><Badge value={item.classification} /></View>)}</Section>
      <Section title="SOLVER STRATEGY"><Text style={styles.copy}>These are architecture options, not installed solvers. Licensing statements require legal review before adoption.</Text>{review.solverOptions.map((item) => <View key={item.option} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.option} · {item.representative}</Text><Text style={styles.meta}>License: {item.license}</Text><Text style={styles.meta}>Integration: {item.integrationComplexity} · I/O: {item.inputOutput}</Text><Text style={styles.meta}>Sandbox: {item.sandboxRequirement}</Text><Text style={styles.warn}>Reproducibility: {item.reproducibility} Verification: {item.verification}</Text><Text style={styles.meta}>Performance: {item.performance} Maintainability: {item.maintainability}</Text></View><Badge value={item.recommendation} /></View>)}</Section>
      <Section title="MESHING STRATEGY"><Text style={styles.copy}>OpenCascade viewer triangulation remains display-only; it is not promoted to a solver-grade mesh.</Text>{review.meshingOptions.map((item) => <View key={item.option} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.option}</Text><Text style={styles.meta}>{item.capability}</Text><Text style={styles.warn}>{item.qualityAndVerification}</Text></View><Badge value={item.recommendation} /></View>)}</Section>
      <Section title="MINIMUM VIABLE CAE"><Text style={styles.rowTitle}>{review.minimumViableCAE.analysis.replaceAll("_", " ")}</Text><Text style={styles.copy}>Pipeline: {review.minimumViableCAE.pipeline.join(" → ")}</Text><Text style={styles.meta}>Scope: {review.minimumViableCAE.scope.join(" · ")}</Text><Text style={styles.warn}>Excluded: {review.minimumViableCAE.excluded.join(" · ")}</Text><Text style={styles.decisionReason}>{review.minimumViableCAE.truthRule}</Text></Section>
      <Section title="IMMUTABLE RUNTIME BOUNDARY"><Text style={styles.copy}>Each boundary declares the only allowable artifact flow; no boundary authorizes arbitrary execution.</Text>{review.runtimeBoundary.map((item) => <View key={item.boundaryId} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.from} → {item.to}</Text><Text style={styles.meta}>Inputs: {item.immutableInputs.join(" · ")}</Text><Text style={styles.meta}>Outputs: {item.allowedOutputs.join(" · ")}</Text><Text style={styles.warn}>Prohibited: {item.prohibited.join(" · ")}</Text><Text style={styles.meta}>Hashes: {item.requiredHashes.join(" · ")}</Text></View></View>)}</Section>
      <Section title="RESULT TRUST REQUIREMENTS"><Text style={styles.copy}>Numerical results would remain invalid, unverified, or hidden when a requirement is missing.</Text>{review.resultTrust.map((item) => <View key={item.requirement} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.requirement}</Text><Text style={styles.meta}>{item.condition}</Text><Text style={styles.warn}>Missing behavior: {item.missingBehavior.replaceAll("_", " ")}</Text><Text style={styles.meta}>Evidence: {item.requiredEvidence.join(" · ")}</Text></View></View>)}</Section>
      <Section title="ESSENTIAL SECURITY GATES"><Text style={styles.copy}>Existing trust, identity, audit, external-evidence, and governance controls are reused. The listed runtime controls are essential, not additional governance layers.</Text>{review.essentialSecurityGates.map((item) => <View key={item.gate} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.gate}</Text><Text style={styles.meta}>{item.whyRequired}</Text><Text style={styles.warn}>Minimum evidence: {item.minimumEvidence.join(" · ")}</Text></View><Badge value={item.currentState} /></View>)}</Section>
      <Section title="FAIL-CLOSED FAILURE MODEL"><Text style={styles.copy}>Failure preserves bounded diagnostic evidence but never promotes partial or corrupt output into a trusted result.</Text>{review.failureModel.map((item) => <View key={item.failure} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.failure}</Text><Text style={styles.meta}>{item.failClosedBehavior}</Text><Text style={styles.warn}>Preserve: {item.preservedArtifacts.join(" · ")} · Result: {item.resultState}</Text></View></View>)}</Section>
      <Section title={`IMPLEMENTATION PLAN · ${review.estimatedComplexity}`}><Text style={styles.copy}>The plan stops at a future security review; it does not approve execution.</Text>{review.implementationPlan.map((item) => <View key={item.order} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.order}. {item.title} · {item.complexity}</Text><Text style={styles.meta}>{item.outcome}</Text><Text style={styles.warn}>Gate: {item.gateBeforeNext}</Text></View></View>)}</Section>
      <Section title="SOURCES & EVIDENCE GRAPH"><Text style={styles.copy}>Primary sources used for this strategy review are preserved in the project research notes. Their presence is not evidence that a solver, mesher, or container is installed.</Text>{review.sourceUrls.map((url) => <Text key={url} style={styles.source}>{url}</Text>)}<Pressable disabled={graph.isPending} onPress={inspectGraph} style={({ pressed }) => [styles.secondary, graph.isPending && styles.disabled, pressed && styles.pressed]}><Text style={styles.secondaryText}>{graph.isPending ? "INSPECTING…" : "INSPECT READINESS EVIDENCE GRAPH"}</Text></Pressable>{graphSummary ? <Text style={styles.meta}>{graphSummary}</Text> : null}</Section>
    </>}
    <Text style={styles.notice}>{notice}</Text>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, hero: { backgroundColor: "#302222", borderColor: "#9A5F55", borderWidth: 1, borderRadius: 12, padding: 12, gap: 6 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, kicker: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, title: { color: "#F3F1EA", fontSize: 14, fontWeight: "900" }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, decision: { borderColor: "#E78966", backgroundColor: "#E7896618", borderWidth: 1, borderRadius: 9, padding: 9, gap: 2 }, decisionLabel: { color: "#E9B198", fontSize: 8, fontWeight: "900", letterSpacing: 0.7 }, decisionValue: { color: "#E78966", fontSize: 15, fontWeight: "900" }, row: { gap: 5, borderTopColor: "#2B3A41", borderTopWidth: 1, paddingTop: 8 }, rowTitle: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, meta: { color: "#90A0A8", fontSize: 8, lineHeight: 13 }, warn: { color: "#E9B198", fontSize: 8, lineHeight: 13 }, source: { color: "#8EC4E8", fontSize: 8, lineHeight: 13 }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3, alignSelf: "flex-start" }, badgeText: { fontSize: 7, fontWeight: "900" }, primary: { backgroundColor: "#1167B1", minHeight: 42, borderRadius: 9, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, secondary: { borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 7, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, decisionReason: { color: "#F3F1EA", fontSize: 9, lineHeight: 14, fontWeight: "700" }, notice: { color: "#8EC4E8", fontSize: 8, lineHeight: 13, textAlign: "center" }, disabled: { opacity: 0.45 }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] } });
