import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

type Tone = "danger" | "neutral" | "good";
function toneFor(status: string): Tone { return status === "PASS" || status === "WITHIN_LIMIT" ? "good" : status === "FAIL" || status === "EXCEEDS_LIMIT" || status === "NOT_READY" || status === "DISABLED" ? "danger" : "neutral"; }
function Badge({ value }: { value: string }) { const tone = toneFor(value); const color = tone === "good" ? "#62B39A" : tone === "danger" ? "#E78966" : "#8EC4E8"; return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.badgeText, { color }]}>{value.replaceAll("_", " ")}</Text></View>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.card}><Text style={styles.kicker}>{title}</Text>{children}</View>; }

export function RuntimeReadinessPanel() {
  const [project, setProject] = useState<StoredProjectAccess>(); const [notice, setNotice] = useState("No Phase 6.1 readiness review exists. All missing evidence remains unknown and runtime approval stays disabled."); const [validation, setValidation] = useState(""); const [attestorIdentity, setAttestorIdentity] = useState(""); const [scope, setScope] = useState(""); const [environment, setEnvironment] = useState(""); const [hash, setHash] = useState(""); const [method, setMethod] = useState(""); const [graphSummary, setGraphSummary] = useState("");
  useEffect(() => { let stopped = false; const load = async () => { const current = await loadProjectAccess("active-engineering-workbench"); if (!stopped && current) setProject(current); }; void load(); const timer = setInterval(() => void load(), 1_000); return () => { stopped = true; clearInterval(timer); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }; const reviews = trpc.cae.listRuntimeReadinessReviews.useQuery(access, { enabled: Boolean(project) }); const policies = trpc.cae.listCapacityPolicies.useQuery(access, { enabled: Boolean(project) }); const attestations = trpc.cae.listIndependentSandboxAttestations.useQuery(access, { enabled: Boolean(project) }); const create = trpc.cae.createRuntimeReadinessReview.useMutation(); const validate = trpc.cae.validateCapacityPolicy.useMutation(); const registerAttestation = trpc.cae.registerIndependentSandboxAttestation.useMutation(); const graph = trpc.cae.runtimeReadinessGraph.useMutation(); const review = reviews.data?.[0]; const policy = policies.data?.[0];
  const refresh = () => { void reviews.refetch(); void policies.refetch(); void attestations.refetch(); };
  const createReview = () => { if (!project) return; create.mutate(access, { onSuccess: (item) => { setNotice(item.reason); refresh(); }, onError: (error) => setNotice(error.message) }); };
  const validateUnknown = () => { if (!project || !policy) return; validate.mutate({ ...access, policyId: policy.policyId, limit: "CPU_LIMIT", observedValue: "UNKNOWN", observedUnit: "millicores" }, { onSuccess: (item) => setValidation(`${item.limit}: ${item.outcome}. ${item.reason}`), onError: (error) => setValidation(error.message) }); };
  const saveAttestation = () => { if (!project || !review) return; registerAttestation.mutate({ ...access, designId: review.sandboxDesign.designId, attestorIdentity, attestorPublisherRelationship: "INDEPENDENT", attestationScope: scope, environmentIdentity: environment, evidenceHash: hash, attestationTime: new Date().toISOString(), verificationMethod: method }, { onSuccess: (item) => { setNotice(item.reason); setAttestorIdentity(""); setScope(""); setEnvironment(""); setHash(""); setMethod(""); refresh(); }, onError: (error) => setNotice(error.message) }); };
  const inspectGraph = () => { if (!project || !review) return; graph.mutate({ ...access, readinessId: review.readinessId }, { onSuccess: (item) => setGraphSummary(`${item.nodes.length} evidence nodes · ${item.edges.length} links · ${item.limitations.at(-1)}`), onError: (error) => setNotice(error.message) }); };
  const canRegister = Boolean(review && attestorIdentity.trim() && scope.trim() && environment.trim() && /^[a-f0-9]{64}$/i.test(hash) && method.trim());
  return <View style={styles.wrap} accessibilityLabel="Phase 6.1 runtime readiness dashboard">
    <View style={styles.hero}><Text style={styles.kicker}>PHASE 6.1 · DESIGN / VERIFICATION ONLY</Text><Text style={styles.title}>Execution infrastructure readiness</Text><Text style={styles.copy}>This dashboard records capacity, sandbox, attestation, attack-test, and assurance evidence. It cannot start a solver, mesher, shell, plugin, process, network, credential, or filesystem runtime.</Text><View style={styles.decision}><Text style={styles.decisionLabel}>RUNTIME READINESS</Text><Text style={styles.decisionValue}>{review?.readiness ?? "NOT_READY"}</Text><Text style={styles.copy}>Execution approval: DISABLED · Eligible: false · Executable: false</Text></View></View>
    {!review ? <Section title="CREATE READINESS REVIEW"><Text style={styles.copy}>Create an immutable Phase 6.1 review. Its capacity values are UNKNOWN by default because no infrastructure capability is assumed.</Text><Pressable disabled={create.isPending || !project} onPress={createReview} style={({ pressed }) => [styles.primary, (create.isPending || !project) && styles.disabled, pressed && styles.pressed]}>{create.isPending ? <ActivityIndicator color="#F3F1EA" /> : <Text style={styles.primaryText}>CREATE READINESS REVIEW</Text>}</Pressable></Section> : <>
      <Section title="CAPACITY POLICY"><Text style={styles.copy}>{review.capacityPolicy.reason}</Text>{review.capacityPolicy.limits.map((item) => <View key={item.kind} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.kind}</Text><Text style={styles.meta}>Value: {String(item.value)} {item.unit} · environment: {item.environment}</Text><Text style={styles.meta}>Version {item.version} · effective {item.effectiveDate}</Text><Text style={styles.warn}>{item.rationale}</Text></View><Badge value={item.value === "UNKNOWN" ? "UNKNOWN" : review.capacityPolicy.state} /></View>)}<Pressable style={styles.secondary} disabled={!policy || validate.isPending} onPress={validateUnknown}><Text style={styles.secondaryText}>{validate.isPending ? "VALIDATING…" : "DEMONSTRATE UNKNOWN-LIMIT REFUSAL"}</Text></Pressable>{validation ? <Text style={styles.warn}>{validation}</Text> : null}</Section>
      <Section title="SANDBOX DESIGN · NOT IMPLEMENTATION"><Text style={styles.copy}>{review.sandboxDesign.statement}</Text>{review.sandboxDesign.controls.map((item) => <View key={item.control} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.control}</Text><Text style={styles.meta}>{item.proposal}</Text><Text style={styles.warn}>Required evidence: {item.requiredEvidence.join(" · ")}</Text></View><Badge value={item.status} /></View>)}</Section>
      <Section title="INDEPENDENT ATTESTATION EVIDENCE"><Text style={styles.copy}>Registration is evidence intake only. It never converts evidence into ATTESTED; the verifier must be separate from the adapter publisher.</Text>{(attestations.data ?? []).map((item) => <View key={item.attestationEvidenceId} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.attestorIdentity}</Text><Text style={styles.meta}>{item.attestationScope} · {item.environmentIdentity}</Text><Text style={styles.meta}>SHA-256: {item.evidenceHash.slice(0, 16)}… · {item.verificationMethod}</Text></View><Badge value={item.status} /></View>)}<TextInput value={attestorIdentity} onChangeText={setAttestorIdentity} placeholder="Independent attestor identity" placeholderTextColor="#71828B" style={styles.input} /><TextInput value={scope} onChangeText={setScope} placeholder="Attestation scope" placeholderTextColor="#71828B" style={styles.input} /><TextInput value={environment} onChangeText={setEnvironment} placeholder="Environment identity" placeholderTextColor="#71828B" style={styles.input} /><TextInput value={hash} onChangeText={setHash} autoCapitalize="none" placeholder="Evidence SHA-256 (64 hexadecimal characters)" placeholderTextColor="#71828B" style={styles.input} /><TextInput value={method} onChangeText={setMethod} placeholder="Independent verification method" placeholderTextColor="#71828B" style={styles.input} /><Pressable disabled={!canRegister || registerAttestation.isPending} onPress={saveAttestation} style={({ pressed }) => [styles.secondary, (!canRegister || registerAttestation.isPending) && styles.disabled, pressed && styles.pressed]}><Text style={styles.secondaryText}>{registerAttestation.isPending ? "REGISTERING…" : "REGISTER INDEPENDENT EVIDENCE"}</Text></Pressable></Section>
      <Section title="HOSTILE SECURITY TEST PLAN"><Text style={styles.copy}>A planned test is not a passing test. No pass state is issued without an actual execution result.</Text>{review.hostileTests.map((item) => <View key={item.simulationId} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.attack} · {item.severity}</Text><Text style={styles.meta}>Expected: {item.expectedBehavior}</Text><Text style={styles.warn}>Failure: {item.failureCondition}</Text></View><Badge value={item.status} /></View>)}</Section>
      <Section title="SECURITY INVARIANTS & ASSURANCE"><Text style={styles.copy}>No single secure flag is displayed. Every assurance dimension and invariant remains visible.</Text>{review.securityInvariants.map((item) => <View key={item.invariantId} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.statement}</Text><Text style={styles.meta}>{item.requiredEnforcement}</Text></View><Badge value={item.status} /></View>)}{review.assurance.map((item) => <View key={item.dimension} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.dimension}</Text><Text style={styles.meta}>{item.statement}</Text></View><Badge value={item.status} /></View>)}</Section>
      <Section title="MAJOR UNKNOWNS & DECISION"><View style={styles.unknowns}>{review.majorUnknowns.map((item) => <Text key={item} style={styles.warn}>• {item}</Text>)}</View><Text style={styles.decisionReason}>{review.reason}</Text><Pressable disabled={graph.isPending} onPress={inspectGraph} style={({ pressed }) => [styles.secondary, graph.isPending && styles.disabled, pressed && styles.pressed]}><Text style={styles.secondaryText}>{graph.isPending ? "INSPECTING…" : "INSPECT READINESS EVIDENCE GRAPH"}</Text></Pressable>{graphSummary ? <Text style={styles.meta}>{graphSummary}</Text> : null}</Section>
    </>}
    <Text style={styles.notice}>{notice}</Text>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, hero: { backgroundColor: "#302222", borderColor: "#9A5F55", borderWidth: 1, borderRadius: 12, padding: 12, gap: 6 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, kicker: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, title: { color: "#F3F1EA", fontSize: 14, fontWeight: "900" }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, decision: { borderColor: "#E78966", backgroundColor: "#E7896618", borderWidth: 1, borderRadius: 9, padding: 9, gap: 2 }, decisionLabel: { color: "#E9B198", fontSize: 8, fontWeight: "900", letterSpacing: 0.7 }, decisionValue: { color: "#E78966", fontSize: 16, fontWeight: "900" }, row: { gap: 5, borderTopColor: "#2B3A41", borderTopWidth: 1, paddingTop: 8 }, rowTitle: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, meta: { color: "#90A0A8", fontSize: 8, lineHeight: 13 }, warn: { color: "#E9B198", fontSize: 8, lineHeight: 13 }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3, alignSelf: "flex-start" }, badgeText: { fontSize: 7, fontWeight: "900" }, primary: { backgroundColor: "#1167B1", minHeight: 42, borderRadius: 9, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, secondary: { borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 7, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, input: { borderColor: "#405762", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 7, color: "#F3F1EA", fontSize: 9, minHeight: 34 }, unknowns: { gap: 4 }, decisionReason: { color: "#F3F1EA", fontSize: 10, lineHeight: 15, fontWeight: "700" }, notice: { color: "#8EC4E8", fontSize: 8, lineHeight: 13, textAlign: "center" }, disabled: { opacity: 0.45 }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] } });
