import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import { MaterialIcons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { INPUT_PACKAGE_FIELD_TYPES, approveSeatInputPackage, attachSeatInputEvidence, createSeatInputPackage, releaseSeatInputPackage, updateSeatInputPackage, validateSeatInputPackage, type EngineeringConnection, type EngineeringInputField, type InputPackageFieldType, type SeatInputPackageSnapshot } from "@/lib/engineering-api";

type Draft = Record<InputPackageFieldType, Omit<EngineeringInputField, "fieldType">>;
const emptyDraft = (): Draft => Object.fromEntries(INPUT_PACKAGE_FIELD_TYPES.map((fieldType) => [fieldType, { value: "", unit: "", source: "", applicability: "", evidenceFileIds: [], approvalStatus: "UNREVIEWED" }])) as unknown as Draft;
const groups: { title: string; description: string; fields: InputPackageFieldType[] }[] = [
  { title: "Material", description: "Certificate and declared material properties.", fields: ["MATERIAL_CERTIFICATE", "MATERIAL_PROPERTIES"] },
  { title: "Fixtures", description: "Mount definition, coordinates, and constrained degrees of freedom.", fields: ["MOUNT_FIXTURES", "FIXTURE_COORDINATES", "FIXTURE_DOF"] },
  { title: "Loads", description: "Declared regions, magnitude, direction, and application coordinates.", fields: ["LOAD_REGIONS", "LOAD_MAGNITUDE", "LOAD_DIRECTION", "LOAD_APPLICATION_COORDINATES"] },
  { title: "Boundary & coordinates", description: "Boundary conditions and the coordinate system used to interpret them.", fields: ["BOUNDARY_CONDITIONS", "COORDINATE_SYSTEM"] },
  { title: "Mesh & solver", description: "Meshing and solver controls; editing them never starts a solver.", fields: ["MESH_SETTINGS", "SOLVER_SETTINGS"] },
  { title: "Validation", description: "Model-specific validation method and traceable reference criterion.", fields: ["VALIDATION_METHOD", "REFERENCE_CRITERION"] },
];

async function base64ForAsset(asset: DocumentPicker.DocumentPickerAsset) {
  if (asset.base64) return asset.base64;
  if (Platform.OS === "web" && asset.file) return Buffer.from(await asset.file.arrayBuffer()).toString("base64");
  return FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.Base64 });
}

export function SeatInputPackageEditor({ connection, seatDesignId, revisionId }: { connection: EngineeringConnection; seatDesignId: string; revisionId: string }) {
  const [cadRevisionHash, setCadRevisionHash] = useState("");
  const [cadArtifactHash, setCadArtifactHash] = useState("");
  const [draft, setDraft] = useState<Draft>(emptyDraft);
  const [packageItem, setPackageItem] = useState<SeatInputPackageSnapshot | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [openGroup, setOpenGroup] = useState("Material");
  const fields = useMemo(() => INPUT_PACKAGE_FIELD_TYPES.map((fieldType) => ({ fieldType, ...draft[fieldType] })), [draft]);
  const update = (fieldType: InputPackageFieldType, patch: Partial<Draft[InputPackageFieldType]>) => setDraft((current) => ({ ...current, [fieldType]: { ...current[fieldType], ...patch } }));
  async function create() {
    try { const item = await createSeatInputPackage(connection, { seatDesignId, seatRevisionId: revisionId, cadRevisionHash, cadArtifactHash, fields }); setPackageItem(item); setNotice(item.status); }
    catch (error) { setNotice(error instanceof Error ? error.message : "INPUT_PACKAGE_CREATE_REJECTED"); }
  }
  async function save() { if (!packageItem) return; try { const item = await updateSeatInputPackage(connection, packageItem.packageId, fields); setPackageItem(item); setNotice("INPUT_PACKAGE_SAVED"); } catch (error) { setNotice(error instanceof Error ? error.message : "INPUT_PACKAGE_SAVE_REJECTED"); } }
  async function validate() { if (!packageItem) return; try { const item = await validateSeatInputPackage(connection, packageItem.packageId); setPackageItem(item); setNotice(item.requiredInputs.length ? `REQUIRED_INPUT: ${item.requiredInputs.join(", ")}` : item.status); } catch (error) { setNotice(error instanceof Error ? error.message : "INPUT_PACKAGE_VALIDATE_REJECTED"); } }
  async function approve() { if (!packageItem) return; try { const item = await approveSeatInputPackage(connection, packageItem.packageId); setPackageItem(item); setNotice(item.status); } catch (error) { setNotice(error instanceof Error ? error.message : "INPUT_PACKAGE_APPROVE_REJECTED"); } }
  async function release() { if (!packageItem) return; try { const item = await releaseSeatInputPackage(connection, packageItem.packageId); setPackageItem(item); setNotice(item.status); } catch (error) { setNotice(error instanceof Error ? error.message : "INPUT_PACKAGE_RELEASE_REJECTED"); } }
  async function attach(fieldType: InputPackageFieldType) {
    if (!packageItem) return setNotice("CREATE_INPUT_PACKAGE_BEFORE_ATTACHMENT");
    try {
      const picked = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: true, type: "*/*" });
      if (picked.canceled) return;
      const asset = picked.assets[0];
      const attachment = await attachSeatInputEvidence(connection, packageItem.packageId, { fileName: asset.name, mimeType: asset.mimeType ?? undefined, base64: await base64ForAsset(asset) });
      update(fieldType, { evidenceFileIds: [...draft[fieldType].evidenceFileIds!, attachment.attachmentId] });
      setNotice(`EVIDENCE_ATTACHED:${attachment.fileName}`);
    } catch (error) { setNotice(error instanceof Error ? error.message : "INPUT_EVIDENCE_ATTACHMENT_REJECTED"); }
  }
  return <View style={styles.box}><View style={styles.heading}><View><Text style={styles.eyebrow}>CAE INPUT PACKAGE</Text><Text style={styles.title}>Engineering input workspace</Text></View><Text style={styles.status}>{packageItem?.status ?? "DRAFT"}</Text></View><Text style={styles.help}>Enter only approved engineering information. Empty fields remain REQUIRED_INPUT; no default values are supplied.</Text>{notice ? <View style={styles.noticeBox}><MaterialIcons color="#F7C873" name="info-outline" size={16} /><Text style={styles.notice}>{notice.replace(/_/g, " ")}</Text></View> : null}<View style={styles.binding}><Text style={styles.bindingTitle}>CAD binding</Text><Text style={styles.bindingText}>The package is cryptographically checked against the exact Seat revision and CAD artifact before review.</Text><TextInput value={cadRevisionHash} onChangeText={setCadRevisionHash} placeholder="CAD revision SHA-256" placeholderTextColor="#6A8AA2" style={styles.input} editable={!packageItem} /><TextInput value={cadArtifactHash} onChangeText={setCadArtifactHash} placeholder="CAD artifact SHA-256" placeholderTextColor="#6A8AA2" style={styles.input} editable={!packageItem} /></View>
    {groups.map((group) => <View key={group.title} style={styles.group}><Pressable onPress={() => setOpenGroup(openGroup === group.title ? "" : group.title)} style={({ pressed }) => [styles.groupHeader, pressed && styles.pressed]} accessibilityRole="button"><View style={styles.groupCopy}><Text style={styles.groupTitle}>{group.title}</Text><Text style={styles.groupDescription}>{group.description}</Text></View><MaterialIcons color="#72D8EF" name={openGroup === group.title ? "expand-less" : "expand-more"} size={22} /></Pressable>{openGroup === group.title ? group.fields.map((fieldType) => <View key={fieldType} style={styles.field}><View style={styles.fieldHeader}><Text style={styles.label}>{fieldType.replace(/_/g, " ")}</Text><Text style={styles.approval}>{draft[fieldType].approvalStatus}</Text></View><Text style={styles.fieldHint}>USER INPUT · SOURCE EVIDENCE · APPROVAL</Text><TextInput value={String(draft[fieldType].value ?? "")} onChangeText={(value) => update(fieldType, { value })} placeholder="Declared value" placeholderTextColor="#6A8AA2" style={styles.input} editable={packageItem?.status !== "RELEASED"} /><View style={styles.split}><TextInput value={draft[fieldType].unit ?? ""} onChangeText={(unit) => update(fieldType, { unit })} placeholder="Unit" placeholderTextColor="#6A8AA2" style={[styles.input, styles.half]} editable={packageItem?.status !== "RELEASED"} /><TextInput value={draft[fieldType].applicability ?? ""} onChangeText={(applicability) => update(fieldType, { applicability })} placeholder="Applicability" placeholderTextColor="#6A8AA2" style={[styles.input, styles.half]} editable={packageItem?.status !== "RELEASED"} /></View><TextInput value={draft[fieldType].source ?? ""} onChangeText={(source) => update(fieldType, { source })} placeholder="Source / certificate / reference" placeholderTextColor="#6A8AA2" style={styles.input} editable={packageItem?.status !== "RELEASED"} /><View style={styles.row}><Pressable onPress={() => attach(fieldType)} disabled={packageItem?.status === "RELEASED"} style={styles.minor}><MaterialIcons color="#BDEFFC" name="attach-file" size={15} /><Text style={styles.minorText}>{draft[fieldType].evidenceFileIds?.length ? `${draft[fieldType].evidenceFileIds?.length} evidence files` : "Attach evidence"}</Text></Pressable><Pressable onPress={() => update(fieldType, { approvalStatus: draft[fieldType].approvalStatus === "APPROVED" ? "UNREVIEWED" : "APPROVED" })} disabled={packageItem?.status === "RELEASED"} style={styles.minor}><MaterialIcons color="#BDEFFC" name={draft[fieldType].approvalStatus === "APPROVED" ? "verified" : "pending"} size={15} /><Text style={styles.minorText}>{draft[fieldType].approvalStatus === "APPROVED" ? "Approved" : "Mark reviewed"}</Text></Pressable></View></View>) : null}</View>)}
    <View style={styles.row}><Pressable onPress={create} disabled={Boolean(packageItem)} style={styles.action}><Text style={styles.actionText}>Create</Text></Pressable><Pressable onPress={save} disabled={!packageItem} style={styles.action}><Text style={styles.actionText}>Save</Text></Pressable><Pressable onPress={validate} disabled={!packageItem} style={styles.action}><Text style={styles.actionText}>Validate</Text></Pressable><Pressable onPress={approve} disabled={!packageItem} style={styles.action}><Text style={styles.actionText}>Approve</Text></Pressable><Pressable onPress={release} disabled={!packageItem} style={styles.action}><Text style={styles.actionText}>Release</Text></Pressable></View>{packageItem ? <Text style={styles.hash}>Package {packageItem.packageHash} · {packageItem.status}</Text> : null}</View>;
}

const styles = StyleSheet.create({ box: { backgroundColor: "#091B2A", borderColor: "#214B63", borderRadius: 18, borderWidth: 1, gap: 12, marginTop: 10, padding: 14 }, heading: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, eyebrow: { color: "#72D8EF", fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { color: "#F0F7FB", fontSize: 18, fontWeight: "800", marginTop: 3 }, status: { backgroundColor: "#3A321F", borderRadius: 12, color: "#F7C873", fontSize: 10, fontWeight: "800", paddingHorizontal: 8, paddingVertical: 5 }, help: { color: "#A9C0D0", fontSize: 12, lineHeight: 18 }, noticeBox: { alignItems: "flex-start", backgroundColor: "#2A2A1B", borderColor: "#735B26", borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 7, padding: 10 }, notice: { color: "#F7E1A1", flex: 1, fontSize: 11, fontWeight: "700", lineHeight: 16 }, binding: { backgroundColor: "#0D2637", borderColor: "#1C4A63", borderRadius: 12, borderWidth: 1, gap: 8, padding: 11 }, bindingTitle: { color: "#E7F0F6", fontSize: 13, fontWeight: "800" }, bindingText: { color: "#8BA4B8", fontSize: 11, lineHeight: 16 }, group: { borderColor: "#1B4056", borderRadius: 12, borderWidth: 1, overflow: "hidden" }, groupHeader: { alignItems: "center", backgroundColor: "#0D2637", flexDirection: "row", gap: 8, justifyContent: "space-between", padding: 11 }, groupCopy: { flex: 1, gap: 2 }, groupTitle: { color: "#E7F0F6", fontSize: 14, fontWeight: "800" }, groupDescription: { color: "#8BA4B8", fontSize: 11, lineHeight: 15 }, field: { borderTopColor: "#1B4056", borderTopWidth: 1, gap: 7, padding: 11 }, fieldHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, label: { color: "#D8EAF3", fontSize: 12, fontWeight: "800" }, approval: { backgroundColor: "#26323B", borderRadius: 10, color: "#B7CCDA", fontSize: 9, fontWeight: "800", paddingHorizontal: 7, paddingVertical: 4 }, fieldHint: { color: "#6F97AA", fontSize: 9, fontWeight: "700", letterSpacing: .5 }, input: { backgroundColor: "#071522", borderColor: "#2A566F", borderRadius: 8, borderWidth: 1, color: "#E7F0F6", fontSize: 12, minHeight: 38, paddingHorizontal: 9 }, split: { flexDirection: "row", gap: 7 }, half: { flex: 1 }, row: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, action: { backgroundColor: "#2EC5E8", borderRadius: 8, paddingHorizontal: 9, paddingVertical: 8 }, actionText: { color: "#081827", fontSize: 11, fontWeight: "800" }, minor: { alignItems: "center", borderColor: "#2A607C", borderRadius: 8, borderWidth: 1, flexDirection: "row", gap: 5, paddingHorizontal: 8, paddingVertical: 7 }, minorText: { color: "#BDEFFC", fontSize: 10, fontWeight: "700" }, hash: { color: "#8BA4B8", fontFamily: "monospace", fontSize: 9 }, pressed: { opacity: .76, transform: [{ scale: .985 }] } });
