import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

const MAX_BYTES = 5 * 1024 * 1024;
function webBase64(bytes: Uint8Array) { let text = ""; for (let offset = 0; offset < bytes.length; offset += 0x8000) text += String.fromCharCode(...bytes.subarray(offset, Math.min(offset + 0x8000, bytes.length))); return globalThis.btoa(text); }
function Badge({ value }: { value: string }) { const color = ["REVOKED", "INVALID", "UNVERIFIED", "UNTRUSTED", "UNAVAILABLE", "FAIL"].includes(value) ? "#E78966" : ["VERIFIED", "APPROVED", "EXECUTION_ELIGIBLE", "VALID", "PASS"].includes(value) ? "#62B39A" : "#8EC4E8"; return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.badgeText, { color }]}>{value}</Text></View>; }

export function SolverTrustPanel({ simulationId }: { simulationId: string }) {
  const [project, setProject] = useState<StoredProjectAccess>(); const [notice, setNotice] = useState("No adapter is executable in this phase. Trust records only establish review evidence and a future conceptual eligibility gate."); const [name, setName] = useState("Reviewer name"); const [role, setRole] = useState("Engineering reviewer"); const [actor, setActor] = useState("Human actor"); const [method, setMethod] = useState("Declared identity verification method"); const [instrument, setInstrument] = useState("Instrument"); const [reason, setReason] = useState("Human verification reason"); const [manifestVerified, setManifestVerified] = useState(false); const [signatureVerified, setSignatureVerified] = useState(false); const [capabilities, setCapabilities] = useState("");
  useEffect(() => { let dead = false; const load = async () => { const stored = await loadProjectAccess("active-engineering-workbench"); if (!dead && stored) setProject(stored); }; void load(); const interval = setInterval(() => void load(), 1_000); return () => { dead = true; clearInterval(interval); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }; const reviewers = trpc.cae.listReviewers.useQuery(access, { enabled: Boolean(project) }); const certificates = trpc.cae.listCalibrationCertificates.useQuery(access, { enabled: Boolean(project) }); const adapters = trpc.cae.listExternalSolverAdapters.useQuery(access, { enabled: Boolean(project) }); const audits = trpc.cae.securityAudit.useQuery(access, { enabled: Boolean(project) }); const reviewer = useMemo(() => reviewers.data?.find((item) => item.status === "VERIFIED") ?? reviewers.data?.[0], [reviewers.data]); const adapter = adapters.data?.[0]; const eligibility = trpc.cae.adapterEligibility.useQuery({ ...access, registrationId: adapter?.registrationId ?? "UNAVAILABLE" }, { enabled: Boolean(project && adapter) }); const trust = trpc.cae.listAdapterTrustVerifications.useQuery({ ...access, registrationId: adapter?.registrationId }, { enabled: Boolean(project && adapter) });
  const registerReviewer = trpc.cae.registerReviewer.useMutation(); const verifyReviewer = trpc.cae.verifyReviewer.useMutation(); const attachCertificate = trpc.cae.attachCalibrationCertificate.useMutation(); const verifyCertificate = trpc.cae.verifyCalibrationCertificate.useMutation(); const verifyTrust = trpc.cae.verifyAdapterTrust.useMutation(); const approve = trpc.cae.authorizeEngineeringApproval.useMutation(); const revoke = trpc.cae.revokeTrustObject.useMutation(); const graph = trpc.cae.trustEvidenceGraph.useMutation(); const [graphSummary, setGraphSummary] = useState("");
  const createReviewer = () => { if (!project) return; registerReviewer.mutate({ ...access, displayName: name, role, projectScope: [project.projectId], permissions: ["APPROVE_SOLVER_ADAPTER", "APPROVE_CALIBRATION", "APPROVE_MATERIAL", "APPROVE_VALIDATION"], actor }, { onSuccess: (item) => { setNotice(`Registered ${item.displayName} as UNVERIFIED. Registration is not approval.`); void reviewers.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const verifyIdentity = () => { if (!project || !reviewer) return; verifyReviewer.mutate({ ...access, reviewerId: reviewer.reviewerId, verificationMethod: method, actor }, { onSuccess: (item) => { setNotice(`Reviewer ${item.displayName} is ${item.status}; permissions remain project scoped.`); void reviewers.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const attachCert = async () => { if (!project) return; try { const result = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "text/plain", "application/octet-stream"], copyToCacheDirectory: true }); if (result.canceled) return setNotice("Certificate selection cancelled; no file or metadata was recorded."); const asset = result.assets[0]; if (asset.size && asset.size > MAX_BYTES) return setNotice("Certificate exceeds the 5 MiB bounded evidence limit."); const base64 = Platform.OS === "web" ? webBase64(new Uint8Array(await (await fetch(asset.uri)).arrayBuffer())) : await FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.Base64 }); attachCertificate.mutate({ ...access, fileName: asset.name, mimeType: asset.mimeType ?? "application/octet-stream", base64, instrument, actor, issuer: "UNKNOWN", certificateNumber: "UNKNOWN", scope: "UNKNOWN", uncertainty: "UNKNOWN" }, { onSuccess: (item) => { setNotice(`Stored certificate ${item.certificateId} · SHA-256 ${item.fileHash.slice(0, 16)}… · UNVERIFIED.`); void certificates.refetch(); }, onError: (error) => setNotice(error.message) }); } catch (error) { setNotice(error instanceof Error ? error.message : "Certificate attachment failed."); } };
  const checkCertificate = () => { const certificate = certificates.data?.[0]; if (!project || !reviewer || !certificate) return; verifyCertificate.mutate({ ...access, certificateId: certificate.certificateId, reviewerId: reviewer.reviewerId, sourceVerified: false, signatureVerified: false, scopeMatch: false, reason }, { onSuccess: (item) => { setNotice(`Certificate verification is ${item.status}; metadata was not converted into source or signature proof.`); void certificates.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const checkAdapter = () => { if (!project || !reviewer || !adapter) return; verifyTrust.mutate({ ...access, registrationId: adapter.registrationId, reviewerId: reviewer.reviewerId, manifestVerified, signatureVerified, verifiedCapabilities: capabilities.split(";").map((item) => item.trim()).filter(Boolean), grantedPermissions: ["READ_CAD", "READ_REQUIREMENTS", "READ_MATERIAL_EVIDENCE", "READ_CAE_PLAN"], sandbox: { sandboxType: "DECLARATION_ONLY", networkPolicy: "NO_NETWORK", resourceLimits: ["No runtime provisioned"], allowedInputs: ["Declared evidence only"], allowedOutputs: ["No output in this phase"] }, reason }, { onSuccess: (item) => { setNotice(`Adapter trust is ${item.trustState}; executable remains ${String(item.executable)}.`); void trust.refetch(); void eligibility.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const approveAdapter = () => { const verification = trust.data?.[0]; if (!project || !reviewer || !adapter || !verification) return; approve.mutate({ ...access, reviewerId: reviewer.reviewerId, targetType: "ADAPTER", targetId: adapter.registrationId, decision: "APPROVE", evidenceIds: [verification.verificationId], revision: 1, reason }, { onSuccess: () => { setNotice("Verified human approval recorded. Conceptual eligibility may change; execution remains permanently unavailable in this phase."); void eligibility.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const revokeAdapter = () => { if (!project || !adapter) return; revoke.mutate({ ...access, objectType: "ADAPTER", objectId: adapter.registrationId, actor, reason }, { onSuccess: () => { setNotice("Adapter revoked. Historic records remain immutable and new eligibility is false."); void eligibility.refetch(); void audits.refetch(); }, onError: (error) => setNotice(error.message) }); };
  const inspectGraph = () => { if (!project) return; graph.mutate({ ...access, simulationId }, { onSuccess: (item) => setGraphSummary(`${item.nodes.length} nodes · ${item.edges.length} explicit links · ${item.limitations.at(-1)}`), onError: (error) => setNotice(error.message) }); };
  return <View style={styles.wrap}>
    <View style={styles.alert}><Text style={styles.kicker}>SOLVER TRUST · SECURITY FOUNDATION</Text><Text style={styles.copy}>`EXECUTION_ELIGIBLE` is a future trust gate only. This app still has no solver runtime, mesher, shell, arbitrary plugin, network, or unrestricted filesystem capability.</Text><Badge value={eligibility.data?.trustState ?? "UNTRUSTED"} /><Text style={styles.meta}>Executable: {String(eligibility.data?.executable ?? false)} · {eligibility.data?.reason ?? "No adapter selected."}</Text></View>
    <View style={styles.card}><Text style={styles.kicker}>REVIEWER IDENTITY & AUTHORIZATION</Text><TextInput value={name} onChangeText={setName} style={styles.input} placeholder="Reviewer" placeholderTextColor="#71828B" /><TextInput value={role} onChangeText={setRole} style={styles.input} placeholder="Role" placeholderTextColor="#71828B" /><TextInput value={actor} onChangeText={setActor} style={styles.input} placeholder="Actor" placeholderTextColor="#71828B" /><Pressable style={styles.primary} disabled={!project || registerReviewer.isPending} onPress={createReviewer}><Text style={styles.primaryText}>REGISTER UNVERIFIED REVIEWER</Text></Pressable>{reviewer ? <View style={styles.record}><Text style={styles.recordTitle}>{reviewer.displayName} · {reviewer.role}</Text><Badge value={reviewer.status} /></View> : null}<TextInput value={method} onChangeText={setMethod} style={styles.input} placeholder="Verification method" placeholderTextColor="#71828B" /><Pressable style={styles.secondary} disabled={!reviewer || verifyReviewer.isPending} onPress={verifyIdentity}><Text style={styles.secondaryText}>VERIFY SELECTED REVIEWER</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.kicker}>CALIBRATION CERTIFICATE EVIDENCE</Text><TextInput value={instrument} onChangeText={setInstrument} style={styles.input} placeholder="Instrument" placeholderTextColor="#71828B" /><Pressable style={styles.primary} disabled={!project || attachCertificate.isPending} onPress={attachCert}>{attachCertificate.isPending ? <ActivityIndicator color="#F3F1EA" /> : <Text style={styles.primaryText}>ATTACH CERTIFICATE</Text>}</Pressable>{certificates.data?.slice(0, 2).map((item) => <View key={item.certificateId} style={styles.record}><Text style={styles.recordTitle}>{item.instrument} · SHA-256 {item.fileHash.slice(0, 12)}…</Text><Badge value={item.status} /></View>)}<Pressable style={styles.secondary} disabled={!reviewer || !certificates.data?.length || verifyCertificate.isPending} onPress={checkCertificate}><Text style={styles.secondaryText}>RUN EVIDENCE CHECKS (NO AUTO-VALID)</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.kicker}>ADAPTER MANIFEST, CAPABILITIES & SANDBOX</Text>{adapter ? <><Text style={styles.recordTitle}>{adapter.solverName} · {adapter.version} · {adapter.provider}</Text><Text style={styles.meta}>Publisher identity: {adapter.publisherIdentity} · signature: {adapter.signature ? "PRESENT, NOT TRUSTED" : "MISSING"}</Text><Text style={styles.meta}>Declared capabilities: {adapter.capabilities.join(" · ") || "none"}</Text><Text style={styles.meta}>Permissions: READ_CAD · READ_REQUIREMENTS · READ_MATERIAL_EVIDENCE · READ_CAE_PLAN. Network, arbitrary filesystem, and shell remain prohibited.</Text><TextInput value={capabilities} onChangeText={setCapabilities} style={styles.input} placeholder="Verified capabilities; separated by semicolons" placeholderTextColor="#71828B" /><View style={styles.row}><Pressable style={[styles.choice, manifestVerified && styles.choiceOn]} onPress={() => setManifestVerified((value) => !value)}><Text style={styles.choiceText}>MANIFEST {manifestVerified ? "ASSERTED" : "UNVERIFIED"}</Text></Pressable><Pressable style={[styles.choice, signatureVerified && styles.choiceOn]} onPress={() => setSignatureVerified((value) => !value)}><Text style={styles.choiceText}>SIGNATURE {signatureVerified ? "ASSERTED" : "UNVERIFIED"}</Text></Pressable></View><TextInput value={reason} onChangeText={setReason} style={styles.input} placeholder="Human evidence reason" placeholderTextColor="#71828B" /><Pressable style={styles.secondary} disabled={!reviewer || verifyTrust.isPending} onPress={checkAdapter}><Text style={styles.secondaryText}>RECORD TRUST-GATE EVIDENCE</Text></Pressable>{trust.data?.[0] ? <Text style={styles.meta}>Latest gates: identity {trust.data[0].identityCheck} · manifest {trust.data[0].manifestValidation} · signature {trust.data[0].signatureCheck} · capability {trust.data[0].capabilityCheck} · permission {trust.data[0].permissionCheck}</Text> : null}<Pressable style={styles.secondary} disabled={!reviewer || !trust.data?.length || approve.isPending} onPress={approveAdapter}><Text style={styles.secondaryText}>RECORD VERIFIED HUMAN APPROVAL</Text></Pressable><Pressable style={styles.danger} disabled={revoke.isPending} onPress={revokeAdapter}><Text style={styles.dangerText}>REVOKE ADAPTER</Text></Pressable></> : <Text style={styles.meta}>No adapter has been registered. Registration remains non-executable and must precede trust verification.</Text>}</View>
    <View style={styles.card}><Text style={styles.kicker}>IMMUTABLE SECURITY AUDIT & TRUST GRAPH</Text><Pressable style={styles.secondary} disabled={!project || graph.isPending} onPress={inspectGraph}><Text style={styles.secondaryText}>INSPECT TRUST GRAPH</Text></Pressable>{graphSummary ? <Text style={styles.meta}>{graphSummary}</Text> : null}{audits.data?.slice(0, 4).map((item) => <View key={item.eventId} style={styles.record}><Text style={styles.recordTitle}>{item.action} · {item.objectType}</Text><Text style={styles.meta}>{item.newState} · {item.actor}</Text></View>)}</View>
    <Text style={styles.notice}>{notice}</Text>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, alert: { backgroundColor: "#33251D", borderColor: "#9A6843", borderWidth: 1, borderRadius: 12, padding: 11, gap: 6 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, kicker: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, meta: { color: "#90A0A8", fontSize: 8, lineHeight: 13 }, input: { color: "#F3F1EA", backgroundColor: "#111C22", borderColor: "#34434B", borderWidth: 1, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 7, fontSize: 9 }, primary: { backgroundColor: "#1167B1", minHeight: 40, justifyContent: "center", alignItems: "center", borderRadius: 9 }, primaryText: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, secondary: { borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 6, alignSelf: "flex-start" }, secondaryText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, danger: { borderColor: "#E78966", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 6, alignSelf: "flex-start" }, dangerText: { color: "#E78966", fontSize: 8, fontWeight: "900" }, record: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, borderTopWidth: 1, borderTopColor: "#2B3A41", paddingTop: 7 }, recordTitle: { color: "#F3F1EA", fontSize: 9, fontWeight: "800", flex: 1 }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3, alignSelf: "flex-start" }, badgeText: { fontSize: 7, fontWeight: "900" }, row: { flexDirection: "row", gap: 6, flexWrap: "wrap" }, choice: { borderColor: "#34434B", borderWidth: 1, borderRadius: 7, paddingHorizontal: 7, paddingVertical: 5 }, choiceOn: { borderColor: "#5B9DCA", backgroundColor: "#1E3A4A" }, choiceText: { color: "#B5C8D0", fontSize: 7, fontWeight: "800" }, notice: { color: "#8EC4E8", fontSize: 8, lineHeight: 13, textAlign: "center" } });
