import { useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

function tone(value?: string) { if (["VERIFIED", "VALID", "FRESH"].includes(value ?? "")) return "#62B39A"; if (["CONFLICT", "STALE", "INVALID", "REJECTED", "REVOKED"].includes(value ?? "")) return "#E78966"; return "#8EC4E8"; }
function Badge({ value }: { value: string }) { const color = tone(value); return <View style={[styles.badge, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.badgeText, { color }]}>{value}</Text></View>; }
function Detail({ label, value }: { label: string; value?: string | number }) { return <View style={styles.detail}><Text style={styles.label}>{label}</Text><Text style={styles.detailValue} numberOfLines={2}>{value === undefined ? "UNKNOWN" : String(value)}</Text></View>; }

export function SolverInputPackageInspector() {
  const [project, setProject] = useState<StoredProjectAccess>(); const [cadRevision, setCadRevision] = useState(""); const [cadHash, setCadHash] = useState(""); const [jobRevision, setJobRevision] = useState(""); const [meshId, setMeshId] = useState(""); const [meshHash, setMeshHash] = useState(""); const [graphSummary, setGraphSummary] = useState<string>();
  useEffect(() => { let cancelled = false; const hydrate = async () => { const value = await loadProjectAccess("active-engineering-workbench"); if (!cancelled && value) setProject(value); }; void hydrate(); const interval = setInterval(() => void hydrate(), 1_000); return () => { cancelled = true; clearInterval(interval); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" }; const filters = { ...access, cadRevision: cadRevision || undefined, cadGeometryHash: cadHash || undefined, jobRevision: jobRevision ? Number(jobRevision) : undefined, meshId: meshId || undefined, meshHash: meshHash || undefined }; const packages = trpc.cae.listSolverInputPackages.useQuery(filters, { enabled: Boolean(project) }); const verifications = trpc.cae.listMeshQualityVerifications.useQuery(access, { enabled: Boolean(project) }); const graph = trpc.cae.solverInputPackageGraph.useMutation(); const selected = packages.data?.[0]; const latestVerification = useMemo(() => selected?.meshQualityVerificationId ? verifications.data?.find((item) => item.verificationId === selected.meshQualityVerificationId) : undefined, [selected, verifications.data]);
  const clear = () => { setCadRevision(""); setCadHash(""); setJobRevision(""); setMeshId(""); setMeshHash(""); setGraphSummary(undefined); };
  const inspectGraph = () => { if (!selected) return; graph.mutate({ ...access, packageId: selected.packageId }, { onSuccess: (value) => setGraphSummary(`${value.nodes.length} nodes · ${value.edges.length} links · ${value.limitations[0]}`) }); };
  return <View style={styles.wrap}>
    <View style={styles.hero}><View style={{ flex: 1 }}><Text style={styles.kicker}>PHASE 6.7 · SOLVER INPUT PACKAGE FOUNDATION</Text><Text style={styles.title}>Immutable package provenance, never execution</Text><Text style={styles.copy}>Packages contain only bounded immutable references, hashes, validation evidence, and declared configuration identity. This panel cannot create, write, execute, transmit, or run a solver package.</Text></View><Badge value="NON-EXECUTABLE" /></View>
    <View style={styles.card}><View style={styles.row}><Text style={styles.kicker}>READ-ONLY REVISION FILTERS</Text><Pressable style={styles.clear} onPress={clear}><Text style={styles.clearText}>CLEAR</Text></Pressable></View><View style={styles.filterGrid}><TextInput style={styles.input} value={cadRevision} onChangeText={setCadRevision} placeholder="CAD revision" placeholderTextColor="#77909A" autoCapitalize="characters" /><TextInput style={styles.input} value={cadHash} onChangeText={setCadHash} placeholder="CAD hash" placeholderTextColor="#77909A" autoCapitalize="none" /><TextInput style={styles.input} value={jobRevision} onChangeText={setJobRevision} placeholder="CAE job revision" placeholderTextColor="#77909A" keyboardType="number-pad" /><TextInput style={styles.input} value={meshId} onChangeText={setMeshId} placeholder="Mesh revision / ID" placeholderTextColor="#77909A" autoCapitalize="characters" /><TextInput style={styles.input} value={meshHash} onChangeText={setMeshHash} placeholder="Mesh hash" placeholderTextColor="#77909A" autoCapitalize="none" /></View><Text style={styles.meta}>Filters only select immutable records. They do not modify package state, evidence, CAD, job, or mesh history. Empty fields mean no restriction.</Text></View>
    <View style={styles.card}><View style={styles.row}><View><Text style={styles.kicker}>SOLVER INPUT PACKAGE MANIFEST</Text><Text style={styles.value}>{selected?.packageId ?? "NO MATCHING PACKAGE"}</Text></View><Badge value={selected?.status ?? "UNKNOWN"} /></View>{selected ? <><Detail label="MANIFEST HASH" value={selected.manifestHash} /><Detail label="JOB / CAD / MESH" value={`${selected.jobId} rev ${selected.jobRevision} · ${selected.cadRevision} · ${selected.meshArtifactId}`} /><Detail label="IDENTITIES" value={`${selected.cadGeometryHash} · ${selected.meshHash} · ${selected.materialEvidenceHash}`} /><Detail label="SOLVER CONFIGURATION" value={`${selected.solverReference} · ${selected.solverConfiguration.configurationReference} · declared-only`} /><Detail label="UNITS" value={selected.units.join(" · ")} /><Detail label="STATUS" value={`${selected.status} · executionEligible=${String(selected.executionEligible)} · executable=${String(selected.executable)}`} /><Text style={styles.meta}>A package may be VERIFIED only with independently verified mesh-quality evidence. VERIFIED does not authorize input generation or execution.</Text></> : <Text style={styles.meta}>No matching package exists. This interface will not synthesize a package, mesh, solver configuration, hash, material, load, boundary condition, contact, or verification claim.</Text>}</View>
    <View style={styles.grid}><View style={styles.card}><Text style={styles.kicker}>INDEPENDENT MESH QUALITY VERIFICATION</Text><Text style={styles.value}>{latestVerification?.verificationId ?? "NOT VERIFIED"}</Text><Badge value={latestVerification?.status ?? "NOT_VERIFIED"} />{latestVerification ? <><Detail label="SUBMITTER ≠ VERIFIER" value={`${latestVerification.submitter} → ${latestVerification.verifierIdentity}`} /><Detail label="METHOD / VERSION" value={`${latestVerification.verificationMethod} · ${latestVerification.verificationVersion}`} /><Detail label="BOUND EVIDENCE" value={latestVerification.evidenceHash} /><Text style={styles.meta}>Verified identity and separation are required. System-generated mesh metrics never become VERIFIED automatically.</Text></> : <Text style={styles.meta}>No independent verification is bound to the selected package. Unknown mesh quality is not silently treated as valid or executable.</Text>}</View><View style={styles.card}><Text style={styles.kicker}>INTEGRITY, STALENESS & CONFLICTS</Text><Text style={styles.copy}>{selected ? `Stale reasons: ${selected.staleReasons.join(" · ") || "none recorded"}` : "No manifest selected."}</Text><Text style={styles.copy}>{selected ? `Conflicts: ${selected.conflicts.join(" · ") || "none recorded"}` : ""}</Text><Text style={styles.meta}>Any CAD revision/hash, job revision, mesh ID/hash, material evidence, or verification identity mismatch makes the package STALE or UNKNOWN. Historical manifests are never silently updated.</Text></View></View>
    <View style={styles.card}><Text style={styles.kicker}>TRACEABILITY & SECURITY BOUNDARY</Text><Text style={styles.copy}>{selected ? selected.traceability.map((link) => `${link.from} → ${link.to}`).join(" · ") : "Requirement → CAD Revision → CAE Plan → CAE Job → Mesh → Mesh Quality → Solver Input Package"}</Text><Text style={styles.meta}>Prohibited: arbitrary commands, executables, filesystem paths, network destinations, credentials, and environment secrets. References are immutable; status never enables execution.</Text><Pressable disabled={!selected || graph.isPending} style={[styles.inspect, !selected && styles.disabled]} onPress={inspectGraph}><Text style={styles.inspectText}>{graph.isPending ? "INSPECTING…" : "INSPECT PACKAGE TRACEABILITY"}</Text></Pressable>{graphSummary ? <Text style={styles.meta}>{graphSummary}</Text> : null}</View>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 10 }, hero: { backgroundColor: "#1A2933", borderWidth: 1, borderColor: "#2F4652", borderRadius: 14, padding: 14, flexDirection: "row", gap: 10 }, kicker: { color: "#8EC4E8", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, title: { color: "#F3F1EA", fontSize: 15, fontWeight: "900", marginTop: 4 }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15, marginTop: 6 }, meta: { color: "#90A0A8", fontSize: 9, lineHeight: 14, marginTop: 6 }, value: { color: "#F3F1EA", fontSize: 11, fontWeight: "900", marginTop: 4 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 12, gap: 5 }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, filterGrid: { gap: 6, marginTop: 5 }, input: { color: "#E4EBED", backgroundColor: "#101B21", borderColor: "#36505C", borderWidth: 1, borderRadius: 7, paddingHorizontal: 9, paddingVertical: 7, fontSize: 10 }, clear: { borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, clearText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 7, paddingVertical: 4, alignSelf: "flex-start" }, badgeText: { fontSize: 8, fontWeight: "900" }, detail: { marginTop: 4, gap: 2 }, label: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.6 }, detailValue: { color: "#D7E0E3", fontSize: 9, lineHeight: 13 }, grid: { gap: 8 }, inspect: { marginTop: 7, borderColor: "#5B9DCA", borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 7, alignSelf: "flex-start" }, inspectText: { color: "#8EC4E8", fontSize: 8, fontWeight: "900" }, disabled: { opacity: 0.42 } });
