import { FlatList, StyleSheet, Text, View } from "react-native";

type Gate = { id: string; title: string; state: "INFRASTRUCTURE_BLOCKED" | "BLOCKED" | "EXECUTION_UNAVAILABLE" | "EVIDENCE_INSUFFICIENT" | "UNKNOWN" | "NOT_READY"; evidence: string; missing: string };

const gates: Gate[] = [
  { id: "G1", title: "Approved isolated sandbox", state: "INFRASTRUCTURE_BLOCKED", evidence: "Policy, rubric, and attestation contracts only.", missing: "Approved environment ID, enforced configuration, observed controls, independent attestation." },
  { id: "G2", title: "Sandbox escape resistance", state: "BLOCKED", evidence: "Defensive test schemas only.", missing: "Segregated campaign, raw evidence, hashes, independent review." },
  { id: "G3", title: "Gmsh adapter execution", state: "EXECUTION_UNAVAILABLE", evidence: "No Gmsh executable was found on the workspace path.", missing: "Approved environment, pinned artifact/SBOM, mesh receipt, independent mesh verification." },
  { id: "G4", title: "CalculiX adapter execution", state: "EXECUTION_UNAVAILABLE", evidence: "No CalculiX or ccx executable was found on the workspace path.", missing: "Approved environment, pinned artifact/SBOM, benchmark receipt, independent reference comparison." },
  { id: "G5", title: "Numerical correctness", state: "EVIDENCE_INSUFFICIENT", evidence: "Result-trust contracts exist; no observed numerical output exists.", missing: "Reference, solver value, tolerance, units, checks, convergence/sensitivity evidence." },
  { id: "G6", title: "Result integrity and recovery", state: "BLOCKED", evidence: "Binding and failure-model contracts exist.", missing: "Raw result, receipt, parser evidence, corruption/partial-output and recovery observations." },
  { id: "G7", title: "Reproducibility and independent review", state: "BLOCKED", evidence: "Retention, reviewer, revocation, and review controls exist.", missing: "Repeated real runs and a complete independently reviewed evidence package." },
  { id: "G8", title: "Production readiness", state: "NOT_READY", evidence: "Existing planning, trust, audit, and governance foundations remain non-executable.", missing: "Every critical gate above must have current, valid, independent observed evidence." },
];

function color(state: Gate["state"]) { return state === "NOT_READY" || state === "BLOCKED" || state === "INFRASTRUCTURE_BLOCKED" || state === "EXECUTION_UNAVAILABLE" ? "#E78966" : state === "EVIDENCE_INSUFFICIENT" ? "#E8B65D" : "#8EC4E8"; }

export function StrictRuntimeReadinessPanel() {
  return <View style={styles.wrap} accessibilityLabel="Strict runtime readiness dashboard">
    <View style={styles.hero}><Text style={styles.kicker}>STRICT RUNTIME SECURITY REVIEW</Text><Text style={styles.title}>Production CAE execution is not ready</Text><Text style={styles.copy}>This is a fail-closed evidence dashboard, not a test launcher. It reports only current review observations. It does not create a sandbox, execute a hostile test, invoke Gmsh or CalculiX, generate a mesh, run a solver, read a result, or promote any numerical value.</Text><View style={styles.decision}><Text style={styles.decisionLabel}>FINAL DECISION</Text><Text style={styles.decisionValue}>NOT_READY · EXECUTION_UNAVAILABLE</Text></View></View>
    <View style={styles.notice}><Text style={styles.kicker}>SEPARATED TEST ENVIRONMENT REQUIRED</Text><Text style={styles.copy}>The next permissible action is independent authorization of a segregated test environment. Do not treat this workspace, a user computer, or a policy record as sandbox-test evidence.</Text></View>
    <FlatList data={gates} scrollEnabled={false} keyExtractor={(item) => item.id} renderItem={({ item }) => { const tint = color(item.state); return <View style={styles.card}><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.gate}>{item.id} · {item.title}</Text><Text style={styles.meta}>Observed: {item.evidence}</Text><Text style={styles.missing}>Missing: {item.missing}</Text></View><View style={[styles.badge, { borderColor: tint, backgroundColor: `${tint}18` }]}><Text style={[styles.badgeText, { color: tint }]}>{item.state.replaceAll("_", " ")}</Text></View></View></View>; }} />
    <View style={styles.footer}><Text style={styles.kicker}>NO PASS WITHOUT OBSERVED EVIDENCE</Text><Text style={styles.copy}>A future pass requires a control/test ID, expected and observed behavior, raw evidence and hash, timestamp, environment ID, independent reviewer, current validity, and immutable provenance. Critical `UNKNOWN`, `BLOCKED`, `FAIL`, expired, revoked, or contradictory evidence retains `NOT_READY`.</Text></View>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, hero: { backgroundColor: "#302222", borderColor: "#9A5F55", borderWidth: 1, borderRadius: 13, padding: 13, gap: 6 }, notice: { backgroundColor: "#3A2A1C", borderColor: "#73512E", borderWidth: 1, borderRadius: 11, padding: 11, gap: 4 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 11, padding: 11, marginBottom: 7 }, row: { flexDirection: "row", gap: 9, alignItems: "flex-start" }, kicker: { color: "#9DAEB6", fontSize: 8, letterSpacing: 0.9, fontWeight: "900" }, title: { color: "#F3F1EA", fontSize: 15, fontWeight: "900" }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, decision: { backgroundColor: "#E7896618", borderColor: "#E78966", borderWidth: 1, borderRadius: 9, padding: 9, gap: 2 }, decisionLabel: { color: "#E9B198", fontSize: 8, fontWeight: "900" }, decisionValue: { color: "#E78966", fontSize: 11, fontWeight: "900" }, gate: { color: "#F3F1EA", fontSize: 10, lineHeight: 14, fontWeight: "900" }, meta: { color: "#9AAAB1", fontSize: 9, lineHeight: 13, marginTop: 4 }, missing: { color: "#E9B198", fontSize: 9, lineHeight: 13, marginTop: 4 }, badge: { maxWidth: 114, borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 4 }, badgeText: { fontSize: 7, lineHeight: 9, fontWeight: "900", textAlign: "center" }, footer: { backgroundColor: "#172932", borderColor: "#315063", borderWidth: 1, borderRadius: 11, padding: 11, gap: 4 } });
