import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";

import { loadProjectAccess, type StoredProjectAccess } from "@/lib/project-memory";
import { trpc } from "@/lib/trpc";

const GATES = ["IDENTITY", "ADAPTER_SIGNATURE", "CAPABILITY", "PERMISSIONS", "CERTIFICATE", "REVIEWER_APPROVAL", "SANDBOX_ATTESTATION", "REVOCATION_CHECK", "EXECUTION_ELIGIBILITY"] as const;
function tint(status: string) { return status === "PASS" ? "#62B39A" : status === "FAIL" ? "#E78966" : "#8EC4E8"; }
function GateStatus({ status }: { status: "PASS" | "FAIL" | "UNKNOWN" }) { const color = tint(status); return <View style={[styles.status, { borderColor: color, backgroundColor: `${color}18` }]}><Text style={[styles.statusText, { color }]}>{status}</Text></View>; }

export function TrustReadinessPanel({ simulationId }: { simulationId: string }) {
  const [project, setProject] = useState<StoredProjectAccess>(); const [notice, setNotice] = useState("No readiness record exists. Every mandatory gate is UNKNOWN and execution is disabled.");
  useEffect(() => { let stopped = false; const load = async () => { const current = await loadProjectAccess("active-engineering-workbench"); if (!stopped && current) setProject(current); }; void load(); const timer = setInterval(() => void load(), 1_000); return () => { stopped = true; clearInterval(timer); }; }, []);
  const access = { projectId: project?.projectId ?? "UNAVAILABLE", accessKey: project?.accessKey ?? "UNAVAILABLE" };
  const adapters = trpc.cae.listExternalSolverAdapters.useQuery(access, { enabled: Boolean(project) }); const identities = trpc.cae.listExternalIdentityClaims.useQuery(access, { enabled: Boolean(project) }); const certificates = trpc.cae.listCalibrationCertificates.useQuery(access, { enabled: Boolean(project) }); const attestations = trpc.cae.listSandboxAttestations.useQuery(access, { enabled: Boolean(project) }); const adapter = adapters.data?.[0]; const readiness = trpc.cae.listExecutionTrustReadiness.useQuery({ ...access, registrationId: adapter?.registrationId }, { enabled: Boolean(project && adapter) }); const evaluate = trpc.cae.evaluateExecutionTrustReadiness.useMutation();
  const current = readiness.data?.[0]; const gates = current?.gates ?? GATES.map((gate) => ({ gate, status: "UNKNOWN" as const, statement: "No readiness evaluation has been recorded.", evidenceIds: [], mandatory: true as const }));
  const run = () => { if (!project || !adapter) return; evaluate.mutate({ ...access, registrationId: adapter.registrationId, externalIdentityClaimId: identities.data?.[0]?.claimId, certificateId: certificates.data?.[0]?.certificateId, attestationId: attestations.data?.[0]?.attestationId }, { onSuccess: (item) => { setNotice(item.reason); void readiness.refetch(); }, onError: (error) => setNotice(error.message) }); };
  return <View style={styles.wrap} accessibilityLabel="Execution trust readiness">
    <View style={styles.hero}><Text style={styles.kicker}>PHASE 5.4 · TRUST READINESS</Text><Text style={styles.title}>Nine evidence gates, evaluated individually</Text><Text style={styles.copy}>No combined trusted badge is shown. Missing, unknown, invalid, expired, or revoked evidence fails closed. The final execution gate is deliberately FAIL: Phase 5.4 includes no solver, mesher, plugin runtime, shell, process, arbitrary network, or arbitrary filesystem capability.</Text><View style={styles.execution}><Text style={styles.executionLabel}>EXECUTION_ELIGIBLE</Text><Text style={styles.executionValue}>FALSE</Text><Text style={styles.meta}>Executable: false</Text></View></View>
    <View style={styles.card}><Text style={styles.kicker}>GATE EVIDENCE</Text>{gates.map((item) => <View key={item.gate} style={styles.gate}><View style={styles.gateBody}><Text style={styles.gateName}>{item.gate}</Text><Text style={styles.gateReason}>{item.statement}</Text>{item.evidenceIds.length ? <Text style={styles.evidence}>Evidence: {item.evidenceIds.slice(0, 3).join(" · ")}</Text> : <Text style={styles.evidence}>Evidence: none</Text>}</View><GateStatus status={item.status} /></View>)}</View>
    <View style={styles.card}><Text style={styles.kicker}>FAIL-CLOSED EVALUATION</Text><Text style={styles.meta}>{adapter ? `${adapter.solverName} · ${adapter.version}` : "No registered adapter is available; evaluation remains UNKNOWN."}</Text><Pressable style={({ pressed }) => [styles.button, (!project || !adapter || evaluate.isPending) && styles.disabled, pressed && styles.pressed]} disabled={!project || !adapter || evaluate.isPending} onPress={run}>{evaluate.isPending ? <ActivityIndicator color="#F3F1EA" /> : <Text style={styles.buttonText}>EVALUATE ALL NINE GATES</Text>}</Pressable><Text style={styles.notice}>{notice}</Text><Text style={styles.meta}>Simulation context: {simulationId}. This records evidence readiness only and cannot start execution.</Text></View>
  </View>;
}

const styles = StyleSheet.create({ wrap: { gap: 9 }, hero: { backgroundColor: "#33251D", borderColor: "#9A6843", borderWidth: 1, borderRadius: 12, padding: 12, gap: 6 }, card: { backgroundColor: "#192831", borderColor: "#2F4652", borderWidth: 1, borderRadius: 12, padding: 11, gap: 7 }, kicker: { color: "#9DAEB6", fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, title: { color: "#F3F1EA", fontSize: 14, fontWeight: "900" }, copy: { color: "#D7E0E3", fontSize: 10, lineHeight: 15 }, execution: { borderColor: "#E78966", backgroundColor: "#E7896618", borderWidth: 1, borderRadius: 9, padding: 9, gap: 2 }, executionLabel: { color: "#E9B198", fontSize: 8, fontWeight: "900", letterSpacing: 0.7 }, executionValue: { color: "#E78966", fontSize: 16, fontWeight: "900" }, meta: { color: "#90A0A8", fontSize: 8, lineHeight: 13 }, gate: { flexDirection: "row", gap: 8, alignItems: "flex-start", borderTopColor: "#2B3A41", borderTopWidth: 1, paddingTop: 8 }, gateBody: { flex: 1, gap: 2 }, gateName: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, gateReason: { color: "#B5C8D0", fontSize: 8, lineHeight: 12 }, evidence: { color: "#71828B", fontSize: 7, lineHeight: 11 }, status: { minWidth: 57, alignItems: "center", borderWidth: 1, borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3 }, statusText: { fontSize: 7, fontWeight: "900" }, button: { backgroundColor: "#1167B1", minHeight: 40, borderRadius: 9, alignItems: "center", justifyContent: "center" }, buttonText: { color: "#F3F1EA", fontSize: 9, fontWeight: "900" }, notice: { color: "#8EC4E8", fontSize: 8, lineHeight: 13 }, disabled: { opacity: 0.45 }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] } });
