/**
 * Server-only contracts for a controlled CAE runtime. These contracts do not
 * authorize execution by themselves; callers must pass Runtime Admission first.
 */
export type CaeEngineKind = "GMSH" | "CALCULIX";

export type CaeEngineStatus =
  | "READY"
  | "ENGINE_UNAVAILABLE"
  | "ENGINE_INVALID"
  | "ADMISSION_DENIED"
  | "INVALID_INPUT"
  | "REQUIRED_INPUT"
  | "RESOURCE_LIMIT"
  | "EXECUTION_FAILED"
  | "EXECUTION_TIMEOUT"
  | "OUTPUT_INVALID";

export interface EngineResourceLimits {
  timeoutMs: number;
  maxMemoryMb: number;
  maxCpuSeconds: number;
  maxDiskMb: number;
  networkDisabled: true;
}

export interface EngineIdentity {
  kind: CaeEngineKind;
  executablePath: string;
  version: string;
  environmentHash: string;
  capabilities: readonly string[];
}

export interface EngineAvailability {
  status: CaeEngineStatus;
  identity?: EngineIdentity;
  diagnostics: readonly string[];
}

export interface CaeExecutionContext {
  projectId: string;
  authorizedProjectId: string;
  operationAuthorized: boolean;
  cadArtifactHash: string;
  cadRevisionHash: string;
  workingDirectory: string;
  resourceLimits: EngineResourceLimits;
}

export interface MeshRequest {
  /** Server-resolved path to a managed STEP artifact; never client supplied. */
  stepPath: string;
  /** SHA-256 over the exact managed STEP bytes. */
  stepHash: string;
  dimension: 2 | 3;
  elementOrder: 1 | 2;
  globalSize?: number;
  physicalGroups: readonly string[];
  options: Readonly<Record<string, string | number | boolean>>;
}

export interface MeshResult {
  status: CaeEngineStatus;
  meshPath?: string;
  /** Exact generated bytes are held only until the authorized artifact store consumes them. */
  meshBytes?: Buffer;
  meshHash?: string;
  nodeCount?: number;
  elementCount?: number;
  evidence?: GmshExecutionEvidence;
  diagnostics: readonly string[];
}

export interface GmshExecutionEvidence {
  engine: "GMSH";
  version?: string;
  binaryPath?: string;
  executionStatus: CaeEngineStatus;
  inputHash?: string;
  outputHash?: string;
  durationMs: number;
  exitCode?: number;
  stdoutSummary: string;
  stderrSummary: string;
  cleanupStatus: "NOT_STARTED" | "PASS" | "FAIL";
}

export interface SolverInput {
  analysisType: "STATIC_STRUCTURAL";
  meshHash: string;
  /** Exact managed MSH2 bytes supplied only by the authorized server lifecycle. */
  meshBytes: Uint8Array;
  materialId: string;
  unitSystem: string;
  boundaryConditionIds: readonly string[];
  loadIds: readonly string[];
  material: { elasticModulusPa: number; poissonRatio: number; densityKgM3: number; source: "TEST_FIXTURE" | "APPROVED_EVIDENCE" };
  boundaryCondition: { nodeSet: "ALL" | "BOTTOM_FACE"; constrainedDofs: readonly (1 | 2 | 3)[] };
  load: { nodeSet: "ALL" | "TOP_FACE"; direction: 1 | 2 | 3; magnitudeN: number };
}

export interface SolverResult {
  status: CaeEngineStatus;
  solverInputHash?: string;
  solverOutputHash?: string;
  /** Exact solver bytes are held only until authorized result persistence consumes them. */
  resultBytes?: Buffer;
  evidence?: CalculiXExecutionEvidence;
  resultPaths: readonly string[];
  exitCode?: number;
  diagnostics: readonly string[];
}

export interface CalculiXExecutionEvidence {
  engine: "CALCULIX";
  version?: string;
  executionStatus: CaeEngineStatus;
  meshHash?: string;
  solverInputHash?: string;
  solverOutputHash?: string;
  durationMs: number;
  exitCode?: number;
  stdoutSummary: string;
  stderrSummary: string;
  cleanupStatus: "NOT_STARTED" | "PASS" | "FAIL";
}

export interface ResultReadRequest {
  projectId: string;
  workingDirectory: string;
  outputPath: string;
  expectedOutputHash: string;
  expectedMeshHash: string;
}

export interface ResultReadResult {
  status: CaeEngineStatus;
  resultHash?: string;
  fields: Readonly<Record<string, number>>;
  diagnostics: readonly string[];
}

export interface IMesher {
  readonly kind: "GMSH";
  availability(): Promise<EngineAvailability>;
  mesh(context: CaeExecutionContext, request: MeshRequest): Promise<MeshResult>;
}

export interface ICAEASolver {
  readonly kind: "CALCULIX";
  availability(): Promise<EngineAvailability>;
  solve(context: CaeExecutionContext, input: SolverInput): Promise<SolverResult>;
}

export interface IResultReader {
  read(request: ResultReadRequest): Promise<ResultReadResult>;
}
