import { createHash } from "node:crypto";

import type { CAEEvidenceGraph, CalibrationCandidate, CalibrationRecord, DatasetProcessingRecord, EngineeringReviewDecision, ExternalSolverAdapterRegistration, MeasurementDataset, SimulationMeasurementComparison } from "../shared/cae";
import { getCAEPlan } from "./caeAgent";
import { buildEvidenceGraph } from "./caeEvidence";
import { listCalibrationRecords, listDatasetProcessing, listMeasurementDatasets } from "./caeReconciliation";
import { appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";

type ProjectAccess = { projectId: string; accessKey: string };
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
function parse<T>(content: string): T | undefined { try { return JSON.parse(content) as T; } catch { return undefined; } }
async function authorize(args: ProjectAccess) { return openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function records<T>(args: ProjectAccess, kind: string): Promise<T[]> { await authorize(args); return (await projectMemorySnapshot(args)).records.filter((record) => record.kind === kind).flatMap((record) => { const item = parse<T>(record.content); return item ? [item] : []; }); }

export async function createSimulationMeasurementComparison(args: ProjectAccess & { simulationId: string; datasetId: string; quantity: string; location?: string; timeWindow?: string; measurementValue?: number; uncertainty?: string; comparisonMethod: string }): Promise<SimulationMeasurementComparison> {
  const plan = await getCAEPlan(args); const dataset = (await listMeasurementDatasets(args)).find((item) => item.datasetId === args.datasetId);
  if (!dataset) throw new Error("The measurement dataset is unavailable in the authorized project.");
  if (dataset.simulationId && dataset.simulationId !== plan.simulationId) throw new Error("The measurement dataset is linked to a different simulation in this project. No cross-simulation relationship was created.");
  if (!args.quantity.trim() || !args.comparisonMethod.trim()) throw new Error("A quantity and comparison method are required. Missing values remain unknown rather than inferred.");
  const status = args.measurementValue === undefined ? "MISSING_MEASUREMENT_VALUE" as const : "NO_SIMULATION_RESULT" as const;
  const comparison: SimulationMeasurementComparison = { comparisonId: id("SIMULATION-MEASUREMENT-COMPARISON"), projectId: args.projectId, simulationId: plan.simulationId, simulationRevision: plan.sourceCadRevision, datasetId: dataset.datasetId, quantity: args.quantity.trim(), location: args.location?.trim() || undefined, timeWindow: args.timeWindow?.trim() || undefined, measurementValue: args.measurementValue, uncertainty: args.uncertainty?.trim() || undefined, comparisonMethod: args.comparisonMethod.trim(), status, truthCategory: args.measurementValue === undefined ? "UNKNOWN" : "DERIVED", createdAt: new Date().toISOString() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_COMPARISON", title: `Simulation ↔ measurement comparison · ${comparison.quantity} · ${comparison.status}`, content: JSON.stringify(comparison), truthStatus: "UNKNOWN", validationStage: "CONCEPTUAL", relatedConfigurationId: plan.sourceCadRevision, relatedGeometry: plan.geometryScope.selectedGeometry, authorSource: "USER" } });
  return comparison;
}
export async function listComparisons(args: ProjectAccess & { simulationId?: string }) { return (await records<SimulationMeasurementComparison>(args, "CAE_COMPARISON")).filter((item) => !args.simulationId || item.simulationId === args.simulationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }

export async function createCalibrationCandidate(args: ProjectAccess & { comparisonId: string; statement: string }): Promise<CalibrationCandidate> {
  const comparison = (await records<SimulationMeasurementComparison>(args, "CAE_COMPARISON")).find((item) => item.comparisonId === args.comparisonId);
  if (!comparison) throw new Error("The comparison is unavailable in the authorized project.");
  if (!args.statement.trim()) throw new Error("A calibration candidate requires an explicit human-review statement. No parameter is changed automatically.");
  const candidate: CalibrationCandidate = { candidateId: id("CALIBRATION-CANDIDATE"), projectId: args.projectId, comparisonId: comparison.comparisonId, status: "CALIBRATION_CANDIDATE", statement: args.statement.trim(), requiresHumanReview: true, prohibitsAutomaticParameterChange: true, createdAt: new Date().toISOString() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_CALIBRATION_CANDIDATE", title: `Calibration candidate · ${candidate.comparisonId}`, content: JSON.stringify(candidate), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM" } });
  return candidate;
}

export async function registerExternalSolverAdapter(args: ProjectAccess & Omit<ExternalSolverAdapterRegistration, "registrationId" | "projectId" | "verificationStatus" | "executable" | "revocable" | "createdAt">): Promise<ExternalSolverAdapterRegistration> {
  await authorize(args);
  if (!args.solverId.trim() || !args.solverName.trim() || !args.provider.trim() || !args.adapterVersion.trim() || !args.adapterManifest.trim() || !args.publisherIdentity.trim()) throw new Error("Solver ID, name, provider, adapter version, manifest, and publisher identity are required for registration.");
  const calculatedHash = createHash("sha256").update(args.adapterManifest).digest("hex");
  const status = args.adapterHash === calculatedHash && Boolean(args.signature?.trim()) ? "UNVERIFIED" as const : "REJECTED" as const;
  const registration: ExternalSolverAdapterRegistration = { registrationId: id("SOLVER-ADAPTER-REGISTRATION"), projectId: args.projectId, solverId: args.solverId.trim(), solverName: args.solverName.trim(), version: args.version.trim(), provider: args.provider.trim(), adapterVersion: args.adapterVersion.trim(), supportedAnalysisTypes: args.supportedAnalysisTypes, capabilities: args.capabilities, executionMode: args.executionMode, inputSchemaVersion: args.inputSchemaVersion.trim(), outputSchemaVersion: args.outputSchemaVersion.trim(), securityRequirements: args.securityRequirements, adapterManifest: args.adapterManifest.trim(), adapterHash: args.adapterHash, publisherIdentity: args.publisherIdentity.trim(), signature: args.signature?.trim() || undefined, capabilityManifest: args.capabilityManifest, verificationStatus: status, executable: false, revocable: true, createdAt: new Date().toISOString() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_ADAPTER_REGISTRATION", title: `External solver adapter registration · ${registration.solverName} · ${status}`, content: JSON.stringify(registration), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER" } });
  return registration;
}
export async function listExternalSolverAdapterRegistrations(args: ProjectAccess) { return (await records<ExternalSolverAdapterRegistration>(args, "CAE_ADAPTER_REGISTRATION")).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }

export async function buildExtendedEvidenceGraph(args: ProjectAccess & { simulationId: string }): Promise<CAEEvidenceGraph> {
  const base = await buildEvidenceGraph(args); const datasets = await listMeasurementDatasets({ ...args, simulationId: args.simulationId }); const comparisons = await listComparisons({ ...args, simulationId: args.simulationId }); const processing = (await Promise.all(datasets.map((item) => listDatasetProcessing({ ...args, datasetId: item.datasetId })))).flat(); const calibrations = (await Promise.all(datasets.map((item) => listCalibrationRecords({ ...args, datasetId: item.datasetId })))).flat(); const decisions = await records<EngineeringReviewDecision>(args, "CAE_REVIEW_DECISION"); const adapters = await listExternalSolverAdapterRegistrations(args); const candidates = await records<CalibrationCandidate>(args, "CAE_CALIBRATION_CANDIDATE");
  const nodes = [...base.nodes, ...datasets.map((item) => ({ id: item.datasetId, type: "MEASURED_DATASET" as const, label: item.fileName, truthStatus: item.truthCategory === "MEASURED" ? "VERIFIED" as const : "UNKNOWN" as const })), ...processing.map((item) => ({ id: item.recordId, type: "DATASET_PROCESSING" as const, label: `${item.stage}: ${item.transformation}`, truthStatus: "UNVALIDATED" as const })), ...calibrations.map((item) => ({ id: item.calibrationId, type: "CALIBRATION" as const, label: `${item.instrument} · ${item.status}`, truthStatus: item.status === "CALIBRATED" ? "UNVALIDATED" as const : "UNKNOWN" as const })), ...comparisons.map((item) => ({ id: item.comparisonId, type: "COMPARISON" as const, label: `${item.quantity} · ${item.status}`, truthStatus: "UNKNOWN" as const })), ...decisions.map((item) => ({ id: item.decisionId, type: "ENGINEERING_DECISION" as const, label: `${item.reviewer} · ${item.decision}`, truthStatus: "UNVALIDATED" as const })), ...adapters.map((item) => ({ id: item.registrationId, type: "ADAPTER_REGISTRATION" as const, label: `${item.solverName} · ${item.verificationStatus}`, truthStatus: "UNVALIDATED" as const }))];
  const edges = [...base.edges, ...datasets.flatMap((item) => [ ...(item.experimentId ? [{ id: id("GRAPH"), fromId: item.experimentId, toId: item.datasetId, relationship: "generated dataset", status: "DECLARED" as const }] : []), { id: id("GRAPH"), fromId: item.datasetId, toId: args.simulationId, relationship: "linked measurement evidence", status: item.simulationId === args.simulationId ? "DECLARED" as const : "UNKNOWN" as const } ]), ...processing.map((item) => ({ id: id("GRAPH"), fromId: item.datasetId, toId: item.recordId, relationship: "processed as", status: "DECLARED" as const })), ...calibrations.map((item) => ({ id: id("GRAPH"), fromId: item.datasetId ?? args.simulationId, toId: item.calibrationId, relationship: "calibration evidence", status: item.status === "CALIBRATED" ? "UNKNOWN" as const : "UNKNOWN" as const })), ...comparisons.map((item) => ({ id: id("GRAPH"), fromId: item.datasetId, toId: item.comparisonId, relationship: "compared with simulation", status: "DECLARED" as const })), ...candidates.map((item) => ({ id: id("GRAPH"), fromId: item.comparisonId, toId: item.candidateId, relationship: "creates candidate", status: "DECLARED" as const })), ...decisions.map((item) => ({ id: id("GRAPH"), fromId: item.reconciliationId, toId: item.decisionId, relationship: "reviewed by human", status: "DECLARED" as const })), ...adapters.map((item) => ({ id: id("GRAPH"), fromId: item.registrationId, toId: args.simulationId, relationship: "registration only; not executable", status: "UNKNOWN" as const }))];
  return { ...base, nodes, edges, limitations: [...base.limitations, "Dataset, calibration, comparison, decision, and adapter links are declared only when recorded. No comparison contains a solver result, and registered adapters remain non-executable."] };
}
