import { createHash } from "node:crypto";
import type { AllowlistedSolverArtifact, CADRevisionBinding, CAEEvidenceGraph, CAEJobFailureModel, CAEJobProvenance, CAEJobStalenessAssessment, CAEJobTraceabilityLink, CAEJobVerificationRecord, CanonicalCAEJobContract, FutureCAEJobResultArtifact, NonExecutableMeshArtifact } from "../shared/cae";
import { appendTrustSecurityAudit } from "./caeTrust";
import { appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";

type Access = { projectId: string; accessKey: string };
type ContractInput = Omit<CanonicalCAEJobContract, "jobId" | "projectId" | "contractVersion" | "revision" | "revisionOf" | "contractHash" | "lifecycleState" | "readinessState" | "executionEligible" | "executable" | "createdAt" | "provenance"> & { provenance: Omit<CAEJobProvenance, "createdAt"> & { createdAt?: string } };
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const now = () => new Date().toISOString();
const parse = <T,>(content: string): T | undefined => { try { return JSON.parse(content) as T; } catch { return undefined; } };
const isHash = (value: string | undefined): value is string => Boolean(value && /^[a-f0-9]{64}$/i.test(value));
const safeReference = (value: string | undefined) => Boolean(value && /^[A-Za-z0-9][A-Za-z0-9._:@-]*$/.test(value));
const requiredVerification = ["INPUT_INTEGRITY", "CAD_IDENTITY", "MESH_IDENTITY", "SOLVER_IDENTITY", "SOLVER_VERSION", "UNITS", "BOUNDARY_CONDITIONS", "MATERIAL", "CONVERGENCE", "WARNINGS", "RESULT_INTEGRITY", "REPRODUCIBILITY"] as const;
const allowedSolverReferences = new Set(["CALCULIX_LINEAR_STATIC_SCHEMA_ONLY"]);

async function authorize(args: Access) { return openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function records<T>(args: Access, kind: string) { await authorize(args); return (await projectMemorySnapshot(args)).records.filter((record) => record.kind === kind).flatMap((record) => { const item = parse<T>(record.content); return item ? [item] : []; }); }
function validate(input: ContractInput) {
  if (input.analysisType !== "STATIC_STRUCTURAL") throw new Error("Phase 6.5 accepts only the explicitly bounded STATIC_STRUCTURAL analysis contract.");
  if (!safeReference(input.cadRevision) || !safeReference(input.requirementRevision) || !safeReference(input.materialReference) || !safeReference(input.meshStrategy.strategyReference) || !safeReference(input.solverReference) || !safeReference(input.environmentReference) || !safeReference(input.resourcePolicy.policyReference)) throw new Error("References must be bounded identifiers; paths, commands, URLs, and executable instructions are not accepted.");
  if (![input.cadGeometryHash, input.materialEvidenceHash, input.meshStrategy.strategyHash, input.resourcePolicy.policyHash, input.provenance.requirementHash].every(isHash)) throw new Error("CAD, material, mesh strategy, resource policy, and requirement provenance hashes must be SHA-256 values.");
  if (!allowedSolverReferences.has(input.solverReference) || !safeReference(input.solverVersion)) throw new Error("Solver reference is not an allowlisted non-executable Phase 6.5 schema reference.");
  if (!input.boundaryConditions.length || !input.loads.length) throw new Error("At least one declared boundary condition and one declared load are required for a canonical static job contract.");
  if (input.boundaryConditions.some((item) => !safeReference(item.boundaryId) || !safeReference(item.geometryReference) || !isHash(item.sourceHash) || (item.magnitude !== undefined && !item.unit))) throw new Error("Boundary conditions require bounded references, source hashes, and units whenever a magnitude is present.");
  if (input.loads.some((item) => !safeReference(item.loadId) || !safeReference(item.geometryReference) || !isHash(item.sourceHash) || !Number.isFinite(item.magnitude) || (item.type === "FORCE" && !["N", "kN"].includes(item.unit)) || (item.type === "PRESSURE" && !["Pa", "MPa"].includes(item.unit)))) throw new Error("Loads require bounded references, SHA-256 sources, finite values, direction, and compatible units.");
  if (input.contacts.some((item) => !safeReference(item.contactId) || !safeReference(item.primaryGeometryReference) || !safeReference(item.secondaryGeometryReference) || !isHash(item.sourceHash))) throw new Error("Contacts require bounded identifiers and source hashes.");
  if (!input.meshStrategy.qualityRequirements.length || input.meshStrategy.status !== "NOT_EXECUTED" || (input.meshStrategy.targetSize !== undefined && (!Number.isFinite(input.meshStrategy.targetSize) || !input.meshStrategy.unit))) throw new Error("Mesh strategy must be NOT_EXECUTED, include quality requirements, and declare a unit for any target size.");
  if (new Set(input.resourcePolicy.constraints).size !== 8 || input.resourcePolicy.constraints.length !== 8) throw new Error("Resource policy must reference all eight capacity constraints exactly once.");
  if (!input.expectedOutputs.includes("SOLVER_LOG") || !input.expectedOutputs.includes("EXECUTION_RECEIPT") || !requiredVerification.every((item) => input.verificationRequirements.includes(item))) throw new Error("Expected outputs and all required verification checks must be declared.");
  if (input.provenance.cadRevision !== input.cadRevision || input.provenance.requirementRevision !== input.requirementRevision || input.provenance.materialReference !== input.materialReference || input.provenance.materialEvidenceHash !== input.materialEvidenceHash || input.provenance.cadGeometryHash !== input.cadGeometryHash || !input.provenance.requirementIds.length || !input.provenance.createdBy.trim() || !input.createdBy.trim()) throw new Error("Provenance must exactly bind the CAD, requirements, material evidence, creator, and contract references.");
}
function makeContract(projectId: string, input: ContractInput, revision: number, revisionOf?: string): CanonicalCAEJobContract { validate(input); const createdAt = now(); const payload = { projectId, input, revision, revisionOf, createdAt }; return { ...input, jobId: id("CAE-JOB"), projectId, contractVersion: "1.0.0", revision, revisionOf, provenance: { ...input.provenance, createdAt }, contractHash: hash(payload), lifecycleState: "VALIDATED", readinessState: "DISABLED", executionEligible: false, executable: false, createdAt }; }
async function requireCadBinding(args: Access, input: ContractInput) { const binding = (await records<CADRevisionBinding>(args, "CAE_CAD_REVISION_BINDING")).find((item) => item.cadBindingId === input.cadBindingId); if (!binding || !input.cadProjectId || binding.cadProjectId !== input.cadProjectId || binding.cadRevision !== input.cadRevision || binding.cadGeometryHash !== input.cadGeometryHash || input.provenance.cadBindingId !== binding.cadBindingId || input.provenance.cadProjectId !== binding.cadProjectId) throw new Error("A canonical CAE job requires a resolvable immutable CAD binding with matching CAD project, revision, geometry hash, and provenance; caller-declared CAD values are insufficient."); return binding; }
export async function submitCAEJobContract(args: Access & { input: ContractInput }) { await authorize(args); await requireCadBinding(args, args.input); const job = makeContract(args.projectId, args.input, 1); await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_CANONICAL_JOB_CONTRACT", title: `CAE job · ${job.jobId} · revision 1 · VALIDATED`, content: JSON.stringify(job), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER", sourceRecordId: job.cadBindingId } }); await appendTrustSecurityAudit(args, { actor: job.createdBy, action: "RUNTIME_ARCHITECTURE_REVIEW", objectType: "RUNTIME_ARCHITECTURE", objectId: job.jobId, newState: "VALIDATED_NON_EXECUTABLE", reason: "CAD-bound canonical CAE Job Contract submitted. It is immutable and has no execution path." }); return job; }
export async function listCAEJobContracts(args: Access) { return (await records<CanonicalCAEJobContract>(args, "CAE_CANONICAL_JOB_CONTRACT")).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
export async function getCAEJobContract(args: Access & { jobId: string }) { return (await listCAEJobContracts(args)).find((item) => item.jobId === args.jobId); }
export async function reviseCAEJobContract(args: Access & { jobId: string; input: ContractInput }) { const prior = await getCAEJobContract(args); if (!prior) throw new Error("The authorized project has no matching CAE Job Contract to revise."); await requireCadBinding(args, args.input); const revision = makeContract(args.projectId, args.input, prior.revision + 1, prior.jobId); await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_CANONICAL_JOB_CONTRACT", title: `CAE job · ${revision.jobId} · revision ${revision.revision} · immutable successor`, content: JSON.stringify(revision), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER", sourceRecordId: prior.jobId } }); await appendTrustSecurityAudit(args, { actor: revision.createdBy, action: "RUNTIME_ARCHITECTURE_REVIEW", objectType: "RUNTIME_ARCHITECTURE", objectId: revision.jobId, previousState: prior.jobId, newState: "REVISED_NON_EXECUTABLE", reason: "A changed input creates a new immutable CAD-bound CAE Job Contract revision; the original is preserved." }); return revision; }
export async function evaluateCAEJobStaleness(args: Access & { jobId: string; observedCadRevision?: string; observedRequirementRevision?: string; observedMaterialEvidenceHash?: string; observedMeshStrategyHash?: string; observedSolverVersion?: string }): Promise<CAEJobStalenessAssessment> { const job = await getCAEJobContract(args); if (!job) throw new Error("CAE Job Contract is unavailable in the authorized project."); const values = [{ dimension: "CAD" as const, expected: job.cadRevision, observed: args.observedCadRevision }, { dimension: "REQUIREMENTS" as const, expected: job.requirementRevision, observed: args.observedRequirementRevision }, { dimension: "MATERIAL_EVIDENCE" as const, expected: job.materialEvidenceHash, observed: args.observedMaterialEvidenceHash }, { dimension: "MESH_STRATEGY" as const, expected: job.meshStrategy.strategyHash, observed: args.observedMeshStrategyHash }, { dimension: "SOLVER_DEFINITION" as const, expected: job.solverVersion, observed: args.observedSolverVersion }]; const checks = values.map((item) => ({ ...item, status: item.observed === undefined ? "UNKNOWN" as const : item.observed === item.expected ? "FRESH" as const : "STALE" as const, reason: item.observed === undefined ? `${item.dimension} observation is unavailable; it is never assumed fresh.` : item.observed === item.expected ? `${item.dimension} matches the immutable job contract.` : `${item.dimension} differs from the immutable job contract.` })); const status = checks.some((item) => item.status === "STALE") ? "STALE" as const : checks.some((item) => item.status === "UNKNOWN") ? "UNKNOWN" as const : "FRESH" as const; const assessment: CAEJobStalenessAssessment = { assessmentId: id("CAE-JOB-STALENESS"), projectId: args.projectId, jobId: job.jobId, checks, status, executionEligible: false, executable: false, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EVIDENCE", title: `CAE job staleness · ${job.jobId} · ${status}`, content: JSON.stringify(assessment), truthStatus: status === "FRESH" ? "DERIVED" : "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM", sourceRecordId: job.jobId } }); return assessment; }
export async function listCAEJobStaleness(args: Access & { jobId?: string }) { return (await records<CAEJobStalenessAssessment>(args, "CAE_EVIDENCE")).filter((item) => Boolean(item.assessmentId && (!args.jobId || item.jobId === args.jobId))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
export async function registerNonExecutableMeshArtifact(args: Access & { input: Omit<NonExecutableMeshArtifact, "meshId" | "projectId" | "jobId" | "artifactHash" | "status" | "executable" | "createdAt"> & { jobId: string } }) { const input = args.input; const job = await getCAEJobContract({ ...args, jobId: input.jobId }); if (!job) throw new Error("Mesh schema registration requires an authorized canonical job."); if (input.sourceCadHash !== job.cadGeometryHash || ![input.coordinatesHash, input.connectivityHash].every(isHash) || !safeReference(input.generatorReference) || !safeReference(input.generatorVersion) || !["NOT_MEASURED", "UNKNOWN"].includes(input.qualitySummary)) throw new Error("Mesh artifact schema is invalid, has stale CAD identity, uses unbounded references, or claims unmeasured quality."); const artifact: NonExecutableMeshArtifact = { ...input, meshId: id("MESH-SCHEMA"), projectId: args.projectId, jobId: job.jobId, artifactHash: hash(input), status: "SCHEMA_REGISTERED", executable: false, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EVIDENCE", title: `Non-executable mesh schema · ${artifact.meshId}`, content: JSON.stringify(artifact), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER", sourceRecordId: job.jobId } }); return artifact; }
export async function registerAllowlistedSolverArtifact(args: Access & { input: Omit<AllowlistedSolverArtifact, "artifactId" | "projectId" | "executable" | "createdAt"> }) { const input = args.input; if (!safeReference(input.solverName) || !safeReference(input.solverVersion) || !isHash(input.artifactHash) || !safeReference(input.source) || !input.licenseReference.trim() || !input.provenance.length) throw new Error("Solver artifact schema requires bounded identity/source values, a SHA-256 hash, license reference, and provenance."); const artifact: AllowlistedSolverArtifact = { ...input, artifactId: id("SOLVER-SCHEMA"), projectId: args.projectId, executable: false, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EVIDENCE", title: `Non-executable solver artifact · ${artifact.solverName} · ${artifact.allowlistStatus}`, content: JSON.stringify(artifact), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); return artifact; }
export async function registerFutureCAEJobResultArtifact(args: Access & { input: Omit<FutureCAEJobResultArtifact, "resultId" | "projectId" | "numericalResults" | "verificationStatus" | "createdAt"> }) { const input = args.input; const job = await getCAEJobContract({ ...args, jobId: input.jobId }); if (!job) throw new Error("Future result schema requires an authorized canonical job; orphan results are rejected."); if (input.solverReference !== job.solverReference || ![input.inputHash, input.meshHash, input.resultHash].every(isHash) || !["NOT_AVAILABLE", "UNKNOWN"].includes(input.convergenceStatus) || !input.provenance.length) throw new Error("Future result schema is invalid, attempts to claim solver behavior without an approved runtime receipt, has mismatched identity, or lacks hash/provenance evidence."); const artifact: FutureCAEJobResultArtifact = { ...input, resultId: id("RESULT-SCHEMA"), projectId: args.projectId, verificationStatus: "NOT_VERIFIED", numericalResults: [], createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EVIDENCE", title: `Future result schema · ${artifact.resultId} · NOT_VERIFIED`, content: JSON.stringify(artifact), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER", sourceRecordId: job.jobId } }); return artifact; }
export async function createCAEJobVerificationRecord(args: Access & { jobId: string; resultId?: string }) { const job = await getCAEJobContract(args); if (!job) throw new Error("Verification contract requires an authorized canonical job."); const verification: CAEJobVerificationRecord = { verificationId: id("CAE-JOB-VERIFICATION"), projectId: args.projectId, jobId: job.jobId, resultId: args.resultId, checks: job.verificationRequirements.map((requirement) => ({ requirement, status: "NOT_VERIFIED", statement: "Phase 6.5 defines this future verifier check but does not execute it.", evidenceIds: [job.contractHash] })), status: "NOT_VERIFIED", createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EVIDENCE", title: `CAE job verification contract · ${job.jobId} · NOT_VERIFIED`, content: JSON.stringify(verification), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM", sourceRecordId: job.jobId } }); return verification; }
export async function buildCAEJobTraceability(args: Access & { jobId: string }) { const job = await getCAEJobContract(args); if (!job) throw new Error("Traceability requires an authorized canonical job."); const links: CAEJobTraceabilityLink[] = [{ linkId: id("TRACE"), projectId: args.projectId, jobId: job.jobId, from: "REQUIREMENT", fromId: job.provenance.requirementIds[0]!, to: "CAD_REVISION", toId: job.cadRevision, relationship: "requirements constrain CAD revision", status: "DECLARED" }, { linkId: id("TRACE"), projectId: args.projectId, jobId: job.jobId, from: "CAD_REVISION", fromId: job.cadRevision, to: "CAE_JOB", toId: job.jobId, relationship: "immutable CAD snapshot defines job input", status: "PROVEN" }, { linkId: id("TRACE"), projectId: args.projectId, jobId: job.jobId, from: "CAE_JOB", fromId: job.jobId, to: "MESH", toId: job.meshStrategy.strategyReference, relationship: "declared non-executable mesh strategy", status: "DECLARED" }, { linkId: id("TRACE"), projectId: args.projectId, jobId: job.jobId, from: "MESH", fromId: job.meshStrategy.strategyReference, to: "SOLVER", toId: job.solverReference, relationship: "future mesh-to-solver handoff only", status: "UNKNOWN" }, { linkId: id("TRACE"), projectId: args.projectId, jobId: job.jobId, from: "SOLVER", fromId: job.solverReference, to: "RESULT", toId: `FUTURE-RESULT-${job.jobId}`, relationship: "future non-executable result schema", status: "UNKNOWN" }, { linkId: id("TRACE"), projectId: args.projectId, jobId: job.jobId, from: "RESULT", fromId: `FUTURE-RESULT-${job.jobId}`, to: "VERIFICATION", toId: `FUTURE-VERIFICATION-${job.jobId}`, relationship: "future verifier gate", status: "UNKNOWN" }, { linkId: id("TRACE"), projectId: args.projectId, jobId: job.jobId, from: "VERIFICATION", fromId: `FUTURE-VERIFICATION-${job.jobId}`, to: "EVIDENCE", toId: job.contractHash, relationship: "verification must retain input provenance", status: "DECLARED" }]; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EVIDENCE_GRAPH", title: `CAE job traceability · ${job.jobId}`, content: JSON.stringify(links), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM", sourceRecordId: job.jobId } }); return links; }
export function caeJobFailureModel(): CAEJobFailureModel { return { states: ["CREATED", "VALIDATED", "STALE", "REJECTED", "READY_FOR_EXECUTION", "EXECUTING", "FAILED", "COMPLETED", "VERIFICATION_FAILED", "VERIFIED"], readyForExecutionBehavior: "DISABLED_IN_PHASE_6_5", prohibited: ["ARBITRARY_COMMAND", "ARBITRARY_PATH", "ARBITRARY_EXECUTABLE", "ARBITRARY_NETWORK", "ARBITRARY_FILESYSTEM"] }; }
export async function buildCAEJobContractGraph(args: Access & { jobId: string }): Promise<CAEEvidenceGraph> { const job = await getCAEJobContract(args); if (!job) return { projectId: args.projectId, simulationId: "CAE-JOB-CONTRACT", nodes: [], edges: [], limitations: ["No authorized CAE Job Contract exists."] }; const staleness = (await listCAEJobStaleness({ ...args, jobId: job.jobId }))[0]; const nodes = [{ id: job.jobId, type: "CAE_SIMULATION" as const, label: `CAE Job · revision ${job.revision} · VALIDATED`, truthStatus: "DERIVED" as const }, { id: job.cadRevision, type: "CAD_REVISION" as const, label: job.cadRevision, truthStatus: "DERIVED" as const }, { id: job.provenance.requirementIds[0]!, type: "REQUIREMENT" as const, label: job.requirementRevision, truthStatus: "DERIVED" as const }, { id: job.materialReference, type: "MATERIAL_EVIDENCE" as const, label: job.materialReference, truthStatus: "UNVALIDATED" as const }, { id: job.solverReference, type: "SOLVER_ADAPTER" as const, label: `${job.solverReference} · non-executable`, truthStatus: "UNVALIDATED" as const }, { id: `VERIFY-${job.jobId}`, type: "VALIDATION" as const, label: "Future verification contract · NOT_VERIFIED", truthStatus: "UNVALIDATED" as const }, ...(staleness ? [{ id: staleness.assessmentId, type: "VALIDATION" as const, label: `Staleness · ${staleness.status}`, truthStatus: staleness.status === "FRESH" ? "DERIVED" as const : "UNKNOWN" as const }] : [])]; const edges = nodes.filter((item) => item.id !== job.jobId).map((item) => ({ id: id("JOB-GRAPH"), fromId: item.id, toId: job.jobId, relationship: "canonical job contract traceability", status: "DECLARED" as const })); return { projectId: args.projectId, simulationId: job.jobId, nodes, edges, limitations: ["No solver, mesher, runtime, sandbox, process, shell, plugin, arbitrary network, arbitrary filesystem, or numerical result execution exists in Phase 6.5."] }; }
