import { createHash } from "node:crypto";

import type { AdapterCapabilityVerification, AdapterPermission, AdapterTrustVerification, AuthorizedEngineeringApproval, CAEEvidenceGraph, CalibrationCertificate, CalibrationEvidenceVerification, ExternalSolverAdapterRegistration, ReviewerPermission, RevocationRecord, SandboxContract, SecurityAuditEvent, VerifiedReviewerIdentity } from "../shared/cae";
import { listExternalSolverAdapterRegistrations } from "./caeIntegration";
import { buildExtendedEvidenceGraph } from "./caeIntegration";
import { appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";
import { storagePut } from "./storage";

type ProjectAccess = { projectId: string; accessKey: string };
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const MAX_CERTIFICATE_BYTES = 5 * 1024 * 1024;
const trustedPermissions = new Set<AdapterPermission>(["READ_CAD", "READ_REQUIREMENTS", "READ_MATERIAL_EVIDENCE", "READ_CAE_PLAN", "WRITE_RESULTS", "WRITE_LOGS"]);

function parse<T>(value: string): T | undefined { try { return JSON.parse(value) as T; } catch { return undefined; } }
async function authorize(args: ProjectAccess) { return openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function records<T>(args: ProjectAccess, kind: string): Promise<T[]> { await authorize(args); return (await projectMemorySnapshot(args)).records.filter((record) => record.kind === kind).flatMap((record) => { const value = parse<T>(record.content); return value ? [value] : []; }); }
async function audit(args: ProjectAccess, event: Omit<SecurityAuditEvent, "eventId" | "projectId" | "timestamp">) {
  const item: SecurityAuditEvent = { eventId: id("SECURITY-AUDIT"), projectId: args.projectId, timestamp: new Date().toISOString(), ...event };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_SECURITY_AUDIT", title: `${item.action} · ${item.objectType} · ${item.objectId}`, content: JSON.stringify(item), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER" } });
  return item;
}
function safeBytes(base64: string) { const clean = base64.replace(/\s/g, ""); if (!clean || clean.length > Math.ceil(MAX_CERTIFICATE_BYTES * 4 / 3) + 4 || !/^[A-Za-z0-9+/]*={0,2}$/.test(clean)) throw new Error("Certificate payload is invalid or exceeds the 5 MiB bounded envelope."); const bytes = Buffer.from(clean, "base64"); if (!bytes.length || bytes.length > MAX_CERTIFICATE_BYTES || bytes.toString("base64").replace(/=+$/, "") !== clean.replace(/=+$/, "")) throw new Error("Certificate bytes failed integrity validation."); return bytes; }
function safeName(value: string) { return value.trim().replace(/[^a-zA-Z0-9._-]+/g, "-").slice(0, 255) || "certificate.bin"; }

export async function registerReviewerIdentity(args: ProjectAccess & { displayName: string; role: string; projectScope: string[]; permissions: ReviewerPermission[]; actor: string }): Promise<VerifiedReviewerIdentity> {
  await authorize(args); if (!args.displayName.trim() || !args.role.trim() || !args.projectScope.length || !args.actor.trim()) throw new Error("Reviewer display name, role, project scope, and actor are required. New identities are always unverified.");
  const reviewer: VerifiedReviewerIdentity = { reviewerId: id("REVIEWER"), projectId: args.projectId, displayName: args.displayName.trim(), identityStatus: "UNVERIFIED", role: args.role.trim(), projectScope: args.projectScope, permissions: args.permissions, status: "UNVERIFIED", createdAt: new Date().toISOString() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_REVIEWER_IDENTITY", title: `Reviewer identity · ${reviewer.displayName} · UNVERIFIED`, content: JSON.stringify(reviewer), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER" } });
  await audit(args, { actor: args.actor.trim(), action: "REGISTRATION", objectType: "REVIEWER", objectId: reviewer.reviewerId, newState: "UNVERIFIED", reason: "Identity registration is not verification." }); return reviewer;
}
export async function listReviewerIdentities(args: ProjectAccess) { const all = await records<VerifiedReviewerIdentity>(args, "CAE_REVIEWER_IDENTITY"); return [...new Map(all.map((item) => [item.reviewerId, item])).values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
async function latestReviewer(args: ProjectAccess, reviewerId: string) { const candidates = (await records<VerifiedReviewerIdentity>(args, "CAE_REVIEWER_IDENTITY")).filter((item) => item.reviewerId === reviewerId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return candidates[0]; }
export async function verifyReviewerIdentity(args: ProjectAccess & { reviewerId: string; verificationMethod: string; actor: string }): Promise<VerifiedReviewerIdentity> {
  const current = await latestReviewer(args, args.reviewerId); if (!current) throw new Error("Reviewer identity is unavailable in the authorized project."); if (current.status === "REVOKED" || current.status === "SUSPENDED") throw new Error("A suspended or revoked reviewer cannot be verified without a new authorized identity process."); if (!args.verificationMethod.trim() || !args.actor.trim()) throw new Error("A verification method and human actor are required.");
  const verified: VerifiedReviewerIdentity = { ...current, identityStatus: "VERIFIED", status: "VERIFIED", verificationMethod: args.verificationMethod.trim(), verificationTimestamp: new Date().toISOString(), createdAt: new Date().toISOString() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_REVIEWER_IDENTITY", title: `Reviewer identity · ${verified.displayName} · VERIFIED`, content: JSON.stringify(verified), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await audit(args, { actor: args.actor.trim(), action: "IDENTITY_CHANGE", objectType: "REVIEWER", objectId: verified.reviewerId, previousState: current.status, newState: "VERIFIED", reason: args.verificationMethod.trim() }); return verified;
}
export async function requireReviewerAuthorization(args: ProjectAccess & { reviewerId: string; permission: ReviewerPermission }) { const reviewer = await latestReviewer(args, args.reviewerId); if (!reviewer || reviewer.status !== "VERIFIED" || reviewer.identityStatus !== "VERIFIED") throw new Error("Engineering approval is blocked: reviewer identity is not verified."); if (!reviewer.projectScope.includes(args.projectId) || !reviewer.permissions.includes(args.permission)) throw new Error("Engineering approval is blocked: reviewer lacks the required project-scoped permission."); return reviewer; }

export async function attachCalibrationCertificate(args: ProjectAccess & { fileName: string; mimeType?: string; base64: string; issuer?: string; certificateNumber?: string; instrument: string; calibrationDate?: string; expirationDate?: string; scope?: string; uncertainty?: string; actor: string }): Promise<CalibrationCertificate> {
  await authorize(args); if (!args.instrument.trim() || !args.actor.trim()) throw new Error("Instrument and actor are required for certificate attachment."); const bytes = safeBytes(args.base64); const fileHash = createHash("sha256").update(bytes).digest("hex"); const existing = (await records<CalibrationCertificate>(args, "CAE_CERTIFICATE")).find((item) => item.fileHash === fileHash); if (existing) return existing; const fileName = safeName(args.fileName); const storage = await storagePut(`engineering-projects/${args.projectId.replace(/[^a-zA-Z0-9_-]/g, "_")}/calibration-certificates/${fileHash}/${fileName}`, bytes, args.mimeType ?? "application/octet-stream"); const certificate: CalibrationCertificate = { certificateId: id("CALIBRATION-CERTIFICATE"), projectId: args.projectId, fileName, mimeType: args.mimeType ?? "application/octet-stream", fileHash, fileSizeBytes: bytes.length, storage, issuer: args.issuer?.trim() || undefined, certificateNumber: args.certificateNumber?.trim() || undefined, instrument: args.instrument.trim(), calibrationDate: args.calibrationDate, expirationDate: args.expirationDate, scope: args.scope?.trim() || undefined, uncertainty: args.uncertainty?.trim() || undefined, status: "UNVERIFIED", createdAt: new Date().toISOString() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_CERTIFICATE", title: `Calibration certificate · ${certificate.instrument} · UNVERIFIED`, content: JSON.stringify(certificate), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await audit(args, { actor: args.actor.trim(), action: "REGISTRATION", objectType: "CERTIFICATE", objectId: certificate.certificateId, newState: "UNVERIFIED", reason: "File presence and metadata do not establish certificate validity." }); return certificate;
}
export async function listCalibrationCertificates(args: ProjectAccess) { return (await records<CalibrationCertificate>(args, "CAE_CERTIFICATE")).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
async function revoked(args: ProjectAccess, objectType: RevocationRecord["objectType"], objectId: string) { return (await records<RevocationRecord>(args, "CAE_REVOCATION")).some((item) => item.objectType === objectType && item.objectId === objectId && item.newState === "REVOKED"); }
export async function verifyCalibrationCertificate(args: ProjectAccess & { certificateId: string; reviewerId: string; sourceVerified: boolean; signatureVerified: boolean; scopeMatch: boolean; reason: string }): Promise<CalibrationEvidenceVerification> {
  const reviewer = await requireReviewerAuthorization({ ...args, permission: "APPROVE_CALIBRATION" }); const certificate = (await listCalibrationCertificates(args)).find((item) => item.certificateId === args.certificateId); if (!certificate) throw new Error("Calibration certificate is unavailable in the authorized project."); const isRevoked = await revoked(args, "CERTIFICATE", certificate.certificateId); const dateValid = Boolean(certificate.expirationDate && new Date(certificate.expirationDate).getTime() >= Date.now()); const metadataValid = Boolean(certificate.issuer && certificate.certificateNumber && certificate.calibrationDate && certificate.expirationDate && certificate.scope && certificate.uncertainty); const checks = { filePresent: "PASS" as const, metadataValid: metadataValid ? "PASS" as const : "FAIL" as const, sourceVerified: args.sourceVerified ? "PASS" as const : "FAIL" as const, dateValid: dateValid ? "PASS" as const : "FAIL" as const, scopeMatch: args.scopeMatch ? "PASS" as const : "FAIL" as const, signatureVerified: args.signatureVerified ? "PASS" as const : "FAIL" as const }; const status = isRevoked ? "REVOKED" as const : !dateValid ? "EXPIRED" as const : Object.values(checks).every((item) => item === "PASS") ? "VALID" as const : "UNVERIFIED" as const; const verification: CalibrationEvidenceVerification = { verificationId: id("CERTIFICATE-VERIFICATION"), projectId: args.projectId, certificateId: certificate.certificateId, ...checks, status, findings: [args.reason.trim() || "No reason supplied.", "Metadata presence was assessed independently from source and signature verification."], createdAt: new Date().toISOString() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_CERTIFICATE_VERIFICATION", title: `Certificate verification · ${certificate.instrument} · ${status}`, content: JSON.stringify(verification), truthStatus: status === "VALID" ? "DERIVED" : "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await audit(args, { actor: reviewer.displayName, action: "CERTIFICATE_VALIDATION", objectType: "CERTIFICATE", objectId: certificate.certificateId, previousState: certificate.status, newState: status, reason: args.reason.trim() || "Certificate verification performed." }); return verification;
}

function defaultSandbox(): SandboxContract { return { sandboxType: "DECLARATION_ONLY", resourceLimits: ["No runtime provisioned"], filesystemScope: [], networkPolicy: "NO_NETWORK", allowedInputs: ["Declared CAD, requirements, material evidence, CAE plan"], allowedOutputs: ["Future validated results only"], prohibitsShellExecution: true, prohibitsArbitraryFilesystem: true }; }
export async function verifyAdapterTrust(args: ProjectAccess & { registrationId: string; reviewerId: string; manifestVerified: boolean; signatureVerified: boolean; verifiedCapabilities: string[]; grantedPermissions: AdapterPermission[]; sandbox?: Partial<SandboxContract>; reason: string }): Promise<AdapterTrustVerification> {
  const reviewer = await requireReviewerAuthorization({ ...args, permission: "APPROVE_SOLVER_ADAPTER" }); const registration = (await listExternalSolverAdapterRegistrations(args)).find((item) => item.registrationId === args.registrationId); if (!registration) throw new Error("Adapter registration is unavailable in the authorized project."); const isRevoked = await revoked(args, "ADAPTER", registration.registrationId); const declared = new Set(registration.capabilities); const verified = new Set(args.verifiedCapabilities); const capabilityNames = [...new Set([...declared, ...verified])]; const capabilities: AdapterCapabilityVerification[] = capabilityNames.map((capability) => ({ capability, declared: declared.has(capability), verified: verified.has(capability), status: declared.has(capability) === verified.has(capability) ? "VERIFIED" : "CAPABILITY_CONFLICT" })); const capabilityCheck = capabilities.every((item) => item.status === "VERIFIED") ? "PASS" as const : "FAIL" as const; const permissionCheck = args.grantedPermissions.every((item) => trustedPermissions.has(item)) ? "PASS" as const : "FAIL" as const; const sandbox: SandboxContract = { ...defaultSandbox(), ...args.sandbox, networkPolicy: "NO_NETWORK", prohibitsShellExecution: true, prohibitsArbitraryFilesystem: true, filesystemScope: [] }; const identityCheck = reviewer.status === "VERIFIED" ? "PASS" as const : "FAIL" as const; const manifestValidation = args.manifestVerified && registration.verificationStatus !== "REJECTED" ? "PASS" as const : "FAIL" as const; const signatureCheck = args.signatureVerified ? "PASS" as const : "FAIL" as const; const securityReview = sandbox.networkPolicy === "NO_NETWORK" && sandbox.prohibitsShellExecution && sandbox.prohibitsArbitraryFilesystem ? "PASS" as const : "FAIL" as const; const allPass = [identityCheck, manifestValidation, signatureCheck, capabilityCheck, securityReview, permissionCheck].every((item) => item === "PASS"); const executionEligible = false; const trustState = isRevoked ? "REVOKED" as const : allPass ? "VERIFIED" as const : manifestValidation === "FAIL" || signatureCheck === "FAIL" || capabilityCheck === "FAIL" || permissionCheck === "FAIL" ? "INVALID" as const : "REGISTERED" as const; const verification: AdapterTrustVerification = { verificationId: id("ADAPTER-TRUST"), projectId: args.projectId, registrationId: registration.registrationId, reviewerId: reviewer.reviewerId, trustState, identityCheck, manifestValidation, signatureCheck, capabilityCheck, securityReview, permissionCheck, capabilities, grantedPermissions: args.grantedPermissions, sandbox, executionEligible, executable: false, reason: `${args.reason.trim() || "Trust verification completed."} A separate verified-human approval is required before conceptual eligibility; no executable solver runtime exists in this phase.` , createdAt: new Date().toISOString() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_ADAPTER_TRUST_VERIFICATION", title: `Adapter trust verification · ${registration.solverName} · ${trustState}`, content: JSON.stringify(verification), truthStatus: trustState === "VERIFIED" ? "DERIVED" : "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await audit(args, { actor: reviewer.displayName, action: trustState === "INVALID" ? "REJECTION" : "APPROVAL", objectType: "VERIFICATION", objectId: verification.verificationId, newState: trustState, reason: verification.reason }); return verification;
}
export async function listAdapterTrustVerifications(args: ProjectAccess & { registrationId?: string }) { return (await records<AdapterTrustVerification>(args, "CAE_ADAPTER_TRUST_VERIFICATION")).filter((item) => !args.registrationId || item.registrationId === args.registrationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
export async function authorizeEngineeringApproval(args: ProjectAccess & { reviewerId: string; targetType: AuthorizedEngineeringApproval["targetType"]; targetId: string; decision: AuthorizedEngineeringApproval["decision"]; evidenceIds: string[]; revision: number; reason: string }): Promise<AuthorizedEngineeringApproval> {
  const permission: ReviewerPermission = args.targetType === "ADAPTER" ? "APPROVE_SOLVER_ADAPTER" : args.targetType === "CALIBRATION" ? "APPROVE_CALIBRATION" : args.targetType === "MATERIAL_RECONCILIATION" ? "APPROVE_MATERIAL" : "APPROVE_VALIDATION"; const reviewer = await requireReviewerAuthorization({ ...args, permission }); if (!args.targetId.trim() || !args.reason.trim() || !args.evidenceIds.length || args.revision < 1) throw new Error("A reviewer, target, explicit evidence, revision, and reason are required; anonymous approvals are blocked."); if (args.targetType === "ADAPTER") { const verification = (await listAdapterTrustVerifications({ ...args, registrationId: args.targetId }))[0]; if (!verification || verification.trustState !== "VERIFIED") throw new Error("Adapter approval is blocked until all verification gates pass."); } const approval: AuthorizedEngineeringApproval = { approvalId: id("ENGINEERING-APPROVAL"), projectId: args.projectId, reviewerId: reviewer.reviewerId, targetType: args.targetType, targetId: args.targetId.trim(), decision: args.decision, evidenceIds: args.evidenceIds, revision: args.revision, reason: args.reason.trim(), timestamp: new Date().toISOString() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_AUTHORIZED_APPROVAL", title: `Human ${approval.decision} · ${approval.targetType} · ${approval.targetId}`, content: JSON.stringify(approval), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await audit(args, { actor: reviewer.displayName, action: approval.decision === "APPROVE" ? "APPROVAL" : approval.decision === "REJECT" ? "REJECTION" : "VERIFICATION", objectType: "DECISION", objectId: approval.approvalId, newState: approval.decision, reason: approval.reason }); return approval;
}
export async function listAuthorizedApprovals(args: ProjectAccess & { targetId?: string }) { return (await records<AuthorizedEngineeringApproval>(args, "CAE_AUTHORIZED_APPROVAL")).filter((item) => !args.targetId || item.targetId === args.targetId).sort((a, b) => b.timestamp.localeCompare(a.timestamp)); }
export async function revokeTrustObject(args: ProjectAccess & { objectType: RevocationRecord["objectType"]; objectId: string; actor: string; reason: string }): Promise<RevocationRecord> {
  await authorize(args); if (!args.actor.trim() || !args.reason.trim()) throw new Error("A revocation actor and reason are required."); let previousState = "UNKNOWN"; if (args.objectType === "REVIEWER") { const reviewer = await latestReviewer(args, args.objectId); if (!reviewer) throw new Error("Reviewer is unavailable in the authorized project."); previousState = reviewer.status; const revokedReviewer: VerifiedReviewerIdentity = { ...reviewer, identityStatus: "REVOKED", status: "REVOKED", createdAt: new Date().toISOString() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_REVIEWER_IDENTITY", title: `Reviewer identity · ${revokedReviewer.displayName} · REVOKED`, content: JSON.stringify(revokedReviewer), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); } else if (args.objectType === "ADAPTER") { const registration = (await listExternalSolverAdapterRegistrations(args)).find((item) => item.registrationId === args.objectId); if (!registration) throw new Error("Adapter registration is unavailable in the authorized project."); previousState = registration.verificationStatus; } else { const certificate = (await listCalibrationCertificates(args)).find((item) => item.certificateId === args.objectId); if (!certificate) throw new Error("Certificate is unavailable in the authorized project."); previousState = certificate.status; }
  const revocation: RevocationRecord = { revocationId: id("REVOCATION"), projectId: args.projectId, objectType: args.objectType, objectId: args.objectId, previousState, newState: "REVOKED", reason: args.reason.trim(), actor: args.actor.trim(), timestamp: new Date().toISOString() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_REVOCATION", title: `Revocation · ${revocation.objectType} · ${revocation.objectId}`, content: JSON.stringify(revocation), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await audit(args, { actor: revocation.actor, action: "REVOCATION", objectType: revocation.objectType, objectId: revocation.objectId, previousState, newState: "REVOKED", reason: revocation.reason }); return revocation;
}
export async function adapterEligibility(args: ProjectAccess & { registrationId: string }) { const latest = (await listAdapterTrustVerifications({ ...args, registrationId: args.registrationId }))[0]; const approval = (await listAuthorizedApprovals({ ...args, targetId: args.registrationId })).find((item) => item.targetType === "ADAPTER" && item.decision === "APPROVE"); const isRevoked = await revoked(args, "ADAPTER", args.registrationId); const reviewerRevoked = approval ? await revoked(args, "REVIEWER", approval.reviewerId) : false; const approved = Boolean(approval) && !reviewerRevoked; const executionEligible = Boolean(latest && latest.trustState === "VERIFIED" && approved && !isRevoked); return { registrationId: args.registrationId, trustState: isRevoked ? "REVOKED" as const : executionEligible ? "EXECUTION_ELIGIBLE" as const : latest?.trustState ?? "UNTRUSTED" as const, executionEligible, executable: false, reason: isRevoked ? "Adapter revocation immediately blocks new eligibility; immutable historical records remain available." : reviewerRevoked ? "The approving reviewer is revoked; no new eligibility may rely on that approval." : executionEligible ? "All trust gates and a current verified-human approval are recorded. Execution remains unavailable because no solver runtime exists." : latest?.reason ?? "No adapter trust verification exists." }; }
export async function listSecurityAudit(args: ProjectAccess) { return (await records<SecurityAuditEvent>(args, "CAE_SECURITY_AUDIT")).sort((a, b) => b.timestamp.localeCompare(a.timestamp)); }
export async function buildTrustEvidenceGraph(args: ProjectAccess & { simulationId: string }) {
  let base: CAEEvidenceGraph; try { base = await buildExtendedEvidenceGraph(args); } catch { base = { projectId: args.projectId, simulationId: args.simulationId, nodes: [], edges: [], limitations: ["No CAE simulation plan was found for this graph request; project-scoped trust evidence remains visible without a hidden simulation link."] }; } const reviewers = await listReviewerIdentities(args); const certificates = await listCalibrationCertificates(args); const certificateVerifications = await records<CalibrationEvidenceVerification>(args, "CAE_CERTIFICATE_VERIFICATION"); const verifications = await listAdapterTrustVerifications(args); const approvals = await listAuthorizedApprovals(args); const revocations = await records<RevocationRecord>(args, "CAE_REVOCATION"); const audits = await listSecurityAudit(args); const adapters = await listExternalSolverAdapterRegistrations(args); const eligibility = await Promise.all(adapters.map((item) => adapterEligibility({ ...args, registrationId: item.registrationId })));
  const nodes = [...base.nodes, ...reviewers.map((item) => ({ id: item.reviewerId, type: "REVIEWER" as const, label: `${item.displayName} · ${item.status}`, truthStatus: item.status === "VERIFIED" ? "VERIFIED" as const : "UNVALIDATED" as const })), ...certificates.map((item) => ({ id: item.certificateId, type: "CALIBRATION_CERTIFICATE" as const, label: `${item.instrument} · ${item.status}`, truthStatus: item.status === "VALID" ? "DERIVED" as const : "UNVALIDATED" as const })), ...certificateVerifications.map((item) => ({ id: item.verificationId, type: "CERTIFICATE_VERIFICATION" as const, label: `Certificate verification · ${item.status}`, truthStatus: item.status === "VALID" ? "DERIVED" as const : "UNVALIDATED" as const })), ...verifications.map((item) => ({ id: item.verificationId, type: "ADAPTER_TRUST_VERIFICATION" as const, label: `Adapter trust · ${item.trustState}`, truthStatus: item.trustState === "VERIFIED" ? "DERIVED" as const : "UNVALIDATED" as const })), ...approvals.map((item) => ({ id: item.approvalId, type: "ENGINEERING_DECISION" as const, label: `${item.targetType} · ${item.decision}`, truthStatus: "DERIVED" as const })), ...eligibility.map((item) => ({ id: `ELIGIBILITY-${item.registrationId}`, type: "EXECUTION_ELIGIBILITY" as const, label: `${item.trustState} · executable false`, truthStatus: item.executionEligible ? "DERIVED" as const : "UNVALIDATED" as const })), ...revocations.map((item) => ({ id: item.revocationId, type: "REVOCATION" as const, label: `${item.objectType} · REVOKED`, truthStatus: "DERIVED" as const })), ...audits.map((item) => ({ id: item.eventId, type: "SECURITY_AUDIT" as const, label: `${item.action} · ${item.objectType}`, truthStatus: "DERIVED" as const }))];
  const edges = [...base.edges, ...certificateVerifications.map((item) => ({ id: id("GRAPH"), fromId: item.certificateId, toId: item.verificationId, relationship: "verified as certificate evidence", status: "DECLARED" as const })), ...verifications.flatMap((item) => [{ id: id("GRAPH"), fromId: item.registrationId, toId: item.verificationId, relationship: "trust verification", status: "DECLARED" as const }, ...(item.reviewerId ? [{ id: id("GRAPH"), fromId: item.reviewerId, toId: item.verificationId, relationship: "verified by reviewer", status: "DECLARED" as const }] : [])]), ...approvals.flatMap((item) => [{ id: id("GRAPH"), fromId: item.reviewerId, toId: item.approvalId, relationship: "authorized approval", status: "DECLARED" as const }, { id: id("GRAPH"), fromId: item.approvalId, toId: item.targetId, relationship: "approves target", status: "DECLARED" as const }]), ...eligibility.map((item) => ({ id: id("GRAPH"), fromId: item.registrationId, toId: `ELIGIBILITY-${item.registrationId}`, relationship: "conceptual eligibility only", status: item.executionEligible ? "DECLARED" as const : "UNKNOWN" as const })), ...revocations.map((item) => ({ id: id("GRAPH"), fromId: item.revocationId, toId: item.objectId, relationship: "revokes future approval or eligibility", status: "DECLARED" as const })), ...audits.map((item) => ({ id: id("GRAPH"), fromId: item.eventId, toId: item.objectId, relationship: "audits security-sensitive action", status: "DECLARED" as const }))];
  return { ...base, nodes, edges, limitations: [...base.limitations, "Trust evidence records verification and approval relationships explicitly. Conceptual execution eligibility does not provide an executable solver, runtime, shell, network, or filesystem capability."] };
}
