import { createHash } from "node:crypto";

export const CAM_ENGINE_VERSION = "cad-ai-2p5d-cam-1";
export type CamOperationKind = "FACING" | "POCKET" | "CONTOUR";
export type CamEngineStatus = "ENGINE_AVAILABLE" | "ENGINE_UNAVAILABLE" | "ENGINE_INVALID" | "READY" | "INVALID_INPUT" | "GEOMETRY_INVALID" | "TOOLPATH_INVALID" | "POST_PROCESS_INVALID";
export type Vec3 = readonly [number, number, number];
export type CamTool = { toolId: string; type: "FLAT_END_MILL"; diameterMm: number; fluteCount: number; material: "HSS" | "CARBIDE"; maxSpindleRpm: number; maxFeedMmMin: number; cuttingFeedMmMin: number; spindleRpm: number };
export type CamStock = { stockId: string; sizeMm: Vec3; originMm: Vec3; material: string; workOrigin: "STOCK_MIN_CORNER"; coordinateSystem: "CARTESIAN_MM" };
export type CamGeometry = { sourceCadHash: string; vertices: readonly Vec3[] };
export type CamOperation = { operationId: string; kind: CamOperationKind; depthMm: number; safeZMm: number; stepOverMm: number; pocket?: { minX: number; minY: number; maxX: number; maxY: number } };
export type CamPathSegment = { from: Vec3; to: Vec3; feedMmMin: number; cutting: boolean };
export type CamResult = { status: CamEngineStatus; diagnostics: string[]; bounds?: { min: Vec3; max: Vec3 }; toolpath?: CamPathSegment[]; toolpathHash?: string; gcode?: Buffer; gcodeHash?: string; postProcessor?: "GRBL_1_1"; engineEvidence: { engine: "CAD_AI_2P5D_CAM"; version: string; runtime: string; cleanupStatus: "NOT_APPLICABLE"; durationMs: number } };

const sha256 = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex");
const finite = (value: number) => Number.isFinite(value);
const stable = (value: unknown) => JSON.stringify(value);

export function inspectLocalCamEngine() { return { status: "ENGINE_AVAILABLE" as const, engine: "CAD_AI_2P5D_CAM", version: CAM_ENGINE_VERSION, runtime: `node-${process.versions.node}`, supportedOperations: ["FACING", "POCKET", "CONTOUR"] as const, supportedPostProcessors: ["GRBL_1_1"] as const }; }
export function validateCamTool(tool: CamTool) { return Boolean(/^[A-Za-z0-9_-]{3,80}$/.test(tool.toolId) && tool.type === "FLAT_END_MILL" && finite(tool.diameterMm) && tool.diameterMm > 0 && tool.diameterMm <= 100 && Number.isInteger(tool.fluteCount) && tool.fluteCount >= 1 && tool.fluteCount <= 12 && finite(tool.maxSpindleRpm) && finite(tool.spindleRpm) && tool.spindleRpm > 0 && tool.spindleRpm <= tool.maxSpindleRpm && finite(tool.maxFeedMmMin) && finite(tool.cuttingFeedMmMin) && tool.cuttingFeedMmMin > 0 && tool.cuttingFeedMmMin <= tool.maxFeedMmMin); }
export function validateCamStock(stock: CamStock) { return Boolean(/^[A-Za-z0-9_-]{3,80}$/.test(stock.stockId) && stock.coordinateSystem === "CARTESIAN_MM" && stock.workOrigin === "STOCK_MIN_CORNER" && stock.sizeMm.every((value) => finite(value) && value > 0 && value <= 10_000) && stock.originMm.every(finite) && stock.material.trim().length > 0 && stock.material.length <= 120); }
function bounds(vertices: readonly Vec3[]) { if (vertices.length < 4 || vertices.length > 100_000 || vertices.some((point) => point.length !== 3 || point.some((value) => !finite(value)))) return undefined; const min: [number, number, number] = [...vertices[0]]; const max: [number, number, number] = [...vertices[0]]; for (const point of vertices) for (let axis = 0; axis < 3; axis += 1) { min[axis] = Math.min(min[axis], point[axis]); max[axis] = Math.max(max[axis], point[axis]); } return max.every((value, axis) => value > min[axis]) ? { min: min as Vec3, max: max as Vec3 } : undefined; }
function segment(from: Vec3, to: Vec3, feedMmMin: number, cutting: boolean): CamPathSegment { return { from, to, feedMmMin, cutting }; }
function rectangularContour(minX: number, minY: number, maxX: number, maxY: number, z: number, feed: number) { const points: Vec3[] = [[minX, minY, z], [maxX, minY, z], [maxX, maxY, z], [minX, maxY, z], [minX, minY, z]]; return points.slice(1).map((point, index) => segment(points[index], point, feed, true)); }
function validatePath(path: CamPathSegment[], stock: CamStock) { return path.length > 0 && path.length <= 50_000 && path.every((item) => finite(item.feedMmMin) && item.feedMmMin > 0 && [...item.from, ...item.to].every(finite) && [item.from, item.to].every((point) => point[0] >= stock.originMm[0] && point[0] <= stock.originMm[0] + stock.sizeMm[0] && point[1] >= stock.originMm[1] && point[1] <= stock.originMm[1] + stock.sizeMm[1] && point[2] >= stock.originMm[2] && point[2] <= stock.originMm[2] + stock.sizeMm[2])); }
export function postProcessGrbl(tool: CamTool, path: readonly CamPathSegment[]) { const lines = ["%", "(CAD-AI validated 2.5D CAM; NOT_MACHINE_CERTIFIED)", "G21", "G90", "G94", `S${tool.spindleRpm.toFixed(0)} M3`]; for (const item of path) { const target = item.to; lines.push(`${item.cutting ? "G1" : "G0"} X${target[0].toFixed(3)} Y${target[1].toFixed(3)} Z${target[2].toFixed(3)}${item.cutting ? ` F${item.feedMmMin.toFixed(2)}` : ""}`); } lines.push("M5", "M30", "%"); const gcode = Buffer.from(lines.join("\n") + "\n", "utf8"); const valid = gcode.length <= 2_000_000 && /^%\n[\s\S]*\nM30\n%\n$/.test(gcode.toString("utf8")) && !/\b(G2|G3|G28|G53|G92|M6|M98|M99)\b/.test(gcode.toString("utf8")); return valid ? gcode : undefined; }
export function createLocalCamToolpath(input: { geometry: CamGeometry; tool: CamTool; stock: CamStock; operation: CamOperation }): CamResult { const started = Date.now(); const evidence = () => ({ engine: "CAD_AI_2P5D_CAM" as const, version: CAM_ENGINE_VERSION, runtime: `node-${process.versions.node}`, cleanupStatus: "NOT_APPLICABLE" as const, durationMs: Date.now() - started }); if (!/^[a-f0-9]{64}$/i.test(input.geometry.sourceCadHash) || !validateCamTool(input.tool) || !validateCamStock(input.stock) || !/^[A-Za-z0-9_-]{3,80}$/.test(input.operation.operationId) || !finite(input.operation.depthMm) || input.operation.depthMm <= 0 || !finite(input.operation.safeZMm) || input.operation.safeZMm < 0 || !finite(input.operation.stepOverMm) || input.operation.stepOverMm <= 0) return { status: "INVALID_INPUT", diagnostics: ["explicit valid geometry hash, tool, stock, operation, depth, safe Z, and step-over are required"], engineEvidence: evidence() }; const shape = bounds(input.geometry.vertices); if (!shape) return { status: "GEOMETRY_INVALID", diagnostics: ["server-resolved CAD viewer geometry must be non-empty, finite, bounded, and three-dimensional"], engineEvidence: evidence() }; const [minX, minY, minZ] = shape.min; const [maxX, maxY, maxZ] = shape.max; const [ox, oy, oz] = input.stock.originMm; const [sx, sy, sz] = input.stock.sizeMm; if (minX < ox || minY < oy || minZ < oz || maxX > ox + sx || maxY > oy + sy || maxZ > oz + sz || input.operation.depthMm >= maxZ - minZ || input.operation.safeZMm > oz + sz) return { status: "GEOMETRY_INVALID", diagnostics: ["CAD envelope, cut depth, and safe Z must remain inside the declared stock"], engineEvidence: evidence() }; const cutZ = maxZ - input.operation.depthMm; const path: CamPathSegment[] = []; if (input.operation.kind === "FACING") { for (let y = minY; y <= maxY; y += input.operation.stepOverMm) { const from: Vec3 = [minX, Math.min(y, maxY), input.operation.safeZMm]; const to: Vec3 = [maxX, Math.min(y, maxY), cutZ]; path.push(segment(from, to, input.tool.cuttingFeedMmMin, true)); } } else if (input.operation.kind === "CONTOUR") path.push(...rectangularContour(minX, minY, maxX, maxY, cutZ, input.tool.cuttingFeedMmMin)); else { const pocket = input.operation.pocket; if (!pocket || ![pocket.minX, pocket.minY, pocket.maxX, pocket.maxY].every(finite) || pocket.minX < minX || pocket.minY < minY || pocket.maxX > maxX || pocket.maxY > maxY || pocket.maxX - pocket.minX < input.tool.diameterMm || pocket.maxY - pocket.minY < input.tool.diameterMm) return { status: "GEOMETRY_INVALID", diagnostics: ["pocket boundary must be explicit, finite, tool-accessible, and inside actual CAD envelope"], engineEvidence: evidence() }; for (let y = pocket.minY; y <= pocket.maxY; y += input.operation.stepOverMm) path.push(segment([pocket.minX, Math.min(y, pocket.maxY), cutZ], [pocket.maxX, Math.min(y, pocket.maxY), cutZ], input.tool.cuttingFeedMmMin, true)); }
  if (!validatePath(path, input.stock)) return { status: "TOOLPATH_INVALID", diagnostics: ["generated path is empty, non-finite, oversized, or leaves the declared stock envelope"], engineEvidence: evidence() }; const gcode = postProcessGrbl(input.tool, path); if (!gcode) return { status: "POST_PROCESS_INVALID", diagnostics: ["controlled GRBL post processor rejected the generated program"], engineEvidence: evidence() }; return { status: "READY", diagnostics: ["toolpath is geometry-derived and syntax/boundary validated; NOT_MACHINE_CERTIFIED"], bounds: shape, toolpath: path, toolpathHash: sha256(stable(path)), gcode, gcodeHash: sha256(gcode), postProcessor: "GRBL_1_1", engineEvidence: evidence() };
}
