import { createHash } from "node:crypto";
import { createLocalCamToolpath, type CamGeometry, type CamOperation, type CamResult, type CamStock, type CamTool } from "./camEngine";
import { appendLineageNode, appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";
import { storagePut } from "./storage";
type Access = { projectId: string; accessKey: string };
export type ManagedCamArtifact = { artifactId: string; projectId: string; sourceCadHash: string; toolId: string; stockId: string; operationId: string; toolpathHash: string; gcodeHash: string; postProcessor: "GRBL_1_1"; storageKey: string; storageUrl: string; createdAt: string };
const sha256 = (value: Uint8Array | string) => createHash("sha256").update(value).digest("hex");
export async function executeAndPersistLocalCam(args: Access & { geometry: CamGeometry; tool: CamTool; stock: CamStock; operation: CamOperation }): Promise<CamResult & { artifact?: ManagedCamArtifact }> { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); const result = createLocalCamToolpath(args); if (result.status !== "READY" || !result.gcode || !result.gcodeHash || !result.toolpathHash || !result.postProcessor) return result; const artifactId = `CAM-${crypto.randomUUID()}`; const storage = await storagePut(`engineering-projects/${args.projectId}/cam/${artifactId}-${result.gcodeHash}.nc`, result.gcode, "text/x.gcode"); if (sha256(result.gcode) !== result.gcodeHash) throw new Error("CAM_GCODE_HASH_MISMATCH"); const artifact: ManagedCamArtifact = { artifactId, projectId: args.projectId, sourceCadHash: args.geometry.sourceCadHash, toolId: args.tool.toolId, stockId: args.stock.stockId, operationId: args.operation.operationId, toolpathHash: result.toolpathHash, gcodeHash: result.gcodeHash, postProcessor: result.postProcessor, storageKey: storage.key, storageUrl: storage.url, createdAt: new Date().toISOString() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EVIDENCE", title: `Local CAM artifact · ${artifact.artifactId} · GENERATED_VALIDATED_NOT_MACHINE_CERTIFIED`, content: JSON.stringify(artifact), truthStatus: "DERIVED", validationStage: "GEOMETRICALLY_VALIDATED", authorSource: "SYSTEM", sourceRecordId: artifact.sourceCadHash } }); await appendLineageNode({ projectId: args.projectId, accessKey: args.accessKey, node: { kind: "CONFIGURATION", sourceRecordId: artifact.artifactId, title: `CAM program · ${artifact.artifactId}`, reasonForChange: "A validated geometry-derived local CAM operation produced a controlled G-code artifact.", changeSummary: `cad=${artifact.sourceCadHash}; toolpath=${artifact.toolpathHash}; gcode=${artifact.gcodeHash}; post=${artifact.postProcessor}`, status: "VALIDATED", authorSource: "SYSTEM" } }); return { ...result, gcode: undefined, toolpath: undefined, artifact }; }
export async function listManagedCamArtifacts(args: Access): Promise<ManagedCamArtifact[]> { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); return (await projectMemorySnapshot(args)).records.filter((record) => record.kind === "CAE_EVIDENCE").flatMap((record) => { try { return [JSON.parse(record.content) as ManagedCamArtifact]; } catch { return []; } }).filter((item) => Boolean(item.artifactId?.startsWith("CAM-") && item.gcodeHash && item.toolpathHash)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
