import { createHash, randomUUID } from "node:crypto";
import { execFileSync, spawn } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

export const TEXT_TO_CAD_SOURCE_REPOSITORY = "https://github.com/earthtojake/text-to-cad.git";
export const TEXT_TO_CAD_SOURCE_COMMIT = "b97ff01f3f34ff0c87c84d1e9a6bd42d3cec21ed";
export const TEXT_TO_CAD_ADAPTER_VERSION = "1.1.0";
export const TEXT_TO_CAD_SKILL_ID = "external.text_to_cad.cad.rectangular_plate.v1";
const ALLOWED_RUNTIME_ROOT = "/home/ubuntu/external-runtimes/text-to-cad-b97ff01";
const ALLOWED_SOURCE_ROOT = "/home/ubuntu/external-audits/text-to-cad-current";
const REQUIRED_RUNTIME_MANIFEST = "runtime-manifest.json";

export type ExternalSkillPermission = "READ" | "WRITE" | "EXECUTE" | "EXPORT";
export type ExternalSkillStatus = "AVAILABLE" | "EXECUTABLE" | "FAILED" | "DEPENDENCY_MISSING" | "UNSUPPORTED" | "BLOCKED" | "SECURITY_REJECTED" | "VALIDATION_FAILED";
export type RectangularPlateInput = { widthMm: number; heightMm: number; thicknessMm: number; unit: "mm" };
export type ExternalTextToCadSkill = { skillId: string; name: string; domain: "CAD" | "CAE" | "CAM"; description: string; sourceRepository: string; sourceCommit: string; version: string; entrypoint: string; inputSchema: Record<string, unknown>; outputSchema: Record<string, unknown>; requiredDependencies: string[]; runtime: string; permissions: ExternalSkillPermission[]; status: ExternalSkillStatus; testStatus: "NOT_EXECUTED" | "EXECUTED"; securityStatus: "PARTIAL" | "BLOCKED"; limitations: string[] };
export type ExternalTextToCadExecution = { status: ExternalSkillStatus; skill: ExternalTextToCadSkill; input?: RectangularPlateInput; stdout?: string; stderr?: string; sourceFileSha256?: string; stepBytes?: Buffer; stepSha256?: string; executionPath: string[]; limitations: string[] };
export type ExternalTextToCadRuntimeReadiness = { status: "AVAILABLE" | "DEPENDENCY_MISSING" | "ENGINE_INVALID"; runtimeRoot: string; sourceRoot: string; python: string; sourceCommit?: string; diagnostics: string[] };

function runtimeConfig() { return { runtimeRoot: process.env.TEXT_TO_CAD_RUNTIME_ROOT, sourceRoot: process.env.TEXT_TO_CAD_SOURCE_ROOT, python: process.env.TEXT_TO_CAD_PYTHON ?? "python3" }; }
function safeText(value: string) { return value.length > 2_000 ? value.slice(0, 2_000) : value; }
function pinnedSourceCommit(sourceRoot: string) { try { return execFileSync("git", ["-C", sourceRoot, "rev-parse", "HEAD"], { encoding: "utf8", timeout: 3_000, stdio: ["ignore", "pipe", "ignore"] }).trim(); } catch { return undefined; } }
function allowedConfig() { const config = runtimeConfig(); return config.runtimeRoot === ALLOWED_RUNTIME_ROOT && config.sourceRoot === ALLOWED_SOURCE_ROOT && config.python === "python3" ? config : undefined; }

/** Explicit runtime discovery. It never downloads, upgrades, or falls back to a non-pinned source. */
export function inspectExternalTextToCadRuntime(): ExternalTextToCadRuntimeReadiness {
  const config = allowedConfig(); const diagnostics: string[] = [];
  if (!config) return { status: "DEPENDENCY_MISSING", runtimeRoot: ALLOWED_RUNTIME_ROOT, sourceRoot: ALLOWED_SOURCE_ROOT, python: "python3", diagnostics: ["TEXT_TO_CAD_RUNTIME_ROOT, TEXT_TO_CAD_SOURCE_ROOT, and TEXT_TO_CAD_PYTHON must exactly match the adapter-owned allowlist."] };
  const manifestPath = join(config.runtimeRoot!, REQUIRED_RUNTIME_MANIFEST); const cliPath = join(config.sourceRoot!, "skills", "cad", "scripts", "gen", "cli.py"); const packages = join(config.runtimeRoot!, "site-packages");
  if (!existsSync(packages) || !existsSync(join(packages, "cadgen")) || !existsSync(join(packages, "build123d")) || !existsSync(cliPath) || !existsSync(manifestPath)) return { status: "DEPENDENCY_MISSING", runtimeRoot: config.runtimeRoot!, sourceRoot: config.sourceRoot!, python: config.python, diagnostics: ["The pinned source, adapter CLI, package target, or immutable runtime manifest is missing. Run the explicit project bootstrap; no execution fallback exists."] };
  const sourceCommit = pinnedSourceCommit(config.sourceRoot!); if (sourceCommit !== TEXT_TO_CAD_SOURCE_COMMIT) return { status: "ENGINE_INVALID", runtimeRoot: config.runtimeRoot!, sourceRoot: config.sourceRoot!, python: config.python, sourceCommit, diagnostics: ["The source checkout HEAD does not equal the pinned adapter revision."] };
  try { const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, unknown>; if (manifest.sourceRepository !== TEXT_TO_CAD_SOURCE_REPOSITORY || manifest.sourceCommit !== TEXT_TO_CAD_SOURCE_COMMIT || manifest.cadgen !== "0.4.26" || manifest.build123d !== "0.11.1") return { status: "ENGINE_INVALID", runtimeRoot: config.runtimeRoot!, sourceRoot: config.sourceRoot!, python: config.python, sourceCommit, diagnostics: ["The runtime manifest does not match the adapter's pinned source and package contract."] }; } catch { return { status: "ENGINE_INVALID", runtimeRoot: config.runtimeRoot!, sourceRoot: config.sourceRoot!, python: config.python, sourceCommit, diagnostics: ["The required runtime manifest is unreadable or malformed."] }; }
  return { status: "AVAILABLE", runtimeRoot: config.runtimeRoot!, sourceRoot: config.sourceRoot!, python: config.python, sourceCommit, diagnostics };
}
export function getExternalTextToCadSkills(): ExternalTextToCadSkill[] { const readiness = inspectExternalTextToCadRuntime(); return [{ skillId: TEXT_TO_CAD_SKILL_ID, name: "text-to-cad controlled rectangular plate", domain: "CAD", description: "Runs the pinned upstream CAD generator only for an adapter-owned deterministic rectangular plate source; output must re-enter CAD-AGENT through managed STEP ingestion and OpenCascade validation.", sourceRepository: TEXT_TO_CAD_SOURCE_REPOSITORY, sourceCommit: TEXT_TO_CAD_SOURCE_COMMIT, version: "cadgen==0.4.26", entrypoint: "skills/cad/scripts/gen/cli.py", inputSchema: { type: "object", required: ["widthMm", "heightMm", "thicknessMm", "unit"], additionalProperties: false }, outputSchema: { type: "object", required: ["stepBytes", "stepSha256"], additionalProperties: false }, requiredDependencies: ["Python 3.11+", "cadgen==0.4.26", "build123d==0.11.1"], runtime: "short-lived adapter-owned Python process; no viewer server", permissions: ["READ", "WRITE", "EXECUTE", "EXPORT"], status: readiness.status === "AVAILABLE" ? "AVAILABLE" : readiness.status === "ENGINE_INVALID" ? "SECURITY_REJECTED" : "DEPENDENCY_MISSING", testStatus: "NOT_EXECUTED", securityStatus: "PARTIAL", limitations: ["Upstream CAD Viewer is not started because it is an unauthenticated local-filesystem service.", "The adapter accepts no arbitrary user Python, target path, command, network URL, or external skill CLI arguments.", "Execution is disabled unless the exact pinned source revision and local runtime manifest are present.", "CAE and CAM skills are not activated by this adapter."] }]; }
function validatePlate(input: unknown): RectangularPlateInput | undefined { if (!input || typeof input !== "object") return undefined; const value = input as Partial<RectangularPlateInput>; if (Object.keys(value).some((key) => !["widthMm", "heightMm", "thicknessMm", "unit"].includes(key))) return undefined; if (value.unit !== "mm" || ![value.widthMm, value.heightMm, value.thicknessMm].every((item) => typeof item === "number" && Number.isFinite(item) && item > 0 && item <= 10_000)) return undefined; return { widthMm: value.widthMm!, heightMm: value.heightMm!, thicknessMm: value.thicknessMm!, unit: "mm" }; }
function run(command: string, args: string[], cwd: string, env: NodeJS.ProcessEnv) { return new Promise<{ code: number | null; stdout: string; stderr: string }>((resolvePromise, reject) => { const child = spawn(command, args, { cwd, env, stdio: ["ignore", "pipe", "pipe"] }); let stdout = ""; let stderr = ""; child.stdout.on("data", (chunk) => { stdout = safeText(stdout + String(chunk)); }); child.stderr.on("data", (chunk) => { stderr = safeText(stderr + String(chunk)); }); child.once("error", reject); child.once("close", (code) => resolvePromise({ code, stdout, stderr })); }); }
export async function executeExternalTextToCadPlate(input: unknown): Promise<ExternalTextToCadExecution> { const skill = getExternalTextToCadSkills()[0]; const plate = validatePlate(input); if (!plate) return { status: "VALIDATION_FAILED", skill, executionPath: ["INPUT_SCHEMA_VALIDATION"], limitations: ["The adapter accepts only explicit positive widthMm, heightMm, thicknessMm values and unit mm."] }; const readiness = inspectExternalTextToCadRuntime(); if (readiness.status !== "AVAILABLE") return { status: readiness.status === "ENGINE_INVALID" ? "SECURITY_REJECTED" : "DEPENDENCY_MISSING", skill, input: plate, executionPath: ["ADAPTER_CONFIGURATION", readiness.status], limitations: readiness.diagnostics }; const workdir = resolve(readiness.runtimeRoot, "runs", `plate-${randomUUID()}`); const generatorName = "external_plate.step.py"; const stepName = "external_plate.step"; await mkdir(workdir, { recursive: true }); const source = `from build123d import Box\n\ndef gen_step():\n    return Box(${plate.widthMm}, ${plate.heightMm}, ${plate.thicknessMm})\n`; const sourcePath = join(workdir, generatorName); const stepPath = join(workdir, stepName); await writeFile(sourcePath, source, "utf8"); try { const result = await run(readiness.python, [join(readiness.sourceRoot, "skills", "cad", "scripts", "gen", "cli.py"), generatorName, "--write", "--json"], workdir, { ...process.env, PYTHONPATH: join(readiness.runtimeRoot, "site-packages"), HOME: workdir, NO_PROXY: "*" }); if (result.code !== 0 || !existsSync(stepPath)) return { status: "FAILED", skill, input: plate, stdout: result.stdout, stderr: result.stderr, sourceFileSha256: createHash("sha256").update(source).digest("hex"), executionPath: ["ADAPTER_OWNED_SOURCE", "PINNED_EXTERNAL_GEN_CLI"], limitations: ["The upstream CLI did not produce its expected STEP output; no CAD-AGENT artifact was created."] }; const stepBytes = await readFile(stepPath); return { status: "EXECUTABLE", skill: { ...skill, status: "EXECUTABLE", testStatus: "EXECUTED" }, input: plate, stdout: result.stdout, stderr: result.stderr, sourceFileSha256: createHash("sha256").update(source).digest("hex"), stepBytes, stepSha256: createHash("sha256").update(stepBytes).digest("hex"), executionPath: ["ADAPTER_OWNED_SOURCE", "PINNED_EXTERNAL_GEN_CLI", "STEP_OUTPUT"], limitations: skill.limitations }; } finally { await rm(workdir, { recursive: true, force: true }); } }
