import { createHash } from "node:crypto";

import type { CAEEvidenceGraph, ExternalEvidenceLifecycleEvent, ExternalEvidenceVerificationRecord, ExternalHostileTestEvidence, ExternalInfrastructureEvidence, ExternalVerificationReadiness, IndependentSandboxReview, IsolatedHostileTestEnvironment } from "../shared/cae";
import { INFRASTRUCTURE_EVIDENCE_KINDS } from "../shared/cae";
import { appendTrustSecurityAudit, listReviewerIdentities } from "./caeTrust";
import { appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";

type Access = { projectId: string; accessKey: string };
type EvidenceType = "INFRASTRUCTURE" | "SANDBOX_REVIEW" | "HOSTILE_TEST" | "HOSTILE_TEST_ENVIRONMENT";
type ExternalStatus = "VERIFIED" | "UNVERIFIED" | "UNKNOWN" | "EXPIRED" | "REVOKED" | "INVALID";
const makeId = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
let lastTimestamp = 0;
const now = () => { const next = Math.max(Date.now(), lastTimestamp + 1); lastTimestamp = next; return new Date(next).toISOString(); };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const parse = <T,>(value: string): T | undefined => { try { return JSON.parse(value) as T; } catch { return undefined; } };
const isExpired = (value?: string) => Boolean(value && new Date(value).getTime() <= Date.now());

async function authorize(args: Access) { return openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function records<T>(args: Access, kind: "CAE_EXTERNAL_INFRASTRUCTURE_EVIDENCE" | "CAE_EXTERNAL_SANDBOX_REVIEW" | "CAE_EXTERNAL_HOSTILE_TEST_ENVIRONMENT" | "CAE_EXTERNAL_HOSTILE_TEST_EVIDENCE" | "CAE_EXTERNAL_EVIDENCE_LIFECYCLE" | "CAE_EXTERNAL_EVIDENCE_VERIFICATION" | "CAE_EXTERNAL_VERIFICATION_READINESS") { await authorize(args); return (await projectMemorySnapshot(args)).records.filter((record) => record.kind === kind).flatMap((record) => { const item = parse<T>(record.content); return item ? [item] : []; }); }
function latest<T extends { createdAt: string }>(items: T[]) { return [...items].sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
function evidenceProvenance(args: { source: string; issuer: string; timestamp: string; rawEvidence: string; originalHash: string; verificationMethod: string; verifier?: string }) { const computed = hash(args.rawEvidence); if (computed !== args.originalHash.toLowerCase()) throw new Error("Original hash does not match raw evidence; import rejected."); return { source: args.source, issuer: args.issuer, timestamp: args.timestamp, originalHash: computed, rawEvidence: args.rawEvidence, verificationMethod: args.verificationMethod, verifier: args.verifier }; }
async function lifecycle(args: Access) { return records<ExternalEvidenceLifecycleEvent>(args, "CAE_EXTERNAL_EVIDENCE_LIFECYCLE"); }
async function verification(args: Access, evidenceType: EvidenceType, evidenceId: string) { return latest((await records<ExternalEvidenceVerificationRecord>(args, "CAE_EXTERNAL_EVIDENCE_VERIFICATION")).filter((record) => record.evidenceType === evidenceType && record.evidenceId === evidenceId))[0]; }
async function status(args: Access, evidenceType: EvidenceType, evidenceId: string, validUntil?: string): Promise<ExternalStatus> { const event = latest((await lifecycle(args)).filter((item) => item.evidenceType === evidenceType && item.evidenceId === evidenceId))[0]; if (event?.event === "REVOKED") return "REVOKED"; if (event?.event === "EXPIRED" || event?.event === "SUPERSEDED" || isExpired(validUntil)) return "EXPIRED"; const result = await verification(args, evidenceType, evidenceId); return result?.status ?? "UNVERIFIED"; }

export async function importInfrastructureEvidence(args: Access & { kind: ExternalInfrastructureEvidence["kind"]; measurement: string; measurementMethod: string; environment: string; source: string; issuer: string; timestamp: string; rawEvidence: string; originalHash: string; verificationMethod: string; verifier?: string; validUntil?: string }) { await authorize(args); const evidence: ExternalInfrastructureEvidence = { evidenceId: makeId("EXTERNAL-INFRA"), projectId: args.projectId, kind: args.kind, measurement: args.measurement, measurementMethod: args.measurementMethod, environment: args.environment, provenance: evidenceProvenance(args), verificationStatus: "UNVERIFIED", validUntil: args.validUntil, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EXTERNAL_INFRASTRUCTURE_EVIDENCE", title: `External infrastructure evidence · ${evidence.kind} · UNVERIFIED`, content: JSON.stringify(evidence), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await appendTrustSecurityAudit(args, { actor: args.verifier ?? "EXTERNAL_SOURCE", action: "EXTERNAL_EVIDENCE_IMPORT", objectType: "EXTERNAL_EVIDENCE", objectId: evidence.evidenceId, newState: "UNVERIFIED", reason: "Raw external infrastructure evidence and its original SHA-256 were preserved. Import is not independent verification." }); return evidence; }
export async function listInfrastructureEvidence(args: Access) { return Promise.all((await records<ExternalInfrastructureEvidence>(args, "CAE_EXTERNAL_INFRASTRUCTURE_EVIDENCE")).map(async (item) => ({ ...item, verificationStatus: await status(args, "INFRASTRUCTURE", item.evidenceId, item.validUntil) }))); }

export async function importSandboxReview(args: Access & { reviewer: string; organization: string; scope: string; architectureRevision: string; findings: string[]; severity: IndependentSandboxReview["severity"]; source: string; issuer: string; timestamp: string; rawEvidence: string; originalHash: string; verificationMethod: string; verifier?: string; reportedStatus: IndependentSandboxReview["reportedStatus"]; validUntil?: string }) { await authorize(args); const review: IndependentSandboxReview = { reviewId: makeId("SANDBOX-REVIEW"), projectId: args.projectId, reviewer: args.reviewer, organization: args.organization, scope: args.scope, architectureRevision: args.architectureRevision, findings: args.findings, severity: args.severity, evidence: evidenceProvenance(args), reviewDate: args.timestamp, reportedStatus: args.reportedStatus, status: args.reportedStatus === "REJECTED" ? "REJECTED" : args.reportedStatus === "IN_REVIEW" ? "IN_REVIEW" : "NOT_REVIEWED", verificationStatus: "UNVERIFIED", validUntil: args.validUntil, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EXTERNAL_SANDBOX_REVIEW", title: `External sandbox review · ${review.status} · UNVERIFIED`, content: JSON.stringify(review), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await appendTrustSecurityAudit(args, { actor: args.reviewer, action: "EXTERNAL_EVIDENCE_IMPORT", objectType: "SANDBOX_REVIEW", objectId: review.reviewId, newState: review.status, reason: "Sandbox review imported. A reported acceptance cannot become ACCEPTED until a verified independent evidence reviewer records verification." }); return review; }
export async function listSandboxReviews(args: Access) { return Promise.all((await records<IndependentSandboxReview>(args, "CAE_EXTERNAL_SANDBOX_REVIEW")).map(async (item) => { const verificationStatus = await status(args, "SANDBOX_REVIEW", item.reviewId, item.validUntil); return { ...item, verificationStatus, status: verificationStatus === "EXPIRED" ? "EXPIRED" as const : item.reportedStatus === "ACCEPTED" && verificationStatus === "VERIFIED" ? "ACCEPTED" as const : item.status }; })); }

export async function registerHostileTestEnvironment(args: Access & { environmentName: string; declaredIsolation: "DESIGNED" | "UNKNOWN" }) { await authorize(args); const environment: IsolatedHostileTestEnvironment = { environmentId: makeId("HOSTILE-TEST-ENV"), projectId: args.projectId, environmentName: args.environmentName, isolationRequirements: ["PRODUCTION", "USER_PROJECTS", "CAD_DATA", "CAE_DATA", "CREDENTIALS", "PERSISTENT_PROJECT_STORAGE"], declaredIsolation: args.declaredIsolation, verificationStatus: "UNVERIFIED", productionExecutionProhibited: true, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EXTERNAL_HOSTILE_TEST_ENVIRONMENT", title: `Isolated hostile-test environment · ${environment.declaredIsolation} · UNVERIFIED`, content: JSON.stringify(environment), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM" } }); await appendTrustSecurityAudit(args, { actor: "SYSTEM", action: "REGISTRATION", objectType: "HOSTILE_TEST_ENVIRONMENT", objectId: environment.environmentId, newState: environment.declaredIsolation, reason: "This contract separates a future hostile-test environment from production, user projects, CAD/CAE data, credentials, and persistent project storage. It does not execute a test or prove isolation." }); return environment; }
export async function listHostileTestEnvironments(args: Access) { return Promise.all((await records<IsolatedHostileTestEnvironment>(args, "CAE_EXTERNAL_HOSTILE_TEST_ENVIRONMENT")).map(async (item) => ({ ...item, verificationStatus: await status(args, "HOSTILE_TEST_ENVIRONMENT", item.environmentId) }))); }

export async function importHostileTestEvidence(args: Access & { testId: string; environmentId: string; testVersion: string; attackDescription: string; expectedResult: string; actualResult: string; logs: string; artifacts: string[]; timestamp: string; hash: string; reviewer: string; status: ExternalHostileTestEvidence["status"]; source: string; issuer: string; rawEvidence: string; originalHash: string; verificationMethod: string; verifier?: string; validUntil?: string }) { const environment = (await listHostileTestEnvironments(args)).find((item) => item.environmentId === args.environmentId); if (!environment || environment.declaredIsolation !== "DESIGNED") throw new Error("A declared isolated hostile-test environment is required before evidence can be imported."); if (hash(`${args.logs}\n${args.artifacts.join("\n")}`) !== args.hash.toLowerCase()) throw new Error("Hostile-test log/artifact hash mismatch; import rejected."); const evidence: ExternalHostileTestEvidence = { evidenceId: makeId("HOSTILE-TEST-EVIDENCE"), projectId: args.projectId, testId: args.testId, environmentId: args.environmentId, testVersion: args.testVersion, attackDescription: args.attackDescription, expectedResult: args.expectedResult, actualResult: args.actualResult, logs: args.logs, artifacts: args.artifacts, timestamp: args.timestamp, hash: args.hash.toLowerCase(), reviewer: args.reviewer, status: args.status, provenance: evidenceProvenance(args), verificationStatus: "UNVERIFIED", validUntil: args.validUntil, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EXTERNAL_HOSTILE_TEST_EVIDENCE", title: `External hostile-test evidence · ${evidence.status} · UNVERIFIED`, content: JSON.stringify(evidence), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await appendTrustSecurityAudit(args, { actor: args.reviewer, action: "EXTERNAL_EVIDENCE_IMPORT", objectType: "HOSTILE_TEST_EVIDENCE", objectId: evidence.evidenceId, newState: evidence.status, reason: "Imported external hostile-test evidence preserves logs, artifacts, hashes, and provenance. Import does not execute a test or verify its claimed result." }); return evidence; }
export async function listHostileTestEvidence(args: Access) { return Promise.all((await records<ExternalHostileTestEvidence>(args, "CAE_EXTERNAL_HOSTILE_TEST_EVIDENCE")).map(async (item) => ({ ...item, verificationStatus: await status(args, "HOSTILE_TEST", item.evidenceId, item.validUntil) }))); }

export async function verifyExternalEvidence(args: Access & { evidenceType: EvidenceType; evidenceId: string; reviewerId: string; sourceVerified: boolean; verificationMethod: string; reason: string }) { const reviewer = (await listReviewerIdentities(args)).find((item) => item.reviewerId === args.reviewerId); if (!reviewer || reviewer.identityStatus !== "VERIFIED" || !reviewer.permissions.includes("APPROVE_VALIDATION")) throw new Error("External evidence requires a verified reviewer with validation-approval permission."); const found = args.evidenceType === "INFRASTRUCTURE" ? (await listInfrastructureEvidence(args)).some((item) => item.evidenceId === args.evidenceId) : args.evidenceType === "SANDBOX_REVIEW" ? (await listSandboxReviews(args)).some((item) => item.reviewId === args.evidenceId) : args.evidenceType === "HOSTILE_TEST" ? (await listHostileTestEvidence(args)).some((item) => item.evidenceId === args.evidenceId) : (await listHostileTestEnvironments(args)).some((item) => item.environmentId === args.evidenceId); if (!found) throw new Error("External evidence not found in this project."); const verificationRecord: ExternalEvidenceVerificationRecord = { verificationId: makeId("EXTERNAL-VERIFICATION"), projectId: args.projectId, evidenceType: args.evidenceType, evidenceId: args.evidenceId, reviewerId: args.reviewerId, verificationMethod: args.verificationMethod, sourceVerified: args.sourceVerified, status: args.sourceVerified ? "VERIFIED" : "UNVERIFIED", reason: args.reason, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EXTERNAL_EVIDENCE_VERIFICATION", title: `External evidence verification · ${verificationRecord.status}`, content: JSON.stringify(verificationRecord), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM" } }); await appendTrustSecurityAudit(args, { actor: reviewer.displayName, action: "VERIFICATION", objectType: "EXTERNAL_EVIDENCE", objectId: args.evidenceId, newState: verificationRecord.status, reason: args.reason }); return verificationRecord; }
export async function recordExternalEvidenceLifecycle(args: Access & { evidenceType: EvidenceType; evidenceId: string; event: ExternalEvidenceLifecycleEvent["event"]; reason: string; replacementEvidenceId?: string; actor: string }) { const event: ExternalEvidenceLifecycleEvent = { eventId: makeId("EXTERNAL-LIFECYCLE"), projectId: args.projectId, evidenceType: args.evidenceType, evidenceId: args.evidenceId, event: args.event, reason: args.reason, replacementEvidenceId: args.replacementEvidenceId, actor: args.actor, createdAt: now() }; await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EXTERNAL_EVIDENCE_LIFECYCLE", title: `External evidence lifecycle · ${event.event}`, content: JSON.stringify(event), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "USER" } }); await appendTrustSecurityAudit(args, { actor: args.actor, action: "EXTERNAL_EVIDENCE_LIFECYCLE", objectType: "EXTERNAL_EVIDENCE", objectId: args.evidenceId, previousState: "PRESERVED", newState: event.event, reason: args.reason }); return event; }

export async function evaluateExternalVerificationReadiness(args: Access): Promise<ExternalVerificationReadiness> {
  const infrastructure = await listInfrastructureEvidence(args);
  const sandboxReviews = await listSandboxReviews(args);
  const environments = await listHostileTestEnvironments(args);
  const hostileTests = await listHostileTestEvidence(args);
  const latestInfrastructure = INFRASTRUCTURE_EVIDENCE_KINDS.map((kind) => latest(infrastructure.filter((item) => item.kind === kind))[0]);
  const latestSandbox = latest(sandboxReviews)[0];
  const currentHostileTests = Array.from(new Set(hostileTests.map((item) => item.testId))).map((testId) => latest(hostileTests.filter((item) => item.testId === testId))[0]!);
  const contradictions = [...new Set(latestInfrastructure.flatMap((item) => !item ? [] : infrastructure.filter((candidate) => candidate.kind === item.kind && candidate.environment === item.environment && candidate.verificationStatus === "VERIFIED" && candidate.measurement !== item.measurement).map(() => `${item.kind} has contradictory verified measurements for ${item.environment}.`)))];
  const infrastructurePass = latestInfrastructure.every((item) => item?.verificationStatus === "VERIFIED");
  const sandboxPass = sandboxReviews.some((item) => item.status === "ACCEPTED" && item.verificationStatus === "VERIFIED");
  const environmentPass = environments.some((item) => item.declaredIsolation === "DESIGNED" && item.productionExecutionProhibited && item.verificationStatus === "VERIFIED");
  const hostilePass = currentHostileTests.length > 0 && currentHostileTests.every((item) => item.status === "PASS" && item.verificationStatus === "VERIFIED");
  const currentEvidence = [...latestInfrastructure.filter(Boolean), ...(latestSandbox ? [latestSandbox] : []), ...currentHostileTests];
  const provenancePass = currentEvidence.length > 0 && currentEvidence.every((item: any) => { const provenance = item.provenance ?? item.evidence; return Boolean(provenance?.originalHash && provenance?.source && provenance?.issuer && provenance?.verificationMethod); });
  const lifecycleUnsafe = currentEvidence.some((item: any) => item.verificationStatus === "EXPIRED" || item.verificationStatus === "REVOKED");
  const lifecyclePass = currentEvidence.length > 0 && currentEvidence.every((item: any) => item.verificationStatus === "VERIFIED") && !lifecycleUnsafe;
  const gates = [
    { gate: "INFRASTRUCTURE" as const, status: infrastructurePass ? "PASS" as const : latestInfrastructure.some((item) => !item) ? "UNKNOWN" as const : "NOT_VERIFIED" as const, statement: infrastructurePass ? "All seven infrastructure categories have current verified external evidence." : "Infrastructure evidence is incomplete, unknown, unverified, expired, revoked, or contradictory.", evidenceIds: latestInfrastructure.filter(Boolean).map((item) => item!.evidenceId) },
    { gate: "SANDBOX_REVIEW" as const, status: sandboxPass ? "PASS" as const : sandboxReviews.length ? "NOT_VERIFIED" as const : "UNKNOWN" as const, statement: sandboxPass ? "A current accepted sandbox review is independently verified." : "No current independently verified accepted sandbox review exists.", evidenceIds: sandboxReviews.map((item) => item.reviewId) },
    { gate: "HOSTILE_TEST_ENVIRONMENT" as const, status: environmentPass ? "PASS" as const : environments.length ? "NOT_VERIFIED" as const : "UNKNOWN" as const, statement: environmentPass ? "A non-production hostile-test environment has independently verified isolation evidence." : "No independently verified isolated hostile-test environment exists.", evidenceIds: environments.map((item) => item.environmentId) },
    { gate: "HOSTILE_TEST_EVIDENCE" as const, status: hostilePass ? "PASS" as const : hostileTests.length ? "NOT_VERIFIED" as const : "UNKNOWN" as const, statement: hostilePass ? "All current hostile-test evidence is external, passing, and independently verified." : "No complete current independently verified passing hostile-test evidence set exists.", evidenceIds: currentHostileTests.map((item) => item.evidenceId) },
    { gate: "EVIDENCE_PROVENANCE" as const, status: provenancePass ? "PASS" as const : "UNKNOWN" as const, statement: provenancePass ? "Every current evidence item preserves source, issuer, timestamp, raw evidence, original hash, and verification method." : "Evidence provenance is absent or incomplete.", evidenceIds: [] },
    { gate: "EVIDENCE_LIFECYCLE" as const, status: lifecycleUnsafe ? "FAIL" as const : lifecyclePass ? "PASS" as const : "UNKNOWN" as const, statement: lifecycleUnsafe ? "Expired or revoked external evidence cannot satisfy readiness." : lifecyclePass ? "All current evidence is verified and not expired, revoked, or superseded." : "No complete lifecycle-safe verified evidence set exists.", evidenceIds: [] },
  ];
  const allPass = gates.every((gate) => gate.status === "PASS") && !contradictions.length;
  const missingRequiredEvidence = gates.some((gate) => gate.status === "UNKNOWN");
  const partiallyReady = gates.some((gate) => gate.status === "PASS") && !contradictions.length && !lifecycleUnsafe && !missingRequiredEvidence;
  const readinessState = contradictions.length || lifecycleUnsafe || missingRequiredEvidence ? "NOT_READY" as const : allPass ? "READY_FOR_EXTERNAL_REVIEW" as const : partiallyReady ? "PARTIALLY_READY" as const : "NOT_READY" as const;
  const reason = contradictions.length ? "Contradictory evidence fails closed. Runtime readiness is NOT_READY." : lifecycleUnsafe ? "Expired or revoked evidence fails closed. Runtime readiness is NOT_READY." : missingRequiredEvidence ? "Required external evidence is absent. Runtime readiness is NOT_READY." : allPass ? "External evidence supports external review only. Execution remains disabled." : "Required external evidence is unverified, incomplete, or not executed. Runtime readiness fails closed.";
  const readiness: ExternalVerificationReadiness = { readinessId: makeId("EXTERNAL-READINESS"), projectId: args.projectId, contractVersion: "1.0.0", gates, openGaps: gates.filter((gate) => gate.status !== "PASS").map((gate) => gate.statement), contradictions, readiness: readinessState, executionApproval: "DISABLED", executionEligible: false, executable: false, reason, createdAt: now() };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_EXTERNAL_VERIFICATION_READINESS", title: `Phase 6.2 external verification readiness · ${readiness.readiness}`, content: JSON.stringify(readiness), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM" } });
  await appendTrustSecurityAudit(args, { actor: "SYSTEM", action: "EXTERNAL_VERIFICATION_READINESS", objectType: "EXTERNAL_VERIFICATION_READINESS", objectId: readiness.readinessId, newState: readiness.readiness, reason: readiness.reason });
  return readiness;
}
export async function listExternalVerificationReadiness(args: Access) { return latest(await records<ExternalVerificationReadiness>(args, "CAE_EXTERNAL_VERIFICATION_READINESS")); }
export async function buildExternalVerificationGraph(args: Access & { readinessId?: string }): Promise<CAEEvidenceGraph> { const readiness = args.readinessId ? (await records<ExternalVerificationReadiness>(args, "CAE_EXTERNAL_VERIFICATION_READINESS")).find((item) => item.readinessId === args.readinessId) : (await listExternalVerificationReadiness(args))[0]; if (!readiness) return { projectId: args.projectId, simulationId: "EXTERNAL-VERIFICATION", nodes: [], edges: [], limitations: ["No Phase 6.2 readiness record exists. Execution remains disabled."] }; const infrastructure = await listInfrastructureEvidence(args); const sandbox = await listSandboxReviews(args); const environments = await listHostileTestEnvironments(args); const tests = await listHostileTestEvidence(args); const nodes = [{ id: readiness.readinessId, type: "EXTERNAL_VERIFICATION_READINESS" as const, label: readiness.readiness, truthStatus: "UNVALIDATED" as const }, ...infrastructure.map((item) => ({ id: item.evidenceId, type: "EXTERNAL_INFRASTRUCTURE_EVIDENCE" as const, label: `${item.kind} · ${item.verificationStatus}`, truthStatus: item.verificationStatus === "VERIFIED" ? "VERIFIED" as const : "UNKNOWN" as const })), ...sandbox.map((item) => ({ id: item.reviewId, type: "EXTERNAL_SANDBOX_REVIEW" as const, label: `${item.status} · ${item.verificationStatus}`, truthStatus: "UNVALIDATED" as const })), ...environments.map((item) => ({ id: item.environmentId, type: "HOSTILE_TEST_ENVIRONMENT" as const, label: item.declaredIsolation, truthStatus: "UNVALIDATED" as const })), ...tests.map((item) => ({ id: item.evidenceId, type: "EXTERNAL_HOSTILE_TEST_EVIDENCE" as const, label: `${item.status} · ${item.verificationStatus}`, truthStatus: "UNVALIDATED" as const })), ...readiness.gates.map((item) => ({ id: `${readiness.readinessId}-${item.gate}`, type: "EXTERNAL_VERIFICATION_GATE" as const, label: `${item.gate} · ${item.status}`, truthStatus: "UNVALIDATED" as const }))]; const edges = nodes.filter((item) => item.id !== readiness.readinessId).map((item) => ({ id: makeId("EXTERNAL-GRAPH"), fromId: item.id, toId: readiness.readinessId, relationship: "external verification readiness evidence", status: "UNKNOWN" as const })); return { projectId: args.projectId, simulationId: "EXTERNAL-VERIFICATION", nodes, edges, limitations: [...readiness.openGaps, ...readiness.contradictions, "No solver, hostile test, shell, plugin, arbitrary process, network, filesystem, or credential execution occurs in the production system."] }; }
