import { extractKernelViewerMesh, getOpenCascadeKernel } from "./cadKernel";
import { appendLineageNode, appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";
import { storagePut } from "./storage";
import type { CircleFeatureInput, FeatureHistoryComparison, FeatureHistoryFailure, FeatureHistoryRevision, FeaturePlanEdit, FeatureParameter, CADFeatureHistoryNode, FilletReadinessGate, TopologyInspection } from "../shared/featureHistory";

const histories = new Map<string, FeatureHistoryRevision[]>();
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const key = (projectId: string, revisionId: string) => `${projectId}:${revisionId}`;
const previews = new Map<string, FeatureHistoryRevision>();

type RectangularFeatureInput = { title: string; width: number; height: number; extrudeDistance: number; unit: "mm" | "cm" | "m" };
type HistoryArgs = { projectId: string; accessKey: string };
function toMm(value: number, unit: RectangularFeatureInput["unit"]) { if (!Number.isFinite(value)) throw new Error("A feature parameter must be a finite number."); if (unit === "mm") return value; if (unit === "cm") return value * 10; if (unit === "m") return value * 1000; throw new Error("Ambiguous or unsupported unit. Use mm, cm, or m explicitly."); }
function parameter(name: FeatureParameter["name"], value: number, source: FeatureParameter["provenance"] = "USER"): FeatureParameter { return { name, value, unit: "mm", normalizedValueMm: value, editable: true, provenance: source }; }
function failure(stage: FeatureHistoryFailure["stage"], reason: string, featureId?: string, parameterName?: string, affectedDependencies: string[] = [], corrections: string[] = []): FeatureHistoryFailure { return { stage, reason, featureId, parameter: parameterName, affectedDependencies, corrections }; }
function publicRevision(revision: FeatureHistoryRevision): FeatureHistoryRevision { return { ...revision, geometry: { validation: revision.geometry.validation, kernel: revision.geometry.kernel, boundingBox: revision.geometry.boundingBox, topology: revision.geometry.topology, export: revision.geometry.export }, features: revision.features.map((node) => ({ ...node, inputGeometryReferences: node.inputGeometryReferences.map((ref) => ({ ...ref })), parameters: node.parameters.map((item) => ({ ...item })), constraints: node.constraints.map((item) => ({ ...item })) })) }; }
async function authorize(args: HistoryArgs) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function persistRevision(args: HistoryArgs, revision: FeatureHistoryRevision) {
  const parentSnapshot = await projectMemorySnapshot(args); const parent = revision.parentRevisionId ? parentSnapshot.lineage.find((node) => node.title.includes(revision.parentRevisionId!)) : undefined;
  const node = await appendLineageNode({ ...args, node: { kind: "REVISION", parentId: parent?.id, title: `Feature history revision · ${revision.revisionId}`, reasonForChange: revision.decisionSummary, changeSummary: `Feature chain: ${revision.features.map((feature) => feature.featureType).join(" → ")}. The new revision is immutable; its parent remains unchanged.`, status: "VALIDATED", authorSource: "CAD_AGENT" } });
  await appendPersistentMemory({ ...args, record: { kind: "FEATURE_REVISION", title: `Kernel validated feature history · ${revision.revisionId}`, content: JSON.stringify({ revision: publicRevision(revision), lineageId: node.id }), truthStatus: "DERIVED", validationStage: "GEOMETRICALLY_VALIDATED", relatedConfigurationId: revision.revisionId, authorSource: "CAD_AGENT" } });
  await appendPersistentMemory({ ...args, record: { kind: "EVIDENCE", title: `Feature-history geometry evidence · ${revision.revisionId}`, content: "OpenCascade.js constructed a closed rectangular wire, made a planar face, extruded the face with BRepPrimAPI_MakePrism, validated the resulting BRep, and tessellated its actual result for the viewer. This establishes parametric and geometric kernel evidence only; engineering, physical, manufacturing, safety, and certification validity remain unverified.", truthStatus: "DERIVED", validationStage: "GEOMETRICALLY_VALIDATED", relatedConfigurationId: revision.revisionId, authorSource: "CAD_AGENT" } });
}
async function persistFailure(args: HistoryArgs, attempted: FeatureHistoryRevision) { if (!attempted.failure) return; await appendPersistentMemory({ ...args, record: { kind: "FEATURE_HISTORY", title: `Feature regeneration failed · ${attempted.revisionId}`, content: JSON.stringify({ revision: publicRevision(attempted), lastValidParent: attempted.parentRevisionId }), truthStatus: "FACT", validationStage: "CONCEPTUAL", relatedConfigurationId: attempted.parentRevisionId, authorSource: "CAD_AGENT" } }); }
async function latest(projectId: string, revisionId?: string) {
  const cached = histories.get(projectId) ?? []; if (revisionId) return cached.find((item) => item.revisionId === revisionId);
  return cached.filter((item) => item.status === "KERNEL_VALIDATED").at(-1);
}
function applyEdit(source: FeatureHistoryRevision, edit?: FeaturePlanEdit) {
  const sketch = source.features.find((feature) => feature.featureType === "RECTANGLE_SKETCH"); const extrude = source.features.find((feature) => feature.featureType === "EXTRUDE");
  if (!sketch || !extrude) return { error: failure("REFERENCE", "Source history does not contain the supported rectangular sketch and extrusion feature chain.", undefined, undefined, [], ["Create a new supported rectangular sketch-to-extrude history."]) } as const;
  const read = (feature: CADFeatureHistoryNode, name: FeatureParameter["name"]) => feature.parameters.find((item) => item.name === name)?.normalizedValueMm;
  let values = { width: read(sketch, "width") ?? Number.NaN, height: read(sketch, "height") ?? Number.NaN, extrudeDistance: read(extrude, "extrudeDistance") ?? Number.NaN };
  if (!edit) return { values, sourceRevision: source.revisionId } as const;
  if (edit.featureType && edit.featureType !== "RECTANGLE_SKETCH" && edit.featureType !== "EXTRUDE") return { error: failure("VALIDATION", `Feature type ${edit.featureType} is not kernel-backed in Phase 4.6.`, edit.featureId, undefined, [edit.featureId], ["Use RECTANGLE_SKETCH or EXTRUDE only."]) } as const;
  if (edit.operationOrder !== undefined && edit.operationOrder !== (edit.featureId === "SKETCH-001" ? 0 : 1)) return { error: failure("VALIDATION", "Feature order changes are not supported because the rectangular sketch must precede the extrusion.", edit.featureId, undefined, ["SKETCH-001", "EXTRUDE-001"], ["Keep SKETCH-001 before EXTRUDE-001."]) } as const;
  if (edit.targetReferenceId && edit.targetReferenceId !== "REF-SKETCH-001-PROFILE") return { error: failure("REFERENCE", "Topology reference is not the declared current sketch profile and cannot be silently remapped.", edit.featureId, undefined, ["SKETCH-001", "EXTRUDE-001"], ["Select REF-SKETCH-001-PROFILE from the current feature history."]) } as const;
  if (edit.parameter) values = { ...values, [edit.parameter.name]: toMm(edit.parameter.value, edit.parameter.unit) };
  return { values, sourceRevision: source.revisionId } as const;
}
async function build(args: HistoryArgs & { title: string; values: { width: number; height: number; extrudeDistance: number }; parentRevisionId?: string; preview?: boolean; decision: string }): Promise<FeatureHistoryRevision> {
  const revisionId = id(args.preview ? "FEATURE-PREVIEW" : "FEATURE-REVISION"); const base = { revisionId, projectId: args.projectId, parentRevisionId: args.parentRevisionId, title: args.title, status: args.preview ? "PREVIEW" as const : "KERNEL_VALIDATED" as const, truth: "KERNEL_VALIDATED" as const, requirementsSummary: "Feature-history foundation has no linked system requirements in this operation; geometry is intentionally engineeringally unverified.", decisionSummary: args.decision, createdAt: new Date().toISOString() };
  const invalid = Object.entries(args.values).find(([, value]) => !Number.isFinite(value) || value <= 0);
  if (invalid) return { ...base, status: "FAILED", truth: "FACT", features: [], geometry: { validation: "UNAVAILABLE", kernel: "OpenCascade.js" }, failure: failure("VALIDATION", `${invalid[0]} must be a positive finite normalized millimetre value.`, invalid[0] === "extrudeDistance" ? "EXTRUDE-001" : "SKETCH-001", invalid[0], ["SKETCH-001", "EXTRUDE-001"], ["Use an explicit positive mm, cm, or m value and preview again."]) };
  const sketch: CADFeatureHistoryNode = { featureId: "SKETCH-001", featureType: "RECTANGLE_SKETCH", implementation: "KERNEL_BACKED", parentFeatures: [], inputGeometryReferences: [], parameters: [parameter("width", args.values.width), parameter("height", args.values.height)], units: "mm", constraints: [{ id: "CONSTRAINT-HORIZONTAL", kind: "HORIZONTAL", status: "SATISFIED", description: "Opposing rectangular profile segments are built on the global X axis." }, { id: "CONSTRAINT-VERTICAL", kind: "VERTICAL", status: "SATISFIED", description: "Opposing rectangular profile segments are built on the global Y axis." }, { id: "CONSTRAINT-COINCIDENT", kind: "COINCIDENT", status: "SATISFIED", description: "The polygon is closed into a single wire." }, { id: "CONSTRAINT-WIDTH", kind: "DIMENSION", status: "SATISFIED", description: `Width = ${args.values.width} mm.` }, { id: "CONSTRAINT-HEIGHT", kind: "DIMENSION", status: "SATISFIED", description: `Height = ${args.values.height} mm.` }], dependencies: [], sourceRevision: args.parentRevisionId ?? "ROOT", resultRevision: revisionId, status: args.preview ? "PREVIEW_READY" : "KERNEL_VALIDATED", provenance: "KERNEL_VALIDATED", description: "Closed rectangular XY-plane profile constructed as a real OpenCascade polygonal wire." };
  const extrude: CADFeatureHistoryNode = { featureId: "EXTRUDE-001", featureType: "EXTRUDE", implementation: "KERNEL_BACKED", parentFeatures: [sketch.featureId], inputGeometryReferences: [{ id: "REF-SKETCH-001-PROFILE", kind: "SKETCH_PROFILE", ownerFeatureId: "SKETCH-001", sourceRevisionId: revisionId, resolution: "DECLARED", note: "The extrusion consumes only the declared rectangular sketch profile from this feature history revision." }], parameters: [parameter("extrudeDistance", args.values.extrudeDistance)], units: "mm", constraints: [{ id: "CONSTRAINT-NORMAL", kind: "DIMENSION", status: "SATISFIED", description: "Prism direction is global +Z, normal to the XY sketch plane." }], dependencies: [sketch.featureId, "REF-SKETCH-001-PROFILE"], sourceRevision: args.parentRevisionId ?? "ROOT", resultRevision: revisionId, status: args.preview ? "PREVIEW_READY" : "KERNEL_VALIDATED", provenance: "KERNEL_VALIDATED", description: "OpenCascade prism made from the current rectangular sketch face and a positive +Z vector." };
  let polygon: any; let faceMaker: any; let prism: any; let analyzer: any; let writer: any; let points: any[] = [];
  try { const oc = await getOpenCascadeKernel(); points = [[0, 0], [args.values.width, 0], [args.values.width, args.values.height], [0, args.values.height]].map(([x, y]) => new oc.gp_Pnt_3(x, y, 0)); polygon = new oc.BRepBuilderAPI_MakePolygon_1(); for (const point of points) polygon.Add_1(point); polygon.Close(); if (!polygon.IsDone()) throw new Error("OpenCascade did not close the rectangular sketch wire."); faceMaker = new oc.BRepBuilderAPI_MakeFace_15(polygon.Wire(), true); if (!faceMaker.IsDone()) throw new Error("OpenCascade did not create a planar sketch face."); prism = new oc.BRepPrimAPI_MakePrism_1(faceMaker.Face(), new oc.gp_Vec_4(0, 0, args.values.extrudeDistance), true, true); const shape = prism.Shape(); analyzer = new oc.BRepCheck_Analyzer(shape, true, false); if (!analyzer.IsValid_2()) throw new Error("OpenCascade BRep validation failed after extrusion."); const viewerMesh = extractKernelViewerMesh(oc, shape, "EXTRUDE-001"); writer = new oc.STEPControl_Writer_1(); const progress = new oc.Message_ProgressRange_1(); const path = `/feature-history-${revisionId}.step`; writer.Transfer(shape, (oc.STEPControl_StepModelType as any).STEPControl_AsIs, true, progress); writer.Write(path); const stepBase64 = Buffer.from((oc as any).FS.readFile(path)).toString("base64"); (oc as any).FS.unlink(path); return { ...base, features: [sketch, extrude], geometry: { validation: "VALID", kernel: "OpenCascade.js", viewerMesh, stepBase64, boundingBox: viewerMesh.boundingBox } }; }
  catch (error) { const reason = error instanceof Error ? error.message : "Unknown OpenCascade feature regeneration failure."; return { ...base, status: "FAILED", truth: "FACT", features: [sketch, { ...extrude, status: "FAILED", provenance: "FACT" }], geometry: { validation: "INVALID", kernel: "OpenCascade.js" }, failure: failure("KERNEL_REGENERATION", reason, "EXTRUDE-001", "extrudeDistance", ["SKETCH-001", "EXTRUDE-001"], ["Check sketch dimensions, extrusion distance, and the declared profile reference; then create a separate preview."]) }; }
  finally { analyzer?.delete?.(); writer?.delete?.(); prism?.delete?.(); faceMaker?.delete?.(); polygon?.delete?.(); for (const point of points) point.delete?.(); }
}
export async function createFeatureHistory(args: HistoryArgs & { input: RectangularFeatureInput }) { await authorize(args); const values = { width: toMm(args.input.width, args.input.unit), height: toMm(args.input.height, args.input.unit), extrudeDistance: toMm(args.input.extrudeDistance, args.input.unit) }; const revision = await build({ ...args, title: args.input.title, values, decision: "Created a real rectangular sketch-to-extrude feature chain." }); if (revision.status === "FAILED") { await persistFailure(args, revision); return revision; } histories.set(args.projectId, [...(histories.get(args.projectId) ?? []), revision]); await persistRevision(args, revision); return revision; }
export async function previewFeatureRegeneration(args: HistoryArgs & { sourceRevisionId: string; edit: FeaturePlanEdit }): Promise<FeatureHistoryRevision> { await authorize(args); const source = await latest(args.projectId, args.sourceRevisionId); if (!source) throw new Error("Source feature revision is unavailable in this controlled session. No regeneration was attempted."); const prepared = applyEdit(source, args.edit); if ("error" in prepared) { const invalid: FeatureHistoryRevision = { ...source, revisionId: id("FEATURE-PREVIEW"), status: "FAILED", truth: "FACT", features: source.features.map((feature) => ({ ...feature, status: "REFERENCE_INVALIDATED" })), geometry: { validation: "UNAVAILABLE", kernel: "OpenCascade.js" }, failure: prepared.error }; await persistFailure(args, invalid); return invalid; }
  const preview = await build({ ...args, title: `${source.title} · Preview`, values: prepared.values, parentRevisionId: source.revisionId, preview: true, decision: `Preview regeneration from ${source.revisionId} after controlled feature-plan edit ${args.edit.featureId}.` }); previews.set(key(args.projectId, preview.revisionId), preview); return preview; }
export async function executeFeatureRegeneration(args: HistoryArgs & { previewRevisionId: string }): Promise<FeatureHistoryRevision> { await authorize(args); const preview = previews.get(key(args.projectId, args.previewRevisionId)); if (!preview) throw new Error("Feature preview is unavailable or expired. Create a new preview; no source revision was changed."); if (preview.status !== "PREVIEW" || preview.geometry.validation !== "VALID") { const failed: FeatureHistoryRevision = { ...preview, status: "FAILED", truth: "FACT", failure: preview.failure ?? failure("VALIDATION", "Only a valid non-persistent feature preview can execute.", undefined, undefined, [], ["Preview the feature chain successfully before Apply."]) }; await persistFailure(args, failed); return failed; }
  const sketch = preview.features.find((feature) => feature.featureId === "SKETCH-001")!; const extrude = preview.features.find((feature) => feature.featureId === "EXTRUDE-001")!; const revision = await build({ ...args, title: preview.title.replace(" · Preview", ""), values: { width: sketch.parameters.find((item) => item.name === "width")!.normalizedValueMm, height: sketch.parameters.find((item) => item.name === "height")!.normalizedValueMm, extrudeDistance: extrude.parameters[0].normalizedValueMm }, parentRevisionId: preview.parentRevisionId, decision: `Approved regeneration from preview ${preview.revisionId}.` }); if (revision.status === "FAILED") { await persistFailure(args, revision); return revision; } histories.set(args.projectId, [...(histories.get(args.projectId) ?? []), revision]); await persistRevision(args, revision); return revision; }
export async function listFeatureHistory(args: HistoryArgs) { await authorize(args); const snapshot = await projectMemorySnapshot(args); const durable = snapshot.records.filter((record) => record.kind === "FEATURE_REVISION").flatMap((record) => { try { return [(JSON.parse(record.content) as { revision: FeatureHistoryRevision }).revision]; } catch { return []; } }); const cached = histories.get(args.projectId) ?? []; const combined = [...durable, ...cached].filter((item, index, all) => all.findIndex((candidate) => candidate.revisionId === item.revisionId) === index); return combined.sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }
export async function compareFeatureRevisions(args: HistoryArgs & { baseRevisionId: string; comparedRevisionId: string }): Promise<FeatureHistoryComparison> { const revisions = await listFeatureHistory(args); const base = revisions.find((item) => item.revisionId === args.baseRevisionId); const compared = revisions.find((item) => item.revisionId === args.comparedRevisionId); if (!base || !compared) throw new Error("Both immutable feature revisions must exist in the authorized project before comparison."); const baseParameters = base.features.flatMap((feature) => feature.parameters.map((parameter) => ({ featureId: feature.featureId, ...parameter }))); const comparedParameters = compared.features.flatMap((feature) => feature.parameters.map((parameter) => ({ featureId: feature.featureId, ...parameter }))); const keys = new Set([...baseParameters, ...comparedParameters].map((item) => `${item.featureId}:${item.name}`)); return { baseRevision: base.revisionId, comparedRevision: compared.revisionId, sameFeatureDefinitions: base.features.map((feature) => feature.featureType).join("|") === compared.features.map((feature) => feature.featureType).join("|"), parameterChanges: [...keys].map((entry) => { const [featureId, name] = entry.split(":"); return { featureId, name, baseValue: baseParameters.find((item) => item.featureId === featureId && item.name === name)?.normalizedValueMm, comparedValue: comparedParameters.find((item) => item.featureId === featureId && item.name === name)?.normalizedValueMm, unit: "mm" as const }; }).filter((item) => item.baseValue !== item.comparedValue), geometryMetadata: { base: base.geometry.boundingBox, compared: compared.geometry.boundingBox, deviationAnalysis: "NOT_IMPLEMENTED" }, requirements: { base: base.requirementsSummary, compared: compared.requirementsSummary }, decisions: { base: base.decisionSummary, compared: compared.decisionSummary }, validation: { base: base.status, compared: compared.status } }; }

export async function diagnoseFeatureHistoryFailure(args: HistoryArgs) {
  await authorize(args); const snapshot = await projectMemorySnapshot(args); const record = snapshot.records.find((item) => item.kind === "FEATURE_HISTORY");
  if (!record) return { noRecordedFailure: true, diagnosis: "NO RECORDED FEATURE-HISTORY FAILURE.", alternatives: [] as Array<{ title: string; reason: string; truth: "INFERRED" | "UNKNOWN" }> };
  try { const parsed = JSON.parse(record.content) as { revision?: FeatureHistoryRevision }; const failed = parsed.revision?.failure; if (!failed) return { noRecordedFailure: true, diagnosis: "The latest feature-history failure record has no diagnostic payload.", alternatives: [] as Array<{ title: string; reason: string; truth: "INFERRED" | "UNKNOWN" }> }; return { noRecordedFailure: false, diagnosis: `${failed.stage}: ${failed.reason} Affected dependency chain: ${failed.affectedDependencies.join(" → ") || "UNKNOWN"}.`, alternatives: failed.corrections.slice(0, 3).map((correction) => ({ title: "Create a separate corrected preview", reason: correction, truth: "INFERRED" as const })) };
  } catch { return { noRecordedFailure: true, diagnosis: "The failure record could not be decoded; no retry was attempted.", alternatives: [] as Array<{ title: string; reason: string; truth: "INFERRED" | "UNKNOWN" }> }; }
}

type CircleValues = { centerX: number; centerY: number; radius: number; extrudeDistance: number };
export function planCircularBoss(message: string) {
  const read = (label: RegExp) => { const match = message.match(label); return match ? { value: Number(match[1]), unit: match[2].toLowerCase() as "mm" | "cm" | "m" } : undefined; };
  const radius = read(/(?:radius|r)\s*(?:of|=|:)?\s*(\d+(?:\.\d+)?)\s*(mm|cm|m)\b/i); const distance = read(/(?:extrude|height|depth|length)\s*(?:of|=|:)?\s*(\d+(?:\.\d+)?)\s*(mm|cm|m)\b/i); const centerX = read(/center\s*x\s*(?:=|:)?\s*(-?\d+(?:\.\d+)?)\s*(mm|cm|m)\b/i); const centerY = read(/center\s*y\s*(?:=|:)?\s*(-?\d+(?:\.\d+)?)\s*(mm|cm|m)\b/i);
  const questions = [!radius && "What explicit circle radius should the boss use (mm, cm, or m)?", !distance && "What explicit extrusion distance should the boss use (mm, cm, or m)?", (!centerX || !centerY) && "What circle center X and Y should be used? The CAD Agent will not silently assume a location."].filter(Boolean) as string[];
  if (questions.length) return { status: "OPEN_QUESTION" as const, executable: false, operation: "CIRCLE_SKETCH → EXTRUDE", questions, limits: ["No fillet is planned or executed.", "No structural, manufacturing, safety, or production claim is made."] };
  const values = { centerX: toMm(centerX!.value, centerX!.unit), centerY: toMm(centerY!.value, centerY!.unit), radius: toMm(radius!.value, radius!.unit), extrudeDistance: toMm(distance!.value, distance!.unit) }; if (values.radius <= 0 || values.extrudeDistance <= 0) return { status: "INVALID" as const, executable: false, operation: "CIRCLE_SKETCH → EXTRUDE", questions: ["Radius and extrusion distance must be positive after unit normalization."], limits: ["No kernel call was made."] };
  return { status: "READY_FOR_PREVIEW" as const, executable: true, operation: "CIRCLE_SKETCH → EXTRUDE", input: { title: "CAD Agent circular boss", ...values, unit: "mm" as const }, steps: ["Create CIRCLE_SKETCH with explicit center and radius.", "Validate closed circular profile.", "Create EXTRUDE along +Z using explicit distance.", "Run kernel preview and BRep validation.", "Require user approval before immutable execution."], limits: ["Only CIRCLE_SKETCH and EXTRUDE are executable.", "Fillet is blocked by FILLET_READY = FALSE.", "No CAE, manufacturing, safety, or production validation is implied."] };
}
function countTopology(oc: any, shape: any, enumName: "TopAbs_SOLID" | "TopAbs_FACE" | "TopAbs_EDGE" | "TopAbs_VERTEX") { const explorer = new oc.TopExp_Explorer_2(shape, oc.TopAbs_ShapeEnum[enumName], oc.TopAbs_ShapeEnum.TopAbs_SHAPE); let count = 0; while (explorer.More()) { count += 1; explorer.Next(); } explorer.delete(); return count; }
function topologyInspection(oc: any, shape: any, revisionId: string): TopologyInspection {
  const counts = { bodies: countTopology(oc, shape, "TopAbs_SOLID"), faces: countTopology(oc, shape, "TopAbs_FACE"), edges: countTopology(oc, shape, "TopAbs_EDGE"), vertices: countTopology(oc, shape, "TopAbs_VERTEX") };
  const references = (["BODY", "FACE", "EDGE", "VERTEX"] as const).flatMap((kind) => Array.from({ length: counts[`${kind.toLowerCase()}s` as keyof typeof counts] ?? 0 }, (_, index) => ({ id: `TOPO-${revisionId}-${kind}-${String(index + 1).padStart(3, "0")}`, kind, ordinal: index + 1, stability: "REVISION_SCOPED" as const, note: "This ordinal is an inspection reference scoped only to this immutable kernel revision. It is not a persistent topological naming guarantee across regeneration." })));
  return { revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", references, counts, repeatability: { performed: false, sameCounts: false, sameBoundingBox: false, stableIdentityAcrossRegeneration: false, note: "A separate same-input kernel build is required before repeatability evidence can be recorded. Identity is intentionally not claimed across separate regenerations." } };
}
function circleFailure(args: { projectId: string; title: string; parentRevisionId?: string; values: CircleValues; preview?: boolean; decision: string }, stage: FeatureHistoryFailure["stage"], reason: string, parameterName?: string, corrections: string[] = []): FeatureHistoryRevision {
  const revisionId = id(args.preview ? "CIRCLE-PREVIEW" : "CIRCLE-REVISION"); const sketch: CADFeatureHistoryNode = { featureId: "CIRCLE-SKETCH-001", featureType: "CIRCLE_SKETCH", implementation: "KERNEL_BACKED", parentFeatures: [], inputGeometryReferences: [], parameters: [parameter("centerX", args.values.centerX), parameter("centerY", args.values.centerY), parameter("radius", args.values.radius)], units: "mm", constraints: [], dependencies: [], sourceRevision: args.parentRevisionId ?? "ROOT", resultRevision: revisionId, status: "FAILED", provenance: "FACT", description: "Circle sketch failed before a valid profile and solid could be committed." };
  return { revisionId, projectId: args.projectId, parentRevisionId: args.parentRevisionId, title: args.title, status: "FAILED", truth: "FACT", features: [sketch], geometry: { validation: "UNAVAILABLE", kernel: "OpenCascade.js", export: { status: "UNAVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", note: "No validated kernel geometry was available for STEP geometry export." } }, requirementsSummary: "No linked system requirement evidence; all non-geometric engineering outcomes remain unverified.", decisionSummary: args.decision, createdAt: new Date().toISOString(), failure: failure(stage, reason, parameterName === "extrudeDistance" ? "EXTRUDE-CIRCLE-001" : "CIRCLE-SKETCH-001", parameterName, ["CIRCLE-SKETCH-001", "EXTRUDE-CIRCLE-001"], corrections) };
}
async function buildCircle(args: HistoryArgs & { title: string; values: CircleValues; parentRevisionId?: string; preview?: boolean; decision: string; storeExport?: boolean }): Promise<FeatureHistoryRevision> {
  const invalid = Object.entries(args.values).find(([, value]) => !Number.isFinite(value)) ?? Object.entries(args.values).find(([name, value]) => (name === "radius" || name === "extrudeDistance") && value <= 0);
  if (invalid) return circleFailure(args, "VALIDATION", `${invalid[0]} must be a finite value${invalid[0] === "radius" || invalid[0] === "extrudeDistance" ? " greater than zero" : ""} in explicit normalized millimetres.`, invalid[0], ["Enter an explicit mm, cm, or m value; radius and extrusion distance must remain positive."]);
  const revisionId = id(args.preview ? "CIRCLE-PREVIEW" : "CIRCLE-REVISION"); const base = { revisionId, projectId: args.projectId, parentRevisionId: args.parentRevisionId, title: args.title, status: args.preview ? "PREVIEW" as const : "KERNEL_VALIDATED" as const, truth: "KERNEL_VALIDATED" as const, requirementsSummary: "Geometry is kernel validated only. Structural, CAE, manufacturing, safety, certification, and production readiness are unverified.", decisionSummary: args.decision, createdAt: new Date().toISOString() };
  const sketch: CADFeatureHistoryNode = { featureId: "CIRCLE-SKETCH-001", featureType: "CIRCLE_SKETCH", implementation: "KERNEL_BACKED", parentFeatures: [], inputGeometryReferences: [], parameters: [parameter("centerX", args.values.centerX), parameter("centerY", args.values.centerY), parameter("radius", args.values.radius)], units: "mm", constraints: [{ id: "CONSTRAINT-CIRCLE-CENTER", kind: "CENTER", status: "SATISFIED", description: `Circle center is explicitly located at (${args.values.centerX}, ${args.values.centerY}, 0) mm on the XY plane.` }, { id: "CONSTRAINT-CIRCLE-RADIUS", kind: "RADIUS", status: "SATISFIED", description: `Circle radius = ${args.values.radius} mm.` }], dependencies: [], sourceRevision: args.parentRevisionId ?? "ROOT", resultRevision: revisionId, status: args.preview ? "PREVIEW_READY" : "KERNEL_VALIDATED", provenance: "KERNEL_VALIDATED", description: "Closed circular XY-plane profile built from a real OpenCascade gp_Circ edge and wire." };
  const extrude: CADFeatureHistoryNode = { featureId: "EXTRUDE-CIRCLE-001", featureType: "EXTRUDE", implementation: "KERNEL_BACKED", parentFeatures: [sketch.featureId], inputGeometryReferences: [{ id: "REF-CIRCLE-SKETCH-001-PROFILE", kind: "SKETCH_PROFILE", ownerFeatureId: sketch.featureId, sourceRevisionId: revisionId, resolution: "DECLARED", note: "The extrusion consumes only this revision’s declared closed circle profile." }], parameters: [parameter("extrudeDistance", args.values.extrudeDistance)], units: "mm", constraints: [{ id: "CONSTRAINT-CIRCLE-NORMAL", kind: "DIMENSION", status: "SATISFIED", description: "Prism direction is global +Z, normal to the XY sketch plane." }], dependencies: [sketch.featureId, "REF-CIRCLE-SKETCH-001-PROFILE"], sourceRevision: args.parentRevisionId ?? "ROOT", resultRevision: revisionId, status: args.preview ? "PREVIEW_READY" : "KERNEL_VALIDATED", provenance: "KERNEL_VALIDATED", description: "OpenCascade prism made from the declared circular sketch face and a positive +Z vector." };
  let center: any; let direction: any; let axis: any; let circle: any; let edge: any; let wire: any; let face: any; let prism: any; let analyzer: any; let writer: any;
  try { const oc = await getOpenCascadeKernel(); center = new oc.gp_Pnt_3(args.values.centerX, args.values.centerY, 0); direction = new oc.gp_Dir_4(0, 0, 1); axis = new oc.gp_Ax2_3(center, direction); circle = new oc.gp_Circ_2(axis, args.values.radius); edge = new oc.BRepBuilderAPI_MakeEdge_8(circle); if (!edge.IsDone()) throw new Error("OpenCascade did not construct a closed circular edge."); wire = new oc.BRepBuilderAPI_MakeWire_2(edge.Edge()); if (!wire.IsDone()) throw new Error("OpenCascade did not construct a closed circular sketch wire."); face = new oc.BRepBuilderAPI_MakeFace_15(wire.Wire(), true); if (!face.IsDone()) throw new Error("OpenCascade did not construct a planar face from the circular sketch."); prism = new oc.BRepPrimAPI_MakePrism_1(face.Face(), new oc.gp_Vec_4(0, 0, args.values.extrudeDistance), true, true); const shape = prism.Shape(); analyzer = new oc.BRepCheck_Analyzer(shape, true, false); if (!analyzer.IsValid_2()) throw new Error("OpenCascade BRep validation failed after circle extrusion."); const viewerMesh = extractKernelViewerMesh(oc, shape, extrude.featureId); const topology = topologyInspection(oc, shape, revisionId); writer = new oc.STEPControl_Writer_1(); const progress = new oc.Message_ProgressRange_1(); const path = `/circle-history-${revisionId}.step`; writer.Transfer(shape, (oc.STEPControl_StepModelType as any).STEPControl_AsIs, true, progress); writer.Write(path); const stepBytes = Buffer.from((oc as any).FS.readFile(path)); (oc as any).FS.unlink(path); let geometryExport: FeatureHistoryRevision["geometry"]["export"] = { status: "UNAVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", note: "Validated STEP geometry was produced but not persisted to managed storage for this preview." }; if (args.storeExport) { try { const stored = await storagePut(`feature-history/${args.projectId}/${revisionId}.step`, stepBytes, "model/step"); geometryExport = { status: "AVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", storageKey: stored.key, url: stored.url, note: "This is a validated BRep geometry exchange export only. STEP does not preserve this application’s parametric feature history." }; } catch (error) { geometryExport = { status: "UNAVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", note: `Kernel geometry remained valid, but managed STEP export persistence failed: ${error instanceof Error ? error.message : "unknown storage error"}` }; } }
    return { ...base, features: [sketch, extrude], geometry: { validation: "VALID", kernel: "OpenCascade.js", viewerMesh, stepBase64: stepBytes.toString("base64"), boundingBox: viewerMesh.boundingBox, topology, export: geometryExport } };
  } catch (error) { return { ...circleFailure(args, "KERNEL_REGENERATION", error instanceof Error ? error.message : "Unknown OpenCascade circle regeneration failure.", "extrudeDistance", ["Check center, radius, extrusion distance, and the declared circle profile; then create a separate preview."]), revisionId, features: [sketch, { ...extrude, status: "FAILED", provenance: "FACT" }] }; }
  finally { analyzer?.delete?.(); writer?.delete?.(); prism?.delete?.(); face?.delete?.(); wire?.delete?.(); edge?.delete?.(); circle?.delete?.(); axis?.delete?.(); direction?.delete?.(); center?.delete?.(); }
}
function circleEdit(source: FeatureHistoryRevision, edit: FeaturePlanEdit) {
  const sketch = source.features.find((feature) => feature.featureType === "CIRCLE_SKETCH"); const extrude = source.features.find((feature) => feature.featureId === "EXTRUDE-CIRCLE-001"); if (!sketch || !extrude) return { error: failure("REFERENCE", "The source revision is not a supported circle-sketch-to-extrude history.", undefined, undefined, [], ["Select a CIRCLE_SKETCH → EXTRUDE revision."]) } as const;
  const value = (feature: CADFeatureHistoryNode, name: FeatureParameter["name"]) => feature.parameters.find((item) => item.name === name)?.normalizedValueMm ?? Number.NaN; let values: CircleValues = { centerX: value(sketch, "centerX"), centerY: value(sketch, "centerY"), radius: value(sketch, "radius"), extrudeDistance: value(extrude, "extrudeDistance") };
  if (edit.featureType && edit.featureType !== "CIRCLE_SKETCH" && edit.featureType !== "EXTRUDE") return { error: failure("VALIDATION", `${edit.featureType} is not kernel-backed in Phase 4.7.`, edit.featureId, undefined, [edit.featureId], ["Use CIRCLE_SKETCH or EXTRUDE only."]) } as const;
  if (edit.operationOrder !== undefined && edit.operationOrder !== (edit.featureId === "CIRCLE-SKETCH-001" ? 0 : 1)) return { error: failure("VALIDATION", "Circle sketch must remain before its extrusion; operation ordering is fixed for this kernel-backed chain.", edit.featureId, undefined, ["CIRCLE-SKETCH-001", "EXTRUDE-CIRCLE-001"], ["Keep CIRCLE-SKETCH-001 before EXTRUDE-CIRCLE-001."]) } as const;
  if (edit.targetReferenceId && edit.targetReferenceId !== "REF-CIRCLE-SKETCH-001-PROFILE") return { error: failure("TOPOLOGY_REFERENCE_INVALIDATED", "The requested topology reference is revision-scoped or stale. It cannot be silently assigned to a different circle edge, face, or vertex after regeneration.", edit.featureId, undefined, ["CIRCLE-SKETCH-001", "EXTRUDE-CIRCLE-001"], ["Select the declared current circle profile reference or inspect a new immutable revision."]) } as const;
  if (edit.parameter) values = { ...values, [edit.parameter.name]: toMm(edit.parameter.value, edit.parameter.unit) }; return { values } as const;
}
export async function createCircleFeatureHistory(args: HistoryArgs & { input: CircleFeatureInput }) { await authorize(args); const values: CircleValues = { centerX: toMm(args.input.centerX, args.input.unit), centerY: toMm(args.input.centerY, args.input.unit), radius: toMm(args.input.radius, args.input.unit), extrudeDistance: toMm(args.input.extrudeDistance, args.input.unit) }; const revision = await buildCircle({ ...args, title: args.input.title, values, decision: "Created a real circle sketch-to-extrude feature chain.", storeExport: true }); if (revision.status === "FAILED") { await persistFailure(args, revision); return revision; } histories.set(args.projectId, [...(histories.get(args.projectId) ?? []), revision]); await persistRevision(args, revision); return revision; }
export async function previewCircleFeatureRegeneration(args: HistoryArgs & { sourceRevisionId: string; edit: FeaturePlanEdit }): Promise<FeatureHistoryRevision> { await authorize(args); const source = await latest(args.projectId, args.sourceRevisionId); if (!source) throw new Error("Circle source feature revision is unavailable in this controlled session. No regeneration was attempted."); const prepared = circleEdit(source, args.edit); if ("error" in prepared) { const invalid: FeatureHistoryRevision = { ...source, revisionId: id("CIRCLE-PREVIEW"), status: "FAILED", truth: "FACT", features: source.features.map((feature) => ({ ...feature, status: "REFERENCE_INVALIDATED" })), geometry: { validation: "UNAVAILABLE", kernel: "OpenCascade.js" }, failure: prepared.error }; await persistFailure(args, invalid); return invalid; } const preview = await buildCircle({ ...args, title: `${source.title} · Circle Preview`, values: prepared.values, parentRevisionId: source.revisionId, preview: true, decision: `Preview circle regeneration from ${source.revisionId} after controlled feature-plan edit ${args.edit.featureId}.`, storeExport: false }); previews.set(key(args.projectId, preview.revisionId), preview); return preview; }
export async function executeCircleFeatureRegeneration(args: HistoryArgs & { previewRevisionId: string }): Promise<FeatureHistoryRevision> { await authorize(args); const preview = previews.get(key(args.projectId, args.previewRevisionId)); if (!preview) throw new Error("Circle preview is unavailable or expired. Create a new preview; no source revision was changed."); if (preview.status !== "PREVIEW" || preview.geometry.validation !== "VALID") { const failed: FeatureHistoryRevision = { ...preview, status: "FAILED", truth: "FACT", failure: preview.failure ?? failure("VALIDATION", "Only a valid non-persistent circle preview can execute.", undefined, undefined, [], ["Preview the supported circle chain successfully before Apply."]) }; await persistFailure(args, failed); return failed; } const sketch = preview.features.find((feature) => feature.featureId === "CIRCLE-SKETCH-001")!; const extrude = preview.features.find((feature) => feature.featureId === "EXTRUDE-CIRCLE-001")!; const get = (name: FeatureParameter["name"]) => [...sketch.parameters, ...extrude.parameters].find((item) => item.name === name)!.normalizedValueMm; const revision = await buildCircle({ ...args, title: preview.title.replace(" · Circle Preview", ""), values: { centerX: get("centerX"), centerY: get("centerY"), radius: get("radius"), extrudeDistance: get("extrudeDistance") }, parentRevisionId: preview.parentRevisionId, decision: `Approved circle regeneration from preview ${preview.revisionId}.`, storeExport: true }); if (revision.status === "FAILED") { await persistFailure(args, revision); return revision; } histories.set(args.projectId, [...(histories.get(args.projectId) ?? []), revision]); await persistRevision(args, revision); return revision; }
export function circleFilletReadiness(revision?: FeatureHistoryRevision, repeatabilityPassed = false): FilletReadinessGate { const valid = revision?.status === "KERNEL_VALIDATED" && revision.geometry.validation === "VALID"; const checks: FilletReadinessGate["checks"] = [{ id: "STABLE_TOPOLOGY_REFERENCES", passed: false, detail: "Body, face, edge, and vertex references are deliberately revision-scoped; no persistent topological naming algorithm exists." }, { id: "DETERMINISTIC_EDGE_IDENTIFICATION", passed: false, detail: "Edge ordinals are inspection-only and cannot be used as deterministic fillet targets across regeneration." }, { id: "SUCCESSFUL_REGENERATION", passed: Boolean(valid), detail: valid ? "The current circle chain regenerated to a kernel-valid BRep." : "No current kernel-valid circle revision is available." }, { id: "FAILURE_PRESERVATION", passed: true, detail: "Failed circle previews/events do not mutate the prior valid revision." }, { id: "BRANCH_PRESERVATION", passed: true, detail: "Approved circle regeneration creates immutable child revisions." }, { id: "KERNEL_VALIDITY", passed: Boolean(valid), detail: valid ? "OpenCascade BRepCheck accepted the current circle extrusion." : "No kernel-valid circle BRep is available." }, { id: "REPEATABILITY", passed: repeatabilityPassed, detail: repeatabilityPassed ? "Independent same-input circle regenerations produced the same counts and display bounds. This still does not prove stable entity identity." : "No successful same-input count-and-bound repeatability check is recorded." }]; const missing = checks.filter((check) => !check.passed).map((check) => check.id); return { ready: false, checks, missing, conclusion: "FILLET_READY = FALSE. Production feature-history fillet execution remains blocked because stable topology references and deterministic edge identification are not demonstrated." }; }
export async function assessCircleRepeatability(args: HistoryArgs & { revisionId: string }) {
  const source = (await listFeatureHistory(args)).find((item) => item.revisionId === args.revisionId); if (!source || !source.features.some((feature) => feature.featureType === "CIRCLE_SKETCH")) throw new Error("A circle feature-history revision is required for repeatability assessment."); const sketch = source.features.find((feature) => feature.featureId === "CIRCLE-SKETCH-001")!; const extrude = source.features.find((feature) => feature.featureId === "EXTRUDE-CIRCLE-001")!; const get = (name: FeatureParameter["name"]) => [...sketch.parameters, ...extrude.parameters].find((item) => item.name === name)!.normalizedValueMm; const values = { centerX: get("centerX"), centerY: get("centerY"), radius: get("radius"), extrudeDistance: get("extrudeDistance") }; const [first, second] = await Promise.all([buildCircle({ ...args, title: `${source.title} · Repeatability A`, values, parentRevisionId: source.revisionId, preview: true, decision: "Independent repeatability check A.", storeExport: false }), buildCircle({ ...args, title: `${source.title} · Repeatability B`, values, parentRevisionId: source.revisionId, preview: true, decision: "Independent repeatability check B.", storeExport: false })]); const countsA = first.geometry.topology?.counts; const countsB = second.geometry.topology?.counts; const sameCounts = JSON.stringify(countsA) === JSON.stringify(countsB); const boundsA = first.geometry.boundingBox?.size; const boundsB = second.geometry.boundingBox?.size; const sameBoundingBox = Boolean(boundsA && boundsB && boundsA.every((value, index) => Math.abs(value - boundsB[index]) < 1e-9)); return { revisionId: source.revisionId, performed: true, firstStatus: first.status, secondStatus: second.status, sameCounts, sameBoundingBox, stableIdentityAcrossRegeneration: false as const, note: sameCounts && sameBoundingBox ? "Two independent OpenCascade circle builds matched in topology counts and tessellated display bounds. Entity ordinals remain revision-scoped and are not considered stable references." : "Independent builds did not match in the bounded repeatability metrics; no topology identity was inferred." }; }
export async function inspectCircleTopology(args: HistoryArgs & { revisionId: string }) { const revision = (await listFeatureHistory(args)).find((item) => item.revisionId === args.revisionId); if (!revision || !revision.features.some((feature) => feature.featureType === "CIRCLE_SKETCH")) throw new Error("A circle feature-history revision is required for topology inspection."); return revision.geometry.topology ?? { revisionId: revision.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", references: [], counts: { bodies: 0, faces: 0, edges: 0, vertices: 0 }, repeatability: { performed: false, sameCounts: false, sameBoundingBox: false, stableIdentityAcrossRegeneration: false, note: "No topology evidence was stored for this revision." } }; }
export async function getCircleFilletReadiness(args: HistoryArgs & { revisionId?: string }) { const revision = args.revisionId ? (await listFeatureHistory(args)).find((item) => item.revisionId === args.revisionId) : undefined; const repeatability = revision ? await assessCircleRepeatability({ ...args, revisionId: revision.revisionId }) : undefined; return circleFilletReadiness(revision, Boolean(repeatability?.sameCounts && repeatability?.sameBoundingBox)); }
export async function getCircleGeometryExport(args: HistoryArgs & { revisionId: string }) { const revision = (await listFeatureHistory(args)).find((item) => item.revisionId === args.revisionId); if (!revision || !revision.features.some((feature) => feature.featureType === "CIRCLE_SKETCH")) throw new Error("A validated circle feature-history revision is required for geometry export lookup."); return revision.geometry.export ?? { status: "UNAVAILABLE" as const, format: "STEP_GEOMETRY" as const, featureHistory: "NOT_PRESERVED" as const, note: "No managed STEP geometry export is available for this revision." }; }
