import { extractKernelViewerMesh, getOpenCascadeKernel } from "./cadKernel";
import { appendLineageNode, appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";
import type { FeatureHistoryComparison, FeatureHistoryFailure, FeatureHistoryRevision, FeaturePlanEdit, FeatureParameter, CADFeatureHistoryNode } from "../shared/featureHistory";

const histories = new Map<string, FeatureHistoryRevision[]>();
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const key = (projectId: string, revisionId: string) => `${projectId}:${revisionId}`;
const previews = new Map<string, FeatureHistoryRevision>();

type RectangularFeatureInput = { title: string; width: number; height: number; extrudeDistance: number; unit: "mm" | "cm" | "m" };
type HistoryArgs = { projectId: string; accessKey: string };
function toMm(value: number, unit: RectangularFeatureInput["unit"]) { if (!Number.isFinite(value)) throw new Error("A feature parameter must be a finite number."); if (unit === "mm") return value; if (unit === "cm") return value * 10; if (unit === "m") return value * 1000; throw new Error("Ambiguous or unsupported unit. Use mm, cm, or m explicitly."); }
function parameter(name: FeatureParameter["name"], value: number, source: FeatureParameter["provenance"] = "USER"): FeatureParameter { return { name, value, unit: "mm", normalizedValueMm: value, editable: true, provenance: source }; }
function failure(stage: FeatureHistoryFailure["stage"], reason: string, featureId?: string, parameterName?: string, affectedDependencies: string[] = [], corrections: string[] = []): FeatureHistoryFailure { return { stage, reason, featureId, parameter: parameterName, affectedDependencies, corrections }; }
function publicRevision(revision: FeatureHistoryRevision): FeatureHistoryRevision { return { ...revision, geometry: { validation: revision.geometry.validation, kernel: revision.geometry.kernel, boundingBox: revision.geometry.boundingBox }, features: revision.features.map((node) => ({ ...node, inputGeometryReferences: node.inputGeometryReferences.map((ref) => ({ ...ref })), parameters: node.parameters.map((item) => ({ ...item })), constraints: node.constraints.map((item) => ({ ...item })) })) }; }
async function authorize(args: HistoryArgs) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function persistRevision(args: HistoryArgs, revision: FeatureHistoryRevision) {
  const parentSnapshot = await projectMemorySnapshot(args); const parent = revision.parentRevisionId ? parentSnapshot.lineage.find((node) => node.title.includes(revision.parentRevisionId!)) : undefined;
  const node = await appendLineageNode({ ...args, node: { kind: "REVISION", parentId: parent?.id, title: `Feature history revision · ${revision.revisionId}`, reasonForChange: revision.decisionSummary, changeSummary: `Feature chain: ${revision.features.map((feature) => feature.featureType).join(" → ")}. The new revision is immutable; its parent remains unchanged.`, status: "VALIDATED", authorSource: "CAD_AGENT" } });
  await appendPersistentMemory({ ...args, record: { kind: "FEATURE_REVISION", title: `Kernel validated feature history · ${revision.revisionId}`, content: JSON.stringify({ revision: publicRevision(revision), lineageId: node.id }), truthStatus: "DERIVED", validationStage: "GEOMETRICALLY_VALIDATED", relatedConfigurationId: revision.revisionId, authorSource: "CAD_AGENT" } });
  await appendPersistentMemory({ ...args, record: { kind: "EVIDENCE", title: `Feature-history geometry evidence · ${revision.revisionId}`, content: "OpenCascade.js constructed a closed rectangular wire, made a planar face, extruded the face with BRepPrimAPI_MakePrism, validated the resulting BRep, and tessellated its actual result for the viewer. This establishes parametric and geometric kernel evidence only; engineering, physical, manufacturing, safety, and certification validity remain unverified.", truthStatus: "DERIVED", validationStage: "GEOMETRICALLY_VALIDATED", relatedConfigurationId: revision.revisionId, authorSource: "CAD_AGENT" } });
}
async function persistFailure(args: HistoryArgs, attempted: FeatureHistoryRevision) { if (!attempted.failure) return; await appendPersistentMemory({ ...args, record: { kind: "FEATURE_HISTORY", title: `Feature regeneration failed · ${attempted.revisionId}`, content: JSON.stringify({ revision: publicRevision(attempted), lastValidParent: attempted.parentRevisionId }), truthStatus: "FACT", validationStage: "CONCEPTUAL", relatedConfigurationId: attempted.parentRevisionId, authorSource: "CAD_AGENT" } }); }
async function latest(projectId: string, revisionId?: string) {
  const cached = histories.get(projectId) ?? []; if (revisionId) return cached.find((item) => item.revisionId === revisionId);
  return cached.filter((item) => item.status === "KERNEL_VALIDATED").at(-1);
}
function applyEdit(source: FeatureHistoryRevision, edit?: FeaturePlanEdit) {
  const sketch = source.features.find((feature) => feature.featureType === "RECTANGLE_SKETCH"); const extrude = source.features.find((feature) => feature.featureType === "EXTRUDE");
  if (!sketch || !extrude) return { error: failure("REFERENCE", "Source history does not contain the supported rectangular sketch and extrusion feature chain.", undefined, undefined, [], ["Create a new supported rectangular sketch-to-extrude history."]) } as const;
  const read = (feature: CADFeatureHistoryNode, name: FeatureParameter["name"]) => feature.parameters.find((item) => item.name === name)?.normalizedValueMm;
  let values = { width: read(sketch, "width") ?? Number.NaN, height: read(sketch, "height") ?? Number.NaN, extrudeDistance: read(extrude, "extrudeDistance") ?? Number.NaN };
  if (!edit) return { values, sourceRevision: source.revisionId } as const;
  if (edit.featureType && edit.featureType !== "RECTANGLE_SKETCH" && edit.featureType !== "EXTRUDE") return { error: failure("VALIDATION", `Feature type ${edit.featureType} is not kernel-backed in Phase 4.6.`, edit.featureId, undefined, [edit.featureId], ["Use RECTANGLE_SKETCH or EXTRUDE only."]) } as const;
  if (edit.operationOrder !== undefined && edit.operationOrder !== (edit.featureId === "SKETCH-001" ? 0 : 1)) return { error: failure("VALIDATION", "Feature order changes are not supported because the rectangular sketch must precede the extrusion.", edit.featureId, undefined, ["SKETCH-001", "EXTRUDE-001"], ["Keep SKETCH-001 before EXTRUDE-001."]) } as const;
  if (edit.targetReferenceId && edit.targetReferenceId !== "REF-SKETCH-001-PROFILE") return { error: failure("REFERENCE", "Topology reference is not the declared current sketch profile and cannot be silently remapped.", edit.featureId, undefined, ["SKETCH-001", "EXTRUDE-001"], ["Select REF-SKETCH-001-PROFILE from the current feature history."]) } as const;
  if (edit.parameter) values = { ...values, [edit.parameter.name]: toMm(edit.parameter.value, edit.parameter.unit) };
  return { values, sourceRevision: source.revisionId } as const;
}
async function build(args: HistoryArgs & { title: string; values: { width: number; height: number; extrudeDistance: number }; parentRevisionId?: string; preview?: boolean; decision: string }): Promise<FeatureHistoryRevision> {
  const revisionId = id(args.preview ? "FEATURE-PREVIEW" : "FEATURE-REVISION"); const base = { revisionId, projectId: args.projectId, parentRevisionId: args.parentRevisionId, title: args.title, status: args.preview ? "PREVIEW" as const : "KERNEL_VALIDATED" as const, truth: "KERNEL_VALIDATED" as const, requirementsSummary: "Feature-history foundation has no linked system requirements in this operation; geometry is intentionally engineeringally unverified.", decisionSummary: args.decision, createdAt: new Date().toISOString() };
  const invalid = Object.entries(args.values).find(([, value]) => !Number.isFinite(value) || value <= 0);
  if (invalid) return { ...base, status: "FAILED", truth: "FACT", features: [], geometry: { validation: "UNAVAILABLE", kernel: "OpenCascade.js" }, failure: failure("VALIDATION", `${invalid[0]} must be a positive finite normalized millimetre value.`, invalid[0] === "extrudeDistance" ? "EXTRUDE-001" : "SKETCH-001", invalid[0], ["SKETCH-001", "EXTRUDE-001"], ["Use an explicit positive mm, cm, or m value and preview again."]) };
  const sketch: CADFeatureHistoryNode = { featureId: "SKETCH-001", featureType: "RECTANGLE_SKETCH", implementation: "KERNEL_BACKED", parentFeatures: [], inputGeometryReferences: [], parameters: [parameter("width", args.values.width), parameter("height", args.values.height)], units: "mm", constraints: [{ id: "CONSTRAINT-HORIZONTAL", kind: "HORIZONTAL", status: "SATISFIED", description: "Opposing rectangular profile segments are built on the global X axis." }, { id: "CONSTRAINT-VERTICAL", kind: "VERTICAL", status: "SATISFIED", description: "Opposing rectangular profile segments are built on the global Y axis." }, { id: "CONSTRAINT-COINCIDENT", kind: "COINCIDENT", status: "SATISFIED", description: "The polygon is closed into a single wire." }, { id: "CONSTRAINT-WIDTH", kind: "DIMENSION", status: "SATISFIED", description: `Width = ${args.values.width} mm.` }, { id: "CONSTRAINT-HEIGHT", kind: "DIMENSION", status: "SATISFIED", description: `Height = ${args.values.height} mm.` }], dependencies: [], sourceRevision: args.parentRevisionId ?? "ROOT", resultRevision: revisionId, status: args.preview ? "PREVIEW_READY" : "KERNEL_VALIDATED", provenance: "KERNEL_VALIDATED", description: "Closed rectangular XY-plane profile constructed as a real OpenCascade polygonal wire." };
  const extrude: CADFeatureHistoryNode = { featureId: "EXTRUDE-001", featureType: "EXTRUDE", implementation: "KERNEL_BACKED", parentFeatures: [sketch.featureId], inputGeometryReferences: [{ id: "REF-SKETCH-001-PROFILE", kind: "SKETCH_PROFILE", ownerFeatureId: "SKETCH-001", sourceRevisionId: revisionId, resolution: "DECLARED", note: "The extrusion consumes only the declared rectangular sketch profile from this feature history revision." }], parameters: [parameter("extrudeDistance", args.values.extrudeDistance)], units: "mm", constraints: [{ id: "CONSTRAINT-NORMAL", kind: "DIMENSION", status: "SATISFIED", description: "Prism direction is global +Z, normal to the XY sketch plane." }], dependencies: [sketch.featureId, "REF-SKETCH-001-PROFILE"], sourceRevision: args.parentRevisionId ?? "ROOT", resultRevision: revisionId, status: args.preview ? "PREVIEW_READY" : "KERNEL_VALIDATED", provenance: "KERNEL_VALIDATED", description: "OpenCascade prism made from the current rectangular sketch face and a positive +Z vector." };
  let polygon: any; let faceMaker: any; let prism: any; let analyzer: any; let writer: any; let points: any[] = [];
  try { const oc = await getOpenCascadeKernel(); points = [[0, 0], [args.values.width, 0], [args.values.width, args.values.height], [0, args.values.height]].map(([x, y]) => new oc.gp_Pnt_3(x, y, 0)); polygon = new oc.BRepBuilderAPI_MakePolygon_1(); for (const point of points) polygon.Add_1(point); polygon.Close(); if (!polygon.IsDone()) throw new Error("OpenCascade did not close the rectangular sketch wire."); faceMaker = new oc.BRepBuilderAPI_MakeFace_15(polygon.Wire(), true); if (!faceMaker.IsDone()) throw new Error("OpenCascade did not create a planar sketch face."); prism = new oc.BRepPrimAPI_MakePrism_1(faceMaker.Face(), new oc.gp_Vec_4(0, 0, args.values.extrudeDistance), true, true); const shape = prism.Shape(); analyzer = new oc.BRepCheck_Analyzer(shape, true, false); if (!analyzer.IsValid_2()) throw new Error("OpenCascade BRep validation failed after extrusion."); const viewerMesh = extractKernelViewerMesh(oc, shape, "EXTRUDE-001"); writer = new oc.STEPControl_Writer_1(); const progress = new oc.Message_ProgressRange_1(); const path = `/feature-history-${revisionId}.step`; writer.Transfer(shape, (oc.STEPControl_StepModelType as any).STEPControl_AsIs, true, progress); writer.Write(path); const stepBase64 = Buffer.from((oc as any).FS.readFile(path)).toString("base64"); (oc as any).FS.unlink(path); return { ...base, features: [sketch, extrude], geometry: { validation: "VALID", kernel: "OpenCascade.js", viewerMesh, stepBase64, boundingBox: viewerMesh.boundingBox } }; }
  catch (error) { const reason = error instanceof Error ? error.message : "Unknown OpenCascade feature regeneration failure."; return { ...base, status: "FAILED", truth: "FACT", features: [sketch, { ...extrude, status: "FAILED", provenance: "FACT" }], geometry: { validation: "INVALID", kernel: "OpenCascade.js" }, failure: failure("KERNEL_REGENERATION", reason, "EXTRUDE-001", "extrudeDistance", ["SKETCH-001", "EXTRUDE-001"], ["Check sketch dimensions, extrusion distance, and the declared profile reference; then create a separate preview."]) }; }
  finally { analyzer?.delete?.(); writer?.delete?.(); prism?.delete?.(); faceMaker?.delete?.(); polygon?.delete?.(); for (const point of points) point.delete?.(); }
}
export async function createFeatureHistory(args: HistoryArgs & { input: RectangularFeatureInput }) { await authorize(args); const values = { width: toMm(args.input.width, args.input.unit), height: toMm(args.input.height, args.input.unit), extrudeDistance: toMm(args.input.extrudeDistance, args.input.unit) }; const revision = await build({ ...args, title: args.input.title, values, decision: "Created a real rectangular sketch-to-extrude feature chain." }); if (revision.status === "FAILED") { await persistFailure(args, revision); return revision; } histories.set(args.projectId, [...(histories.get(args.projectId) ?? []), revision]); await persistRevision(args, revision); return revision; }
export async function previewFeatureRegeneration(args: HistoryArgs & { sourceRevisionId: string; edit: FeaturePlanEdit }): Promise<FeatureHistoryRevision> { await authorize(args); const source = await latest(args.projectId, args.sourceRevisionId); if (!source) throw new Error("Source feature revision is unavailable in this controlled session. No regeneration was attempted."); const prepared = applyEdit(source, args.edit); if ("error" in prepared) { const invalid: FeatureHistoryRevision = { ...source, revisionId: id("FEATURE-PREVIEW"), status: "FAILED", truth: "FACT", features: source.features.map((feature) => ({ ...feature, status: "REFERENCE_INVALIDATED" })), geometry: { validation: "UNAVAILABLE", kernel: "OpenCascade.js" }, failure: prepared.error }; await persistFailure(args, invalid); return invalid; }
  const preview = await build({ ...args, title: `${source.title} · Preview`, values: prepared.values, parentRevisionId: source.revisionId, preview: true, decision: `Preview regeneration from ${source.revisionId} after controlled feature-plan edit ${args.edit.featureId}.` }); previews.set(key(args.projectId, preview.revisionId), preview); return preview; }
export async function executeFeatureRegeneration(args: HistoryArgs & { previewRevisionId: string }): Promise<FeatureHistoryRevision> { await authorize(args); const preview = previews.get(key(args.projectId, args.previewRevisionId)); if (!preview) throw new Error("Feature preview is unavailable or expired. Create a new preview; no source revision was changed."); if (preview.status !== "PREVIEW" || preview.geometry.validation !== "VALID") { const failed: FeatureHistoryRevision = { ...preview, status: "FAILED", truth: "FACT", failure: preview.failure ?? failure("VALIDATION", "Only a valid non-persistent feature preview can execute.", undefined, undefined, [], ["Preview the feature chain successfully before Apply."]) }; await persistFailure(args, failed); return failed; }
  const sketch = preview.features.find((feature) => feature.featureId === "SKETCH-001")!; const extrude = preview.features.find((feature) => feature.featureId === "EXTRUDE-001")!; const revision = await build({ ...args, title: preview.title.replace(" · Preview", ""), values: { width: sketch.parameters.find((item) => item.name === "width")!.normalizedValueMm, height: sketch.parameters.find((item) => item.name === "height")!.normalizedValueMm, extrudeDistance: extrude.parameters[0].normalizedValueMm }, parentRevisionId: preview.parentRevisionId, decision: `Approved regeneration from preview ${preview.revisionId}.` }); if (revision.status === "FAILED") { await persistFailure(args, revision); return revision; } histories.set(args.projectId, [...(histories.get(args.projectId) ?? []), revision]); await persistRevision(args, revision); return revision; }
export async function listFeatureHistory(args: HistoryArgs) { await authorize(args); const snapshot = await projectMemorySnapshot(args); const durable = snapshot.records.filter((record) => record.kind === "FEATURE_REVISION").flatMap((record) => { try { return [(JSON.parse(record.content) as { revision: FeatureHistoryRevision }).revision]; } catch { return []; } }); const cached = histories.get(args.projectId) ?? []; const combined = [...durable, ...cached].filter((item, index, all) => all.findIndex((candidate) => candidate.revisionId === item.revisionId) === index); return combined.sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }
export async function compareFeatureRevisions(args: HistoryArgs & { baseRevisionId: string; comparedRevisionId: string }): Promise<FeatureHistoryComparison> { const revisions = await listFeatureHistory(args); const base = revisions.find((item) => item.revisionId === args.baseRevisionId); const compared = revisions.find((item) => item.revisionId === args.comparedRevisionId); if (!base || !compared) throw new Error("Both immutable feature revisions must exist in the authorized project before comparison."); const baseParameters = base.features.flatMap((feature) => feature.parameters.map((parameter) => ({ featureId: feature.featureId, ...parameter }))); const comparedParameters = compared.features.flatMap((feature) => feature.parameters.map((parameter) => ({ featureId: feature.featureId, ...parameter }))); const keys = new Set([...baseParameters, ...comparedParameters].map((item) => `${item.featureId}:${item.name}`)); return { baseRevision: base.revisionId, comparedRevision: compared.revisionId, sameFeatureDefinitions: base.features.map((feature) => feature.featureType).join("|") === compared.features.map((feature) => feature.featureType).join("|"), parameterChanges: [...keys].map((entry) => { const [featureId, name] = entry.split(":"); return { featureId, name, baseValue: baseParameters.find((item) => item.featureId === featureId && item.name === name)?.normalizedValueMm, comparedValue: comparedParameters.find((item) => item.featureId === featureId && item.name === name)?.normalizedValueMm, unit: "mm" as const }; }).filter((item) => item.baseValue !== item.comparedValue), geometryMetadata: { base: base.geometry.boundingBox, compared: compared.geometry.boundingBox, deviationAnalysis: "NOT_IMPLEMENTED" }, requirements: { base: base.requirementsSummary, compared: compared.requirementsSummary }, decisions: { base: base.decisionSummary, compared: compared.decisionSummary }, validation: { base: base.status, compared: compared.status } }; }

export async function diagnoseFeatureHistoryFailure(args: HistoryArgs) {
  await authorize(args); const snapshot = await projectMemorySnapshot(args); const record = snapshot.records.find((item) => item.kind === "FEATURE_HISTORY");
  if (!record) return { noRecordedFailure: true, diagnosis: "NO RECORDED FEATURE-HISTORY FAILURE.", alternatives: [] as Array<{ title: string; reason: string; truth: "INFERRED" | "UNKNOWN" }> };
  try { const parsed = JSON.parse(record.content) as { revision?: FeatureHistoryRevision }; const failed = parsed.revision?.failure; if (!failed) return { noRecordedFailure: true, diagnosis: "The latest feature-history failure record has no diagnostic payload.", alternatives: [] as Array<{ title: string; reason: string; truth: "INFERRED" | "UNKNOWN" }> }; return { noRecordedFailure: false, diagnosis: `${failed.stage}: ${failed.reason} Affected dependency chain: ${failed.affectedDependencies.join(" → ") || "UNKNOWN"}.`, alternatives: failed.corrections.slice(0, 3).map((correction) => ({ title: "Create a separate corrected preview", reason: correction, truth: "INFERRED" as const })) };
  } catch { return { noRecordedFailure: true, diagnosis: "The failure record could not be decoded; no retry was attempted.", alternatives: [] as Array<{ title: string; reason: string; truth: "INFERRED" | "UNKNOWN" }> }; }
}
