import { createHash } from "node:crypto";
import { exportValidatedStep, extractKernelViewerMesh, getOpenCascadeKernel } from "./cadKernel";
import { runWithOpenCascadeAdmission } from "./runtimeAdmission";
import { openPersistentProject } from "./persistentMemory";
import { executeAuthorizedFeatureHistoryStep } from "./sourceLessCadExecution";
import { topologyManifest } from "./topologyNaming";
import { cacheFeatureHistoryRevision, listFeatureHistory } from "./featureHistory";
import type { CADFeatureHistoryNode, FeatureHistoryFailure, FeatureHistoryRevision, FeatureParameter, MirrorEdit, MirrorInput, MirrorPlane } from "../shared/featureHistory";

type HistoryArgs = { projectId: string; accessKey: string };
type CircleValues = { centerX: number; centerY: number; radius: number; extrudeDistance: number };
const previews = new Map<string, FeatureHistoryRevision>();
const key = (projectId: string, revisionId: string) => `${projectId}:${revisionId}`;
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;

function sourceValues(revision: FeatureHistoryRevision): CircleValues {
  const sketch = revision.features.find((feature) => feature.featureId === "CIRCLE-SKETCH-001"); const extrude = revision.features.find((feature) => feature.featureId === "EXTRUDE-CIRCLE-001");
  if (!sketch || !extrude || revision.status !== "KERNEL_VALIDATED" || revision.geometry.validation !== "VALID") throw new Error("Mirror requires a kernel-validated CIRCLE_SKETCH → EXTRUDE source revision.");
  const read = (name: FeatureParameter["name"]) => [...sketch.parameters, ...extrude.parameters].find((parameter) => parameter.name === name)?.normalizedValueMm;
  return { centerX: read("centerX") ?? Number.NaN, centerY: read("centerY") ?? Number.NaN, radius: read("radius") ?? Number.NaN, extrudeDistance: read("extrudeDistance") ?? Number.NaN };
}
function failure(stage: FeatureHistoryFailure["stage"], reason: string): FeatureHistoryFailure { return { stage, reason, featureId: "MIRROR-001", affectedDependencies: ["EXTRUDE-CIRCLE-001", "MIRROR-001"], corrections: ["Select a current validated source revision and one declared global mirror plane, then create a new preview."] }; }
function failed(args: HistoryArgs & { input: MirrorInput; source?: FeatureHistoryRevision; preview?: boolean; reason: string }): FeatureHistoryRevision { return { revisionId: id(args.preview ? "MIRROR-PREVIEW" : "MIRROR-REVISION"), projectId: args.projectId, parentRevisionId: args.input.sourceRevisionId, title: args.input.title, status: "FAILED", truth: "FACT", features: args.source?.features.map((feature) => ({ ...feature })) ?? [], geometry: { validation: "UNAVAILABLE", kernel: "OpenCascade.js", export: { status: "UNAVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", note: "No mirror STEP geometry exists because the bounded kernel operation did not validate." } }, requirementsSummary: "No engineering claim is made after a failed guarded Mirror operation.", decisionSummary: "Mirror failed before any source revision changed.", createdAt: new Date().toISOString(), failure: failure("VALIDATION", args.reason) }; }
function validPlane(plane: string): plane is MirrorPlane { return plane === "GLOBAL_X" || plane === "GLOBAL_Y" || plane === "GLOBAL_Z"; }
function publicRevision(revision: FeatureHistoryRevision): FeatureHistoryRevision { return { ...revision, geometry: { validation: revision.geometry.validation, kernel: revision.geometry.kernel, boundingBox: revision.geometry.boundingBox, topology: revision.geometry.topology, topologyManifest: revision.geometry.topologyManifest, export: revision.geometry.export }, features: revision.features.map((feature) => ({ ...feature, parameters: feature.parameters.map((parameter) => ({ ...parameter })), inputGeometryReferences: feature.inputGeometryReferences.map((reference) => ({ ...reference })), constraints: feature.constraints.map((constraint) => ({ ...constraint })) })) }; }
async function persistFailure(_args: HistoryArgs, _revision: FeatureHistoryRevision) { return undefined; }

async function build(args: HistoryArgs & { input: MirrorInput; source: FeatureHistoryRevision; historyParentRevisionId?: string; preview?: boolean; decision: string }): Promise<FeatureHistoryRevision> {
  if (!validPlane(args.input.mirrorPlane)) return failed({ ...args, reason: "Mirror plane must be explicitly GLOBAL_X, GLOBAL_Y, or GLOBAL_Z. Geometry-derived planes are intentionally unsupported." });
  let values: CircleValues; try { values = sourceValues(args.source); } catch (error) { return failed({ ...args, reason: error instanceof Error ? error.message : "Mirror source validation failed." }); }
  const revisionId = id(args.preview ? "MIRROR-PREVIEW" : "MIRROR-REVISION"); const mirroredCenter = { x: args.input.mirrorPlane === "GLOBAL_X" ? -values.centerX : values.centerX, y: args.input.mirrorPlane === "GLOBAL_Y" ? -values.centerY : values.centerY };
  const node: CADFeatureHistoryNode = { featureId: "MIRROR-001", featureType: "MIRROR", implementation: "KERNEL_BACKED", parentFeatures: ["EXTRUDE-CIRCLE-001"], inputGeometryReferences: [{ id: "REF-EXTRUDE-CIRCLE-001-SOLID", kind: "FEATURE", ownerFeatureId: "EXTRUDE-CIRCLE-001", sourceRevisionId: args.source.revisionId, resolution: "DECLARED", note: "Mirror consumes only the validated source circle extrusion from its declared immutable source revision." }], parameters: [], units: "mm", constraints: [{ id: "CONSTRAINT-MIRROR-PLANE", kind: "DIMENSION", status: "SATISFIED", description: `The real kernel transformation reflects the source only across declared ${args.input.mirrorPlane} through the global origin.` }], dependencies: ["EXTRUDE-CIRCLE-001", "REF-EXTRUDE-CIRCLE-001-SOLID"], operationData: { source_feature: "EXTRUDE-CIRCLE-001", source_revision: args.source.revisionId, mirror_plane: args.input.mirrorPlane, mirrored_center_x_mm: mirroredCenter.x, mirrored_center_y_mm: mirroredCenter.y }, sourceRevision: args.source.revisionId, resultRevision: revisionId, status: args.preview ? "PREVIEW_READY" : "KERNEL_VALIDATED", provenance: "KERNEL_VALIDATED", description: "OpenCascade plane reflection of the declared source solid. The result contains the transformed Mirror feature only; no source union or arbitrary plane is inferred." };
  let center: any; let normal: any; let plane: any; let circle: any; let edge: any; let wire: any; let face: any; let prism: any; let origin: any; let mirrorNormal: any; let mirrorPlane: any; let transform: any; let analyzer: any; let progress: any;
  return runWithOpenCascadeAdmission({ projectId: args.projectId, resourceClass: "FEATURE_HISTORY" }, async () => { try {
    const oc = await getOpenCascadeKernel(); center = new oc.gp_Pnt_3(values.centerX, values.centerY, 0); normal = new oc.gp_Dir_4(0, 0, 1); plane = new oc.gp_Ax2_3(center, normal); circle = new oc.gp_Circ_2(plane, values.radius); edge = new oc.BRepBuilderAPI_MakeEdge_8(circle); wire = new oc.BRepBuilderAPI_MakeWire_2(edge.Edge()); face = new oc.BRepBuilderAPI_MakeFace_15(wire.Wire(), true); prism = new oc.BRepPrimAPI_MakePrism_1(face.Face(), new oc.gp_Vec_4(0, 0, values.extrudeDistance), true, true); const sourceShape = prism.Shape(); const sourceAnalyzer = new oc.BRepCheck_Analyzer(sourceShape, true, false); if (!sourceAnalyzer.IsValid_2()) throw new Error("The declared source circle extrusion could not be rebuilt as a valid BRep for Mirror."); sourceAnalyzer.delete();
    origin = new oc.gp_Pnt_3(0, 0, 0); const normalVector = args.input.mirrorPlane === "GLOBAL_X" ? [1, 0, 0] : args.input.mirrorPlane === "GLOBAL_Y" ? [0, 1, 0] : [0, 0, 1]; mirrorNormal = new oc.gp_Dir_4(normalVector[0], normalVector[1], normalVector[2]); mirrorPlane = new oc.gp_Ax2_3(origin, mirrorNormal); const mirrorTransform = new oc.gp_Trsf_1(); mirrorTransform.SetMirror_3(mirrorPlane); transform = new oc.BRepBuilderAPI_Transform_2(sourceShape, mirrorTransform, true); mirrorTransform.delete?.(); const mirrored = transform.Shape(); analyzer = new oc.BRepCheck_Analyzer(mirrored, true, false); if (!analyzer.IsValid_2()) throw new Error("OpenCascade BRep validation failed after declared plane reflection."); const viewerMesh = extractKernelViewerMesh(oc, mirrored, node.featureId); progress = new oc.Message_ProgressRange_1(); const stepBytes = exportValidatedStep(oc, mirrored, progress, `mirror-${revisionId}`); const generatorHash = createHash("sha256").update(stepBytes).digest("hex"); const managed = args.preview ? undefined : await executeAuthorizedFeatureHistoryStep({ projectId: args.projectId, accessKey: args.accessKey, featureRevisionId: revisionId, featureKinds: ["MIRROR"], stepBytes, generatorHash }); const stored = { key: managed?.completion.artifact.storageKey ?? "", url: managed?.completion.artifact.storageUrl ?? "" }; const result: FeatureHistoryRevision = { revisionId, projectId: args.projectId, parentRevisionId: args.historyParentRevisionId ?? args.source.revisionId, title: args.input.title, status: args.preview ? "PREVIEW" : "KERNEL_VALIDATED", truth: "KERNEL_VALIDATED", features: [...args.source.features.map((feature) => ({ ...feature })), node], geometry: { validation: "VALID", kernel: "OpenCascade.js", viewerMesh, stepBase64: stepBytes.toString("base64"), boundingBox: viewerMesh.boundingBox, export: { status: "AVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", storageKey: stored.key, url: stored.url, note: "Validated STEP geometry contains the mirrored kernel result only. STEP does not preserve this app’s feature graph." } }, requirementsSummary: "Mirror geometry is kernel validated only. It is not structurally, physically, CAE, manufacturing, safety, certification, or production validated.", decisionSummary: args.decision, createdAt: new Date().toISOString() }; result.geometry.topologyManifest = topologyManifest(result); if (!args.preview) result.geometry.export!.provenance = { projectId: result.projectId, model: result.title, sourceRevisionId: result.revisionId, branch: result.parentRevisionId ?? "ROOT", exportedAt: result.createdAt, geometryValidation: "VALID", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", sha256: generatorHash, storageKey: stored.key, url: stored.url }; return result;
  } catch (error) { return failed({ ...args, reason: error instanceof Error ? error.message : "Unknown OpenCascade Mirror failure." }); }
  finally { progress?.delete?.(); analyzer?.delete?.(); transform?.delete?.(); mirrorPlane?.delete?.(); mirrorNormal?.delete?.(); origin?.delete?.(); prism?.delete?.(); face?.delete?.(); wire?.delete?.(); edge?.delete?.(); circle?.delete?.(); plane?.delete?.(); normal?.delete?.(); center?.delete?.(); } });
}

export async function createMirror(args: HistoryArgs & { input: MirrorInput }) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); const source = (await listFeatureHistory(args)).find((revision) => revision.revisionId === args.input.sourceRevisionId); if (!source) throw new Error("The authorized source revision is unavailable; no Mirror operation was attempted."); const result = await build({ ...args, input: args.input, source, decision: `Created bounded ${args.input.mirrorPlane} Mirror from ${source.revisionId}.` }); if (result.status === "FAILED") { await persistFailure(args, result); return result; } cacheFeatureHistoryRevision(result); return result; }
export async function previewMirrorRegeneration(args: HistoryArgs & { sourceRevisionId: string; edit: MirrorEdit }) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); const parent = (await listFeatureHistory(args)).find((revision) => revision.revisionId === args.sourceRevisionId); const node = parent?.features.find((feature) => feature.featureType === "MIRROR"); if (!parent || !node) throw new Error("A stored Mirror revision is required for controlled regeneration."); const source = (await listFeatureHistory(args)).find((revision) => revision.revisionId === node.operationData?.source_revision); if (!source) throw new Error("The Mirror’s declared immutable source revision is unavailable; no regeneration was attempted."); const mirrorPlane = args.edit.mirrorPlane ?? node.operationData?.mirror_plane as MirrorPlane; const preview = await build({ ...args, input: { title: `${parent.title} · Mirror Preview`, sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", mirrorPlane }, source, historyParentRevisionId: parent.revisionId, preview: true, decision: `Preview Mirror regeneration from ${parent.revisionId}.` }); previews.set(key(args.projectId, preview.revisionId), preview); return preview; }
export async function executeMirrorRegeneration(args: HistoryArgs & { previewRevisionId: string }) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); const preview = previews.get(key(args.projectId, args.previewRevisionId)); if (!preview || preview.status !== "PREVIEW" || preview.geometry.validation !== "VALID") throw new Error("Mirror preview is unavailable or invalid; no source revision changed."); const node = preview.features.find((feature) => feature.featureType === "MIRROR"); const parent = (await listFeatureHistory(args)).find((revision) => revision.revisionId === preview.parentRevisionId); const source = (await listFeatureHistory(args)).find((revision) => revision.revisionId === node?.operationData?.source_revision); if (!node || !parent || !source) throw new Error("Mirror source or immutable parent revision is unavailable; no execution occurred."); const result = await build({ ...args, input: { title: preview.title.replace(" · Mirror Preview", ""), sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", mirrorPlane: node.operationData?.mirror_plane as MirrorPlane }, source, historyParentRevisionId: parent.revisionId, decision: `Approved bounded Mirror preview ${preview.revisionId}.` }); if (result.status === "FAILED") { await persistFailure(args, result); return result; } cacheFeatureHistoryRevision(result); return result; }
export async function rejectMirrorPreview(args: HistoryArgs & { previewRevisionId: string }) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); const preview = previews.get(key(args.projectId, args.previewRevisionId)); if (!preview) throw new Error("Mirror preview is unavailable or expired; no source revision changed."); previews.delete(key(args.projectId, args.previewRevisionId)); return { rejected: true as const, previewRevisionId: preview.revisionId, preservedRevisionId: preview.parentRevisionId, status: "REJECTED" as const, truth: "FACT" as const, note: "The non-persistent Mirror preview was rejected. No immutable source revision was modified." }; }

export function planMirror(message: string) { const sourceRevisionId = message.match(/source\s*(?:revision)?\s*(?:=|:)?\s*([a-z0-9-]{6,})/i)?.[1]; const sourceFeatureId = /\bextrude-circle-001\b|\bthis\s+boss\b/i.test(message) ? "EXTRUDE-CIRCLE-001" as const : undefined; const yz = /\byz\s*plane\b|across\s+(?:the\s+)?global[_\s]*x\b|mirror[_\s]*plane\s*(?:=|:)?\s*global[_\s]*x\b/i.test(message); const xz = /\bxz\s*plane\b|across\s+(?:the\s+)?global[_\s]*y\b|mirror[_\s]*plane\s*(?:=|:)?\s*global[_\s]*y\b/i.test(message); const xy = /\bxy\s*plane\b|across\s+(?:the\s+)?global[_\s]*z\b|mirror[_\s]*plane\s*(?:=|:)?\s*global[_\s]*z\b/i.test(message); const plane = yz ? "GLOBAL_X" as const : xz ? "GLOBAL_Y" as const : xy ? "GLOBAL_Z" as const : undefined; const questions = [!sourceRevisionId && "Which validated source revision contains the feature to mirror? Provide its immutable revision ID.", !sourceFeatureId && "Which source feature should be mirrored? The bounded route supports EXTRUDE-CIRCLE-001 only.", !plane && "Which explicit global mirror plane is required? Use YZ (GLOBAL_X), XZ (GLOBAL_Y), or XY (GLOBAL_Z)."].filter(Boolean) as string[]; if (questions.length) return { status: "OPEN_QUESTION" as const, executable: false, operation: "MIRROR", questions, limits: ["No selected feature or plane was guessed.", "Only EXTRUDE-CIRCLE-001 and GLOBAL_X/GLOBAL_Y/GLOBAL_Z planes are kernel-backed.", "Fillet remains blocked."] }; return { status: "READY_FOR_PREVIEW" as const, executable: true, operation: "MIRROR", input: { title: "CAD Agent Mirror", sourceRevisionId: sourceRevisionId!, sourceFeatureId: sourceFeatureId!, mirrorPlane: plane! }, steps: ["Resolve the declared immutable source revision.", `Reflect the source BRep only across declared ${plane}.`, "Validate the transformed BRep.", "Create a non-persistent preview and require approval before an immutable branch."], limits: ["The result is CAD KERNEL VALIDATED only, not engineering validated.", "No arbitrary mirror plane, fillet, CAE, manufacturing, safety, or production validation is implied."] }; }
