import crypto from "node:crypto";

import type { BOMRevision, BOMRevisionState, DrawingPackage, DrawingPackageState, ManufacturingPlan, ManufacturingPlanState, PLMLifecycleState, PLMRevision } from "../shared/planning";
import type { EngineeringTruthStatus } from "../shared/engineeringTruth";
import { createDigitalThreadArtifact, listDigitalThreadArtifacts } from "./digitalThread";
import { appendPersistentMemory, projectMemorySnapshot } from "./persistentMemory";

type ProjectAccess = { projectId: string; accessKey: string };
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const now = () => new Date().toISOString();
const retention = { historicalRecordPreserved: true as const, deletionPolicy: "NO_SILENT_DELETION" as const };
function parse<T>(content: string): T | undefined { try { return JSON.parse(content) as T; } catch { return undefined; } }
async function records<T>(args: ProjectAccess, kind: "ENGINEERING_DRAWING_PACKAGE" | "ENGINEERING_BOM_REVISION" | "ENGINEERING_PLM_REVISION" | "ENGINEERING_MANUFACTURING_PLAN") { const snapshot = await projectMemorySnapshot(args); return snapshot.records.filter((record) => record.kind === kind).map((record) => parse<T>(record.content)).filter((item): item is T => Boolean(item)); }
async function requireKinds(args: ProjectAccess, artifactIds: string[], required: string[]) { const artifacts = await listDigitalThreadArtifacts(args); const selected = artifacts.filter((item) => artifactIds.includes(item.artifactId)); const missing = required.filter((kind) => !selected.some((item) => item.kind === kind)); if (missing.length) throw new Error(`Planning record requires immutable upstream artifact kinds: ${missing.join(", ")}.`); return selected; }

export async function createDrawingPackage(args: ProjectAccess & { title: string; revision: string; sourceCadArtifactIds: string[]; sourceCadRevision: string; sourceCadHash?: string; views: DrawingPackage["views"]; dimensions: DrawingPackage["dimensions"]; annotations: DrawingPackage["annotations"]; titleBlock: DrawingPackage["titleBlock"]; state: DrawingPackageState; provenance: string[]; limitations: string[]; declaredBy: string }): Promise<DrawingPackage> {
  await requireKinds(args, args.sourceCadArtifactIds, ["CAD_MODEL"]);
  if (args.dimensions.some((dimension) => dimension.value !== undefined && !dimension.sourceReference)) throw new Error("A declared drawing dimension value requires an explicit source reference; no dimension may be invented.");
  const dimensionsSourceBound = args.dimensions.every((dimension) => dimension.value === undefined || Boolean(dimension.sourceReference));
  const artifact = await createDigitalThreadArtifact({ ...args, kind: "DRAWING_PACKAGE", sourceArtifactIds: args.sourceCadArtifactIds, externalSourceRecordIds: [], state: args.state === "REJECTED" ? "REJECTED" : "REVIEW_REQUIRED", truthStatus: "UNVERIFIED", provenance: args.provenance, limitations: [...args.limitations, "No drawing renderer, derived dimension engine, or standards-compliance verifier is available."], declaredBy: args.declaredBy });
  const drawing: DrawingPackage = { drawingPackageId: id("DRAWING"), projectId: args.projectId, digitalThreadArtifactId: artifact.artifactId, title: args.title, revision: args.revision, sourceCadArtifactIds: args.sourceCadArtifactIds, sourceCadRevision: args.sourceCadRevision, sourceCadHash: args.sourceCadHash, views: args.views, dimensions: args.dimensions, annotations: args.annotations, titleBlock: args.titleBlock, state: args.state, validation: { cadReferenceResolved: true, dimensionsSourceBound, rendererAvailable: false, standardsComplianceClaimed: false, status: dimensionsSourceBound ? "UNKNOWN" : "FAIL" }, provenance: args.provenance, limitations: [...args.limitations, "No rendered drawing, manufacturing certification, or standards compliance is claimed."], createdAt: now(), retention, executionEligible: false, executable: false };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "ENGINEERING_DRAWING_PACKAGE", title: `Drawing package · ${drawing.title} · ${drawing.revision}`, content: JSON.stringify(drawing), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", sourceRecordId: drawing.digitalThreadArtifactId, authorSource: "SYSTEM" } });
  return drawing;
}
export async function listDrawingPackages(args: ProjectAccess) { return (await records<DrawingPackage>(args, "ENGINEERING_DRAWING_PACKAGE")).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }

export async function createBOMRevision(args: ProjectAccess & { title: string; revision: string; sourceArtifactIds: string[]; items: BOMRevision["items"]; state: BOMRevisionState; provenance: string[]; limitations: string[]; declaredBy: string }): Promise<BOMRevision> {
  await requireKinds(args, args.sourceArtifactIds, ["CAD_MODEL"]);
  if (!args.items.length) throw new Error("A BOM revision requires at least one explicitly declared item.");
  const artifacts = await listDigitalThreadArtifacts(args);
  if (args.items.some((item) => item.quantity <= 0 || !artifacts.some((artifact) => artifact.artifactId === item.sourceArtifactId))) throw new Error("Every BOM line requires a positive declared quantity and a project-scoped source artifact.");
  const artifact = await createDigitalThreadArtifact({ ...args, kind: "BOM_ITEM", sourceArtifactIds: args.sourceArtifactIds, externalSourceRecordIds: [], state: args.state === "REJECTED" ? "REJECTED" : "REVIEW_REQUIRED", truthStatus: "UNVERIFIED", provenance: args.provenance, limitations: [...args.limitations, "No automatic assembly structure or supplier capability is inferred."], declaredBy: args.declaredBy });
  const bom: BOMRevision = { bomRevisionId: id("BOM"), projectId: args.projectId, digitalThreadArtifactId: artifact.artifactId, title: args.title, revision: args.revision, sourceArtifactIds: args.sourceArtifactIds, items: args.items, state: args.state, validation: { sourceArtifactsResolved: true, quantitiesDeclared: true, autoStructureInference: false, status: "UNKNOWN" }, provenance: args.provenance, limitations: [...args.limitations, "Declared quantities are not procurement, inventory, release, or supplier confirmation."], createdAt: now(), retention, executionEligible: false, executable: false };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "ENGINEERING_BOM_REVISION", title: `BOM revision · ${bom.title} · ${bom.revision}`, content: JSON.stringify(bom), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", sourceRecordId: bom.digitalThreadArtifactId, authorSource: "SYSTEM" } });
  return bom;
}
export async function listBOMRevisions(args: ProjectAccess) { return (await records<BOMRevision>(args, "ENGINEERING_BOM_REVISION")).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }

export async function createPLMRevision(args: ProjectAccess & { partNumber: string; revision: string; parentPLMRevisionId?: string; sourceArtifactIds: string[]; lifecycleState: PLMLifecycleState; engineeringChangeReason: string; comparisonSummary: string; provenance: string[]; limitations: string[]; declaredBy: string }): Promise<PLMRevision> {
  await requireKinds(args, args.sourceArtifactIds, ["CAD_MODEL", "BOM_ITEM", "DRAWING_PACKAGE"]);
  const prior = await records<PLMRevision>(args, "ENGINEERING_PLM_REVISION");
  if (args.parentPLMRevisionId && !prior.some((item) => item.plmRevisionId === args.parentPLMRevisionId)) throw new Error("A PLM revision parent must exist in the authorized project.");
  const artifact = await createDigitalThreadArtifact({ ...args, kind: "PLM_REVISION", title: `PLM revision ${args.partNumber} ${args.revision}`, sourceArtifactIds: args.sourceArtifactIds, externalSourceRecordIds: [], state: args.lifecycleState === "BLOCKED" ? "REJECTED" : "REVIEW_REQUIRED", truthStatus: "UNVERIFIED", provenance: args.provenance, limitations: [...args.limitations, "No release authority, approval, or effectivity decision is created by this record."], declaredBy: args.declaredBy });
  const plm: PLMRevision = { plmRevisionId: id("PLM"), projectId: args.projectId, digitalThreadArtifactId: artifact.artifactId, partNumber: args.partNumber, revision: args.revision, parentPLMRevisionId: args.parentPLMRevisionId, sourceArtifactIds: args.sourceArtifactIds, lifecycleState: args.lifecycleState, engineeringChangeReason: args.engineeringChangeReason, comparisonSummary: args.comparisonSummary, approvalState: "NOT_APPROVED", releaseState: "NOT_RELEASED", provenance: args.provenance, limitations: [...args.limitations, "A release requires independent approval and is not available in this planning foundation."], createdAt: now(), retention, executionEligible: false, executable: false };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "ENGINEERING_PLM_REVISION", title: `PLM revision · ${plm.partNumber} · ${plm.revision}`, content: JSON.stringify(plm), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", sourceRecordId: plm.digitalThreadArtifactId, authorSource: "SYSTEM" } });
  return plm;
}
export async function listPLMRevisions(args: ProjectAccess) { return (await records<PLMRevision>(args, "ENGINEERING_PLM_REVISION")).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }

export async function createManufacturingPlan(args: ProjectAccess & { title: string; revision: string; sourceArtifactIds: string[]; processIntent: ManufacturingPlan["processIntent"]; materialProcessCompatibility: ManufacturingPlan["materialProcessCompatibility"]; dfmFindings: ManufacturingPlan["dfmFindings"]; setupPlanning: ManufacturingPlan["setupPlanning"]; toolSelectionMetadata: ManufacturingPlan["toolSelectionMetadata"]; inspectionPlanning: ManufacturingPlan["inspectionPlanning"]; state: ManufacturingPlanState; provenance: string[]; limitations: string[]; declaredBy: string }): Promise<ManufacturingPlan> {
  await requireKinds(args, args.sourceArtifactIds, ["CAD_MODEL", "BOM_ITEM"]);
  const artifact = await createDigitalThreadArtifact({ ...args, kind: "MANUFACTURING_PLAN", sourceArtifactIds: args.sourceArtifactIds, externalSourceRecordIds: [], state: args.state === "REJECTED" ? "REJECTED" : "REVIEW_REQUIRED", truthStatus: "UNVERIFIED", provenance: args.provenance, limitations: [...args.limitations, "No CAM kernel, toolpath generator, post processor, machine interface, or manufacturing validation has been executed."], declaredBy: args.declaredBy });
  const plan: ManufacturingPlan = { manufacturingPlanId: id("MANUFACTURING"), projectId: args.projectId, digitalThreadArtifactId: artifact.artifactId, title: args.title, revision: args.revision, sourceArtifactIds: args.sourceArtifactIds, processIntent: args.processIntent, materialProcessCompatibility: args.materialProcessCompatibility, dfmFindings: args.dfmFindings, setupPlanning: args.setupPlanning, toolSelectionMetadata: args.toolSelectionMetadata.map((tool) => ({ ...tool, capabilityVerified: false })), inspectionPlanning: args.inspectionPlanning, state: args.state, validation: { sourceArtifactsResolved: true, toolpathPlanningAvailable: false, postProcessorAvailable: false, machineOutputGenerated: false, certificationClaimed: false, status: "UNKNOWN" }, provenance: args.provenance, limitations: [...args.limitations, "All process, setup, tooling, and inspection entries are declared planning information only."], createdAt: now(), retention, executionEligible: false, executable: false };
  await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "ENGINEERING_MANUFACTURING_PLAN", title: `Manufacturing plan · ${plan.title} · ${plan.revision}`, content: JSON.stringify(plan), truthStatus: "UNVERIFIED", validationStage: "CONCEPTUAL", sourceRecordId: plan.digitalThreadArtifactId, authorSource: "SYSTEM" } });
  return plan;
}
export async function listManufacturingPlans(args: ProjectAccess) { return (await records<ManufacturingPlan>(args, "ENGINEERING_MANUFACTURING_PLAN")).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
