import { createHash } from "node:crypto";
import { exportValidatedStep, extractKernelViewerMesh, getOpenCascadeKernel, mergeKernelViewerMeshes } from "./cadKernel";
import { runWithOpenCascadeAdmission } from "./runtimeAdmission";
import { openPersistentProject } from "./persistentMemory";
import { executeAuthorizedFeatureHistoryStep } from "./sourceLessCadExecution";
import { topologyManifest } from "./topologyNaming";
import { cacheFeatureHistoryRevision, listFeatureHistory } from "./featureHistory";
import type { CADFeatureHistoryNode, FeatureHistoryFailure, FeatureHistoryRevision, FeatureParameter, RectangularPatternEdit, RectangularPatternInput } from "../shared/featureHistory";

type HistoryArgs = { projectId: string; accessKey: string };
type PatternValues = Pick<RectangularPatternInput, "directionX" | "directionY"> & { countX: number; countY: number; spacingX: number; spacingY: number };
type SourceValues = { centerX: number; centerY: number; radius: number; extrudeDistance: number };
const previews = new Map<string, FeatureHistoryRevision>();
const key = (projectId: string, revisionId: string) => `${projectId}:${revisionId}`;
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const mm = (value: number, unit: RectangularPatternInput["unit"]) => unit === "mm" ? value : unit === "cm" ? value * 10 : value * 1000;
const param = (name: FeatureParameter["name"], value: number, unit: FeatureParameter["unit"] = "mm"): FeatureParameter => ({ name, value, unit, normalizedValueMm: value, editable: true, provenance: "USER" });

function failure(stage: FeatureHistoryFailure["stage"], reason: string, parameter?: string): FeatureHistoryFailure {
  return { stage, reason, featureId: "RECTANGULAR-PATTERN-001", parameter, affectedDependencies: ["EXTRUDE-CIRCLE-001", "RECTANGULAR-PATTERN-001"], corrections: ["Correct only the reported explicit pattern input and create a separate preview."] };
}

function sourceValues(revision: FeatureHistoryRevision): SourceValues {
  const sketch = revision.features.find((feature) => feature.featureId === "CIRCLE-SKETCH-001");
  const extrude = revision.features.find((feature) => feature.featureId === "EXTRUDE-CIRCLE-001");
  if (!sketch || !extrude || revision.status !== "KERNEL_VALIDATED" || revision.geometry.validation !== "VALID") throw new Error("Rectangular Pattern requires a kernel-validated CIRCLE_SKETCH → EXTRUDE source revision.");
  const get = (name: FeatureParameter["name"]) => [...sketch.parameters, ...extrude.parameters].find((item) => item.name === name)?.normalizedValueMm;
  return { centerX: get("centerX") ?? Number.NaN, centerY: get("centerY") ?? Number.NaN, radius: get("radius") ?? Number.NaN, extrudeDistance: get("extrudeDistance") ?? Number.NaN };
}

function validate(values: PatternValues, source: SourceValues): string | undefined {
  if (!Number.isInteger(values.countX) || values.countX < 1 || values.countX > 24) return "countX must be an integer from 1 to 24.";
  if (!Number.isInteger(values.countY) || values.countY < 1 || values.countY > 24) return "countY must be an integer from 1 to 24.";
  if (values.countX * values.countY > 144) return "The guarded rectangular pattern is limited to 144 generated instances.";
  if (!Number.isFinite(values.spacingX) || values.spacingX <= 0) return "spacingX must be a positive finite normalized millimetre value.";
  if (!Number.isFinite(values.spacingY) || values.spacingY <= 0) return "spacingY must be a positive finite normalized millimetre value.";
  const minimum = 2 * source.radius;
  if (values.countX > 1 && values.spacingX <= minimum + 1e-9) return "spacingX would overlap or touch adjacent source solids under the guarded minimum-separation rule.";
  if (values.countY > 1 && values.spacingY <= minimum + 1e-9) return "spacingY would overlap or touch adjacent source solids under the guarded minimum-separation rule.";
  return undefined;
}

function failed(args: HistoryArgs & { input: RectangularPatternInput; source?: FeatureHistoryRevision; preview?: boolean; reason: string; parameter?: string }): FeatureHistoryRevision {
  return { revisionId: id(args.preview ? "RECTANGULAR-PATTERN-PREVIEW" : "RECTANGULAR-PATTERN-REVISION"), projectId: args.projectId, parentRevisionId: args.input.sourceRevisionId, title: args.input.title, status: "FAILED", truth: "FACT", features: args.source?.features.map((feature) => ({ ...feature })) ?? [], geometry: { validation: "UNAVAILABLE", kernel: "OpenCascade.js", export: { status: "UNAVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", note: "No successful rectangular-pattern geometry export exists because the pattern did not pass validation." } }, requirementsSummary: "No engineering claim is made after a failed guarded pattern operation.", decisionSummary: "Rectangular Pattern failed before any source revision changed.", createdAt: new Date().toISOString(), failure: failure("VALIDATION", args.reason, args.parameter) };
}

async function build(args: HistoryArgs & { input: RectangularPatternInput; values: PatternValues; source: FeatureHistoryRevision; historyParentRevisionId?: string; preview?: boolean; decision: string }): Promise<FeatureHistoryRevision> {
  const source = sourceValues(args.source);
  const invalid = validate(args.values, source);
  if (invalid) return failed({ ...args, reason: invalid, parameter: invalid.startsWith("count") ? invalid.slice(0, 6) : invalid.startsWith("spacing") ? invalid.slice(0, 8) : undefined });
  const revisionId = id(args.preview ? "RECTANGULAR-PATTERN-PREVIEW" : "RECTANGULAR-PATTERN-REVISION");
  const node: CADFeatureHistoryNode = { featureId: "RECTANGULAR-PATTERN-001", featureType: "RECTANGULAR_PATTERN", implementation: "KERNEL_BACKED", parentFeatures: ["EXTRUDE-CIRCLE-001"], inputGeometryReferences: [{ id: "REF-EXTRUDE-CIRCLE-001-SOLID", kind: "FEATURE", ownerFeatureId: "EXTRUDE-CIRCLE-001", sourceRevisionId: args.source.revisionId, resolution: "DECLARED", note: "The pattern consumes only the validated source circle extrusion from the declared immutable source revision." }], parameters: [param("countX", args.values.countX, "count"), param("countY", args.values.countY, "count"), param("spacingX", args.values.spacingX), param("spacingY", args.values.spacingY)], units: "mm", constraints: [{ id: "CONSTRAINT-PATTERN-DIRECTIONS", kind: "DIMENSION", status: "SATISFIED", description: `Translations are restricted to declared ${args.values.directionX} and ${args.values.directionY} vectors.` }], dependencies: ["EXTRUDE-CIRCLE-001", "REF-EXTRUDE-CIRCLE-001-SOLID"], operationData: { source_feature: "EXTRUDE-CIRCLE-001", source_revision: args.source.revisionId, direction_x: args.values.directionX, direction_y: args.values.directionY, count_x: args.values.countX, count_y: args.values.countY, spacing_x_mm: args.values.spacingX, spacing_y_mm: args.values.spacingY }, generatedInstances: [], sourceRevision: args.source.revisionId, resultRevision: revisionId, status: args.preview ? "PREVIEW_READY" : "KERNEL_VALIDATED", provenance: "KERNEL_VALIDATED", description: "Real OpenCascade compound of translated validated source solids. Generated instances retain source feature, grid key, and exact translation provenance." };
  let center: any; let normal: any; let plane: any; let circle: any; let edge: any; let wire: any; let face: any; let prism: any; let compound: any; let builder: any; let analyzer: any; let progress: any; const resources: any[] = []; const instanceMeshes: any[] = [];
  return runWithOpenCascadeAdmission({ projectId: args.projectId, resourceClass: "FEATURE_HISTORY" }, async () => { try {
    const oc = await getOpenCascadeKernel();
    center = new oc.gp_Pnt_3(source.centerX, source.centerY, 0); normal = new oc.gp_Dir_4(0, 0, 1); plane = new oc.gp_Ax2_3(center, normal); circle = new oc.gp_Circ_2(plane, source.radius); edge = new oc.BRepBuilderAPI_MakeEdge_8(circle); wire = new oc.BRepBuilderAPI_MakeWire_2(edge.Edge()); face = new oc.BRepBuilderAPI_MakeFace_15(wire.Wire(), true); prism = new oc.BRepPrimAPI_MakePrism_1(face.Face(), new oc.gp_Vec_4(0, 0, source.extrudeDistance), true, true);
    const sourceShape = prism.Shape(); const sourceAnalyzer = new oc.BRepCheck_Analyzer(sourceShape, true, false); if (!sourceAnalyzer.IsValid_2()) throw new Error("The source circle extrusion could not be rebuilt as a valid BRep for rectangular pattern generation."); sourceAnalyzer.delete();
    compound = new oc.TopoDS_Compound(); builder = new oc.BRep_Builder(); builder.MakeCompound(compound);
    const sx = args.values.directionX === "GLOBAL_X_POSITIVE" ? 1 : -1; const sy = args.values.directionY === "GLOBAL_Y_POSITIVE" ? 1 : -1;
    let index = 0;
    for (let y = 0; y < args.values.countY; y += 1) for (let x = 0; x < args.values.countX; x += 1) { const xOffset = sx * x * args.values.spacingX; const yOffset = sy * y * args.values.spacingY; const vector = new oc.gp_Vec_4(xOffset, yOffset, 0); const trsf = new oc.gp_Trsf_1(); trsf.SetTranslation_1(vector); const transform = new oc.BRepBuilderAPI_Transform_2(sourceShape, trsf, true); const instanceKey = `GRID-X${x + 1}-Y${y + 1}`; builder.Add(compound, transform.Shape()); instanceMeshes.push({ mesh: extractKernelViewerMesh(oc, transform.Shape(), node.featureId), instanceKey, instanceIdentity: "PROVEN" }); index += 1; node.generatedInstances!.push({ instanceId: `RECTANGULAR-INSTANCE-${String(index).padStart(3, "0")}`, instanceKey, index, sourceFeatureId: "EXTRUDE-CIRCLE-001", xOffset, yOffset, geometryReference: `INSTANCE:${instanceKey}`, topologyStatus: "PROVEN", status: "KERNEL_VALIDATED" }); resources.push(vector, trsf, transform); }
    analyzer = new oc.BRepCheck_Analyzer(compound, true, false); if (!analyzer.IsValid_2()) throw new Error("OpenCascade BRep validation failed for the assembled rectangular pattern compound."); const viewerMesh = mergeKernelViewerMeshes(instanceMeshes);
    progress = new oc.Message_ProgressRange_1(); const stepBytes = exportValidatedStep(oc, compound, progress, `rectangular-pattern-${revisionId}`); const generatorHash = createHash("sha256").update(stepBytes).digest("hex"); const managed = args.preview ? undefined : await executeAuthorizedFeatureHistoryStep({ projectId: args.projectId, accessKey: args.accessKey, featureRevisionId: revisionId, featureKinds: ["RECTANGULAR_PATTERN"], stepBytes, generatorHash }); const stored = { key: managed?.completion.artifact.storageKey ?? "", url: managed?.completion.artifact.storageUrl ?? "" };
    const result: FeatureHistoryRevision = { revisionId, projectId: args.projectId, parentRevisionId: args.historyParentRevisionId ?? args.source.revisionId, title: args.input.title, status: args.preview ? "PREVIEW" : "KERNEL_VALIDATED", truth: "KERNEL_VALIDATED", features: [...args.source.features.map((feature) => ({ ...feature })), node], geometry: { validation: "VALID", kernel: "OpenCascade.js", viewerMesh, stepBase64: stepBytes.toString("base64"), boundingBox: viewerMesh.boundingBox, export: { status: "AVAILABLE", format: "STEP_GEOMETRY", featureHistory: "NOT_PRESERVED", storageKey: stored.key, url: stored.url, note: "Validated STEP geometry is a compound of generated translated instances. STEP does not preserve this app’s feature graph." } }, requirementsSummary: "Pattern geometry is kernel validated only; it is not structurally, physically, manufacturing, safety, or production validated.", decisionSummary: args.decision, createdAt: new Date().toISOString() };
    result.geometry.topologyManifest = topologyManifest(result); if (!args.preview) result.geometry.export!.provenance = { projectId: result.projectId, model: result.title, sourceRevisionId: result.revisionId, branch: result.parentRevisionId ?? "ROOT", exportedAt: result.createdAt, geometryValidation: "VALID", format: "STEP_GEOMETRY", sha256: generatorHash, storageKey: stored.key, url: stored.url, featureHistory: "NOT_PRESERVED" }; return result;
  } catch (error) { return failed({ ...args, reason: error instanceof Error ? error.message : "Unknown rectangular-pattern kernel failure." }); }
  finally { progress?.delete?.(); analyzer?.delete?.(); resources.forEach((resource) => resource.delete?.()); builder?.delete?.(); compound?.delete?.(); prism?.delete?.(); face?.delete?.(); wire?.delete?.(); edge?.delete?.(); circle?.delete?.(); plane?.delete?.(); normal?.delete?.(); center?.delete?.(); } });
}

function publicRevision(revision: FeatureHistoryRevision): FeatureHistoryRevision { return { ...revision, geometry: { validation: revision.geometry.validation, kernel: revision.geometry.kernel, boundingBox: revision.geometry.boundingBox, topology: revision.geometry.topology, topologyManifest: revision.geometry.topologyManifest, export: revision.geometry.export }, features: revision.features.map((feature) => ({ ...feature, inputGeometryReferences: feature.inputGeometryReferences.map((reference) => ({ ...reference })), parameters: feature.parameters.map((parameter) => ({ ...parameter })), constraints: feature.constraints.map((constraint) => ({ ...constraint })), generatedInstances: feature.generatedInstances?.map((instance) => ({ ...instance })) })) }; }
async function storeFailure(_args: HistoryArgs, _revision: FeatureHistoryRevision) { return undefined; }

export async function createRectangularPattern(args: HistoryArgs & { input: RectangularPatternInput }) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); const source = (await listFeatureHistory(args)).find((revision) => revision.revisionId === args.input.sourceRevisionId); if (!source) throw new Error("The authorized source circle revision is unavailable; no rectangular pattern was attempted."); const values: PatternValues = { directionX: args.input.directionX, directionY: args.input.directionY, countX: args.input.countX, countY: args.input.countY, spacingX: mm(args.input.spacingX, args.input.unit), spacingY: mm(args.input.spacingY, args.input.unit) }; const result = await build({ ...args, input: args.input, values, source, decision: `Created guarded rectangular pattern from ${source.revisionId}.` }); if (result.status === "FAILED") { await storeFailure(args, result); return result; } cacheFeatureHistoryRevision(result); return result; }
export async function previewRectangularPatternRegeneration(args: HistoryArgs & { sourceRevisionId: string; edit: RectangularPatternEdit }) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); const revision = (await listFeatureHistory(args)).find((item) => item.revisionId === args.sourceRevisionId); const node = revision?.features.find((feature) => feature.featureType === "RECTANGULAR_PATTERN"); if (!revision || !node) throw new Error("A stored Rectangular Pattern revision is required for controlled regeneration."); const source = (await listFeatureHistory(args)).find((item) => item.revisionId === node.operationData?.source_revision); if (!source) throw new Error("The pattern’s declared immutable source circle revision is unavailable; no regeneration was attempted."); const unit = args.edit.unit ?? "mm"; const values: PatternValues = { directionX: args.edit.directionX ?? node.operationData?.direction_x as PatternValues["directionX"], directionY: args.edit.directionY ?? node.operationData?.direction_y as PatternValues["directionY"], countX: args.edit.countX ?? Number(node.operationData?.count_x), countY: args.edit.countY ?? Number(node.operationData?.count_y), spacingX: args.edit.spacingX === undefined ? Number(node.operationData?.spacing_x_mm) : mm(args.edit.spacingX, unit), spacingY: args.edit.spacingY === undefined ? Number(node.operationData?.spacing_y_mm) : mm(args.edit.spacingY, unit) }; const preview = await build({ ...args, input: { title: `${revision.title} · Rectangular Pattern Preview`, sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", ...values, unit: "mm" }, values, source, historyParentRevisionId: revision.revisionId, preview: true, decision: `Preview rectangular-pattern regeneration from ${revision.revisionId}.` }); previews.set(key(args.projectId, preview.revisionId), preview); return preview; }
export async function executeRectangularPatternRegeneration(args: HistoryArgs & { previewRevisionId: string }) { await openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); const preview = previews.get(key(args.projectId, args.previewRevisionId)); if (!preview || preview.status !== "PREVIEW" || preview.geometry.validation !== "VALID") throw new Error("Rectangular pattern preview is unavailable or invalid; no source revision changed."); const node = preview.features.find((feature) => feature.featureType === "RECTANGULAR_PATTERN"); const parent = (await listFeatureHistory(args)).find((item) => item.revisionId === preview.parentRevisionId); const source = (await listFeatureHistory(args)).find((item) => item.revisionId === node?.operationData?.source_revision); if (!node || !parent || !source) throw new Error("Pattern source or immutable parent revision is unavailable; no execution occurred."); const values: PatternValues = { directionX: node.operationData?.direction_x as PatternValues["directionX"], directionY: node.operationData?.direction_y as PatternValues["directionY"], countX: Number(node.operationData?.count_x), countY: Number(node.operationData?.count_y), spacingX: Number(node.operationData?.spacing_x_mm), spacingY: Number(node.operationData?.spacing_y_mm) }; const result = await build({ ...args, input: { title: preview.title.replace(" · Rectangular Pattern Preview", ""), sourceRevisionId: source.revisionId, sourceFeatureId: "EXTRUDE-CIRCLE-001", ...values, unit: "mm" }, values, source, historyParentRevisionId: parent.revisionId, decision: `Approved guarded rectangular-pattern preview ${preview.revisionId}.` }); if (result.status === "FAILED") { await storeFailure(args, result); return result; } cacheFeatureHistoryRevision(result); return result; }

export function planRectangularPattern(message: string) {
  const sourceRevisionId = message.match(/source\s*(?:revision)?\s*(?:=|:)?\s*([a-z0-9-]{6,})/i)?.[1];
  const sourceFeatureId = /\bextrude-circle-001\b/i.test(message) ? "EXTRUDE-CIRCLE-001" as const : undefined;
  const grid = message.match(/\b(\d+)\s*(?:x|×|by)\s*(\d+)\b/i);
  const countX = grid ? Number(grid[1]) : undefined; const countY = grid ? Number(grid[2]) : undefined;
  const xDirection = /(?:direction\s*x|x\s*direction)\s*(?:=|:)?\s*(?:global[_\s]*)?x(?:\s*(?:positive|\+))?/i.test(message) ? "GLOBAL_X_POSITIVE" as const : /(?:direction\s*x|x\s*direction)\s*(?:=|:)?\s*(?:global[_\s]*)?x\s*(?:negative|-)/i.test(message) ? "GLOBAL_X_NEGATIVE" as const : undefined;
  const yDirection = /(?:direction\s*y|y\s*direction)\s*(?:=|:)?\s*(?:global[_\s]*)?y(?:\s*(?:positive|\+))?/i.test(message) ? "GLOBAL_Y_POSITIVE" as const : /(?:direction\s*y|y\s*direction)\s*(?:=|:)?\s*(?:global[_\s]*)?y\s*(?:negative|-)/i.test(message) ? "GLOBAL_Y_NEGATIVE" as const : undefined;
  const distance = (label: "x" | "y") => message.match(new RegExp(`(?:spacing\\s*${label}|${label}\\s*spacing)\\s*(?:=|:)?\\s*(\\d+(?:\\.\\d+)?)\\s*(mm|cm|m)\\b`, "i"));
  const xSpacing = distance("x"); const ySpacing = distance("y"); const spacingX = xSpacing ? mm(Number(xSpacing[1]), xSpacing[2].toLowerCase() as RectangularPatternInput["unit"]) : undefined; const spacingY = ySpacing ? mm(Number(ySpacing[1]), ySpacing[2].toLowerCase() as RectangularPatternInput["unit"]) : undefined;
  const questions = [!sourceRevisionId && "Which validated source revision contains the boss to pattern? Provide its immutable revision ID.", !sourceFeatureId && "Which source feature should be patterned? The supported source is EXTRUDE-CIRCLE-001 only.", !xDirection && "What signed X direction should be used? Provide GLOBAL_X_POSITIVE or GLOBAL_X_NEGATIVE.", !yDirection && "What signed Y direction should be used? Provide GLOBAL_Y_POSITIVE or GLOBAL_Y_NEGATIVE.", (!countX || !countY) && "What grid counts should be used? Provide an explicit countX x countY grid, for example 3 x 2.", spacingX === undefined && "What explicit X spacing should be used with units (mm, cm, or m)?", spacingY === undefined && "What explicit Y spacing should be used with units (mm, cm, or m)?"].filter(Boolean) as string[];
  if (questions.length) return { status: "OPEN_QUESTION" as const, executable: false, operation: "RECTANGULAR_PATTERN", questions, limits: ["No source, direction, count, spacing, or units were guessed.", "Only signed Global X and Global Y translations over a validated offset circle extrusion are supported.", "FILLET_READY remains FALSE."] };
  if (!Number.isInteger(countX) || !Number.isInteger(countY) || countX! < 1 || countY! < 1 || countX! > 24 || countY! > 24 || !Number.isFinite(spacingX) || !Number.isFinite(spacingY) || spacingX! <= 0 || spacingY! <= 0) return { status: "INVALID" as const, executable: false, operation: "RECTANGULAR_PATTERN", questions: ["Counts must be integers from 1 to 24 and both spacing values must be positive after unit normalization."], limits: ["No kernel operation was attempted."] };
  return { status: "READY_FOR_PREVIEW" as const, executable: true, operation: "RECTANGULAR_PATTERN", input: { title: "CAD Agent rectangular pattern", sourceRevisionId: sourceRevisionId!, sourceFeatureId: sourceFeatureId!, directionX: xDirection!, directionY: yDirection!, countX: countX!, countY: countY!, spacingX: spacingX!, spacingY: spacingY!, unit: "mm" as const }, steps: ["Resolve the declared immutable source revision.", "Validate signed global X/Y directions and explicit grid count/spacing units.", "Validate conservative non-overlap.", "Build real translated BRep instances in a compound.", "Require user approval before immutable execution."], limits: ["Only GLOBAL_X and GLOBAL_Y translations are supported.", "No fillet, CAE, manufacturing, safety, structural, physical, or production validation is implied."] };
}
