import type { CAEEvidenceGraph, FutureRuntimeArchitectureReview, FutureRuntimeBoundary, FutureRuntimeFailurePolicy, FutureRuntimeHumanGate, FutureRuntimePermissionPolicy, FutureRuntimeResourceLimit, FutureRuntimeSecurityTest, FutureRuntimeThreat, FutureSolverInputOutputContract } from "../shared/cae";
import { appendTrustSecurityAudit } from "./caeTrust";
import { appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";

type ProjectAccess = { projectId: string; accessKey: string };
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
function parse<T>(value: string): T | undefined { try { return JSON.parse(value) as T; } catch { return undefined; } }
async function authorize(args: ProjectAccess) { return openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function records(args: ProjectAccess) { await authorize(args); return (await projectMemorySnapshot(args)).records.filter((record) => record.kind === "CAE_RUNTIME_ARCHITECTURE_REVIEW").flatMap((record) => { const item = parse<FutureRuntimeArchitectureReview>(record.content); return item ? [item] : []; }); }

const boundaries: FutureRuntimeBoundary[] = [
  { boundaryId: "BOUNDARY-CAD-CAE", from: "CAD_AI", to: "CAE_AGENT", permittedData: ["immutable CAD revision reference", "validated geometry provenance", "requirements references"], prohibitedOperations: ["solver invocation", "result creation"], requiredEvidence: ["CAD revision hash", "geometry validation status"], trustRequirement: "CAE Agent may consume declared input only." },
  { boundaryId: "BOUNDARY-CAE-ADAPTER", from: "CAE_AGENT", to: "SOLVER_ADAPTER", permittedData: ["versioned CAE plan", "declared material evidence references", "selected geometry references"], prohibitedOperations: ["adapter code loading", "shell instruction transfer"], requiredEvidence: ["adapter trust readiness", "input schema version"], trustRequirement: "Adapter is data-bound and may not obtain ambient authority." },
  { boundaryId: "BOUNDARY-ADAPTER-MANAGER", from: "SOLVER_ADAPTER", to: "EXECUTION_MANAGER", permittedData: ["signed adapter manifest", "declared capabilities", "bounded execution request"], prohibitedOperations: ["direct solver launch", "permission self-grant"], requiredEvidence: ["verified adapter identity", "verified human approval"], trustRequirement: "Execution Manager alone would authorize a future launch." },
  { boundaryId: "BOUNDARY-MANAGER-SANDBOX", from: "EXECUTION_MANAGER", to: "SANDBOX", permittedData: ["immutable input bundle", "approved resource policy", "allowlisted solver image identity"], prohibitedOperations: ["host mount", "credential injection", "network policy relaxation"], requiredEvidence: ["sandbox attestation", "resource policy hash"], trustRequirement: "Sandbox policy is enforced below the adapter trust boundary." },
  { boundaryId: "BOUNDARY-SANDBOX-SOLVER", from: "SANDBOX", to: "SOLVER", permittedData: ["read-only input bundle", "bounded temporary workspace"], prohibitedOperations: ["host process control", "arbitrary network", "arbitrary filesystem"], requiredEvidence: ["solver identity", "image or binary hash"], trustRequirement: "Solver receives least privilege only." },
  { boundaryId: "BOUNDARY-SOLVER-COLLECTOR", from: "SOLVER", to: "RESULT_COLLECTOR", permittedData: ["bounded result files", "bounded logs", "exit status"], prohibitedOperations: ["result acceptance", "provenance rewriting"], requiredEvidence: ["output hash", "runtime event record"], trustRequirement: "All output is untrusted until verification." },
  { boundaryId: "BOUNDARY-COLLECTOR-VERIFY", from: "RESULT_COLLECTOR", to: "RESULT_VERIFICATION", permittedData: ["parsed candidate output", "immutable raw output hash", "warnings and errors"], prohibitedOperations: ["automatic verified classification"], requiredEvidence: ["schema and provenance contract"], trustRequirement: "Parsing is not validation." },
  { boundaryId: "BOUNDARY-VERIFY-GRAPH", from: "RESULT_VERIFICATION", to: "EVIDENCE_GRAPH", permittedData: ["verification outcome", "provenance links", "immutable failure records"], prohibitedOperations: ["silent overwrite", "history deletion"], requiredEvidence: ["human acceptance decision for verified result"], trustRequirement: "Graph retains both accepted and invalid history." },
];
const threatDefinitions: Array<[FutureRuntimeThreat["threat"], string, string, string[]]> = [
  ["MALICIOUS_ADAPTER", "adapter package", "arbitrary behavior or privilege request", ["signed identity", "capability diff", "isolated runtime", "human approval"]], ["TAMPERED_SOLVER", "solver binary or image", "incorrect or hostile numerical output", ["immutable solver hash", "trusted registry provenance", "revocation check"]], ["MALICIOUS_INPUT", "CAE or CAD input bundle", "parser abuse or unintended solver behavior", ["strict schemas", "bounded sizes", "content hashing"]], ["MALICIOUS_OUTPUT", "result and log files", "parser exploitation or false engineering claim", ["bounded collector", "schema validation", "untrusted parsed state"]], ["RESOURCE_EXHAUSTION", "CPU, memory, storage, runtime", "availability loss", ["kernel-enforced limits", "watchdog", "immutable timeout event"]], ["FILESYSTEM_ESCAPE", "temporary workspace", "host data access", ["read-only inputs", "no host mounts", "sandbox attestation"]], ["NETWORK_ESCAPE", "solver or adapter", "exfiltration or remote control", ["default-deny network", "egress enforcement", "network violation test"]], ["PRIVILEGE_ESCALATION", "adapter or solver process", "host control", ["non-root identity", "no capabilities", "process isolation"]], ["CREDENTIAL_EXPOSURE", "environment and files", "secret disclosure", ["no credentials in sandbox", "redacted logging", "secret scanning"]], ["DATA_EXFILTRATION", "output and logs", "engineering data loss", ["egress deny", "bounded outputs", "reviewed export path"]], ["RESULT_MANIPULATION", "output collector", "false result provenance", ["raw result hash", "append-only evidence", "independent verification"]], ["REPLAY", "old input or result bundle", "stale result acceptance", ["nonce and timestamp", "revision hashes", "replay detection"]], ["VERSION_MISMATCH", "adapter, solver, schemas", "non-reproducible result", ["version lock", "compatibility gate", "reproduction manifest"]],
];
const threats: FutureRuntimeThreat[] = threatDefinitions.map(([threat, entryPoint, impact, requiredMitigations]) => ({ threat, entryPoint, impact, requiredMitigations, residualRisk: "NOT_ACCEPTED" as const }));
const permissions: FutureRuntimePermissionPolicy[] = ["READ_CAD_INPUT", "READ_CAE_INPUT", "READ_MATERIAL_EVIDENCE", "WRITE_TEMPORARY_FILES", "WRITE_RESULT_FILES", "WRITE_LOGS", "NETWORK", "CPU", "MEMORY", "STORAGE", "RUNTIME", "PROCESS"].map((permission) => ({ permission: permission as FutureRuntimePermissionPolicy["permission"], defaultDecision: "DENY", futureGrantRequirement: "Verified-human approval, adapter manifest match, attested sandbox policy, and Execution Manager enforcement.", scope: permission === "NETWORK" ? "No network is permitted." : "Single immutable execution bundle only.", evidenceRequired: ["adapter trust verification", "sandbox attestation", "policy hash"] }));
const limits: FutureRuntimeResourceLimit[] = ["CPU", "RAM", "DISK", "RUNTIME", "PROCESS_COUNT", "FILE_COUNT", "INPUT_SIZE", "OUTPUT_SIZE"].map((resource) => ({ resource: resource as FutureRuntimeResourceLimit["resource"], enforcementPoint: resource === "INPUT_SIZE" || resource === "OUTPUT_SIZE" ? "STORAGE_GATEWAY" : resource === "PROCESS_COUNT" ? "KERNEL" : "SANDBOX", unit: resource === "CPU" ? "millicores" : resource === "RAM" || resource === "DISK" || resource.endsWith("SIZE") ? "bytes" : resource === "RUNTIME" ? "seconds" : "count", status: "NOT_CONFIGURED", bypassPrevention: "A future Execution Manager and kernel-backed sandbox must enforce this outside adapter and solver control; no unapproved limit is assumed." }));
const ioContract: FutureSolverInputOutputContract = { contractVersion: "1.0.0", inputSchema: ["CAD revision hash", "CAE plan revision", "geometry selection references", "material evidence references"], configurationSchema: ["solver version", "adapter version", "schema version", "declared analysis configuration"], outputSchema: ["quantity identifier", "value payload", "unit", "location or region reference", "solver status", "convergence evidence"], metadataSchema: ["execution identifier", "timestamps", "resource outcome", "exit classification"], logSchema: ["bounded structured events", "warning list", "error list", "redaction status"], errorSchema: ["failure class", "immutable diagnostic reference", "no result acceptance"], provenanceSchema: ["solver identity", "solver version", "adapter identity", "adapter version", "input hash", "CAD revision hash", "CAE plan revision", "material references", "runtime identity", "execution timestamp", "result hash"], parserTrustRule: "PARSED_OUTPUT_IS_UNVERIFIED" };
const failures: FutureRuntimeFailurePolicy[] = [["TIMEOUT", "Stop collection; preserve partial artifacts as unverified."], ["CRASH", "Preserve exit evidence; mark result invalid."], ["MEMORY_EXHAUSTION", "Terminate through enforced limit; mark invalid."], ["INVALID_RESULT", "Retain raw output hash; refuse result acceptance."], ["PARTIAL_RESULT", "Retain partial artifact; prohibit engineering use."], ["SOLVER_WARNING", "Retain warning; require verifier and human disposition."], ["SOLVER_DIVERGENCE", "Mark invalid; prohibit metric extraction."], ["SANDBOX_VIOLATION", "Terminate; preserve violation audit; revoke future authorization pending review."], ["ADAPTER_FAILURE", "Stop; preserve adapter event; prohibit silent retry."]].map(([failure, response]) => ({ failure: failure as FutureRuntimeFailurePolicy["failure"], response, historicalRecord: "IMMUTABLE" as const, resultState: failure === "SOLVER_WARNING" || failure === "PARTIAL_RESULT" ? "UNVERIFIED" as const : "INVALID" as const }));
const humanGates: FutureRuntimeHumanGate[] = [["SOLVER_REGISTRATION", ["solver identity", "version", "hash", "license and provenance"]], ["ADAPTER_APPROVAL", ["adapter verification", "permission diff", "sandbox attestation"]], ["EXECUTION_AUTHORIZATION", ["complete execution trust readiness", "approved resource policy", "approved input bundle"]], ["RESULT_ACCEPTANCE", ["result provenance", "verification record", "warnings disposition"]], ["VALIDATION_DECISION", ["accepted result", "engineering rationale", "human reviewer identity"]]].map(([operation, requiredEvidence]) => ({ operation: operation as FutureRuntimeHumanGate["operation"], actor: "VERIFIED_HUMAN", aiMayRecommend: true, aiMayApprove: false, requiredEvidence: requiredEvidence as string[] }));
const securityTests: FutureRuntimeSecurityTest[] = [["SANDBOX_ESCAPE", "Attempted escape is blocked and immutably audited."], ["PERMISSION_ESCALATION", "Undeclared permission is denied outside adapter control."], ["RESOURCE_EXHAUSTION", "Every configured resource limit terminates safely without host impact."], ["TAMPERED_INPUT", "Input hash or schema mismatch prevents execution."], ["TAMPERED_OUTPUT", "Output hash or provenance mismatch remains invalid."], ["ADAPTER_REVOCATION", "Revoked adapter cannot receive new authorization."], ["SOLVER_REVOCATION", "Revoked solver cannot receive new authorization."], ["RESULT_PROVENANCE", "Required provenance fields resolve to immutable references."], ["REPRODUCIBILITY", "Complete locked manifest can be independently reviewed before reproduction."], ["FAIL_CLOSED", "Any unknown, missing, invalid, expired, or revoked signal refuses execution."]].map(([test, passCriteria]) => ({ test: test as FutureRuntimeSecurityTest["test"], requiredBeforeExecution: true, passCriteria }));

function build(projectId: string): FutureRuntimeArchitectureReview { return { reviewId: id("RUNTIME-ARCHITECTURE"), projectId, contractVersion: "1.0.0", architecture: ["CAD_AI", "CAE_AGENT", "SOLVER_ADAPTER", "EXECUTION_MANAGER", "SANDBOX", "SOLVER", "RESULT_COLLECTOR", "RESULT_VERIFICATION", "EVIDENCE_GRAPH"], boundaries, threats, permissions, resourceLimits: limits, sandboxRequirements: ["No host mount or host process control.", "Default-deny network and no ambient credentials.", "Read-only immutable inputs and a bounded temporary workspace.", "Non-root process identity with dropped capabilities.", "Kernel-enforced CPU, memory, storage, runtime, process, and file limits.", "Independent attestation, revocation checks, and violation auditing before any future execution."], ioContract, resultTrustRequirements: ["solverIdentity", "solverVersion", "adapterIdentity", "adapterVersion", "inputHash", "cadRevisionHash", "caePlanRevision", "materialEvidenceReferences", "runtimeIdentity", "executionTimestamp", "resultHash"], verification: { requiredChecks: ["SCHEMA_VALIDITY", "HASH_INTEGRITY", "EXPECTED_QUANTITIES", "UNITS", "RANGES", "MISSING_VALUES", "SOLVER_STATUS", "CONVERGENCE_EVIDENCE", "WARNINGS", "ERRORS"], resultStates: ["VERIFIED", "UNVERIFIED", "INVALID"], automaticVerificationProhibited: true }, failures, reproducibility: { requiredReferences: ["CAD_REVISION", "CAE_REVISION", "MATERIAL_EVIDENCE", "SOLVER_VERSION", "ADAPTER_VERSION", "CONFIGURATION", "INPUT_HASH", "RUNTIME_VERSION"], reproductionRequiresHumanReview: true, missingReferenceBehavior: "REFUSE_REPRODUCTION" }, humanGates, securityTests, readinessDecision: "RUNTIME_NOT_APPROVED", decisionReason: "No reviewed Execution Manager, attested enforcement substrate, configured kernel-backed limits, allowlisted solver image, result verifier, or completed hostile-security test evidence exists. Phase 6.0 is architecture review only; runtime implementation is not approved.", executionEligible: false, executable: false, createdAt: new Date().toISOString() }; }

export async function createRuntimeArchitectureReview(args: ProjectAccess): Promise<FutureRuntimeArchitectureReview> { await authorize(args); const review = build(args.projectId); await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_RUNTIME_ARCHITECTURE_REVIEW", title: "Phase 6.0 runtime architecture review · RUNTIME_NOT_APPROVED", content: JSON.stringify(review), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM" } }); await appendTrustSecurityAudit(args, { actor: "SYSTEM", action: "RUNTIME_ARCHITECTURE_REVIEW", objectType: "RUNTIME_ARCHITECTURE", objectId: review.reviewId, newState: review.readinessDecision, reason: review.decisionReason }); return review; }
export async function listRuntimeArchitectureReviews(args: ProjectAccess) { return (await records(args)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
export async function buildRuntimeArchitectureGraph(args: ProjectAccess & { reviewId?: string }): Promise<CAEEvidenceGraph> { const review = args.reviewId ? (await records(args)).find((item) => item.reviewId === args.reviewId) : (await listRuntimeArchitectureReviews(args))[0]; if (!review) return { projectId: args.projectId, simulationId: "RUNTIME-ARCHITECTURE-REVIEW", nodes: [], edges: [], limitations: ["No Phase 6.0 architecture review record exists. Execution remains not approved."] }; const nodes = [{ id: review.reviewId, type: "RUNTIME_ARCHITECTURE" as const, label: "Future runtime architecture · review only", truthStatus: "UNVALIDATED" as const }, ...review.boundaries.map((item) => ({ id: item.boundaryId, type: "RUNTIME_BOUNDARY" as const, label: `${item.from} → ${item.to}`, truthStatus: "UNVALIDATED" as const })), ...review.threats.map((item) => ({ id: `THREAT-${item.threat}`, type: "RUNTIME_THREAT" as const, label: item.threat, truthStatus: "UNVALIDATED" as const })), ...review.permissions.map((item) => ({ id: `PERMISSION-${item.permission}`, type: "RUNTIME_PERMISSION" as const, label: `${item.permission} · DENY`, truthStatus: "UNVALIDATED" as const })), ...review.resourceLimits.map((item) => ({ id: `LIMIT-${item.resource}`, type: "RUNTIME_LIMIT" as const, label: `${item.resource} · ${item.status}`, truthStatus: "UNVALIDATED" as const })), { id: `CONTRACT-${review.reviewId}`, type: "RUNTIME_RESULT_CONTRACT" as const, label: review.ioContract.parserTrustRule, truthStatus: "UNVALIDATED" as const }, ...review.humanGates.map((item) => ({ id: `GATE-${item.operation}`, type: "RUNTIME_APPROVAL_GATE" as const, label: item.operation, truthStatus: "UNVALIDATED" as const })), ...review.securityTests.map((item) => ({ id: `TEST-${item.test}`, type: "RUNTIME_TEST_PLAN" as const, label: item.test, truthStatus: "UNVALIDATED" as const })), { id: `DECISION-${review.reviewId}`, type: "RUNTIME_DECISION" as const, label: review.readinessDecision, truthStatus: "UNVALIDATED" as const }]; const edges = [...review.boundaries.map((item) => ({ id: id("GRAPH"), fromId: item.boundaryId, toId: review.reviewId, relationship: "reviewed architecture boundary", status: "DECLARED" as const })), { id: id("GRAPH"), fromId: `CONTRACT-${review.reviewId}`, toId: `DECISION-${review.reviewId}`, relationship: "parsed output remains unverified", status: "DECLARED" as const }, ...review.securityTests.map((item) => ({ id: id("GRAPH"), fromId: `TEST-${item.test}`, toId: `DECISION-${review.reviewId}`, relationship: "required before implementation approval", status: "UNKNOWN" as const }))]; return { projectId: args.projectId, simulationId: "RUNTIME-ARCHITECTURE-REVIEW", nodes, edges, limitations: [review.decisionReason, "No solver, mesher, executable adapter, shell, arbitrary plugin, arbitrary network, process execution, or arbitrary filesystem access exists in Phase 6.0."] }; }
