import type { CAEEvidenceGraph, ControlledRuntimeBoundary, EssentialRuntimeSecurityGate, MinimumViableCAEReview, RuntimeFailureModeReview, RuntimeImplementationBlocker, RuntimeImplementationPlanStep, RuntimeImplementationReadinessReview, RuntimeInventoryItem, RuntimeMeshingOption, RuntimeResultTrustRequirement, RuntimeSolverOption } from "../shared/cae";
import { appendTrustSecurityAudit } from "./caeTrust";
import { appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";

type ProjectAccess = { projectId: string; accessKey: string };
const sourceUrls = ["https://www.calculix.de/", "https://code-aster.org/en", "https://openfoam.org/", "https://gmsh.info/", "https://occt3d.com/dev/doc/overview/html/occt_user_guides__mesh.html", "https://docs.salome-platform.org/latest/gui/SMESH/index.html", "https://csrc.nist.gov/pubs/sp/800/190/final", "https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html", "https://github.com/opencontainers/runtime-spec"];
const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const parse = <T,>(content: string): T | undefined => { try { return JSON.parse(content) as T; } catch { return undefined; } };

async function authorize(args: ProjectAccess) { return openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function records(args: ProjectAccess) { await authorize(args); return (await projectMemorySnapshot(args)).records.filter((record) => record.kind === "CAE_RUNTIME_IMPLEMENTATION_REVIEW").flatMap((record) => { const review = parse<RuntimeImplementationReadinessReview>(record.content); return review ? [review] : []; }); }

const inventory: RuntimeInventoryItem[] = [
  { capability: "CAD_KERNEL", status: "IMPLEMENTED", implementedEvidence: ["OpenCascade.js bounded real geometry, validation, STEP provenance, feature history, topology evidence"], runtimeGap: "No immutable CAD-to-solver mesh snapshot or solver job binding exists." },
  { capability: "CAD_AGENT", status: "IMPLEMENTED", implementedEvidence: ["Requirements-gated deterministic plans and controlled OpenCascade operations"], runtimeGap: "No CAE job emitter may authorize a runtime." },
  { capability: "CAE_PLANNING", status: "IMPLEMENTED", implementedEvidence: ["Solver-independent plan, readiness, uncertainty, stale-CAD detection, no-result envelope"], runtimeGap: "No solver-grade meshing, job serialization, or result collector exists." },
  { capability: "REQUIREMENTS", status: "IMPLEMENTED", implementedEvidence: ["Structured requirements, open questions, unit/conflict validation, traceability"], runtimeGap: "A first job needs an explicit requirements-to-load/boundary approval snapshot." },
  { capability: "EVIDENCE", status: "EVIDENCE_BACKED", implementedEvidence: ["Hash-preserved material, measurement, calibration, and external evidence records"], runtimeGap: "No numerical-result artifact evidence exists." },
  { capability: "TRUST", status: "EVIDENCE_BACKED", implementedEvidence: ["Adapter gates, certificates, revocation sources, sandbox attestation contracts, fail-closed trust readiness"], runtimeGap: "No allowlisted runtime image or executable adapter has independently verified evidence." },
  { capability: "IDENTITY", status: "EVIDENCE_BACKED", implementedEvidence: ["Verified reviewer identity, external identity claims, independent review separation"], runtimeGap: "No production runtime operator identity or signer key has been provisioned." },
  { capability: "SANDBOX_ARCHITECTURE", status: "DESIGNED_ONLY", implementedEvidence: ["Default-deny boundary, isolation controls, threat model, hostile-test design"], runtimeGap: "No independently attested enforcement substrate exists." },
  { capability: "CAPACITY_POLICY", status: "DESIGNED_ONLY", implementedEvidence: ["Eight unknown-safe capacity policy dimensions and validation contracts"], runtimeGap: "No measured, enforced capacity limits are available." },
  { capability: "EXTERNAL_VERIFICATION", status: "EVIDENCE_BACKED", implementedEvidence: ["Immutable provenance, lifecycle, expiry, revocation, test-environment evidence intake"], runtimeGap: "No verified real runtime infrastructure/sandbox/test evidence has been supplied." },
  { capability: "GOVERNANCE", status: "EVIDENCE_BACKED", implementedEvidence: ["Independent review, retention, reviewer revocation, conflict handling, immutable lifecycle"], runtimeGap: "No approved runtime change-control package exists." },
  { capability: "AUDIT", status: "IMPLEMENTED", implementedEvidence: ["Append-only security audit and project-isolated memory records"], runtimeGap: "No runtime event-stream or immutable artifact capture exists." },
  { capability: "PROVENANCE", status: "EVIDENCE_BACKED", implementedEvidence: ["SHA-256 input evidence, CAD revision, adapter, material, and review references"], runtimeGap: "No canonical job manifest, result hash, or environment capture is implemented." },
];

const blockers: RuntimeImplementationBlocker[] = [
  { blockerId: "BLOCKER-JOB", classification: "BLOCKER", title: "No controlled CAE job compiler", why: "A validated CAE plan cannot yet be transformed into a bounded, hashable, immutable solver input package.", evidenceNeeded: ["Versioned CAE Job Contract", "input schema validation", "CAD/material/load/boundary snapshot hash"], preventsFirstControlledRuntime: true },
  { blockerId: "BLOCKER-MESH", classification: "BLOCKER", title: "No solver-grade meshing or mesh-quality verifier", why: "Viewer tessellation is not a verified finite-element volume mesh.", evidenceNeeded: ["Mesher adapter", "mesh artifact hash", "quality metrics and threshold policy"], preventsFirstControlledRuntime: true },
  { blockerId: "BLOCKER-SANDBOX", classification: "BLOCKER", title: "No implemented and independently attested execution sandbox", why: "A design declaration cannot enforce process, filesystem, network, credential, and resource boundaries.", evidenceNeeded: ["Enforcement configuration", "independent attestation", "hostile-test evidence"], preventsFirstControlledRuntime: true },
  { blockerId: "BLOCKER-RESULT", classification: "BLOCKER", title: "No result collector and verifier", why: "No system currently validates solver completion, convergence, warnings, units, hashes, provenance, or result schema.", evidenceNeeded: ["Bounded parser", "result trust gates", "corrupt/partial-output refusal tests"], preventsFirstControlledRuntime: true },
  { blockerId: "BLOCKER-ADAPTER", classification: "BLOCKER", title: "No allowlisted executable adapter or solver image", why: "Existing adapters are intentionally non-executable and no binary/image identity is verified.", evidenceNeeded: ["Pinned signed artifact", "SBOM/license review", "adapter capability verification"], preventsFirstControlledRuntime: true },
  { blockerId: "REQUIRED-CAPACITY", classification: "REQUIRED", title: "Measured enforced capacity limits", why: "Declared or unknown limits are fail closed; the first runtime needs measured and enforced CPU, memory, disk, timeout, process, and I/O limits.", evidenceNeeded: ["Infrastructure measurement evidence", "enforcement test evidence"], preventsFirstControlledRuntime: true },
  { blockerId: "REQUIRED-SECURITY", classification: "REQUIRED", title: "Independent sandbox review and hostile testing", why: "The existing review workflow is ready to hold evidence, but no evidence verifies an actual execution substrate.", evidenceNeeded: ["Independent review", "segregated hostile-test environment", "test reports"], preventsFirstControlledRuntime: true },
  { blockerId: "RECOMMENDED-REGRESSION", classification: "RECOMMENDED", title: "Golden problem and reproducibility corpus", why: "A small canonical beam/bracket corpus would detect adapter, mesher, parser, and version regressions before broader analysis support.", evidenceNeeded: ["Reviewed fixtures", "expected qualitative checks", "reproduction manifests"], preventsFirstControlledRuntime: false },
  { blockerId: "OPTIONAL-REMOTE", classification: "OPTIONAL", title: "Remote solver strategy", why: "Remote execution adds transport, tenancy, data residency, and provider assurance complexity; it is not necessary for a first controlled local/containerized path.", evidenceNeeded: ["Remote provider contract", "transport and tenancy evidence"], preventsFirstControlledRuntime: false },
];

const solverOptions: RuntimeSolverOption[] = [
  { option: "NATIVE_OPEN_SOURCE_SOLVER", representative: "CalculiX linear-static structural adapter", license: "GPL v2 or later; legal review required before distribution/integration.", integrationComplexity: "MEDIUM", sandboxRequirement: "Dedicated future execution sandbox; no host process or ambient credential access.", inputOutput: "Bounded Abaqus-style input deck and explicitly allowlisted result files.", reproducibility: "Pin solver build, adapter version, deck hash, mesh hash, and environment identity.", verification: "Independent mesh, status, warning, convergence, unit, provenance, and parser checks.", performance: "Appropriate first scope for small bounded linear-static jobs; measure rather than assume capacity.", maintainability: "Narrow adapter surface and public format are favorable; GPL obligations need review.", recommendation: "FIRST_CANDIDATE", sourceUrls: ["https://www.calculix.de/"] },
  { option: "EXTERNAL_SOLVER_ADAPTER", representative: "Adapter to an externally managed solver", license: "Provider-specific; contractual and licensing review required.", integrationComplexity: "HIGH", sandboxRequirement: "Adapter boundary plus explicit network, credential, tenancy, and data-egress controls.", inputOutput: "Versioned API and artifact schema, not opaque result claims.", reproducibility: "Provider image/version and input/result retention must be evidenced.", verification: "Add transport integrity, provider identity, and remote environment provenance.", performance: "Provider dependent; cannot be claimed before capacity evidence.", maintainability: "Higher provider and contract dependency.", recommendation: "DEFER", sourceUrls: [] },
  { option: "CONTAINERIZED_SOLVER", representative: "Pinned CalculiX image behind a minimal adapter", license: "Solver and image component licenses require an SBOM/legal review.", integrationComplexity: "HIGH", sandboxRequirement: "Rootless/non-privileged, read-only root, no Docker socket, default-deny network, strict mounts, cgroups, and independent attestation.", inputOutput: "Read-only immutable job input mount; bounded result/log output mount only.", reproducibility: "Pin image digest, OCI configuration, solver version, adapter version, and job hashes.", verification: "Hostile testing and independent sandbox review are mandatory before use.", performance: "Resource limits must be measured and enforced.", maintainability: "Most controllable first deployment model after implementation and review.", recommendation: "FIRST_CANDIDATE", sourceUrls: ["https://www.calculix.de/", "https://csrc.nist.gov/pubs/sp/800/190/final", "https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html", "https://github.com/opencontainers/runtime-spec"] },
  { option: "REMOTE_SOLVER", representative: "Provider-hosted execution", license: "Provider-specific and potentially restrictive.", integrationComplexity: "HIGH", sandboxRequirement: "Remote isolation is not a substitute for local input/output and credential boundaries.", inputOutput: "Authenticated remote job API and returned artifacts require strict schema/version control.", reproducibility: "Requires provider environment identity and retention guarantees.", verification: "Requires external provider review and independent evidence.", performance: "Network and scheduling dependent.", maintainability: "High operational and vendor dependency.", recommendation: "NOT_FOR_FIRST_RUNTIME", sourceUrls: [] },
  { option: "HYBRID_ARCHITECTURE", representative: "Local job preparation and meshing with remote solving", license: "Combined local and provider licensing review.", integrationComplexity: "HIGH", sandboxRequirement: "Both local and remote trust boundaries must be enforced and attested.", inputOutput: "Cross-boundary artifact manifests and transport integrity are mandatory.", reproducibility: "Two environment identities complicate reproduction.", verification: "Requires duplicated provenance and failure handling.", performance: "Potentially flexible but operationally complex.", maintainability: "Defer until a single-boundary path is proven.", recommendation: "NOT_FOR_FIRST_RUNTIME", sourceUrls: [] },
];

const meshingOptions: RuntimeMeshingOption[] = [
  { option: "OPENCASCADE_TRIANGULATION", capability: "Existing BRep tessellation for viewer display.", integrationComplexity: "LOW", qualityAndVerification: "Not accepted as solver-grade mesh: it lacks a controlled volume-mesh artifact and required CAE quality policy.", recommendation: "NOT_FOR_FIRST_RUNTIME", sourceUrls: ["https://occt3d.com/dev/doc/overview/html/occt_user_guides__mesh.html"] },
  { option: "DEDICATED_OPEN_SOURCE_MESHER", capability: "Gmsh-style bounded volume meshing through a separate adapter.", integrationComplexity: "MEDIUM", qualityAndVerification: "Emit versioned mesh artifact plus element counts, topology groups, quality metrics, and threshold evidence; GPL review required.", recommendation: "FIRST_CANDIDATE", sourceUrls: ["https://gmsh.info/"] },
  { option: "SOLVER_NATIVE_MESHER", capability: "Meshing delegated to a solver-specific preprocessor.", integrationComplexity: "MEDIUM", qualityAndVerification: "Tightens coupling and still needs mesh artifact and quality evidence extraction.", recommendation: "DEFER", sourceUrls: ["https://www.calculix.de/"] },
  { option: "HYBRID_MESHING", capability: "Dedicated mesher plus solver-specific preparation.", integrationComplexity: "HIGH", qualityAndVerification: "Adds transfer validation and multiple artifact formats; use only after a single mesher path is proven.", recommendation: "DEFER", sourceUrls: ["https://docs.salome-platform.org/latest/gui/SMESH/index.html"] },
];

const minimumViableCAE: MinimumViableCAEReview = { analysis: "LINEAR_STATIC_STRUCTURAL", scope: ["One validated solid CAD revision", "one material with evidence-backed elastic properties", "one explicitly approved fixed/support boundary set", "one explicitly approved static force/pressure load with units", "one solver-grade tetrahedral volume mesh", "one allowlisted adapter/solver artifact", "displacement and equivalent-stress result artifacts only after verification"], pipeline: ["CAD snapshot", "mesh artifact", "linear-static input deck", "controlled solver", "result artifacts", "result verification", "evidence graph"], excluded: ["Nonlinear material/contact", "crash/explicit dynamics", "optimization", "fatigue", "modal", "thermal coupling", "automatic design modification", "unverified numerical display"], truthRule: "A numerical field is never shown as engineering evidence unless all result-trust requirements pass; otherwise the result is INVALID or UNVERIFIED." };

const runtimeBoundary: ControlledRuntimeBoundary[] = [
  { boundaryId: "BOUNDARY-CAD-JOB", from: "CAD_AI", to: "CAE_JOB_CONTRACT", immutableInputs: ["validated CAD revision", "selected geometry references", "requirements approval", "CAE plan revision"], allowedOutputs: ["canonical job manifest"], prohibited: ["solver invocation", "mesh generation", "result creation"], requiredHashes: ["cadRevisionHash", "caePlanHash", "jobManifestHash"] },
  { boundaryId: "BOUNDARY-JOB-SANDBOX", from: "CAE_JOB_CONTRACT", to: "EXECUTION_SANDBOX", immutableInputs: ["validated job manifest", "allowlisted adapter identity", "pinned runtime identity"], allowedOutputs: ["bounded execution receipt"], prohibited: ["ambient environment inheritance", "unbounded mount", "arbitrary command"], requiredHashes: ["jobManifestHash", "adapterHash", "imageDigest"] },
  { boundaryId: "BOUNDARY-SANDBOX-ADAPTER", from: "EXECUTION_SANDBOX", to: "SOLVER_ADAPTER", immutableInputs: ["read-only input artifact set"], allowedOutputs: ["bounded solver input and logs"], prohibited: ["host process control", "network by default", "credential access"], requiredHashes: ["inputHash", "adapterHash"] },
  { boundaryId: "BOUNDARY-ADAPTER-SOLVER", from: "SOLVER_ADAPTER", to: "SOLVER", immutableInputs: ["allowlisted solver input deck"], allowedOutputs: ["allowlisted result/log artifacts"], prohibited: ["plugin installation", "unrecognized output paths"], requiredHashes: ["solverInputHash", "solverBinaryHash"] },
  { boundaryId: "BOUNDARY-SOLVER-RESULT", from: "SOLVER", to: "RESULT_ARTIFACT", immutableInputs: ["solver completion status"], allowedOutputs: ["bounded raw output artifacts"], prohibited: ["trusted numerical interpretation"], requiredHashes: ["resultHash", "logHash"] },
  { boundaryId: "BOUNDARY-RESULT-VERIFY", from: "RESULT_ARTIFACT", to: "RESULT_VERIFICATION", immutableInputs: ["raw result artifacts", "execution receipt", "job manifest"], allowedOutputs: ["verified or invalid result assessment"], prohibited: ["missing-evidence promotion", "silent warning suppression"], requiredHashes: ["resultHash", "inputHash", "environmentIdentityHash"] },
  { boundaryId: "BOUNDARY-VERIFY-GRAPH", from: "RESULT_VERIFICATION", to: "EVIDENCE_GRAPH", immutableInputs: ["verification record", "all provenance hashes"], allowedOutputs: ["append-only provenance links"], prohibited: ["result mutation", "automatic release"], requiredHashes: ["verificationHash", "resultHash"] },
];

const resultTrust: RuntimeResultTrustRequirement[] = [
  { requirement: "MESH_QUALITY", condition: "A solver-grade mesh artifact has passed declared quality metrics and topology checks.", missingBehavior: "INVALID_RESULT", requiredEvidence: ["meshHash", "qualityReport", "elementCount"] },
  { requirement: "SOLVER_STATUS", condition: "The allowlisted solver reports a completed success state through a bounded parser.", missingBehavior: "INVALID_RESULT", requiredEvidence: ["solverExitReceipt", "solverLogHash"] },
  { requirement: "CONVERGENCE", condition: "Declared convergence evidence is present for the analysis class, or the solver explicitly documents a direct-solution basis.", missingBehavior: "UNVERIFIED_RESULT", requiredEvidence: ["convergenceRecord", "solverMethod"] },
  { requirement: "UNITS", condition: "Input and result units are declared, internally consistent, and parser-validated.", missingBehavior: "REFUSE_DISPLAY", requiredEvidence: ["unitManifest", "parserCheck"] },
  { requirement: "BOUNDARY_CONDITIONS", condition: "All applied boundary references and values match the approved immutable job manifest.", missingBehavior: "INVALID_RESULT", requiredEvidence: ["boundaryHash", "geometryReferenceProof"] },
  { requirement: "LOADS", condition: "All applied load references, direction, magnitude, and units match the approved immutable job manifest.", missingBehavior: "INVALID_RESULT", requiredEvidence: ["loadHash", "unitManifest"] },
  { requirement: "MATERIAL", condition: "Material properties are evidence-backed, current, and linked to the exact input deck.", missingBehavior: "INVALID_RESULT", requiredEvidence: ["materialEvidenceIds", "materialHash"] },
  { requirement: "WARNINGS", condition: "Warnings are retained and evaluated; warnings cannot be silently discarded.", missingBehavior: "UNVERIFIED_RESULT", requiredEvidence: ["solverWarningLog"] },
  { requirement: "RESULT_HASH", condition: "Every displayed result artifact is hash bound to the collection record.", missingBehavior: "REFUSE_DISPLAY", requiredEvidence: ["resultHash"] },
  { requirement: "SOLVER_VERSION", condition: "Solver binary/image version is pinned and recorded.", missingBehavior: "REFUSE_DISPLAY", requiredEvidence: ["solverVersion", "solverBinaryHash"] },
  { requirement: "INPUT_HASH", condition: "Canonical job input and solver deck hashes match the execution receipt.", missingBehavior: "INVALID_RESULT", requiredEvidence: ["jobManifestHash", "solverInputHash"] },
  { requirement: "ENVIRONMENT_IDENTITY", condition: "The execution environment identity is attested, current, and linked to the receipt.", missingBehavior: "UNVERIFIED_RESULT", requiredEvidence: ["environmentIdentity", "attestationEvidence"] },
];

const essentialSecurityGates: EssentialRuntimeSecurityGate[] = [
  { gate: "SIGNED_ALLOWLISTED_ARTIFACT", whyRequired: "A solver/adapter must be identifiable and revocable before it can receive engineering inputs.", minimumEvidence: ["signature", "artifact hash", "SBOM", "license review"], currentState: "FAIL" },
  { gate: "ENFORCED_SANDBOX", whyRequired: "Default-deny declarations do not prevent host escape or privilege escalation.", minimumEvidence: ["runtime configuration", "independent attestation", "sandbox escape test"], currentState: "FAIL" },
  { gate: "MEASURED_ENFORCED_LIMITS", whyRequired: "Timeout and exhaustion resistance requires enforced, measured limits rather than policy text.", minimumEvidence: ["capacity evidence", "cgroup/limit configuration", "exhaustion test"], currentState: "FAIL" },
  { gate: "IMMUTABLE_JOB_MANIFEST", whyRequired: "Inputs cannot be trusted without a canonical hash-bound job snapshot.", minimumEvidence: ["schema", "input hash", "approval record"], currentState: "FAIL" },
  { gate: "MESH_AND_RESULT_VERIFIER", whyRequired: "Raw output is not evidence without mesh quality and result parsing/verification.", minimumEvidence: ["mesh report", "bounded parser", "corruption/partial-output tests"], currentState: "FAIL" },
  { gate: "INDEPENDENT_SECURITY_EVIDENCE", whyRequired: "Existing governance is meaningful only when independent evidence of an actual runtime is imported and reviewed.", minimumEvidence: ["independent review", "segregated hostile-test report", "lifecycle validity"], currentState: "FAIL" },
  { gate: "EXISTING_TRUST_GOVERNANCE", whyRequired: "Identity, revocation, audit, external-evidence, and governance controls are the required approval wrapper, not additional optional layers.", minimumEvidence: ["Phase 5.3–6.3 records"], currentState: "PASS" },
];

const failureModel: RuntimeFailureModeReview[] = [
  { failure: "SOLVER_CRASH", failClosedBehavior: "Terminate the job, preserve bounded logs and receipt, create no trusted result.", preservedArtifacts: ["jobManifest", "solverLog", "exitReceipt"], resultState: "NOT_CREATED" },
  { failure: "TIMEOUT", failClosedBehavior: "Enforced termination; preserve timeout evidence and invalidate all partial outputs.", preservedArtifacts: ["timeoutReceipt", "resourceUsage"], resultState: "INVALID" },
  { failure: "MEMORY_EXHAUSTION", failClosedBehavior: "Enforced cgroup/limit stop; do not retry automatically or treat output as valid.", preservedArtifacts: ["limitViolation", "resourceUsage"], resultState: "INVALID" },
  { failure: "INVALID_MESH", failClosedBehavior: "Refuse solver handoff and retain the quality report.", preservedArtifacts: ["meshArtifact", "qualityReport"], resultState: "NOT_CREATED" },
  { failure: "DIVERGENCE", failClosedBehavior: "Mark invalid and expose logs/warnings; no numerical visualization.", preservedArtifacts: ["solverLog", "convergenceRecord"], resultState: "INVALID" },
  { failure: "MALFORMED_INPUT", failClosedBehavior: "Reject at schema/hash validation before sandbox entry.", preservedArtifacts: ["validationFinding"], resultState: "NOT_CREATED" },
  { failure: "MALICIOUS_INPUT", failClosedBehavior: "Reject, audit, retain bounded evidence, and create a security incident record; never execute.", preservedArtifacts: ["rejectionEvidence", "auditEvent"], resultState: "NOT_CREATED" },
  { failure: "CORRUPT_RESULT", failClosedBehavior: "Hash/schema mismatch invalidates the result and preserves raw artifact references for review.", preservedArtifacts: ["resultHash", "parserFinding"], resultState: "INVALID" },
  { failure: "PARTIAL_OUTPUT", failClosedBehavior: "No partial artifact is promoted to a result; mark invalid.", preservedArtifacts: ["outputInventory", "exitReceipt"], resultState: "INVALID" },
  { failure: "VERSION_MISMATCH", failClosedBehavior: "Reject collection or reproduction when solver/adapter/image does not match the job manifest.", preservedArtifacts: ["versionManifest"], resultState: "UNVERIFIED" },
  { failure: "STALE_CAD", failClosedBehavior: "Refuse job construction when CAD revision differs from the approved plan revision.", preservedArtifacts: ["cadInvalidation"], resultState: "NOT_CREATED" },
  { failure: "STALE_MATERIAL_EVIDENCE", failClosedBehavior: "Refuse job construction when required material evidence is expired, revoked, conflicted, or superseded without review.", preservedArtifacts: ["materialLifecycle"], resultState: "NOT_CREATED" },
];

const implementationPlan: RuntimeImplementationPlanStep[] = [
  { order: 1, title: "Canonical CAE job contract", outcome: "Schema-validated, hash-bound snapshot of CAD, mesh request, material, loads, boundaries, solver selection, and approvals.", complexity: "L", gateBeforeNext: "Deterministic invalid-input and stale-context test corpus passes." },
  { order: 2, title: "Dedicated mesher adapter and verifier", outcome: "Versioned tetrahedral mesh artifact with required quality report and explicit refusal behavior.", complexity: "XL", gateBeforeNext: "Independent mesh-quality review of golden geometries passes." },
  { order: 3, title: "Minimal containerized solver adapter", outcome: "Pinned linear-static CalculiX candidate with bounded files, no network, no credentials, and no host mounts.", complexity: "XL", gateBeforeNext: "License/SBOM, signature, sandbox configuration, and non-production hostile-test evidence pass review." },
  { order: 4, title: "Result collector and verifier", outcome: "Bounded result parser verifies status, units, warnings, hashes, versions, and provenance before visualization.", complexity: "L", gateBeforeNext: "Corruption, partial-output, divergence, and version-mismatch tests fail closed." },
  { order: 5, title: "Independent security and engineering review", outcome: "Actual runtime evidence is ingested through the existing external verification and governance workflow.", complexity: "L", gateBeforeNext: "Only a subsequent decision may consider security-review readiness; never execution authorization." },
];

function build(projectId: string): RuntimeImplementationReadinessReview { return { reviewId: id("RUNTIME-IMPLEMENTATION"), projectId, contractVersion: "1.0.0", inventory, blockers, solverOptions, meshingOptions, minimumViableCAE, runtimeBoundary, resultTrust, essentialSecurityGates, failureModel, implementationPlan, estimatedComplexity: "XL", finalDecision: "RUNTIME_IMPLEMENTATION_BLOCKED", decisionReason: "The existing system has substantial planning, provenance, trust, verification, and governance foundations, but has no controlled CAE job compiler, solver-grade mesher, implemented/attested sandbox, allowlisted solver artifact, or result collector/verifier. These are genuine technical blockers; execution remains disabled.", sourceUrls, executionEligible: false, executable: false, createdAt: now() }; }

export async function createRuntimeImplementationReadinessReview(args: ProjectAccess) { await authorize(args); const review = build(args.projectId); await appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind: "CAE_RUNTIME_IMPLEMENTATION_REVIEW", title: `Phase 6.4 runtime implementation readiness · ${review.finalDecision}`, content: JSON.stringify(review), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM" } }); await appendTrustSecurityAudit(args, { actor: "SYSTEM", action: "RUNTIME_ARCHITECTURE_REVIEW", objectType: "RUNTIME_ARCHITECTURE", objectId: review.reviewId, newState: review.finalDecision, reason: review.decisionReason }); return review; }
export async function listRuntimeImplementationReadinessReviews(args: ProjectAccess) { return (await records(args)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
export async function buildRuntimeImplementationReadinessGraph(args: ProjectAccess & { reviewId?: string }): Promise<CAEEvidenceGraph> { const review = args.reviewId ? (await records(args)).find((item) => item.reviewId === args.reviewId) : (await listRuntimeImplementationReadinessReviews(args))[0]; if (!review) return { projectId: args.projectId, simulationId: "RUNTIME-IMPLEMENTATION-REVIEW", nodes: [], edges: [], limitations: ["No Phase 6.4 review exists. Execution remains disabled."] }; const decisionId = `DECISION-${review.reviewId}`; const nodes = [{ id: decisionId, type: "RUNTIME_DECISION" as const, label: review.finalDecision, truthStatus: "UNVALIDATED" as const }, ...review.inventory.map((item) => ({ id: `INVENTORY-${item.capability}`, type: "RUNTIME_ARCHITECTURE" as const, label: `${item.capability} · ${item.status}`, truthStatus: "UNVALIDATED" as const })), ...review.blockers.map((item) => ({ id: item.blockerId, type: "RUNTIME_THREAT" as const, label: `${item.classification} · ${item.title}`, truthStatus: "UNVALIDATED" as const })), ...review.runtimeBoundary.map((item) => ({ id: item.boundaryId, type: "RUNTIME_BOUNDARY" as const, label: `${item.from} → ${item.to}`, truthStatus: "UNVALIDATED" as const })), ...review.resultTrust.map((item) => ({ id: `TRUST-${item.requirement}`, type: "RUNTIME_RESULT_CONTRACT" as const, label: item.requirement, truthStatus: "UNVALIDATED" as const })), ...review.essentialSecurityGates.map((item) => ({ id: `SECURITY-${item.gate}`, type: "RUNTIME_APPROVAL_GATE" as const, label: `${item.gate} · ${item.currentState}`, truthStatus: "UNVALIDATED" as const })), ...review.implementationPlan.map((item) => ({ id: `STEP-${item.order}`, type: "RUNTIME_TEST_PLAN" as const, label: item.title, truthStatus: "UNVALIDATED" as const }))]; const edges = nodes.filter((node) => node.id !== decisionId).map((node) => ({ id: id("IMPLEMENTATION-GRAPH"), fromId: node.id, toId: decisionId, relationship: "runtime implementation readiness evidence", status: "UNKNOWN" as const })); return { projectId: args.projectId, simulationId: "RUNTIME-IMPLEMENTATION-REVIEW", nodes, edges, limitations: [review.decisionReason, "No solver, mesher, runtime process, shell, plugin, arbitrary network, arbitrary filesystem, or credential execution exists in Phase 6.4."] }; }
