import { and, desc, eq } from "drizzle-orm";
import { createHash, randomUUID } from "node:crypto";
import { seatKnowledgeEntities, seatRevisions } from "../drizzle/schema";
import { getDb } from "./db";
import { createSeatDesign, createSeatRevision, getSeatDesign } from "./seatEngineering";
import { createSeatKnowledgeEntity, invalidateSeatKnowledgeRevision, listSeatKnowledgeEntities, reviseSeatKnowledgeEntity } from "./seatKnowledgeRecords";
import { openPersistentProject } from "./persistentMemory";
import { generateBackrestConceptCad } from "./seatConceptCadEngine";
import { executeAuthorizedConceptBackrestEnvelope } from "./sourceLessCadExecution";

type Access = { projectId: string; accessKey: string };
const id = (prefix: string) => `${prefix}-${randomUUID()}`;
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
type Template = { id: string; name: string; source: string; intent: string; mechanism: string; parameters: Array<{ name: string; category: string; unit: string; cadRequired: boolean }> };
const templates: Template[] = [
  { id: "CONCEPT_OCCUPANT_MOTION_CONTROL", name: "Occupant–Seat Control", source: "1-EngineeringProblem.pdf", intent: "Controlled occupant-seat interaction", mechanism: "Temporal occupant-restraint phase mismatch", parameters: [{ name: "INTERACTION_ZONE_LOCATION", category: "INTERFACES", unit: "mm", cadRequired: false }, { name: "CONTROLLED_TRAVEL", category: "TRAVEL", unit: "mm", cadRequired: false }, { name: "RESTRAINT_INTERFACE_LOCATION", category: "INTERFACES", unit: "mm", cadRequired: false }, { name: "ENERGY_MANAGEMENT_TRAVEL", category: "TRAVEL", unit: "mm", cadRequired: false }] },
  { id: "CONCEPT_REAR_SEAT_RESTRAINT_INTERFACE", name: "Rear Restraint Interface", source: "OccupantRestraintintheRearSeatATD.pdf", intent: "Rear restraint interface architecture", mechanism: "Restraint-to-seat force transfer", parameters: [{ name: "RESTRAINT_ANCHOR_LOCATION", category: "MOUNTING", unit: "mm", cadRequired: false }, { name: "SEAT_INTERFACE_LOCATION", category: "INTERFACES", unit: "mm", cadRequired: false }, { name: "OCCUPANT_REFERENCE_LOCATION", category: "GEOMETRY", unit: "mm", cadRequired: false }, { name: "LOAD_TRANSFER_PATH", category: "FORCE_PATHS", unit: "USER_DEFINED", cadRequired: false }] },
  { id: "CONCEPT_CUSHION_STIFFNESS_DISTRIBUTION", name: "Cushion Stiffness Distribution", source: "VariationsinRearSeatCushionProperties.pdf", intent: "Cushion support zoning", mechanism: "Cushion property variation", parameters: [{ name: "CUSHION_WIDTH", category: "DIMENSIONS", unit: "mm", cadRequired: false }, { name: "CUSHION_DEPTH", category: "DIMENSIONS", unit: "mm", cadRequired: false }, { name: "CUSHION_THICKNESS", category: "THICKNESS", unit: "mm", cadRequired: false }, { name: "STIFFNESS_ZONE_LAYOUT", category: "COMPONENT_RELATIONSHIPS", unit: "USER_DEFINED", cadRequired: false }, { name: "MATERIAL_THICKNESS", category: "THICKNESS", unit: "mm", cadRequired: false }] },
  { id: "CONCEPT_BACKREST_LOAD_PATH", name: "Backrest Load Path", source: "CarSeatBackrestStaticStrengthExperimentandSimulation.pdf", intent: "Editable backrest frame/load path", mechanism: "Rearward loading through structural members", parameters: [{ name: "BACKREST_WIDTH", category: "DIMENSIONS", unit: "mm", cadRequired: true }, { name: "BACKREST_HEIGHT", category: "DIMENSIONS", unit: "mm", cadRequired: true }, { name: "PLATE_THICKNESS", category: "THICKNESS", unit: "mm", cadRequired: true }, { name: "TUBE_SECTION", category: "COMPONENT_RELATIONSHIPS", unit: "USER_DEFINED", cadRequired: false }, { name: "WELD_LAYOUT", category: "JOINTS", unit: "USER_DEFINED", cadRequired: false }, { name: "MOUNT_SPACING", category: "MOUNTING", unit: "mm", cadRequired: false }] },
  { id: "CONCEPT_ENERGY_MANAGEMENT", name: "Energy Management", source: "4-5-ConceptExpansionEngineeringInfeasibilityAcceptance.pdf", intent: "Controlled deformation and energy-management architecture", mechanism: "Feasibility-filtered energy absorption", parameters: [{ name: "DEFORMATION_TRAVEL", category: "TRAVEL", unit: "mm", cadRequired: false }, { name: "ABSORBER_LOCATION", category: "GEOMETRY", unit: "mm", cadRequired: false }, { name: "FORCE_TRANSFER_PATH", category: "FORCE_PATHS", unit: "USER_DEFINED", cadRequired: false }, { name: "CLEARANCE", category: "CLEARANCES", unit: "mm", cadRequired: false }, { name: "MATERIAL_THICKNESS", category: "THICKNESS", unit: "mm", cadRequired: false }] },
];
const templateFor = (id: string) => { const value = templates.find((template) => template.id === id); if (!value) throw new Error("DESIGN_TEMPLATE_NOT_FOUND"); return value; };
async function authorize(args: Access) { await openPersistentProject({ name: "", ...args }); }
async function db() { const value = await getDb(); if (!value) throw new Error("PERSISTENT_DATABASE_REQUIRED"); return value; }
const parameterKey = (revisionId: string, name: string) => `DESIGN_PARAM:${revisionId}:${name}`;

export function listEngineeringDesignTemplates() { return templates.map((template) => ({ ...template, modelType: "ENGINEERING_CONCEPT_MODEL", validationStatus: "NOT_VALIDATED", cadReadiness: template.id === "CONCEPT_BACKREST_LOAD_PATH" ? "PARTIAL_CAD_AFTER_REQUIRED_PARAMETERS" : "GEOMETRY_REQUIRED" })); }

export async function createConceptDesign(args: Access & { templateId: string; name: string; description: string }) {
  await authorize(args); const template = templateFor(args.templateId);
  const seat = await createSeatDesign({ ...args, input: { name: args.name, description: args.description, requirements: [{ requirementId: template.id, description: template.intent, constraint: { modelType: "ENGINEERING_CONCEPT_MODEL", validationStatus: "NOT_VALIDATED" }, verificationMethod: "USER_DESIGN_AUTHORING" }], materials: [], components: [{ name: template.name, componentType: "ENGINEERING_CONCEPT_ARCHITECTURE", quantity: 1 }] } });
  const revisionId = seat.revisions[0]?.id; if (!revisionId) throw new Error("DESIGN_REVISION_NOT_CREATED");
  const root = await createSeatKnowledgeEntity({ ...args, input: { seatDesignId: seat.id, seatRevisionId: revisionId, entityType: "GEOMETRY", externalKey: `DESIGN_TEMPLATE:${revisionId}`, name: `ENGINEERING_DESIGN_TEMPLATE: ${template.name}`, description: `CONCEPT_ID=${template.id}. DESIGN_INTENT=${template.intent}. ENGINEERING_MECHANISM=${template.mechanism}. MODEL_TYPE=ENGINEERING_CONCEPT_MODEL. VALIDATION_STATUS=NOT_VALIDATED. CAD_READINESS=${template.id === "CONCEPT_BACKREST_LOAD_PATH" ? "PARTIAL_CAD_AFTER_REQUIRED_PARAMETERS" : "GEOMETRY_REQUIRED"}.`, sourceType: "REFERENCE", sourceReference: template.source, evidenceReference: `concept://${template.id}`, createdBy: "DesignAuthoring", status: "DRAFT" } });
  for (const parameter of template.parameters) await createSeatKnowledgeEntity({ ...args, input: { seatDesignId: seat.id, seatRevisionId: revisionId, parentEntityId: root.id, entityType: "CONSTRAINT", externalKey: parameterKey(revisionId, parameter.name), name: `USER_DEFINED_PARAMETER: ${parameter.name}`, description: `CATEGORY=${parameter.category}. PARAMETER_STATE=REQUIRED_INPUT. VALUE=UNDEFINED. CAD_REQUIRED=${parameter.cadRequired}. DESIGN_STATUS=USER_INPUT_REQUIRED. VALIDATION_STATUS=NOT_VALIDATED.`, unit: parameter.unit, sourceType: "USER_PROVIDED", sourceReference: "USER_DESIGN_INPUT", evidenceReference: "NOT_APPLICABLE", createdBy: "DesignAuthoring", status: "REQUIRED_INPUT" } });
  return { seat, template, revisionId, templateEntityId: root.id };
}

export async function setConceptDesignParameter(args: Access & { seatDesignId: string; revisionId: string; parameterName: string; value: string; unit: string }) {
  await authorize(args); const templateRecord = (await listSeatKnowledgeEntities({ ...args, seatDesignId: args.seatDesignId, seatRevisionId: args.revisionId, limit: 100 })).find((record) => record.externalKey === `DESIGN_TEMPLATE:${args.revisionId}`); if (!templateRecord) throw new Error("DESIGN_TEMPLATE_RECORD_NOT_FOUND");
  const existingCad = (await listSeatKnowledgeEntities({ ...args, seatDesignId: args.seatDesignId, seatRevisionId: args.revisionId, limit: 100 })).some((record) => record.externalKey.startsWith(`CONCEPT_CAD:${args.revisionId}:`) && record.status !== "STALE");
  if (existingCad) throw new Error("CONCEPT_PARAMETER_CHANGE_REQUIRES_SUCCESSOR_REVISION");
  const parameter = (await listSeatKnowledgeEntities({ ...args, seatDesignId: args.seatDesignId, seatRevisionId: args.revisionId, limit: 100 })).find((record) => record.externalKey === parameterKey(args.revisionId, args.parameterName)); if (!parameter) throw new Error("DESIGN_PARAMETER_NOT_FOUND");
  const value = args.value.trim(); if (!value || value.length > 120) throw new Error("DESIGN_PARAMETER_VALUE_REQUIRED");
  return reviseSeatKnowledgeEntity({ ...args, entityId: parameter.id, input: { seatDesignId: args.seatDesignId, seatRevisionId: args.revisionId, parentEntityId: templateRecord.id, entityType: "CONSTRAINT", name: parameter.name, description: parameter.description.replace("PARAMETER_STATE=REQUIRED_INPUT", "PARAMETER_STATE=USER_DEFINED").replace("VALUE=UNDEFINED", `VALUE=${value}`), valueText: value, unit: args.unit.trim() || parameter.unit || "USER_DEFINED", sourceType: "USER_PROVIDED", sourceReference: "USER_DESIGN_INPUT", evidenceReference: "NOT_APPLICABLE", createdBy: "UserDesignAuthor", status: "DRAFT", approvalStatus: "UNREVIEWED", reason: "User-defined design parameter update" } });
}

export async function getConceptDesign(args: Access & { seatDesignId: string; revisionId: string }) {
  await authorize(args); const records = await listSeatKnowledgeEntities({ ...args, seatDesignId: args.seatDesignId, seatRevisionId: args.revisionId, limit: 100 }); const templateRecord = records.find((record) => record.externalKey === `DESIGN_TEMPLATE:${args.revisionId}`); if (!templateRecord) throw new Error("DESIGN_TEMPLATE_RECORD_NOT_FOUND");
  const conceptId = /CONCEPT_ID=([^\.]+)/.exec(templateRecord.description)?.[1]?.trim() ?? "UNKNOWN"; const template = templateFor(conceptId);
  const parameters = template.parameters.map((definition) => { const versions = records.filter((record) => record.externalKey === parameterKey(args.revisionId, definition.name)).sort((a, b) => b.revision - a.revision); const record = versions.find((item) => item.status !== "SUPERSEDED") ?? versions[0]; return { ...definition, value: record?.valueText ?? null, unit: record?.unit ?? definition.unit, state: record?.valueText ? "USER_DEFINED" : "REQUIRED_INPUT", entityId: record?.id }; });
  const artifacts = records.filter((record) => record.externalKey.startsWith(`CONCEPT_CAD:${args.revisionId}:`)).map((record) => ({ ...record, cadFileId: /CAD_FILE_ID=([^\.\s]+)/.exec(record.description)?.[1] ?? null }));
  return { template, templateEntityId: templateRecord.id, parameters, artifacts, cadReadiness: template.parameters.filter((parameter) => parameter.cadRequired).every((parameter) => parameters.find((item) => item.name === parameter.name)?.value) ? "CAD_READY" : "REQUIRED_INPUT", feStatus: "FE_BLOCKED" };
}

export async function generateConceptCad(args: Access & { seatDesignId: string; revisionId: string }) {
  const design = await getConceptDesign(args); if (design.template.id !== "CONCEPT_BACKREST_LOAD_PATH") throw new Error("CONCEPT_GEOMETRY_NOT_IMPLEMENTED");
  const values = Object.fromEntries(design.parameters.map((parameter) => [parameter.name, parameter.value])); const required = ["BACKREST_WIDTH", "BACKREST_HEIGHT", "PLATE_THICKNESS"];
  if (required.some((name) => !values[name] || !Number.isFinite(Number(values[name])) || Number(values[name]) <= 0)) throw new Error("CONCEPT_CAD_REQUIRED_PARAMETERS_MISSING");
  const artifact = await generateBackrestConceptCad({ seatRevisionId: args.revisionId, widthMm: Number(values.BACKREST_WIDTH), heightMm: Number(values.BACKREST_HEIGHT), thicknessMm: Number(values.PLATE_THICKNESS) });
  const execution = await executeAuthorizedConceptBackrestEnvelope({ projectId: args.projectId, accessKey: args.accessKey, seatRevisionId: args.revisionId, widthMm: Number(values.BACKREST_WIDTH), heightMm: Number(values.BACKREST_HEIGHT), thicknessMm: Number(values.PLATE_THICKNESS), stepBytes: Buffer.from(artifact.stepBase64, "base64"), generatorHash: artifact.artifactHash });
  const cadFile = execution.completion.artifact;
  const record = await createSeatKnowledgeEntity({ ...args, input: { seatDesignId: args.seatDesignId, seatRevisionId: args.revisionId, entityType: "GEOMETRY", externalKey: `CONCEPT_CAD:${args.revisionId}:${artifact.artifactHash}`, name: "CAD_ARTIFACT: Backrest envelope", description: `MODEL_TYPE=ENGINEERING_CONCEPT_MODEL. DESIGN_STATUS=USER_DEFINED. VALIDATION_STATUS=NOT_VALIDATED. GEOMETRY_STATUS=PARTIAL_CAD. UNDEFINED_FEATURES=${artifact.undefinedFeatures.join(",")}. CAD_FILE_ID=${cadFile.fileId}. CAD_ARTIFACT_SHA256=${cadFile.sha256}. SOURCELESS_PROVENANCE_ID=${execution.provenanceRecordId}. SOURCELESS_LINEAGE_ID=${execution.revisionId}. CAD_REVISION_HASH=${artifact.cadRevisionHash}.`, valueText: cadFile.fileName, unit: "STEP", sourceType: "TOOL_GENERATED", sourceReference: `CONCEPT_BACKREST_LOAD_PATH; user parameters ${required.join(",")}`, evidenceReference: `CAD_FILE:${cadFile.fileId}`, artifactHash: cadFile.sha256, createdBy: "OpenCascadeConceptCad", status: "DRAFT" } });
  return { record, artifact: { artifactHash: cadFile.sha256, cadRevisionHash: artifact.cadRevisionHash, stepByteLength: artifact.stepByteLength, geometryStatus: artifact.geometryStatus, undefinedFeatures: artifact.undefinedFeatures, cadFileId: cadFile.fileId, provenanceRecordId: execution.provenanceRecordId, lineageRevisionId: execution.revisionId }, feStatus: "FE_BLOCKED" };
}

export async function createConceptDesignSuccessor(args: Access & { seatDesignId: string; revisionId: string }) {
  const current = await getSeatDesign({ ...args, seatDesignId: args.seatDesignId }); const revision = current.revisions.find((item) => item.id === args.revisionId); if (!revision) throw new Error("SEAT_REVISION_NOT_FOUND");
  const priorRecords = await listSeatKnowledgeEntities({ ...args, seatDesignId: args.seatDesignId, seatRevisionId: args.revisionId, limit: 100 });
  const priorTemplate = priorRecords.find((record) => record.externalKey === `DESIGN_TEMPLATE:${args.revisionId}`); if (!priorTemplate) throw new Error("DESIGN_TEMPLATE_RECORD_NOT_FOUND");
  const successor = await createSeatRevision({ ...args, seatDesignId: args.seatDesignId, input: { description: `${revision.description} · user geometry revision`, requirements: current.requirements.map((item) => ({ requirementId: item.requirementId, description: item.description, constraint: item.constraint, verificationMethod: item.verificationMethod })), materials: current.materials.map((item) => ({ name: item.name, specification: item.specification, properties: item.properties, validationStatus: item.validationStatus })), components: current.components.map((item) => ({ name: item.name, componentType: item.componentType, quantity: item.quantity })) } });
  const nextRevisionId = successor.revisions[0]?.id; if (!nextRevisionId) throw new Error("SUCCESSOR_REVISION_NOT_CREATED");
  const nextTemplate = await createSeatKnowledgeEntity({ ...args, input: { seatDesignId: args.seatDesignId, seatRevisionId: nextRevisionId, entityType: "GEOMETRY", externalKey: `DESIGN_TEMPLATE:${nextRevisionId}`, name: priorTemplate.name, description: priorTemplate.description, sourceType: priorTemplate.sourceType, sourceReference: priorTemplate.sourceReference, evidenceReference: priorTemplate.evidenceReference ?? undefined, createdBy: "UserDesignAuthor", status: "DRAFT" } });
  for (const parameter of priorRecords.filter((record) => record.externalKey.startsWith(`DESIGN_PARAM:${args.revisionId}:`) && record.status !== "SUPERSEDED")) {
    const name = parameter.externalKey.split(":").at(-1) ?? parameter.name;
    await createSeatKnowledgeEntity({ ...args, input: { seatDesignId: args.seatDesignId, seatRevisionId: nextRevisionId, parentEntityId: nextTemplate.id, entityType: "CONSTRAINT", externalKey: parameterKey(nextRevisionId, name), name: parameter.name, description: parameter.description, valueText: parameter.valueText ?? undefined, unit: parameter.unit ?? undefined, sourceType: "USER_PROVIDED", sourceReference: "USER_DESIGN_INPUT", evidenceReference: "NOT_APPLICABLE", createdBy: "UserDesignAuthor", status: parameter.valueText ? "DRAFT" : "REQUIRED_INPUT" } });
  }
  await invalidateSeatKnowledgeRevision({ ...args, supersededRevisionId: args.revisionId, replacementRevisionId: nextRevisionId, actor: "UserDesignAuthor", reason: "Geometry-affecting parameter change requires successor CAD revision" });
  return { successor, revisionId: nextRevisionId };
}
