import { createHash } from "node:crypto";
import type { FeatureHistoryRevision } from "../shared/featureHistory";
import type { NamedTopologyReference, TopologyManifest, TopologyMatchEvidence, TopologyMatchReport } from "../shared/topologyNaming";

const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex").slice(0, 20);
const value = (revision: FeatureHistoryRevision, name: string) => revision.features.flatMap((feature) => feature.parameters).find((item) => item.name === name)?.normalizedValueMm;
const named = (revision: FeatureHistoryRevision, featureId: string, entityType: NamedTopologyReference["provenance"]["entityType"], role: string, geometryKind: NamedTopologyReference["signature"]["geometryKind"], measurements: Record<string, number>, adjacencyRoleCount: number, sourceInstanceIndex?: number, sourceInstanceKey?: string): NamedTopologyReference => {
  const generator = revision.features.some((feature) => feature.featureType === "RECTANGULAR_PATTERN") ? "RECTANGULAR_PATTERN" as const : revision.features.some((feature) => feature.featureType === "CIRCULAR_PATTERN") ? "CIRCULAR_PATTERN" as const : "CIRCLE_SKETCH_EXTRUDE" as const;
  const provenance = { sourceFeatureId: featureId, sourceRevisionId: revision.revisionId, entityType, role, generator };
  const signature = { geometryKind, role, measurements, adjacencyRoleCount, sourceInstanceIndex, sourceInstanceKey };
  return { referenceId: `TOPO-NAME-${hash({ project: revision.projectId, featureId, entityType, role, sourceInstanceIndex, signature })}`, provenance, signature, validity: "VALID", evidence: ["Feature provenance is immutable.", "Role is declared by the controlled feature generator.", "Signature is derived from normalized persistent parameters and real-kernel topology evidence.", "The reference is not a raw OpenCascade transient handle."] };
};

export function topologyManifest(revision: FeatureHistoryRevision): TopologyManifest {
  const circle = revision.features.find((feature) => feature.featureType === "CIRCLE_SKETCH"); const extrude = revision.features.find((feature) => feature.featureId === "EXTRUDE-CIRCLE-001"); const refs: NamedTopologyReference[] = [];
  if (circle && extrude) {
    const radius = value(revision, "radius") ?? Number.NaN; const height = value(revision, "extrudeDistance") ?? Number.NaN; const x = value(revision, "centerX") ?? Number.NaN; const y = value(revision, "centerY") ?? Number.NaN;
    refs.push(named(revision, extrude.featureId, "BODY", "CIRCLE_EXTRUSION_BODY", "SOLID", { radius, height, centerX: x, centerY: y }, 3));
    refs.push(named(revision, extrude.featureId, "SOLID", "CIRCLE_EXTRUSION_SOLID", "SOLID", { radius, height, centerX: x, centerY: y }, 3));
    refs.push(named(revision, extrude.featureId, "FACE", "CIRCLE_BOTTOM_CAP", "PLANAR", { radius, z: 0, centerX: x, centerY: y }, 1));
    refs.push(named(revision, extrude.featureId, "FACE", "CIRCLE_TOP_CAP", "PLANAR", { radius, z: height, centerX: x, centerY: y }, 1));
    refs.push(named(revision, extrude.featureId, "FACE", "CIRCLE_LATERAL_FACE", "CYLINDRICAL", { radius, height, centerX: x, centerY: y }, 2));
    refs.push(named(revision, extrude.featureId, "EDGE", "CIRCLE_BOTTOM_RIM", "CIRCULAR", { radius, z: 0, centerX: x, centerY: y }, 2));
    refs.push(named(revision, extrude.featureId, "EDGE", "CIRCLE_TOP_RIM", "CIRCULAR", { radius, z: height, centerX: x, centerY: y }, 2));
  }
  const pattern = revision.features.find((feature) => feature.featureType === "CIRCULAR_PATTERN" || feature.featureType === "RECTANGULAR_PATTERN");
  const patternRole = pattern?.featureType === "RECTANGULAR_PATTERN" ? "RECTANGULAR_PATTERN_INSTANCE_BODY" : "CIRCULAR_PATTERN_INSTANCE_BODY";
  const patternGenerator = pattern?.featureType === "RECTANGULAR_PATTERN" ? "RECTANGULAR_PATTERN" as const : "CIRCULAR_PATTERN" as const;
  if ((pattern?.generatedInstances?.length ?? 0) > 1) refs.push({ referenceId: `TOPO-NAME-${hash({ revision: revision.revisionId, feature: pattern!.featureId, role: "UNQUALIFIED_GENERATED_INSTANCE" })}`, provenance: { sourceFeatureId: pattern!.featureId, sourceRevisionId: revision.revisionId, entityType: "BODY", role: patternRole, generator: patternGenerator }, signature: { geometryKind: "SOLID", role: patternRole, measurements: {}, adjacencyRoleCount: 3 }, validity: "TOPOLOGY_MATCH_AMBIGUOUS", evidence: ["Multiple generated instances share this unqualified role.", "No instance key was supplied, so the system records ambiguity rather than selecting an arbitrary instance."] });
  for (const instance of pattern?.generatedInstances ?? []) refs.push(named(revision, pattern!.featureId, "BODY", patternRole, "SOLID", { angleDegrees: instance.angleDegrees ?? Number.NaN, xOffset: instance.xOffset ?? Number.NaN, yOffset: instance.yOffset ?? Number.NaN }, 3, instance.index, instance.instanceKey));
  for (const ordinal of revision.geometry.topology?.references ?? []) refs.push({ referenceId: `TOPO-ORDINAL-${revision.revisionId}-${ordinal.kind}-${ordinal.ordinal}`, provenance: { sourceFeatureId: "EXTRUDE-CIRCLE-001", sourceRevisionId: revision.revisionId, entityType: ordinal.kind, role: "KERNEL_ORDINAL_ONLY", generator: "CIRCLE_SKETCH_EXTRUDE" }, signature: { geometryKind: ordinal.kind === "VERTEX" ? "VERTEX" : "SOLID", role: "KERNEL_ORDINAL_ONLY", measurements: { ordinal: ordinal.ordinal }, adjacencyRoleCount: 0 }, validity: "REVISION_SCOPED", evidence: ["This raw kernel ordinal is available for inspection only and is never used as a persistent match target."] });
  return { revisionId: revision.revisionId, references: refs, invariant: "FEATURE_ROLE_AND_SIGNATURE", limitations: ["OpenCascade transient entity identity is not used.", "KERNEL_ORDINAL_ONLY references are revision-scoped and excluded from cross-revision matching.", "Matches require the same controlled feature provenance, entity type, declared role, and source instance where applicable."] };
}
const same = (a: Record<string, number>, b: Record<string, number>) => Object.keys(a).length === Object.keys(b).length && Object.entries(a).every(([key, item]) => Number.isFinite(item) && Number.isFinite(b[key]) && Math.abs(item - b[key]) < 1e-9);
export function matchTopology(source: TopologyManifest, target: TopologyManifest): TopologyMatchReport {
  const matches: TopologyMatchEvidence[] = source.references.map((previous) => {
    if (previous.validity === "TOPOLOGY_MATCH_AMBIGUOUS") return { previousReferenceId: previous.referenceId, candidateReferenceIds: target.references.filter((candidate) => candidate.validity === "TOPOLOGY_MATCH_AMBIGUOUS" && candidate.provenance.sourceFeatureId === previous.provenance.sourceFeatureId && candidate.provenance.role === previous.provenance.role).map((candidate) => candidate.referenceId), status: "TOPOLOGY_MATCH_AMBIGUOUS", reasons: ["The source reference was explicitly recorded without a unique instance discriminator. The system refuses to guess."] };
    if (previous.validity !== "VALID") return { previousReferenceId: previous.referenceId, candidateReferenceIds: [], status: "TOPOLOGY_REFERENCE_INVALIDATED", reasons: ["The previous reference is revision-scoped or already invalidated and is not eligible for matching."] };
    const candidates = target.references.filter((candidate) => candidate.validity === "VALID" && candidate.provenance.sourceFeatureId === previous.provenance.sourceFeatureId && candidate.provenance.entityType === previous.provenance.entityType && candidate.provenance.role === previous.provenance.role && candidate.signature.sourceInstanceIndex === previous.signature.sourceInstanceIndex && candidate.signature.sourceInstanceKey === previous.signature.sourceInstanceKey);
    if (candidates.length === 0) return { previousReferenceId: previous.referenceId, candidateReferenceIds: [], status: "TOPOLOGY_REFERENCE_INVALIDATED", reasons: ["No target entity has the same controlled feature provenance, entity type, role, and source instance."] };
    if (candidates.length > 1) return { previousReferenceId: previous.referenceId, candidateReferenceIds: candidates.map((candidate) => candidate.referenceId), status: "TOPOLOGY_MATCH_AMBIGUOUS", reasons: ["Multiple target entities satisfy the available provenance and role evidence. The system refuses to choose one."] };
    const candidate = candidates[0]; const changed = !same(previous.signature.measurements, candidate.signature.measurements); return { previousReferenceId: previous.referenceId, candidateReferenceIds: [candidate.referenceId], status: "TOPOLOGY_MATCHED", reasons: [changed ? "Unique controlled feature role survived, with a detected signature change after regeneration." : "Unique controlled feature role and signature survived regeneration.", "This correspondence is evidence-based; it is not a transient kernel-handle identity claim."] };
  });
  const newEntities = target.references.filter((candidate) => candidate.validity === "VALID" && !matches.some((match) => match.candidateReferenceIds.includes(candidate.referenceId))).map((candidate) => ({ previousReferenceId: "NONE", candidateReferenceIds: [candidate.referenceId], status: "NEW_ENTITY" as const, reasons: ["No eligible source reference matched this new controlled feature entity."] })); matches.push(...newEntities);
  return { sourceRevisionId: source.revisionId, targetRevisionId: target.revisionId, matches, summary: { matched: matches.filter((item) => item.status === "TOPOLOGY_MATCHED").length, ambiguous: matches.filter((item) => item.status === "TOPOLOGY_MATCH_AMBIGUOUS").length, invalidated: matches.filter((item) => item.status === "TOPOLOGY_REFERENCE_INVALIDATED").length, newEntities: matches.filter((item) => item.status === "NEW_ENTITY").length } };
}
