import type { EvidenceRetentionPolicy, GovernedEvidenceType, ReviewerRevocationPolicy, ReviewerSeparationPolicy, TestEnvironmentEvidenceImport, VerificationConflict, VerificationGovernanceLifecycleEvent, VerificationGovernanceReadiness, VerificationReview } from "../shared/cae";
import { appendTrustSecurityAudit, listReviewerIdentities, revokeTrustObject } from "./caeTrust";
import { evaluateExternalVerificationReadiness, listHostileTestEnvironments, listHostileTestEvidence, listInfrastructureEvidence, listSandboxReviews, verifyExternalEvidence } from "./externalVerification";
import { appendPersistentMemory, openPersistentProject, projectMemorySnapshot } from "./persistentMemory";

type Access = { projectId: string; accessKey: string };
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
let lastTimestamp = 0;
const now = () => { const next = Math.max(Date.now(), lastTimestamp + 1); lastTimestamp = next; return new Date(next).toISOString(); };
const parse = <T,>(value: string): T | undefined => { try { return JSON.parse(value) as T; } catch { return undefined; } };
async function authorize(args: Access) { return openPersistentProject({ projectId: args.projectId, accessKey: args.accessKey, name: "" }); }
async function records<T>(args: Access, kind: "CAE_REVIEWER_SEPARATION_POLICY" | "CAE_EVIDENCE_RETENTION_POLICY" | "CAE_REVIEWER_REVOCATION_POLICY" | "CAE_VERIFICATION_REVIEW" | "CAE_TEST_ENVIRONMENT_EVIDENCE_IMPORT" | "CAE_VERIFICATION_GOVERNANCE_LIFECYCLE" | "CAE_VERIFICATION_CONFLICT" | "CAE_VERIFICATION_GOVERNANCE_READINESS") { await authorize(args); return (await projectMemorySnapshot(args)).records.filter((record) => record.kind === kind).flatMap((record) => { const item = parse<T>(record.content); return item ? [item] : []; }); }
const latest = <T extends { createdAt: string }>(items: T[]) => [...items].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
async function append(args: Access, kind: Parameters<typeof appendPersistentMemory>[0]["record"]["kind"], title: string, content: unknown) { return appendPersistentMemory({ projectId: args.projectId, accessKey: args.accessKey, record: { kind, title, content: JSON.stringify(content), truthStatus: "DERIVED", validationStage: "CONCEPTUAL", authorSource: "SYSTEM" } }); }

export async function ensureGovernancePolicies(args: Access) {
  await authorize(args);
  const separation = latest(await records<ReviewerSeparationPolicy>(args, "CAE_REVIEWER_SEPARATION_POLICY"))[0];
  const revocation = latest(await records<ReviewerRevocationPolicy>(args, "CAE_REVIEWER_REVOCATION_POLICY"))[0];
  const retention = await records<EvidenceRetentionPolicy>(args, "CAE_EVIDENCE_RETENTION_POLICY");
  const separationPolicy = separation ?? { policyId: id("SEPARATION-POLICY"), projectId: args.projectId, version: "1.0.0" as const, allowSelfReview: false as const, policyStatement: "Submitter identity must differ from reviewer identity. No anonymous verification and no self-review are permitted.", createdAt: now() };
  const revocationPolicy = revocation ?? { policyId: id("REVOCATION-POLICY"), projectId: args.projectId, version: "1.0.0" as const, reviewerStatusStates: ["ACTIVE", "SUSPENDED", "REVOKED"] as Array<"ACTIVE" | "SUSPENDED" | "REVOKED">, previouslyApprovedEvidence: "REQUIRES_REVIEW" as const, policyStatement: "When a reviewer is revoked, prior approvals require independent re-review before satisfying current readiness gates.", createdAt: now() };
  if (!separation) await append(args, "CAE_REVIEWER_SEPARATION_POLICY", "Phase 6.3 reviewer separation policy", separationPolicy);
  if (!revocation) await append(args, "CAE_REVIEWER_REVOCATION_POLICY", "Phase 6.3 reviewer revocation policy", revocationPolicy);
  const classes: EvidenceRetentionPolicy["evidenceClass"][] = ["EXTERNAL_INFRASTRUCTURE", "SANDBOX_REVIEW", "HOSTILE_TEST", "VERIFICATION_REVIEW", "AUDIT"];
  const policies: EvidenceRetentionPolicy[] = [];
  for (const evidenceClass of classes) { const existing = latest(retention.filter((item) => item.evidenceClass === evidenceClass))[0]; const policy = existing ?? { retentionPolicyId: id("RETENTION-POLICY"), projectId: args.projectId, version: "1.0.0" as const, evidenceClass, retentionPeriod: "REQUIRES_GOVERNANCE_APPROVAL", archiveStatus: "ACTIVE" as const, deletionPolicy: "NO_SILENT_DELETION" as const, legalHold: false, expirationBehavior: "HISTORICAL_NOT_GATE_VALID" as const, createdAt: now() }; if (!existing) await append(args, "CAE_EVIDENCE_RETENTION_POLICY", `Phase 6.3 retention policy · ${evidenceClass}`, policy); policies.push(policy); }
  await appendTrustSecurityAudit(args, { actor: "SYSTEM", action: "GOVERNANCE_POLICY", objectType: "RETENTION_POLICY", objectId: separationPolicy.policyId, newState: "ACTIVE", reason: "Phase 6.3 governance policies were created or retrieved. They do not enable runtime execution." });
  return { separationPolicy, revocationPolicy, retentionPolicies: policies };
}

async function verifiedReviewer(args: Access, reviewerId: string) { const reviewer = (await listReviewerIdentities(args)).find((item) => item.reviewerId === reviewerId); if (!reviewer || reviewer.identityStatus !== "VERIFIED" || reviewer.status !== "VERIFIED" || !reviewer.permissions.includes("APPROVE_VALIDATION")) throw new Error("A named, active verified reviewer with validation-approval permission is required."); return reviewer; }
async function reviewSnapshots(args: Access) { const history = await records<VerificationReview>(args, "CAE_VERIFICATION_REVIEW"); const snapshots = new Map<string, VerificationReview>(); for (const item of latest(history)) if (!snapshots.has(item.reviewId)) snapshots.set(item.reviewId, item); return [...snapshots.values()]; }
async function lifecycle(args: Access, review: VerificationReview, previousState: VerificationReview["status"] | undefined, who: string, why: string) { const event: VerificationGovernanceLifecycleEvent = { eventId: id("GOVERNANCE-LIFECYCLE"), projectId: args.projectId, reviewId: review.reviewId, previousState, newState: review.status, who, why, evidenceReference: review.evidenceReference, reviewerIdentity: review.reviewerIdentity, policyVersion: "1.0.0", timestamp: now() }; await append(args, "CAE_VERIFICATION_GOVERNANCE_LIFECYCLE", `Verification lifecycle · ${event.newState}`, event); await appendTrustSecurityAudit(args, { actor: who, action: "VERIFICATION_REVIEW", objectType: "VERIFICATION_REVIEW", objectId: review.reviewId, previousState, newState: review.status, reason: why }); return event; }

export async function submitVerificationReview(args: Access & { evidenceType: GovernedEvidenceType; evidenceReference: string; submitterIdentity: string; reviewScope: string; reason: string }) { const policies = await ensureGovernancePolicies(args); if (!args.submitterIdentity.trim()) throw new Error("Anonymous evidence submission is not permitted."); const review: VerificationReview = { reviewId: id("VERIFICATION-REVIEW"), projectId: args.projectId, evidenceType: args.evidenceType, evidenceReference: args.evidenceReference, submitterIdentity: args.submitterIdentity, reviewScope: args.reviewScope, decision: "PENDING", reason: args.reason, status: "SUBMITTED", separationPolicyId: policies.separationPolicy.policyId, timestamp: now(), revision: 1, createdAt: now() }; await append(args, "CAE_VERIFICATION_REVIEW", "Verification review · SUBMITTED", review); await lifecycle(args, review, undefined, args.submitterIdentity, args.reason); return { review, readiness: await evaluateVerificationGovernanceReadiness(args) }; }
export async function assignVerificationReview(args: Access & { reviewId: string; reviewerId: string; reason: string }) { const policies = await ensureGovernancePolicies(args); const prior = (await reviewSnapshots(args)).find((item) => item.reviewId === args.reviewId); if (!prior) throw new Error("Verification review not found."); const reviewer = await verifiedReviewer(args, args.reviewerId); if (!policies.separationPolicy.allowSelfReview && (prior.submitterIdentity === reviewer.reviewerId || prior.submitterIdentity === reviewer.displayName)) throw new Error("Reviewer separation policy prohibits self-review of submitted evidence."); if (prior.status !== "SUBMITTED") throw new Error("Only submitted reviews may be assigned."); const review: VerificationReview = { ...prior, reviewerIdentity: reviewer.reviewerId, status: "UNDER_REVIEW", decision: "PENDING", reason: args.reason, revision: prior.revision + 1, timestamp: now(), createdAt: now() }; await append(args, "CAE_VERIFICATION_REVIEW", "Verification review · UNDER_REVIEW", review); await lifecycle(args, review, prior.status, reviewer.displayName, args.reason); return { review, readiness: await evaluateVerificationGovernanceReadiness(args) }; }
async function detectConflict(args: Access, review: VerificationReview) { const relevant = (await reviewSnapshots(args)).filter((item) => item.evidenceType === review.evidenceType && item.evidenceReference === review.evidenceReference && ["ACCEPTED", "REJECTED"].includes(item.status)); const disagree = relevant.some((item) => item.status === "ACCEPTED") && relevant.some((item) => item.status === "REJECTED"); if (!disagree) return undefined; const existing = latest((await records<VerificationConflict>(args, "CAE_VERIFICATION_CONFLICT")).filter((item) => item.evidenceType === review.evidenceType && item.evidenceReference === review.evidenceReference && item.status === "VERIFICATION_CONFLICT"))[0]; if (existing) return existing; const conflict: VerificationConflict = { conflictId: id("VERIFICATION-CONFLICT"), projectId: args.projectId, evidenceType: review.evidenceType, evidenceReference: review.evidenceReference, reviewIds: relevant.map((item) => item.reviewId), status: "VERIFICATION_CONFLICT", reason: "Independent verification reviews disagree. Runtime readiness must fail closed until an authorized resolution is recorded.", createdAt: now() }; await append(args, "CAE_VERIFICATION_CONFLICT", "Verification conflict · active", conflict); await appendTrustSecurityAudit(args, { actor: "SYSTEM", action: "VERIFICATION_CONFLICT", objectType: "VERIFICATION_CONFLICT", objectId: conflict.conflictId, newState: conflict.status, reason: conflict.reason }); return conflict; }
export async function decideVerificationReview(args: Access & { reviewId: string; reviewerId: string; decision: "ACCEPT" | "REJECT"; reason: string }) { const policies = await ensureGovernancePolicies(args); const prior = (await reviewSnapshots(args)).find((item) => item.reviewId === args.reviewId); if (!prior) throw new Error("Verification review not found."); const reviewer = await verifiedReviewer(args, args.reviewerId); if (!policies.separationPolicy.allowSelfReview && (prior.submitterIdentity === reviewer.reviewerId || prior.submitterIdentity === reviewer.displayName)) throw new Error("Reviewer separation policy prohibits self-approval or self-rejection."); if (prior.status !== "UNDER_REVIEW" || prior.reviewerIdentity !== reviewer.reviewerId) throw new Error("Only the assigned active reviewer may decide an under-review verification."); if (args.decision === "ACCEPT") await verifyExternalEvidence({ ...args, evidenceType: prior.evidenceType, evidenceId: prior.evidenceReference, reviewerId: reviewer.reviewerId, sourceVerified: true, verificationMethod: "Phase 6.3 independent governed review", reason: args.reason }); const review: VerificationReview = { ...prior, decision: args.decision, status: args.decision === "ACCEPT" ? "ACCEPTED" : "REJECTED", reason: args.reason, revision: prior.revision + 1, timestamp: now(), createdAt: now() }; await append(args, "CAE_VERIFICATION_REVIEW", `Verification review · ${review.status}`, review); await lifecycle(args, review, prior.status, reviewer.displayName, args.reason); const conflict = await detectConflict(args, review); return { review, conflict, readiness: await evaluateVerificationGovernanceReadiness(args) }; }
export async function transitionVerificationReview(args: Access & { reviewId: string; reviewerId: string; transition: "EXPIRE" | "REVOKE"; reason: string }) { const prior = (await reviewSnapshots(args)).find((item) => item.reviewId === args.reviewId); if (!prior) throw new Error("Verification review not found."); const reviewer = await verifiedReviewer(args, args.reviewerId); if (!prior.reviewerIdentity || prior.reviewerIdentity !== reviewer.reviewerId || !["ACCEPTED", "REJECTED"].includes(prior.status)) throw new Error("Only the assigned active reviewer may expire or revoke a completed review."); const status = args.transition === "EXPIRE" ? "EXPIRED" as const : "REVOKED" as const; const review: VerificationReview = { ...prior, decision: args.transition === "EXPIRE" ? "EXPIRE" : "REVOKE", status, reason: args.reason, revision: prior.revision + 1, timestamp: now(), createdAt: now() }; await append(args, "CAE_VERIFICATION_REVIEW", `Verification review · ${status}`, review); await lifecycle(args, review, prior.status, reviewer.displayName, args.reason); return { review, readiness: await evaluateVerificationGovernanceReadiness(args) }; }
export async function resolveVerificationConflict(args: Access & { conflictId: string; reviewerId: string; reason: string }) { const reviewer = await verifiedReviewer(args, args.reviewerId); const conflict = (await records<VerificationConflict>(args, "CAE_VERIFICATION_CONFLICT")).find((item) => item.conflictId === args.conflictId); if (!conflict || conflict.status !== "VERIFICATION_CONFLICT") throw new Error("Active verification conflict not found."); const snapshots = await reviewSnapshots(args); const conflictedReviewers = snapshots.filter((item) => conflict.reviewIds.includes(item.reviewId)).map((item) => item.reviewerIdentity).filter(Boolean); if (conflictedReviewers.includes(reviewer.reviewerId)) throw new Error("A reviewer implicated in a conflict cannot resolve that conflict."); const resolved: VerificationConflict = { ...conflict, status: "RESOLVED", resolutionReviewId: reviewer.reviewerId, reason: args.reason, createdAt: now() }; await append(args, "CAE_VERIFICATION_CONFLICT", "Verification conflict · RESOLVED", resolved); await appendTrustSecurityAudit(args, { actor: reviewer.displayName, action: "VERIFICATION_CONFLICT", objectType: "VERIFICATION_CONFLICT", objectId: conflict.conflictId, previousState: conflict.status, newState: resolved.status, reason: args.reason }); return { conflict: resolved, readiness: await evaluateVerificationGovernanceReadiness(args) }; }
export async function revokeGovernanceReviewer(args: Access & { reviewerId: string; actor: string; reason: string }) { const policies = await ensureGovernancePolicies(args); const reviewer = await verifiedReviewer(args, args.reviewerId); const revocation = await revokeTrustObject({ ...args, objectType: "REVIEWER", objectId: reviewer.reviewerId, actor: args.actor, reason: args.reason }); await appendTrustSecurityAudit(args, { actor: args.actor, action: "GOVERNANCE_POLICY", objectType: "REVOCATION_POLICY", objectId: policies.revocationPolicy.policyId, newState: "REVOKED", reason: `${args.reason} Previously approved evidence policy: ${policies.revocationPolicy.previouslyApprovedEvidence}.` }); return { revocation, policy: policies.revocationPolicy, readiness: await evaluateVerificationGovernanceReadiness(args) }; }
export async function importTestEnvironmentEvidenceReference(args: Access & { environmentId: string; testRunId: string; testVersion: string; evidenceHash: string; source: string; timestamp: string; reviewer?: string }) { await ensureGovernancePolicies(args); const environment = (await listHostileTestEnvironments(args)).find((item) => item.environmentId === args.environmentId && item.verificationStatus === "VERIFIED"); if (!environment) throw new Error("A separately approved and independently verified hostile-test environment is required."); const evidence = (await listHostileTestEvidence(args)).find((item) => item.environmentId === args.environmentId && item.hash === args.evidenceHash.toLowerCase()); if (!evidence) throw new Error("Hostile-test evidence hash does not resolve to evidence in the separately approved environment."); const record: TestEnvironmentEvidenceImport = { importId: id("TEST-ENV-IMPORT"), projectId: args.projectId, environmentId: args.environmentId, testRunId: args.testRunId, testVersion: args.testVersion, evidenceHash: args.evidenceHash.toLowerCase(), source: args.source, timestamp: args.timestamp, reviewer: args.reviewer, status: "SUBMITTED", createdAt: now() }; await append(args, "CAE_TEST_ENVIRONMENT_EVIDENCE_IMPORT", "Segregated test-environment evidence reference · SUBMITTED", record); await appendTrustSecurityAudit(args, { actor: args.reviewer ?? "EXTERNAL_SOURCE", action: "EXTERNAL_EVIDENCE_IMPORT", objectType: "HOSTILE_TEST_EVIDENCE", objectId: record.importId, newState: record.status, reason: "Reference only: this production system did not execute a hostile test." }); return { record, readiness: await evaluateVerificationGovernanceReadiness(args) }; }
export async function listVerificationReviews(args: Access) { await ensureGovernancePolicies(args); return latest(await reviewSnapshots(args)); }
export async function listGovernancePolicies(args: Access) { return ensureGovernancePolicies(args); }
export async function listVerificationConflicts(args: Access) { return latest(await records<VerificationConflict>(args, "CAE_VERIFICATION_CONFLICT")); }
export async function listGovernanceLifecycle(args: Access) { return [...await records<VerificationGovernanceLifecycleEvent>(args, "CAE_VERIFICATION_GOVERNANCE_LIFECYCLE")].sort((a, b) => b.timestamp.localeCompare(a.timestamp)); }
export async function listTestEnvironmentEvidenceReferences(args: Access) { return latest(await records<TestEnvironmentEvidenceImport>(args, "CAE_TEST_ENVIRONMENT_EVIDENCE_IMPORT")); }

export async function evaluateVerificationGovernanceReadiness(args: Access): Promise<VerificationGovernanceReadiness> {
  const base = await evaluateExternalVerificationReadiness(args); const policies = await ensureGovernancePolicies(args); const reviews = await reviewSnapshots(args); const latestConflicts = new Map<string, VerificationConflict>(); for (const item of latest(await records<VerificationConflict>(args, "CAE_VERIFICATION_CONFLICT"))) if (!latestConflicts.has(item.conflictId)) latestConflicts.set(item.conflictId, item); const conflicts = [...latestConflicts.values()].filter((item) => item.status === "VERIFICATION_CONFLICT"); const reviewers = await listReviewerIdentities(args);
  const infrastructure = await listInfrastructureEvidence(args); const sandbox = await listSandboxReviews(args); const environments = await listHostileTestEnvironments(args); const hostile = await listHostileTestEvidence(args);
  const required = [
    ...infrastructure.filter((item) => item.verificationStatus === "VERIFIED").map((item) => ({ evidenceType: "INFRASTRUCTURE" as const, evidenceReference: item.evidenceId })),
    ...sandbox.filter((item) => item.status === "ACCEPTED" && item.verificationStatus === "VERIFIED").map((item) => ({ evidenceType: "SANDBOX_REVIEW" as const, evidenceReference: item.reviewId })),
    ...environments.filter((item) => item.verificationStatus === "VERIFIED").map((item) => ({ evidenceType: "HOSTILE_TEST_ENVIRONMENT" as const, evidenceReference: item.environmentId })),
    ...hostile.filter((item) => item.status === "PASS" && item.verificationStatus === "VERIFIED").map((item) => ({ evidenceType: "HOSTILE_TEST" as const, evidenceReference: item.evidenceId })),
  ];
  const accepted = reviews.filter((item) => item.status === "ACCEPTED"); const currentAcceptedByEvidence = new Map<string, VerificationReview>(); for (const item of latest(accepted)) { const key = `${item.evidenceType}:${item.evidenceReference}`; if (!currentAcceptedByEvidence.has(key)) currentAcceptedByEvidence.set(key, item); } const currentAccepted = [...currentAcceptedByEvidence.values()]; const independentReviewPass = required.length > 0 && required.every((item) => currentAccepted.some((review) => review.evidenceType === item.evidenceType && review.evidenceReference === item.evidenceReference));
  const separationPass = currentAccepted.every((review) => Boolean(review.reviewerIdentity) && review.submitterIdentity !== review.reviewerIdentity && review.separationPolicyId === policies.separationPolicy.policyId);
  const revokedAccepted = currentAccepted.filter((review) => { const reviewer = reviewers.find((item) => item.reviewerId === review.reviewerIdentity); return !reviewer || reviewer.identityStatus === "REVOKED" || reviewer.status === "REVOKED" || reviewer.identityStatus === "SUSPENDED" || reviewer.status === "SUSPENDED"; });
  const revocationPass = policies.revocationPolicy.previouslyApprovedEvidence === "REQUIRES_REVIEW" ? revokedAccepted.length === 0 : true;
  const retentionPass = policies.retentionPolicies.length === 5 && policies.retentionPolicies.every((item) => item.deletionPolicy === "NO_SILENT_DELETION" && item.expirationBehavior === "HISTORICAL_NOT_GATE_VALID" && item.archiveStatus !== "UNKNOWN");
  const gates: VerificationGovernanceReadiness["gates"] = [
    { gate: "INDEPENDENT_REVIEW", status: independentReviewPass ? "PASS" : required.length ? "FAIL" : "UNKNOWN", statement: independentReviewPass ? "Every current verified external evidence item has an accepted independent review." : "Current verified external evidence is missing an accepted independent review.", evidenceIds: currentAccepted.map((item) => item.reviewId) },
    { gate: "REVIEWER_SEPARATION", status: separationPass && currentAccepted.length ? "PASS" : currentAccepted.length ? "FAIL" : "UNKNOWN", statement: separationPass && currentAccepted.length ? "Accepted reviews used the explicit no-self-review policy." : "Reviewer separation is missing, unproven, or violated.", evidenceIds: currentAccepted.map((item) => item.reviewId) },
    { gate: "REVIEWER_REVOCATION", status: revocationPass ? "PASS" : "FAIL", statement: revocationPass ? "No accepted review depends on a revoked or suspended reviewer under the explicit re-review policy." : "A revoked or suspended reviewer requires independent re-review before readiness can proceed.", evidenceIds: revokedAccepted.map((item) => item.reviewId) },
    { gate: "RETENTION", status: retentionPass ? "PASS" : "FAIL", statement: retentionPass ? "Versioned retention policies preserve immutable evidence and keep expired evidence historical but gate-ineligible." : "Retention policy is incomplete or permits unsafe evidence handling.", evidenceIds: policies.retentionPolicies.map((item) => item.retentionPolicyId) },
    { gate: "VERIFICATION_CONFLICT", status: conflicts.length ? "FAIL" : "PASS", statement: conflicts.length ? "Independent reviews conflict; runtime readiness is NOT_READY until an authorized resolution is recorded." : "No unresolved verification conflict exists.", evidenceIds: conflicts.map((item) => item.conflictId) },
  ];
  const allPass = base.readiness === "READY_FOR_EXTERNAL_REVIEW" && gates.every((gate) => gate.status === "PASS"); const anyPass = gates.some((gate) => gate.status === "PASS"); const readinessState = allPass ? "READY_FOR_EXTERNAL_REVIEW" as const : base.readiness === "NOT_READY" || gates.some((gate) => gate.status === "UNKNOWN" || gate.status === "FAIL") ? "NOT_READY" as const : anyPass ? "PARTIALLY_READY" as const : "NOT_READY" as const;
  const result: VerificationGovernanceReadiness = { readinessId: id("GOVERNANCE-READINESS"), projectId: args.projectId, version: "1.0.0", baseReadiness: base.readiness, gates, readiness: readinessState, executionApproval: "DISABLED", executionEligible: false, executable: false, reason: allPass ? "Independent governance evidence supports external review only. Runtime execution remains disabled." : conflicts.length ? "Verification conflict fails closed. Runtime readiness is NOT_READY." : "Independent governance requirements are absent, incomplete, revoked, expired, or unverified. Runtime readiness fails closed.", createdAt: now() };
  await append(args, "CAE_VERIFICATION_GOVERNANCE_READINESS", `Phase 6.3 governance readiness · ${result.readiness}`, result); await appendTrustSecurityAudit(args, { actor: "SYSTEM", action: "EXTERNAL_VERIFICATION_READINESS", objectType: "EXTERNAL_VERIFICATION_READINESS", objectId: result.readinessId, newState: result.readiness, reason: result.reason }); return result;
}
export async function listVerificationGovernanceReadiness(args: Access) { return latest(await records<VerificationGovernanceReadiness>(args, "CAE_VERIFICATION_GOVERNANCE_READINESS")); }
