import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { healthCheckEngineeringApi, loadEngineeringConnection, type EngineeringConnection } from "@/lib/engineering-api";

export default function SettingsScreen() {
  const [connection, setConnection] = useState<EngineeringConnection | null>(null);
  const [state, setState] = useState<"CHECKING" | "CONNECTED" | "UNAVAILABLE" | "NO_PROJECT">("CHECKING");
  const test = useCallback(async () => { const active = await loadEngineeringConnection(); setConnection(active); if (!active) return setState("NO_PROJECT"); try { const result = await healthCheckEngineeringApi(active.apiBaseUrl); setState(result.ok ? "CONNECTED" : "UNAVAILABLE"); } catch { setState("UNAVAILABLE"); } }, []);
  useEffect(() => { test(); }, [test]);
  return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>SETTINGS</Text><Text style={styles.title}>Connection</Text><Text style={styles.description}>Connection details are kept here so normal engineering work stays focused on projects and designs.</Text><View style={styles.status}><MaterialIcons color={state === "CONNECTED" ? "#8BE4CE" : "#F7C873"} name={state === "CONNECTED" ? "cloud-done" : "cloud-off"} size={23} /><View><Text style={styles.statusTitle}>{state === "CONNECTED" ? "Connected" : state === "CHECKING" ? "Checking connection" : "Connection needs attention"}</Text><Text style={styles.statusText}>{state === "CONNECTED" ? "The configured engineering service is available." : state === "NO_PROJECT" ? "Create or open a project to establish an engineering connection." : "Retry the connection check. Diagnostics remain safe and never expose credentials."}</Text></View></View><View style={styles.card}><Text style={styles.cardLabel}>CONFIGURED ENDPOINT</Text><Text selectable style={styles.endpoint}>{connection?.apiBaseUrl ?? "No project connection stored"}</Text><Text style={styles.cardNote}>Project access credentials, session tokens, and cryptographic secrets are never displayed here.</Text></View><Pressable onPress={test} style={({ pressed }) => [styles.button, pressed && styles.pressed]} accessibilityRole="button"><Text style={styles.buttonText}>{state === "CHECKING" ? "Checking…" : "Test connection"}</Text><MaterialIcons color="#081827" name="refresh" size={18} /></Pressable><Pressable onPress={() => router.push("/recovery" as never)} style={({ pressed }) => [styles.recoveryButton, pressed && styles.pressed]} accessibilityRole="button"><View><Text style={styles.recoveryTitle}>Protected Recovery</Text><Text style={styles.recoveryText}>Inspect CAPRE snapshots and staging-only recovery evidence.</Text></View><MaterialIcons color="#8BE4CE" name="security" size={22} /></Pressable><View style={styles.diagnostics}><Text style={styles.cardLabel}>SAFE DIAGNOSTICS</Text><Text style={styles.diagnosticRow}>Project connection: {connection ? "available" : "not configured"}</Text><Text style={styles.diagnosticRow}>Connection test: {state.toLowerCase().replace(/_/g, " ")}</Text><Text style={styles.cardNote}>Diagnostics show safe connection metadata only.</Text></View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 32, paddingTop: 20 }, eyebrow: { color: "#2EC5E8", fontSize: 10, fontWeight: "800", letterSpacing: 1.1 }, title: { color: "#E7F0F6", fontSize: 28, fontWeight: "800", letterSpacing: -.7 }, description: { color: "#A9C0D0", fontSize: 13, lineHeight: 19 }, status: { alignItems: "flex-start", backgroundColor: "#0D2637", borderColor: "#1B526A", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 10, padding: 14 }, statusTitle: { color: "#E7F0F6", fontSize: 15, fontWeight: "800" }, statusText: { color: "#A9C0D0", fontSize: 12, lineHeight: 18, marginTop: 3 }, card: { backgroundColor: "#0E2436", borderColor: "#1B3B53", borderRadius: 14, borderWidth: 1, gap: 7, padding: 13 }, cardLabel: { color: "#72D8EF", fontSize: 10, fontWeight: "800", letterSpacing: .8 }, endpoint: { color: "#D5E2EB", fontFamily: "monospace", fontSize: 11, lineHeight: 17 }, cardNote: { color: "#8BA4B8", fontSize: 11, lineHeight: 16 }, button: { alignItems: "center", backgroundColor: "#2EC5E8", borderRadius: 12, flexDirection: "row", justifyContent: "space-between", minHeight: 48, paddingHorizontal: 14 }, buttonText: { color: "#081827", fontSize: 14, fontWeight: "800" }, recoveryButton: { alignItems: "center", backgroundColor: "#103448", borderColor: "#176070", borderRadius: 12, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 64, paddingHorizontal: 14 }, recoveryTitle: { color: "#D8FFF4", fontSize: 14, fontWeight: "800" }, recoveryText: { color: "#A9C0D0", fontSize: 11, marginTop: 3 }, diagnostics: { backgroundColor: "#091B2A", borderColor: "#1B4056", borderRadius: 14, borderWidth: 1, gap: 6, padding: 13 }, diagnosticRow: { color: "#B7CCDA", fontSize: 12 }, pressed: { opacity: .78, transform: [{ scale: .985 }] } });
